### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Minasokoni** [vue-styleguidist/vue-styleguidist#1]
I keep on running into this error: 
```
> vue-styleguidist server

env: node\r: No such file or directory
```

Whenever I run that command. 

I'm running node -v v6.10.0
and npm -v 4.1.2

The path it hits is /examples/basic/node_modules/.bin/vue-styleguidist/

**Comment by rafaesc92** [comment]
I guess I never tried to run the cli on system other than Windows though.

I've published the fix under v1.0.9.
Please try it and let me know if it works.

**Comment by happylittleboozer** [comment]
> The path it hits is /examples/basic/node_modules/.bin/vue-styleguidist
This file has windows line-endings (\r\n). Save it with UNIX line-endings (\n) and try again.

**Comment by Minasokoni** [comment]
@rafaesc92 it works! Thank you for the quick update.

**Comment by rafaesc92** [comment]
It's true @happylittleboozer, I had to use http://dos2unix.sourceforge.net/, and it worked out. I closed this issue
