### ISSUE TITLE
Failed to mount component with vue-loader 13.0.0

### ISSUE THREAD

**Issue by lancetharper** [vue-styleguidist/vue-styleguidist#10]
[vue-loader 13.0.0](https://github.com/vuejs/vue-loader/releases/tag/v13.0.0)

Examples no longer load with the new vue-loader update. Get this error in console:

```
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <CdrButton>
       <Root>
```

**Comment by rafaesc92** [comment]
Hello, I could not simulate the error by installing version 13.0.0, please show me a reference to solve it

**Comment by escapedcat** [comment]
We're also running it with 13.0.0 without any issues.

**Comment by lancetharper** [comment]
It may just be me then. I'll have to play around with it and see if I can figure out where the issue is. I don't have problems with the dev server on 13.0.0 though, just with the styleguide and they share the same webpack config.

**Comment by escapedcat** [comment]
@lancetharper sorry, discovered the same issue now. Maybe we alreayd had it earlier even, but didn't notice it.
    
Current stack:
- Vue 2.4.1
- webpack 3.3.0
- vue-loader 13.0.1
- vue-styleguidist 1.1.12 (also tried 1.2.0)

I'll try to create a minimum example as soon as I find some time.

**Comment by rafaesc92** [comment]
Thanks @escapedcat

**Comment by escapedcat** [comment]
Here you go: https://github.com/escapedcat/vue-styleguidist/commits/master

Only did two commits, one updating the general deps which still works. One more updating `vue-loader` and it fails with the error mentioned above.  

Hope this helps. Let me know if I can support in any way.

**Comment by rafaesc92** [comment]
Okay, I think it should be fine by now.
Thanks for the patience, recently I have been able to work in vue-styleguidist.

I've published the fix under v1.2.2.
Please try it and let me know if it works.

**Comment by escapedcat** [comment]
I tried to use the basic example with your latest version here:
https://github.com/escapedcat/vue-styleguidist/blob/master/examples/basic/package.json#L17

Trying `npm run styleguide` I get:
```
> vue-styleguidist server

Style guide server started at:
http://0.0.0.0:6060

Failed to compile.

Error in multi ./node_modules/vue-styleguidist/lib/index ./node_modules/react-dev-utils/webpackHotDevClient.js
Module not found: Can't resolve '/Users/[MY_PATH]/vue-styleguidist/examples/basic/node_modules/vue-styleguidist/lib/index' in '/Users/[MY_PATH]/vue-styleguidist/examples/basic'

 @ multi ./node_modules/vue-styleguidist/lib/index ./node_modules/react-dev-utils/webpackHotDevClient.js
```

Not sure why this is happenign now 😖

**Comment by rafaesc92** [comment]
@escapedcat Do not take git, because I have blocked the .babelrc to be able to compile the examples, only when I upload the package enabled the .babelrc

You can see it here
[https://github.com/vue-styleguidist/vue-styleguidist/blob/master/.babelrc.lock](https://github.com/vue-styleguidist/vue-styleguidist/blob/master/.babelrc.lock)

Reinstall the vue-styleguidist

**Comment by escapedcat** [comment]
Damn, didn't see it. Thx for the PR. Works now! Thanks a lot!

**Comment by rafaesc92** [comment]
Perfect, then I close the issue

**Comment by escapedcat** [comment]
Would be helpful to update the basic example and the `vue-webpack-loaders` I guess. I try to test these and create PRs when I find time.

**Comment by rafaesc92** [comment]
Yes, thanks @escapedcat. Later I will also update ```vue-webpack-loaders```, it needs updating to version 2.4.x of vue.

**Comment by lancetharper** [comment]
Confirmed working in my project now. Thank you!
