### ISSUE TITLE
Sections with spaces in name broken

### ISSUE THREAD

**Issue by viljamis** [vue-styleguidist/vue-styleguidist#100]
Sorry for filing so many issues today, but I hope these help! :-/ 

I found one more thing while building something on top of the `navigation: true` option which is currently preventing me from using it in production. It seems like the issue is only happening in Chrome.

Steps to reproduce (well, only one step, really):

1. Define a section name that has spaces, I have the following:

```
{
      name: "Getting Started",
      content: "docs/getting-started.md"
}
```

2. That’s really it. If you now start up the styleguide server, the links in the sidebar are broken (the once with spaces in name).

3. Additionally, in Chrome, can’t access that section at all by typing the url in Browser’s address bar ( `http://localhost:6060/#!/Getting%20Started`). Gives the following error in Chrome: `Uncaught TypeError: Cannot read property 'name' of undefined at getPageTitle (main.bundle.js:112123)`.

It looks like everything is still working for example in Safari, so this is currently happening only in Chrome and Opera for me.

**Comment by rafaesc** [comment]
Hi @viljamis,

haha don't worry, I will review it this week,

But also you can create a PR,
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/src/utils/getPageTitle.js

Regards!

**Comment by viljamis** [comment]
@rafaesc I will try to take a look, not sure currently what is causing the issue.

**Comment by viljamis** [comment]
Couldn’t yet figure out what’s causing this, but I created a test case that highlights the problem. See comparison of `examples/navigation/styleguide.config.js` in https://github.com/vue-styleguidist/vue-styleguidist/compare/master...viljamis:master

**Comment by viljamis** [comment]
@rafaesc I did some further investigation and it looks like this issue is not just related to the `navigation` option. Styleguide also breaks when trying to view a section (that has spaces) in name in isolated mode. URL looks like this: `http://localhost:6060/#!/Documentation%20Test` and nothing renders on page.

**Comment by viljamis** [comment]
@rafaesc Found the issue finally. It was hidden pretty deep. Working on a fix.

**Comment by viljamis** [comment]
@rafaesc This should be now fixed in https://github.com/vue-styleguidist/vue-styleguidist/pull/106 (I added some additional notes in the pull)
