### ISSUE TITLE
vue-docgen-cli watch mode halts, fix by updating chokidar

### ISSUE THREAD

**Issue by CaitlinWeb-st** [vue-styleguidist/vue-styleguidist#1004]
**Current behavior**

Starting vue-docgen-cli in watch mode `-w` hangs on my Mac.

**To reproduce**

Run `vue-docgen-cli -w`.

**Expected behavior**

vue-docgen-cli starts and enters watch mode, updating on changes.

---

I fixed this by using a newer version of chokidar. Then `vue-docgen-cli -w` worked as expected. I believe this was fixed in 3.2 according to [this issue](https://github.com/paulmillr/chokidar/issues/859).

**Comment by elevatebart** [comment]
Since vue-docgen-api does not have a CLI, I assumed you spoke about vue-docgen-cli.

I will indeed update the demanded dependencies.

**Comment by CaitlinWeb-st** [comment]
My bad, I keep getting them confused. I did mean the CLI. Fixed the original post. Thanks!
