### ISSUE TITLE
The page could not found the imported library

### ISSUE THREAD

**Issue by archi-git** [vue-styleguidist/vue-styleguidist#1006]
I import some library using a global.requires.js file, but it reports 404, i get stuck.

```js
import Vue from 'vue'
import Vuex from 'vuex'
import ElementUI from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'

Vue.use(Vuex)
Vue.use(ElementUI)
```
_the error_
![image](https://user-images.githubusercontent.com/22209404/96822072-cdaa4680-145b-11eb-8a7e-8c5fcb9aff52.png)

_but some components from those library is worked normally._
![image](https://user-images.githubusercontent.com/22209404/96822400-896b7600-145c-11eb-8f44-69292cc91dc8.png)

**Comment by elevatebart** [comment]
Hi @archi-git 

You have hit a snag and it might take us some time to figure it out.
Don't worry! we usually get them bugs after a few tries.

Essentially, styleguidist is a webpack engine with 3 loaders: styleguide loader, vuedocs loader and examples loader.
If things are not working as they should it can be a misconfiguration of webpack or that one of the loaders is broken.

It is very possible in your case that you are using styleguidist the right way but there is a loader in your webpack.config that is messing with resource loading. I would check there first.

To go further here is a couple of question I would like you to answer please.
- Are you using the vue-cli plugin?
- What does your `styleguide.config.js` look like?
- What package manager are you using? npm/yarn/pnpm?

**Comment by archi-git** [comment]
Thanks for your reply. @elevatebart 

Here is my situation.

- I have used vue-cli, so it was installed in my project but I don't invoke it now.

- my _styleguide.config.js_ file
```js
const path = require('path')

module.exports = {
  title: 'demo',
  components: 'src/components/**/*.vue',
  jssThemedEditor: false,
  defaultExample: true,
  progressBar: true,
  styles: {
    Editor: {
      root: {
        isolate: false
      }
    }
  },
  usageMode: 'expand',
  exampleMode: 'collapses',
  require: [
    path.join(__dirname, 'styleguide/vsc-prism.css'),
    path.join(__dirname, 'styleguide/global.requires.js')
  ]
}
```
- I using npm.

**Comment by archi-git** [comment]
I have a discovery that the final page built has not this problem~

**Comment by archi-git** [comment]
I use renderRootJsx option, add the styleguide.root.js and the problems is solved~ thought I don't know what happens~👀

**Comment by elevatebart** [comment]
great news
