### ISSUE TITLE
Does it support exchanging the position between example and the 'PROPS, METHODS, EVENTS & SLOTS' table?

### ISSUE THREAD

**Issue by archi-git** [vue-styleguidist/vue-styleguidist#1011]

**Comment by elevatebart** [comment]
Hello @archi-git,

Short answer is yes. you can.

### First using CSS flex

There is an example of how to do that in the following example
https://vue-styleguidist.github.io/Examples.html#vueds


### Second using customization of `ReactComponent`

https://github.com/styleguidist/react-styleguidist/blob/master/src/client/rsg-components/ReactComponent/ReactComponentRenderer.tsx

**Comment by archi-git** [comment]
Thanks for your answer! @elevatebart 

I understand using customization of ReactComponent, but can you tell me what means using CSS flex? Is it necessary to config if I using the customization of ReactComponent?

**Comment by elevatebart** [comment]
You do not need to use both techniques at once.

Using CSS flex, you can rearrange the [flow of elements on screen](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordering_Flex_Items).
If you modify the ReactComponent, you do not need to change the flow, since elements will already appear in the right order.
But the CSS flex technique allows people who do not know React to still manage to do this trick.

**Comment by archi-git** [comment]
As for the first technique, I can't found out where it using CSS flex in the vueds example. I search the keyword 'flex', the result looks don't like where it uses. Is it configurable?

The second, I config it consulting the vueds example, but some errors are consoled out. I config it as below：
_styleguide.config.js_
```
  styleguideComponents: {
    ReactComponentRenderer: path.join(__dirname, 'styleguide/components/ReactComponent')
  }
```
At styleguide.config.js-webpackConfig-module-rule，I add this:
```
{
          test: /\.tsx?$/,
          loader: 'ts-loader',
          exclude: /node_modules/,
          options: {
            appendTsSuffixTo: [/\.vue$/]
          }
}
```
And the ReactComponent.js is just a copy from vueds example. 
Some relative package dependence is also installed.
But it reports:
![image](https://user-images.githubusercontent.com/22209404/98061892-e5d08b80-1e87-11eb-8d60-c002e8468d3f.png)
I get stuck once again 😂

**Comment by elevatebart** [comment]
I am sorry this issue slipped my care. I am unavailable for the coming weeks but will be back on this ASAP.

The overall principle is to reorder through flexbox, the blocks in side the `ReactComponponent` component.

**Comment by archi-git** [comment]
That's OK~ Thank you for your help！
