### ISSUE TITLE
vue-docgen-cli: Event template doesn't show @property tags

### ISSUE THREAD

**Issue by CaitlinWeb-st** [vue-styleguidist/vue-styleguidist#1013]
**The problem**

The event template shows events with:

* Event name
* Type
* Description

Properties, the value(s) returned with the event, are not shown anywhere.

**Proposed solution**

Add a column with `@property` information, similar to `@binding`.

**Alternative solutions**

Override the template in the config (`templates` option).

**Additional context**

With the comment:

```
/**
 * Return the new value as boolean.
 *
 * @type {change}
 * @property {boolean} val current value of control
 */
```

This gets displayed as:

![Screen Shot 2020-11-11 at 1 44 07 PM](https://user-images.githubusercontent.com/61840918/98853320-f3a58400-2426-11eb-9cc9-eaa1712bcbdc.png)

**Comment by elevatebart** [comment]
Hello @CaitlinWeb-st ,

Thank you for taking the time to post this issue, I think the [documentation of documenting](https://vue-styleguidist.github.io/docs/Documenting.html#in-template) events could use a refresh.

Have you tried the following example?

```html
<div>
  <!--
    trigered on click
    @event click
    @property {object} demo - example
    @property {number} called - test called
  -->
  <button @click="$emit('click', test)"></button>
</div>
```

**Comment by elevatebart** [comment]
I am really thinking of removing the `@type` from events in next major version

**Comment by CaitlinWeb-st** [comment]
> Have you tried the following example?

@elevatebart In my case I'm emitting it from a method, but essentially yes. The properties aren't showing in the documentation anywhere and [the template doesn't even have a place for it](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-cli/src/templates/events.ts).

**Comment by elevatebart** [comment]
Oh my !! You are absolutely correct.
I was still in styleguidist land... My apologies.

Properties are extracted and available, but they simply are unused.

Thank you for pointing it out. Now I need to find a good way to display those properties in a table.
Since we are in markdown land, no rowspan is possible.

I could pack it all in one cell, could use pure html tables, what do you think is best?

**Comment by CaitlinWeb-st** [comment]
The properties could be in a table cell with linebreaks between properties. Or perhaps rethink the whole layout? So instead of a table maybe it has sections for each event with properties in a table. Not really sure.

I actually overwrote the slot template to display bindings a bit better. This is what it looked like by default:

![Screen Shot 2020-11-11 at 3 00 26 PM](https://user-images.githubusercontent.com/61840918/98858581-daa0d100-242e-11eb-8d6d-b1c1827f9e62.png)

This is how I'm displaying it:

![bindings-screenshot](https://user-images.githubusercontent.com/61840918/98857152-a9bf9c80-242c-11eb-979c-24e06098c62e.png)

So maybe something like how I'm displaying bindings could work (and maybe do the same treatment to the slots template for bindings).

**Comment by elevatebart** [comment]
Ohhh I like your designs a lot, would you mind making a PR for how you render the slots? 
I could use the same adjustments for the events.

**Comment by CaitlinWeb-st** [comment]
Sure, I'll try to open a PR with that tomorrow. Might be later in the week.

**Comment by elevatebart** [comment]
thank you, you rock !!!

**Comment by CaitlinWeb-st** [comment]
Haven't had a chance to open a PR (Monday deadline) but here's what I've got in my file for the slots template:

```js
const { mdclean } = require("vue-docgen-cli/lib/templates/utils");

function formatBinding({ name, description, type }) {
  return `<span class="token tag">${name}</span>: <span class="token number">${
    type.name === "union"
      ? type.elements
          .map(
            ({ name }, index) =>
              `${name}</span>${
                index !== type.elements.length - 1 ? '|<span class="token number">' : ""
              }`
          )
          .join("")
      : type.name
  }</span> &mdash; ${description}\n`;
}

module.exports = (slots, opt = {}) => {
  return `
${opt.isSubComponent || opt.hasSubComponents ? "#" : ""}## Slots
| Name          | Description  | Bindings |
| ------------- | ------------ | -------- |
${slots
  .map(slot => {
    const { description, bindings, name } = slot;
    const readableBindings = bindings ? `${Object.values(bindings).map(formatBinding)}` : "";

    return `| ${mdclean(name)} | ${mdclean(description || "")} | ${mdclean(readableBindings)} |`; // replace returns by <br> to allow them in a table cell
  })
  .join("\n")}
`;
};
```

**Comment by CaitlinWeb-st** [comment]
@elevatebart Thanks for the update on this in v4.33.10! 😀 I tried it out with v4.34.1 and it's excellent!
