### ISSUE TITLE
Are there some samples that integrate the vue-styleguidist with Quasar to generate document for Quasar App Project?

### ISSUE THREAD

**Issue by zouzg7829** [vue-styleguidist/vue-styleguidist#1016]
if developer want to use **vue-styleguidist** to generate and maintain the document of the [**Quasar**](https://github.com/quasarframework/quasar) project and is developing App with Quaser, so he/she prefer a sample demo how to integrate the vue-styleguidist with Quaser.
So, are there some samples that integrate the vue-styleguidist with Quasar to generate document for Quasar App Project?
Especially, for Class-Style Vue Components, it also **SHOULD** generate the document, for example:
```
<template>
  <button :style="styles" @click="handleClick">
    <!-- @slot Use this slot to place the button content -->
    <slot></slot>
  </button>
</template>
<script lang="ts">
import { Vue, Component, Prop } from 'vue-property-decorator'

@Component
export default class AppButton extends Vue {
  @Prop(Number)
  size?: number;

  /**
   * Sets the button font color
   */
  @Prop(String)
  color?: string;

  @Prop(String)
  /** 
   * Sets background color of the button
   * @since 1.2.0
   */
  background?: string;

  /** @deprecated Use color instead */
  @Prop(String)
  oldColor?: string;

  get styles () {
    return {
      'font-size': this.size,
      color: this.color,
      background: this.background
    }
  }

  handleClick (e: Event) {
    /**
     * Triggered when button is clicked
     * @event click
     * @type {Event}
     */
    this.$emit('click', e)
    /** 
     * Event for Alligator's example
     * @event gator
     * @type {Event}
     */
    this.$emit('gator', e)
  }
}
</script>
```

**Comment by elevatebart** [comment]
Hello @zouzg7829, I have a really no experience with Quasar. 
Would you have time to work with me, setting up a sample solution to document?
If you do, you can create a quick PR adding your sample quasar repo. I will do my best to make it as well documented as possible.
