### ISSUE TITLE
Version 4.33.7 vue-docgen-cli fails with error

### ISSUE THREAD

**Issue by andreeapanait99** [vue-styleguidist/vue-styleguidist#1018]
**Current behavior**

Version 4.33.7 vue-docgen-cli doc generating fails with error: 

```
Error: Cannot find module './extractConfig'
Require stack:
/root/node_modules/vue-docgen-cli/lib/bin.js
```

Error seems to be from this line of code: [link](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-cli/lib/bin.js#L19).

With version 4.33.6 everything works as expected.

**To reproduce**

Command run: 
`vue-docgen -c doc/docgen.api.config.js`

Config file _docgen.api.config.js_:

```
module.exports = {
        componentsRoot: 'lib',
        components: '**/*.vue',
        outDir: 'doc',
        apiOptions: {
            ...require(path.resolve(process.cwd(), './webpack.config.js')).resolve,
            alias: {
                '@example': path.resolve(process.cwd(), './node_modules/@example')
            },
            validExtends(fullFilePath) {
                return /[\\/]node_modules\/@example[\\/]/.test(fullFilePath);
            }
        },
        getDestFile: (file, config) => path.join(config.outDir, 'API.md'),
        templates: {
            component: require('./template/componentAPI.js'),
            props: require('./template/prop.js'),
            events: require('./template/event.js')
        }
};
```

**Expected behavior**

Like previous version 4.33.6, doc generating should finish without errors.

**Comment by elevatebart** [comment]
Thank you @andreeapanait99,

There seems to have been an issue while releasing.
I am looking for the issue and a fix.

**Comment by elevatebart** [comment]
fixed in 33.9. I believe this could be due to an update/optimization of npm publish...

**Comment by andreeapanait99** [comment]
Tested and it works without errors now. 
Thank you so much!

**Comment by elevatebart** [comment]
np
