### ISSUE TITLE
Better nuxt support

### ISSUE THREAD

**Issue by PeterPorzuczek** [vue-styleguidist/vue-styleguidist#102]
Is there a way to load nuxt modules like for example this lib: 
https://github.com/nuxt-community/axios-module
I've checked yours example and it covers only very simple use case. Could you provide some example with heavier usage of nuxt? I was trying to load modules without success, maybe you could implement nuxt configuration handling or some way to extend styleguidist config with nuxt configs?

**Comment by rafaesc** [comment]
Hi @PeterPorzuczek,

Yes, I would like that you can create a little bit more complex example, here.
https://github.com/vue-styleguidist/vue-styleguidist/tree/master/examples

So I can review it.

Regards

**Comment by PeterPorzuczek** [comment]
I made pr with example that uses @nuxtjs/axios and nuxt-i18n. We have to mock all these nuxt modules on our own in order to make our components load in style guide.

**Comment by aurel-tackoen** [comment]
If anyone has trouble using nuxt and v-i18n I would recommend using this example instead : 
https://github.com/vue-styleguidist/vue-styleguidist/tree/dev/examples/vuetify
