### ISSUE TITLE
vue-docgen not support import 

### ISSUE THREAD

**Issue by jackluson** [vue-styleguidist/vue-styleguidist#1023]
```md
```[import](./_other.vue)
Text typed ere will be entiry ignored. You can use it to describe the example imported for maintenance purposes
```
```
not work?

**Comment by elevatebart** [comment]
That is a great point, it would probably be useful to be added.

**Comment by jd1378** [comment]
hmm, would be nice to have this. I thought it's already there because it's in the docs and was trying to get it working, then I found this issue.

**Comment by elevatebart** [comment]
Soooo... I actually do not parse the markdown in vue-docgen-cli. 
I only copy it into files. 
I would prefer not to add it to docgen-cli. It would add a big dependency on the package `remark` that I would like to avoid.
There are 2 places you can do this on your own. 

## As a plugin to your rendering

Both those tools support using Vue components literally in the markdown. 
So you could make your own preview component there and have this component read the file you need before build.

It will be harder with nuxt-content server-side rendering than with vuepress but is doable.

## As a plugin to the templating engine

A simpler way to accomplish this is to customize the template for `component`.
[As explained in the docs](https://vue-styleguidist.github.io/docs/docgen-cli.html#templates).

Use the standard template to run your code, then parse the result using `remark`. 
Modify the import with the files needed and update the string you return.

---

Hopefully, that will help. 

I should add in the documentation that not all the options described for vue-styleguidist work for vue-docgen-cli. It was my initial intention but when the rendering is done on a webpage, it is not the same as when it's rendered in a file.

Will fix the docs

**Comment by jd1378** [comment]
Well I did find a somewhat workaround so far
I found that I can do the import using `updateExample()` inside my styleguide.config.js. I found an example of it inside the docs and changed it a little bit:
```js
updateExample(props, exampleFilePath) {
    const { settings, lang } = props;
    if (settings && typeof settings.file === 'string') {
      const filepath = path.resolve(
        path.dirname(exampleFilePath),
        settings.file
      );
      delete settings.file;
      const content = fs.readFileSync(filepath, 'utf-8');
      return {
        content,
        settings,
        lang,
      };
    }
    return props;
  },
  ```
  
  then in my readme files I do this:
```
  ```jsx { "file": "./Example1.vue" }
  ` ``
```
And somehow It's working out fine so far for me.

**Comment by elevatebart** [comment]
I see from your usage of `styleguide.config.js` that you are using vue-styleguidist.
This option is supposed to work there out of the box.
If you provide a reproduction repository, I can check why this is not the case.

This feature only does not work on vue-docgen-cli.

**Comment by jd1378** [comment]
Ah, My bad ! you are right, I was using vue-styleguidist
It was supposed to work, but somehow it didn't when I was testing it, that's why I tried using the way I did
But when I tried again now to reproduce the issue, I cannot strangely , and it works as expected...
I updated my vue cli before creating the new repo, so maybe that has something to do with it, because I'm pretty sure I checked it multiple times before trying a workaround. (or maybe there was an issue somewhere else that I was not aware of at the time of issue happening, either way I think it was probably my fault)

still, thanks a lot for putting time and replying to my issue, that means a lot
