### ISSUE TITLE
Can support Vue3 with TSX now ?

### ISSUE THREAD

**Issue by HomyeeKing** [vue-styleguidist/vue-styleguidist#1025]
we choose this in our vue2 project, now we also want use this in our vue3 project

the main code style in our vue3 project is compositionApi + ts + tsx, 

so I wonder if it can support now?

BTW: I've noticed the open issue at top, but the last comment is on OCT, so just ask

**Comment by elevatebart** [comment]
Hello @HomyeeKing ,

I think using TSX in the code of your components should not be a problem.
There is no plan to allow the use of TypeScript in the live coding examples yet.

Would this be something you would need?

I tried to install Monaco as an editor, the editor for typescript. Though it has some issues for now it seems to be working well with autocompletion and all. Now I need to find a compiler transpiling TypeScript into JavaScript before eval. 

The one I found so far is esbuild-wasm but it does not seem light at all.
We could also use babel, but babel is heavy too.

Would you be interested in helping out? 
If so, please ping me directly on discord

ElevateBart#1057

**Comment by HomyeeKing** [comment]
@elevatebart  the problem is this project still depend on `vue-template-compiler` which has been replaced by `@vue/compiler-sfc`

**Comment by elevatebart** [comment]
@HomyeeKing that's true and I was incomplete in my previous explanation.

Though vue-docgen-api and vue-docgen-cli are entirely compatible with vue3, vue-styleguidist does not have a published version that has this compatibility. 

Since I am forced to break backward compatibility, I want to deliver what I promised: 

1. More precise and consistent definition of types in the outputs of vue-docgen-api
1. Replace simple editor with Monaco to make IntelliSense work and simplify documentation
1. Allow the use of TSX in the example since this seems to be the future of Vue

But a TS compiler is about 5 MB to DL. It might not be suited for all uses, I need a way to strip out types without embedding the whole tool.

**Comment by voskresla** [comment]
Does it support TSX only in `script` section?

I try to generate doc for class-based-component in TSX file like
```
// tag.tsx
import Vue from 'vue'
import { Component, Prop } from 'vue-property-decorator'

@Component({
	name: 'tag',
})
export class Tag extends Vue {

	@Prop() xxx!:number
}
```

And always get error:
```
@requires tags: Unexpected token...
```

**Comment by voskresla** [comment]
I was notice that changing code from `export class ...` to `export default class...` all will start generated like a charm.

**Comment by elevatebart** [comment]
Oh yeah @voskresla you might very well be right. 
I did not take into account one could export a class with a named block and it would work.

I can fix that soon, could you open another issue for it please ?

**Comment by lockiechen** [comment]
Is tsx supported now?

![image](https://user-images.githubusercontent.com/33082528/110320921-f4080180-804b-11eb-8a1a-10184dc66594.png)

**Comment by elevatebart** [comment]
@lockiechen 

TSX was always supported in the writing of components.
It is still not supported in the live examples. 

I think I found a way to make TypeScript compile live with enough performance that we'd have a blast doing it. I still need to figure it out. 

- The tool that compiled typescript fast is called [sucrase](https://github.com/alangpierce/sucrase),
- The PR to follow is #1060

**Comment by alewkinr** [comment]
Hello there, any news to vue3 support?
Thanks in advance!

**Comment by elevatebart** [comment]
Hello @alewkinr,

I spent the last 6 month exclusively working and parenting (No OSS).
I apologize if I am not more up here in the weeds.

I have a few cool ideas for vue3. 
Among them, I would really like to get rid of React, 
maybe even use vite.

I still have an outstanding issue on the vite repo about a conflict between React TSX and Vue TSX so the answer to this is: 

Though most of the library is compatible with vue3, it is not compatible with typescript yet. We will probably not have it set up for the next 3 months. Things are moving rapidly and if you want to lend a hand, I would help you get started with pleasure.

Thank you for your patience.
