### ISSUE TITLE
Import file contents for component documentation?

### ISSUE THREAD

**Issue by simonwjackson** [vue-styleguidist/vue-styleguidist#104]
Is there any way to import an existing file and show its code in the documentation?

I have a large snippet that is used in alot of examples, i'd like to show it off somewhere in the docs

```
<docs>
## Navigation fixture

@example /path/to/file.js
</docs>
```

**Comment by philwolstenholme** [comment]
@simonwjackson did you take a look at this option: https://github.com/vue-styleguidist/vue-styleguidist/blob/d9dd4f87a15996aa8154693f045f4d8b8bd074ec/docs/Documenting.md#external-examples-using-doclet-tags

**Comment by simonwjackson** [comment]
It does not work with `.js` files

**Comment by elevatebart** [comment]
Hey @simonwjackson 

What would you think of a syntax like this one:

````markdown
Imported example sample code

```[import](./path/to/file.jsx) readonly no-editor
// the code here would be ignored in the generated docs
```

````

It has a couple of upsides. 
- You would be able to navigate easily to your examples in modern editors (Ctrl or Cmd + Click)
- It would still obviously look like a code sample

Tell me what you think ;)
Bart
