### ISSUE TITLE
src attributes in template tags break the build when aliases are used

### ISSUE THREAD

**Issue by therealpecus** [vue-styleguidist/vue-styleguidist#1042]
**Current behavior**

`src` attributes in `template` tags are not resolved via webpack/enhanced-resolve, and break the build when aliases are used

**To reproduce**

https://codesandbox.io/s/vue-styleguidist-alias-yvq1i?file=/src/components/Modal/Modal.vue

The example shows that with the default `'@'` alias, the external source to a template breaks the build. Local sources (e.g. `<template src="./Modal.html" />` are correctly imported.

**Expected behavior**

The build completes successfully and the component is rendered.

I am not familiar with vue-styleguidist code (I spent a few hours chasing unicorns in the codebase), and this might not be trivial (although vue-loader does this out of the box). But if you can point me in the right direction I might take a stab at it and provide a PR.

**Comment by elevatebart** [comment]
Nice catch @therealpecus! 
I don't know how we missed this one.

**Comment by therealpecus** [comment]
unfortunately I'm having issues compiling the project, otherwise I could provide a PR. I have global lerna + yarn + pnpm + tsc +nvm but the default branch fails to compile even before any changes...
