### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by HomyeeKing** [vue-styleguidist/vue-styleguidist#1044]
![image](https://user-images.githubusercontent.com/49113249/104544375-89959f00-5662-11eb-8c46-1831130cd832.png)

I didn't find `process` was used in webpack config file, so what might cause this kind of error

**Comment by elevatebart** [comment]
It lloks like some error management was meant to be used in the terminal and ended up firing in the browser console.  could it be `bootstrap`? Or `formatWebpackMessages`?

**Comment by HomyeeKing** [comment]
@elevatebart  have no idea about this 🤕, it does use `process` in `chalk` `bootstrap` files , but should it block the render since the project run well

**Comment by elevatebart** [comment]
Chalk is not intended to be used browser-side so if in the process of rendering, there is a call to chalk, it will block the rendering.

**Comment by elevatebart** [comment]
Would you have time to create a reproduction repository with dummy components?

**Comment by clenemt** [comment]
Same problem here with some more info maybe:

![image](https://user-images.githubusercontent.com/447956/109400557-b3bccb00-7949-11eb-90d3-b5163952de6a.png)

![image](https://user-images.githubusercontent.com/447956/109400678-48272d80-794a-11eb-95dc-c4eb7c656ec5.png)

![image](https://user-images.githubusercontent.com/447956/109400680-4e1d0e80-794a-11eb-843d-e12e4f943788.png)

**Comment by kgilden** [comment]
For me this problem occurred today, when trying to upgrade from webpack v4 to v5. I did some digging and the root cause seems to be that in webpack v5 the process global has been removed ([implicitly mentioned in webpack upgrade article](https://webpack.js.org/migrate/5/#test-webpack-5-compatibility), [a stackoverflow answer](https://stackoverflow.com/a/64612964/766120)).

I can see that `react-dev-utils` is the problem here. From  https://github.com/facebook/create-react-app/commit/91e28a45c1ef6cc520c2bf20f5ee4d3fa2b3a024 I see that `chalk` has been removed since `react-dev-utils@11.0.3` (see image below).

![2021-03-17_12-39](https://user-images.githubusercontent.com/918599/111455002-f6d6b680-871d-11eb-8208-07a44e202c2c.png)

But `vue-styleguidist` is currently depending on `react-dev-utils@^7.0.3` ([see here](https://github.com/vue-styleguidist/vue-styleguidist/blob/c03c0cb7e2000735142851f1600952221ce1688a/packages/vue-styleguidist/package.json#L70)). So perhaps upgrading `react-dev-utils` to ^11.0.3 would solve this?

**Comment by elevatebart** [comment]
Thank you @kgilden 

You are right, updating react-dev-utils should help.
For now, react-styleguidist's workflow is a little broken.

I am waiting on an answer from @sapegin before merging my fix. 
Then we will update it inside of vue-styleguidist.

Sorry to have you waiting.

**Comment by flunderpero** [comment]
If you are not using webpack for much else (like we do - we use it for styleguidist exclusively and esbuild everwhere else) you could try the workaround I posted here: https://github.com/styleguidist/react-styleguidist/issues/1785

**Comment by elevatebart** [comment]
Great find, 
Thank you for investigating.

I will try to get a fix into RSG ;)

**Comment by karx** [comment]
@flunderpero could you share how your `styleguide.config.js` looks like?

I am trying to get this work by I think I am running in circles.

**Comment by flunderpero** [comment]
Here it is (with all the unrelated stuff :-) ):

```
const path = require("path")
const webpack = require("webpack")

module.exports = {
    assetsDir: "tests/__assets__",
    title: "Last React Material",
    components: "components/*.tsx",
    defaultExample: true,
    require: [path.join(__dirname, "./components/mdc_all.scss")],
    styleguideDir: path.join(__dirname, "dist", "docs"),
    showSidebar: true,
    pagePerSection: true,
    template: {
        head: {
            links: [
                {
                    rel: "preconnect",
                    href: "https://fonts.gstatic.com",
                },
                {
                    href:
                        "https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined",
                    rel: "stylesheet",
                },
                {
                    href: "https://fonts.googleapis.com/css2?family=Roboto:wght@300;400",
                    rel: "stylesheet",
                },
            ],
        },
    },
    theme: {
        fontFamily: {
            base: '"Roboto", sans-serif',
        },
        fontSize: {
            text: 15,
            h1: 36,
            h2: 24,
            h3: 18,
            h4: 16,
            h5: 15,
            h6: 15,
        },
        baseBackground: "#fdfdfc",
        border: "#e0d2de",
    },
    sections: [
        {
            name: "Introduction",
            content: "README.md",
        },
        {
            name: "Components",
            components: "components/*.tsx",
            exampleMode: "collapse",
            usageMode: "expand",
            sectionDepth: 1,
        },
    ],
    webpackConfig: {
        module: {
            rules: [
                {
                    test: /\.tsx?$/,
                    loader: "ts-loader",
                    exclude: /node_modules/,
                    options: {
                        transpileOnly: true,
                    },
                },
                {
                    test: /\.scss$/,
                    use: ["style-loader", "css-loader", "sass-loader"],
                },
            ],
        },
        resolve: {
            extensions: [".tsx", ".ts", ".js", ".jsx", ".scss"],
        },
        plugins: [
            new webpack.DefinePlugin({
                process: {env: {}},
            }),
        ],
    },
}
```

**Comment by kgilden** [comment]
Sorry to necromance this. @elevatebart is there any way I could help move this forward? Do I understand correctly that this is rather a problem of react-styleguidist than  vue-styleguidist? Yet the dependency is pinned in this repository?

**Comment by timurcatakli** [comment]
I fixed this issue by adding below to webpack v5
```
      new webpack.DefinePlugin({
        process: { env: {} },
      }),
```
