### ISSUE TITLE
vue-docgen-api: get values from array Identifier

### ISSUE THREAD

**Issue by afontcu** [vue-styleguidist/vue-styleguidist#1049]
**The problem**

AFAICT there's no way to get the prop default values from `validator` function if the array comes from a variable.

```js
// works.
myProp: {
  type: String,
  validator: (prop) => ['top', 'bottom', 'right', 'left'].includes(prop),
},
```
```js
// does not work.
// assume validPropValues is defined somewhere else (potentially imported?)
myProp: {
  type: String,
  validator: (prop) => validPropValues.includes(prop),
},

```

**Proposed solution**

I'm not even sure this is doable, to be honest 😅 I assume [`extractStringArray`](https://github.com/vue-styleguidist/vue-styleguidist/blob/025ad018a646e6a74d37f6cf85bade8e11348c60/packages/vue-docgen-api/src/script-handlers/utils/parseValidator.ts#L16) should handle the case where `valuesObjectNode` is an Identifier, but I'm lost on how to get the values from there.

I assume covering all cases is impossible, but maybe some sort of static inference would allow for simple variables to be picked up.

If this is possible, I'd like to tackle it very much :)

Thanks!

_ps: I checked and I couldn't find a similar issue, so I opened a new one. Excuse me if it's not the case!_

**Comment by elevatebart** [comment]
Hello @afontcu ,

That's a great point you are making here: Often the set of valid values is shared by multiple components. It, therefore, makes sense to store the set of values in a shared file. 

From a perf standpoint, it means that every time we see a .includes with a variable we could potentially resolve the set of values, by reading an extra file. 

The enhancement it brings would probably outweigh the perf cost.

I already did a little variable resolution in [resolveExportedComponent.ts](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/src/utils/resolveExportedComponent.ts) both in the same files and imported variables.

If you have time to help, I would love a PR.
Thank you

**Comment by afontcu** [comment]
That's great to hear!

> If you have time to help, I would love a PR.

Sure, let me take a look and see what I can come up with :) I'll try to set up a PR and we can work it out from there 😃
