### ISSUE TITLE
vue-docgen-api: error when compiling v-else in functional pug templates

### ISSUE THREAD

**Issue by qnp** [vue-styleguidist/vue-styleguidist#1052]
**Current behavior**

Compiling this template:

```vue
<template lang="pug" functional>
  div
    div(v-if="true") foo
    div(v-else) bar
</template>
```

in a `vue-cli-3` project through `vue-cli-plugin-docgen` will fail with:
```
Error: Could not parse template expression: v-else
```

**To reproduce**

Just try to apply vue-docgen to the component above.

**Expected behavior**

The compilation should succeed.

**Reasons**

I have performed deep insights into the source code to understand that this is an issue with pug compilation that has already been coined in other projects: by default, Pug does compile `div(v-else)` into `<div v-else="v-else">bar</div>` and thus the `vue-docgen-api` fails to understand expression `v-else`.

**Solution**

The simple and immediate solution is to pass `doctype: "html"` option to `pug.compile` or `pug.render`. (see for example the [pug-plain-loader](https://github.com/yyx990803/pug-plain-loader/blob/master/index.js) source).
Thanks to the great dev behind vue-styleguidist, the `pugOptions` can be passed through all the pipe to the pug compiler via `apiOptions` of `docgen.config.js`! Just add:
```js
module.exports = {
  apiOptions: {
    pugOptions: { doctype: 'html' },
  },
};
```
so this is an immediate fix for those who find the same issue. Meanwhile, it should be great to set by default to the pug compiler.

Best regards.

**Comment by elevatebart** [comment]
Great idea, I will change the default settings.

**Comment by elevatebart** [comment]
Unless you prefer to create a PR so that you can claim ownership of the fix you worked hard to find.

I promise I will review it promptly.

**Comment by qnp** [comment]
I'll be glad to be part of this project, thus I'll make the PR.

**Comment by elevatebart** [comment]
closing since the fix has been delivered
