### ISSUE TITLE
Sidebar links are wrong when `pagePerSection` is true

### ISSUE THREAD

**Issue by clenemt** [vue-styleguidist/vue-styleguidist#1054]
**Current behavior**

When running with option: `pagePerSection: true,` the links from the sidebar are wrong for all components.

It shows `http://localhost:6060/#/-?id=button` instead it should probably show `http://localhost:6060/#button`.

**To reproduce**

Reproducible with any example form the example folder (tried with basic but should be same for all)

**Expected behavior**

Actual
![image](https://user-images.githubusercontent.com/447956/106456597-0495ec80-648e-11eb-84af-9493952ba2ea.png)

Expected
![image](https://user-images.githubusercontent.com/447956/106456749-40c94d00-648e-11eb-961f-2cb1143a069e.png)

**Comment by elevatebart** [comment]
Hello @clenemt 

Thanks for reporting this. This is indeed an inconvenience. 
I will check out the cause of the breakage.

Will keep you posted here.

**Comment by clenemt** [comment]
Thanks for looking in to it 👍  !

I've also tried documenting the props from a `vue-styled-component` but with no success. Is that a limitation currently ?
It renders fine with `export default { extends: Button }`. But it is missing the props.
I can create another issue if needs be.

**Comment by clenemt** [comment]
Thanks for closing this ! 👏
