### ISSUE TITLE
ERROR  Unknown config option tocMode was found, the value is:      'collapse'

### ISSUE THREAD

**Issue by Dragod** [vue-styleguidist/vue-styleguidist#1055]
I am trying to use the accordion like menu but, it gives me an error.

  ```js
//docs.confiig.js
module.exports = {
    // set your styleguidist configuration here
    title: 'Docs',
    pagePerSection: true,
    tocMode: 'collapse',
```

My styleguide is 2 years old so I assume I miss this feature? I can't easily upgrade as I should ask permission to do it.

There is any way I can fix this?
![styleguide](https://user-images.githubusercontent.com/4368630/106589494-5e5cec00-654c-11eb-8def-bbd475a3296b.png)

**Comment by elevatebart** [comment]
The option was added last year (2020) in react-styleguidist. 
I would assume you would have an easier time updating the dependency. 
Without updating the dependency, you have 2 options
- Reverse engineer what is done on vue-design-system (it's a hack and has no guarantees of longevity)
- Customize the table of content, using some ReactJs magic, by following [this recipe](https://vue-styleguidist.github.io/docs/Customize.html).

I hope it helps.

**Comment by Dragod** [comment]
@elevatebart  thanks for taking your time to respond. Appreciate. Thanks!
