### ISSUE TITLE
vuetify Configuration Is not working and Ui did not Build Properly in the example

### ISSUE THREAD

**Issue by sachin-ezee** [vue-styleguidist/vue-styleguidist#1058]
**Current behavior**

vuetify Configuration Is not working and Ui did not Build Properly in the example
https://vue-styleguidist.github.io/vuetify/
https://github.com/vue-styleguidist/vue-styleguidist/tree/dev/examples/vuetify/
**To reproduce**

**Expected behavior**

**Comment by elevatebart** [comment]
Thank you, I missed this one
I should probably have a percy.io check-up.
