### ISSUE TITLE
Nuxtjs Configuration Is not working and Ui did not Build Properly in the example

### ISSUE THREAD

**Issue by sachin-ezee** [vue-styleguidist/vue-styleguidist#1059]
**Current behavior**
Nuxtjs Configuration Is not working and Ui did not Build Properly in the example
https://vue-styleguidist.github.io/nuxtjs/
https://github.com/vue-styleguidist/vue-styleguidist/tree/dev/examples/nuxtjs/

**Notes:-** **I request You to all Possibility check  in the example**

**To reproduce**

**Expected behavior**

**Comment by elevatebart** [comment]
What do you mean here, both components seem to have built properly.

I mean what is the intended behavior?

**Comment by sachin-ezee** [comment]
**CounterButton** Component is not Build Properly in example if it is ok then no issue

![Screenshot from 2021-02-12 12-43-19](https://user-images.githubusercontent.com/60382030/107739909-fa96a800-6d2f-11eb-9f68-750229c68ba1.png)

**Comment by elevatebart** [comment]
Thank you very much. that is not intended and a very clear bug report.

I do not know why this is failing in the monorepo. 
It really should not since it does not fail as an independent package.
It feels like a failed update of pnpm. 

I am investigating.

**Comment by elevatebart** [comment]
I believe it is now repaired
