### ISSUE TITLE
Support custom theme color for dataRow background in TableRenderer

### ISSUE THREAD

**Issue by Xiphe** [vue-styleguidist/vue-styleguidist#1065]
**Current behavior**

Currently, the hover background color of the `dataRow` of a TableRenderer is always `#fbfbfb `

This is problematic when using a dark theme for the styleguide since the text can not be read anymore when hovering.

**To reproduce**

See here:
https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-styleguidist/src/client/rsg-components/Table/TableRenderer.js#L27

**Expected behavior**

I would like to use something like `dataRowHover` in the `theme.js` to set a custom color for this.

---

Please let me know what you think, I'm open to providing a PR for this.

**Comment by elevatebart** [comment]
Hello @Xiphe, 

Thank you for the suggestion, I think it could be a great idea.

Note that what you want to do is already possible using the `styles` option [documented here](https://vue-styleguidist.github.io/docs/Customize.html#style-theme)

Through this option, you can override all styles of each of the components.

```js
module.export = {
  styles: {
    Table: {
      dataRow: {
        "&:hover": {
          background: 'red' // you could use a middleground color or use transparent
        }
      }
    }
  }
}
```

For now, the theme structure comes directly from the parent library [react-styleguidist](https://github.com/styleguidist/react-styleguidist) in this file: https://github.com/styleguidist/react-styleguidist/blob/master/src/client/styles/theme.ts.

If you find an elegant way to extend the theme, this would probably be super useful.

**Comment by Xiphe** [comment]
Cool! Thanks for the styles workaround! I'll probably go with this. But I'll let you know when I got a good idea for the theme extend
