### ISSUE TITLE
vue-docgen-api: failed to parsed when exported component use "as" with typescript 

### ISSUE THREAD

**Issue by mercs600** [vue-styleguidist/vue-styleguidist#1066]
**Current behavior**
We have exported components this way (for better typing extended components with composition api)
```ts
import { defineComponent } from '@vue/composition-api'
import CeHeader from './CeHeader'

const CeHeaderTheme = defineComponent({
  extends: CeHeader
})

export default CeHeaderTheme as typeof CeHeader
```

But this way of exporting causes warnings in storybook: 
```
[vue-docgen-loader] failed to parse the component file with docgen-api: No suitable component definition found on...
```

**To reproduce**

Just export some component as default and add some as typeof operator:

```ts
export default {
  name: 'Test'
} as {
  name: string
}
```
**Expected behavior**

I would like to use "as" operator without any warnings.

**Comment by elevatebart** [comment]
Hello @mercs600,

Sorry for being late to the party, I just got back on this.
It might take a little longer or be a little messier to deliver a fix as I am discovering parenthood.

If you feel like diving into this issue yourself this would be super awesome.

A quick architecture tip on how to approach it:

`vue-docgen-api` is a static analysis tool. 
It looks at your code and extracts what it can from it. 
It never executes it.
This bring it lightning speed, but has a few caveats.

On how it works:

1. Use [babel](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/src/babel-parser.ts) to parse the code
1. Find [where the exports](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/src/utils/resolveExportDeclaration.ts) are in the file
1. Determine if [each export is a components](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/src/utils/resolveExportedComponent.ts) (you don't want to parse and expose constants or misc functions)
1. Extract the found components into an AST variable
1. Apply all the ["handlers"](https://github.com/vue-styleguidist/vue-styleguidist/tree/dev/packages/vue-docgen-api/src/script-handlers) for each expected item you are supposed to find: props, events, slots
1. [Repackage](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/src/Documentation.ts#L100) the final dynamic object into a serializable item


I would probably update `resolveExportedComponent`. Create a test, debug it in jest, and see what is missing to discover the component, then add it and update.

Finally, make a PR. I can absolutely review it.

**Comment by elevatebart** [comment]
I found the time today to look at this issue and it felt simple enough to fix on the spot.

Thank you for your patience.

**Comment by mercs600** [comment]
@elevatebart thank you, I really appreciate it ❤️
