### ISSUE TITLE
Named export with Vue.extend does not extract props, slots, etc

### ISSUE THREAD

**Issue by kris-ellery** [vue-styleguidist/vue-styleguidist#1069]
**Current behavior**

When I use a TSX component with named export, the `vue-docgen-api` does not extract props, slots, etc. When I switch to default export, it works fine.

```tsx
// Works
export default Vue.extend({ // ... });
```

```tsx
// Does not work
export const Component = Vue.extend({ // ... });
```

**To reproduce**

In both cases please view devtools console and compare pass/fail objects.

- CodeSandbox: https://codesandbox.io/s/vigorous-moser-phvoc
- GitHub repository: https://github.com/kris-ellery/vue-docgen-api-bug

<img width="604" alt="Screen Shot 2021-03-18 at 9 11 14 PM" src="https://user-images.githubusercontent.com/2780894/111721750-88354e00-882e-11eb-918e-5380587c6aba.png">

I tried to figure out the issue, but couldn't pin-point the exact file or function. Possibly a related issue: https://github.com/vue-styleguidist/vue-styleguidist/issues/813

**Expected behavior**

Both default and named exports with `Vue.extend({});` should return complete `ComponentDoc` output.

**Comment by elevatebart** [comment]
Very clear bug report makes for an easy fix ;)

**Comment by kris-ellery** [comment]
@elevatebart thank you for your work on this issue! I applied changes locally, in `node_modules`, and I can see props and slots arrays. Cheers!
