### ISSUE TITLE
Provide a "dark mode" switch

### ISSUE THREAD

**Issue by trajano** [vue-styleguidist/vue-styleguidist#1073]
**The problem**

I am trying to make a set of controls that have different colors when the user preference is dark mode vs light mode.

**Proposed solution**

Something like what https://developer.microsoft.com/en-us/fluentui#/controls/ios/button does where there's switcher.

Since the switch would be localized, it should allow some sort of configuration as to the additional class being set for "dark mode"

**Alternative solutions**

I am thinking I have to add some sort of custom control

**Additional context**

**Comment by elevatebart** [comment]
You can get inspiration here 

https://github.com/styleguidist/react-styleguidist/issues/1691

or here

https://github.com/styleguidist/react-styleguidist/issues/53
