### ISSUE TITLE
vue-docgen-cli support ignore node_modules

### ISSUE THREAD

**Issue by falstack** [vue-styleguidist/vue-styleguidist#1075]
`vue-docgen-cli` will get all file of path：[code](https://github.com/vue-styleguidist/vue-styleguidist/blob/264adc38d83c6c373cf6566ae2bf67ea02335bd1/packages/vue-docgen-cli/src/getSources.ts#L25)

when i start node server（yarn2 monorepo），node_modules will be scan...

[glob](https://github.com/isaacs/node-glob#options) option can ignore node_modules

``` javascript
module.exports = {
  ignore: 'node_modules',
  apiOptions: {
    jsx: true
  }
}
```

**Comment by elevatebart** [comment]
Since `vue-docgen-cli` uses https://github.com/sindresorhus/globby you can use a negation using "!"

```js
module.exports = {
	components: ["**/components/*.js", "!**/node_modules/**/*.js"]
}
```

**Comment by falstack** [comment]
thanks
