### ISSUE TITLE
Problem with live-reload when built in prod mode

### ISSUE THREAD

**Issue by ol-ko** [vue-styleguidist/vue-styleguidist#1078]
**Current behavior**

With:

-  an application created with @vue/cli@4.5.12
- styleguide config modified insignificantly (defined sections and set pagePerSection to true) 
- styleguide built with NODE_ENV=production 
 
there is an error `ReferenceError: e is not defined at Object.<anonymous> (compiler.ba42cdc8.js:2)` when editing component code in the live preview. 

**To reproduce**

Clone repo https://github.com/ol-ko/vue-styleguidist-issue, install dependencies and run `NODE_ENV=production yarn build` and serve the resulting styleguide as an http-server. 

**Expected behavior**

When editing code in live preview the changes get applied to the preview and no errors are thrown.

**Comment by elevatebart** [comment]
Thank you @ol-ko ,

I do not know why I do not test this in my examples. It seems like an obvious way to optimize make the components. I am therefore glad that you bring this to my attention.

### Diagnosis

The webpack.config returned by `@vue/cli` in production mode is missing a part of the compiler. It is likely tree shaken out of existence.

### Solutions

Either we load our own version of the compiler, but this might be heavy or we replace those functions by a lighter version, but this would be custom and not future proof. 

In any case, I will check what is wrong and make sure you can use `NODE_ENV=production` if it is at all possible.
