### ISSUE TITLE
Automatic Valid Prop Value Detection

### ISSUE THREAD

**Issue by MentalGear** [vue-styleguidist/vue-styleguidist#1083]
Thanks for your work on this; looking forward to use it with nuxt!
While going over the guide, I noticed the following.

**The problem**
Manually defining valid prop value only for the docs is redundant and requires manual adjustments when code changes.

```
/**
 * The size of the button
 * @values small, normal, large
 */
size: {
  type: String,
  default: 'normal'
},
```

**Proposed solution**
Instead, it would be ideal if valid values would be extracted automatically.

Vue has already a solution for this:
```
// Custom validator function
size: {
  type: String,
  default: 'normal'
  validator: function (value) {
    // The value must match one of these strings
    return ['small', 'normal', 'large'].indexOf(value) !== -1
  }

```

**Comment by elevatebart** [comment]
Hello @MentalGear,

I have great news for you!

It already works, with a different code style.

https://github.com/vue-styleguidist/vue-styleguidist/blob/b1e867acfa310d56ece72dc6ffdc87bc49b6bce6/packages/vue-docgen-api/src/script-handlers/__tests__/propHandler.ts#L499-L583

Namely, if your validation rule is formatted like so, it extracts the values: 

```js

{
validator(va){
				return ['dark', 'light', 'red', 'blue'].indexOf(va) > -1
			}

}
```

I will add the format your are using to the accepted formats.
Will this help ?

**Comment by MentalGear** [comment]
> I will add the format your are using to the accepted formats.
> Will this help ?

Awesome, thanks for the super quick adjustment, @elevatebart !
I assume the name of the value (va/value) can be anything ... Thinking out loud here: maybe a regex could retrieve all lines with "return" in a validation function. Then the values returned could be extracted (split values if an array) and proposed as valid values for the guide. Maybe that'd be another, maybe a more generalized, approach? Maybe not. (let me know what you think)
