### ISSUE TITLE
Yarn 2 issue: YN0002: vue-docgen-api@npm:4.38.1 doesn't provide vue (p363e3), requested by @vue/compiler-sfc

### ISSUE THREAD

**Issue by spiltcoffee** [vue-styleguidist/vue-styleguidist#1089]
**Current behavior**

* Trying to use a project that depends on `vue-docgen-api@4.38.1`
* When using Yarn 2 (`yarn -v` = 2.4.1), the following message appears:

```
$ yarn
...
➤ YN0002: │ vue-docgen-api@npm:4.38.1 doesn't provide vue (p363e3), requested by @vue/compiler-sfc
...
$ yarn explain peer-requirements p363e3
➤ YN0000: vue-docgen-api@npm:4.38.1 doesn't provide vue, breaking the following requirements:

➤ YN0000: @vue/compiler-sfc@npm:3.0.11 [fc8b1] → 3.0.11 ✘
```

**To reproduce**

package.json:
```json
{
  "dependencies": {
    "vue-docgen-api": "^4.38.1"
  }
}
```

Yarn 2:
```
$ yarn set version berry
$ yarn
```

**Expected behavior**
After reading through Yarn 2's docs (https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency), the behavior I expect here is for `vue-docgen-api` to clearly define it's dependency on `vue`, likely as a `peerDependency`.

**Comment by elevatebart** [comment]
Thank you @spiltcoffee 

I am not super familiar with yarn 2.
In `vue-docgen-api`, I use the `@vue/compiler-sfc` 
- to split components between script, style and template
- to parse the template for comments, blocks and other items

Those could be vue2 or vue3 components indistinguishably.
Yarn is asking me here to have a vue 3 peerDependency, therefore dropping all vue 2. 
I cannot have that yet. I would be OK if there was a v2 v3 peer dependency

```json
"peerDependencies": {
  "vue": ">=2"
}
```

If you make a Pull Request with this change I will make sure to deliver it during the next days so you can try.

An alternative would be to maintain two channels one for vue2 and one for vue3. Double the work. I do not know if I can do that either.

**Comment by spiltcoffee** [comment]
Hey @elevatebart,

It seems specifying `">=2"`  would just change the nature of Yarn 2's complaint.

I can achieve this without a change at the moment, as a test, using the `packageExtensions` feature (https://yarnpkg.com/configuration/yarnrc#packageExtensions) in Yarn 2's `.yarnrc.yml` (this is a project specific Yarn 2 file that sits next to the `package.json`).

For example, I can add this to my `.yarnrc.yml`:
```yml
packageExtensions:
  vue-docgen-api@4.38.1:
    peerDependencies:
      vue: ">= 2"
```

Let's say I then changed my `package.json` to the following:
```json
{
  "name": "@spiltcoffee/test",
  "dependencies": {
    "vue": "^2.6.12",
    "vue-docgen-api": "^4.38.1"
  }
}
```

This configuration gets rid of the original message from Yarn 2, however now I see a new message:
```
$ yarn
...
➤ YN0060: │ @spiltcoffee/test@workspace:. provides vue (p820e2) with version 2.6.12, which doesn't satisfy what vue-docgen-api and some of its descendants request
...
$ yarn explain peer-requirements p820e2
➤ YN0000: @spiltcoffee/test@workspace:. provides vue@npm:2.6.12 with version 2.6.12, which doesn't satisfy the following requirements:

➤ YN0000: @vue/compiler-sfc@npm:3.0.11 [18f7a] → 3.0.11 ✘
➤ YN0000: vue-docgen-api@npm:4.38.1 [b0459]    → >= 2   ✓

➤ YN0000: Note: these requirements start with vue-docgen-api@npm:4.38.1 [b0459]
```
(For reference, YN0060: https://yarnpkg.com/advanced/error-codes#yn0060---incompatible_peer_dependency )

I tried replacing `>=2` with a `*` but it seems like that's not the issue now - instead, it looks like in order for me to satisfy `@vue/compiler-sfc`, I need to provide `vue@^3.0.11`. Is this an issue with the upstream project's dependency, perhaps?

p.s. I should clarify here, and as mentioned in the documentation for YN0060 above, Yarn 2 reports these as error codes, but a `yarn install` will still complete successfully even with these error codes showing up, usually. These errors are reported, however, since it might be indicative of an underlying issue with the packages available vs. a package that was expected (i.e., in this case, maybe something actually does expect `vue@3` and I only provide it `vue@2`, causing issues).

**Comment by PhyberApex** [comment]
I have a similar issue. Problem seems to stem from the peerDep in @vue/compiler-sfc which you use 3.0.7 of. If you could update to >3.2.0 that'd be great because the peer dependency was removed there (https://github.com/vuejs/vue-next/commit/bb7b130b0b47fe653cd3edf2924e7576743dd738#diff-5f88be6542dd06b3b15b7a67743c5698bf8b354d13fc7acf1eca3626731ef493)

I would open a PR but I am not familiar with mono-repos as of now and don't want to break too much  :)

**Comment by elevatebart** [comment]
Oh great !!! I'll make sure this is fixed ASAP

**Comment by PhyberApex** [comment]
That was very fast! Thanks!
