### ISSUE TITLE
I use nuxt + tailwind + vue-styleguidist

### ISSUE THREAD

**Issue by davodaslanifakor** [vue-styleguidist/vue-styleguidist#1091]
Hi.
I need show example in *.vue file project , I use Nuxt and @nuxtjs/tailwindcss 
when use tag <docs> for load my example style won't load.
and show in inspect 
![image](https://user-images.githubusercontent.com/14367811/117158658-de595300-add4-11eb-85f9-966f4c1d1919.png)

I need config my nuxtjs/tailwindcss  for vue-styleguid.config.
Please let me a config for resolve this solation.

**Comment by elevatebart** [comment]
Hello @davodaslanifakor 

You hit this bug https://github.com/nuxt/nuxt.js/issues/9190 which makes it hard to get the proper webpack config from nuxt modules like tailwind. It should all work out of the box, once it is fixed.

What you have to do in the menatime is not dissimilar to what is done here

https://github.com/CodyBontecou/nuxt-tailwindcss-cypress-component-test/blob/6968c8a115a7ab3b4a5acdba393406a275bf7466/cypress/plugins/index.js#L14-L31

Add tailwind on your own since it is not added to webpack config automatically.

I hope this helps.

**Comment by davodaslanifakor** [comment]
Hi @elevatebart ,
Thanks for your answer.
I should sent my code styleguid.config  


```// eslint-disable-next-line no-unused-vars
const { resolve } = require("path")
const tailwindPostCSSplugin = require("tailwindcss")
const nuxtDefaultTailwindConfig = require("@nuxtjs/tailwindcss/dist/runtime/tailwind.config.js")
const { getWebpackConfig } = require("nuxt")
console.log(getWebpackConfig)
const FILTERED_PLUGINS = [
  "WebpackBarPlugin",
  "VueSSRClientPlugin",
  "HotModuleReplacementPlugin",
  "FriendlyErrorsWebpackPlugin",
  "HtmlWebpackPlugin"
]

const docSiteUrl =
  process.env.DEPLOY_PRIME_URL || "https://vue-styleguidist.github.io"

/** @type import("vue-styleguidist").Config */
module.exports = async (on, config) => {
  // get the webpack config directly from nuxt
  const nuxtWebpackConfig = await getWebpackConfig("client", {
    for: "dev",
    configOverides: {
      tailwindcss: {
        jit: false
      }
    }
  })

  const webpackConfig = {
    module: {
      rules: [
        ...nuxtWebpackConfig.module.rules.filter(
          // remove the eslint-loader
          (a) => a.loader !== "eslint-loader"
        )
      ]
    },
    resolve: { ...nuxtWebpackConfig.resolve },
    plugins: [
      ...nuxtWebpackConfig.plugins.filter(
        // And some other plugins that could conflcit with ours
        (p) => !FILTERED_PLUGINS.includes(p.constructor.name)
      )
    ]
  }

  webpackConfig.module.rules
    // find the laoder for css
    .find((r) => r.test.toString().includes("css"))
    // avoid touching anything with modules
    .oneOf.find((l) => !l.resourceQuery)
    // find the postcss loader
    .use.find((m) => m.loader.includes("postcss"))
    // add the tailwind plugin
    .options.plugins.push(tailwindPostCSSplugin(nuxtDefaultTailwindConfig))

  return {
    components: "components/**/*.vue",
    ribbon: {
      text: "Back to examples",
      url: `${docSiteUrl}/Examples.html`
    },
    webpackConfig,
    usageMode: "expand",
    styleguideDir: "dist"
  }
}
```

this have one problem error when run vue-styleguidist server --config styleguide.config.js

![image](https://user-images.githubusercontent.com/14367811/117402619-fc7d9b00-af1b-11eb-9196-b8abea007650.png)


remember i change patch  nuxtDefaultTailwindConfig because cant find this url 
```
const nuxtDefaultTailwindConfig = require("@nuxtjs/tailwindcss/lib/files/tailwind.config");
```
![image](https://user-images.githubusercontent.com/14367811/117403640-baedef80-af1d-11eb-9754-0a42471ef0ac.png)

So please show me complete  example styleguide.config.js for nuxt and Tailwind.
Thank u again.

**Comment by davodaslanifakor** [comment]
Oh I foregut Say I use 

```
      "node-sass": "^5.0.0",
     "sass": "^1.32.11",
    "sass-loader": "10.1.1",
    "tailwindcss-rtl": "^0.7.3",

```

in my project
please check it for config.

**Comment by antoineabbou** [comment]
Hello @elevatebart, any news on this issue ? I've got the same problem here.

**Comment by davodaslanifakor** [comment]
Hey @elevatebart 
We wait for this task.

**Comment by davodaslanifakor** [comment]
Any news from this task @elevatebart ?

**Comment by S0NN1** [comment]
@elevatebart I'm trying to reproduce a working config from the one provided but the amount of unnecessary configs from both cypress and your tailwind path makes it really difficult.
By following the tailwind guide, my tailwind.config.js is placed under the root directory of my project but I can't find the correct path to include in the require statement. 
I have never dealt with webpack so if you would provide a better example it would be great!

**Comment by elevatebart** [comment]
Would this setup help anyone here? https://github.com/elevatebart/test-nuxt

**Comment by elevatebart** [comment]
Conceptually, cypress Component Testing and vue-styleguidist work the same. 
Since each component is displayed in isolation they lack a common root.

In a proper app, this root is called `main.js`. In a Nuxt app, it is abstracted away.
Everything that is done in this root needs to be done for components to look correct in the examples.

Building that common root is the purpose of [renderRootJsx](https://vue-styleguidist.github.io/Configuration.html#renderrootjsx). Check out the example in [this file of the example](https://github.com/elevatebart/test-nuxt/blob/master/styleguide/styleguide.root.js)

**Comment by davodaslanifakor** [comment]
please keep it.

**Comment by elevatebart** [comment]
@davodaslanifakor without a reproduction repository, it is very hard to diagnose what is happening.

Using Nuxt + tailwind + styleguidist is done in [this example repo](https://github.com/elevatebart/test-nuxt) and it seems to work fine.

**Comment by davodaslanifakor** [comment]
@elevatebart Great. I check out your example code.
It work fine.
