### ISSUE TITLE
Props from mixin object aren't parsed

### ISSUE THREAD

**Issue by distantnative** [vue-styleguidist/vue-styleguidist#1092]
**Current behavior**

Props defined in a constant that works as a mixin don't show up in the results of using `vue-docgen-api`'s `parse` method.

We are keeping all props in a separate mixin object which gets exported as well (mainly because we have e.g. a UrlInput and a UrlField component - in this way the UrlField component can easily take on the same props from UrlInput plus additional ones).

**To reproduce**

```js
export const props = {
  props: {
    autocomplete: {
      type: String,
      default: "url"
    },
    type: {
      type: String,
      default: "url"
    }
  }
}

export default {
  mixins: [props]
}
```

Output generates no props data at all.

**Expected behavior**

Output should feature data on `autocomplete` and `type` prop.

**Comment by elevatebart** [comment]
Hey @distantnative, Great find!

Vue-docgen-api resolves mixins from other files but for some reason does not resolve them in the same file. That needs to be fixed.

**Comment by distantnative** [comment]
@elevatebart any chance that his gets solved soon? Honest answer appreciated - we all know that open source projects are tough, just trying to make plans if we need to look for an alternative solution as this is blocking our current project :) Thanks for the great work!

**Comment by elevatebart** [comment]
Hey @distantnative,

I appreciate the concern. You will get a fix or an answer probably by tonight.

In any case, this does not seem like a complicated fix. I do not expect it to take more than a week to fix.

**Comment by elevatebart** [comment]
What needs to be done for both the mixin and the extends is:

- Resolve local variables into AST paths
	- declaration with const/var/let and export const 
- Execute all the handlers on those found astPaths
	- We need to first expose the `ExecuteHandlers` function from `parse-scripts.ts`
	- We need to move the resolution of extra script handlers from `parse.ts` to this function (or a wrapper of this function) so if user specifies additional handlers, they are used on the local mixin too.

I will do that during next week unless you feel like making a PR.
I hope it will be fast enough.

**Comment by elevatebart** [comment]
I just saw one hiccup, we have to be careful, to respect the order in which the mixins are written to avoid mistakes. 
In other words, we have to be able to successively run mixins from another file and mixins in the same file one aftre another.

**Comment by distantnative** [comment]
As much as I would like to help, I'm not nearly close to being as familiar with the code to start working on this myself 🙈

**Comment by distantnative** [comment]
On first look, works great in our setup. Thanks a lot for the effort and so quickly!
