### ISSUE TITLE
Error cannot read property compile of undefined

### ISSUE THREAD

**Issue by rothsandro** [vue-styleguidist/vue-styleguidist#111]
I have a new vuejs project (with the webpack template) and try to start the vue-styleguidist dev server but I get an error.

It works fine if I install version 1.4.7 (the previous version) of vue-styleguidist.

**Versions:**
vue-styleguidist@1.7.2
webpack@3.11.0
webpack-dev-server@2.11.2
NPM 5.8.0, Node 6.11.0

Error log:
```
> vue-styleguidist server

TypeError: Cannot read property 'compile' of undefined
TypeError: Cannot read property 'compile' of undefined
    at addCompilerHooks (....../node_modules/vue-styleguidist/node_modules/webpack-dev-server/lib/Server.js:71:15)
    at new Server (....../node_modules/vue-styleguidist/node_modules/webpack-dev-server/lib/Server.js:81:5)
    at createServer (....../node_modules/vue-styleguidist/scripts/create-server.js:28:20)
    at server (....../node_modules/vue-styleguidist/scripts/server.js:5:21)
    at commandServer (....../node_modules/vue-styleguidist/bin/styleguidist.js:121:19)
    at Object.<anonymous> (....../node_modules/vue-styleguidist/bin/styleguidist.js:70:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! expandli-fe@1.0.0 styleguide: `vue-styleguidist server`
npm ERR! Exit status 1
```

**Comment by viljamis** [comment]
I am guessing this is happening since Webpack 3 isn’t supported anymore and Vue Webpack templates don’t yet really have support for Webpack 4.

**Comment by rothsandro** [comment]
OK, I've seen that Webpack 4 is supported with the latest release but didn't know that Webpack 3 isn't supported anymore (should be mentioned in the release notes).

I think I'll use v1.4.7 until the webpack template for Vue is updated (there is an issue for that https://github.com/vuejs-templates/webpack/issues/1280)

**Comment by viljamis** [comment]
@rothsandro Yeah, I’m doing the same with a few projects now since also have dependencies in them that don’t yet support the latest Webpack :-)

**Comment by rafaesc** [comment]
@rothsandro @viljamis I think that webpack 4 it shouldn't be a dependency because there are still projects with that version.

Please try with beta version
`npm install vue-styleguidist@1.7.3-beta.1`
And let me know if it works.

**Comment by viljamis** [comment]
@rafaesc This indeed seems to works for with Webpack 3 and the Vue Webpack template, although now I’m getting another error in Chrome’s console which says:

```
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Playground (created by Examples)
    in article (created by ExamplesRenderer)
    in ExamplesRenderer (created by Styled(Examples))
    in Styled(Examples) (created by Examples)
    in Examples (created by ReactComponent)
    in div (created by ReactComponentRenderer)
    in ReactComponentRenderer (created by Styled(ReactComponent))
    in Styled(ReactComponent) (created by ReactComponent)
    in ReactComponent (created by Components)
```

…but I’m thinking this might be related now to something else entirely?

**Comment by rafaesc** [comment]
@viljamis It's strange, it doesn't seem to be webpack relation.

When I tried an example, I couldn't see that. Please can you share a repository with this issue, I would like to fix it.

Thanks!

**Comment by viljamis** [comment]
@rafaesc I managed to fix that issue, it was related to my styleguidist config file which was using wrong formatting. Everything seems to be working now!

**Comment by rafaesc** [comment]
@viljamis Perfect!!, so, I publish a new stable version, with this commit

https://github.com/vue-styleguidist/vue-styleguidist/commit/122e9e25c444a14237bb8ad756bbba9a6bba72f2

**Comment by viljamis** [comment]
Sounds veeery nice 👍
