### ISSUE TITLE
Keeping both pagePerSection and navigation options

### ISSUE THREAD

**Issue by viljamis** [vue-styleguidist/vue-styleguidist#113]
Hi @rafaesc! This isn’t really an issue, more of a conversation starter/question:

I noticed that the old navigation option got completely replaced with the new pagePerSection functionality from React Styleguidist. While I personally do prefer this for very large documentations, I’m wondering if it would’ve made sense to keep the old option as well, as in many cases it might make more sense when you have less components and documentation. 

The old navigation option also allowed us to build something like this: https://vueds.com/example/#!/Design%20Tokens (having both markdown docs and multiple components in one view). 

So all in all feel like it got removed too quickly as you had some great thinking behind it. :-)

**Comment by rafaesc** [comment]
Hi @viljamis ,

Yes, I agree with you and it's possible generate the option. Before, I validated the navigation isolate per level deep, maybe it should be the way to setting this behaviour.

An example
```js
{
//...
  navigation: {
    active: true,
    filterPerLevel: 2
  }
}
```
It's a idea, I would like more feedback to manage this setting, and maybe I would have to change the name from `navigation` to `pagePerSection` to I can create a PR in react-styleguidist to standard it.

**Comment by viljamis** [comment]
I’d love to see something like that. Before proceeding further I’d want to get feedback from @sapegin as well as it would make sense to try to keep these projects as much aligned as possible.

@sapegin, any thoughts on this? See my first comment and the example I provided. Happy to also talk in more detail about this with you.
