### ISSUE TITLE
No rendering of components

### ISSUE THREAD

**Issue by upandfine** [vue-styleguidist/vue-styleguidist#114]
> You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

- vue-cli 3.0
- vuetify integrated

**Comment by philwolstenholme** [comment]
I'm seeing this too

**Comment by philwolstenholme** [comment]
Following this comment helped, but it looks like a workaround:

https://github.com/rafaesc/vue-konva/issues/3#issuecomment-362099662

**Comment by philwolstenholme** [comment]
If you don't want to alter your `vue.config.js` file, then this in `styleguide.config.js` works too::

``` javascript
  webpackConfig: Object.assign(
    {},
    require('./node_modules/@vue/cli-service/webpack.config.js'),
    {
      // The workaround below is to prevent a styleguidist problem
      // https://github.com/vue-styleguidist/vue-styleguidist/issues/114#issuecomment-383599000
      resolve: {
        alias: {
          vue$: 'vue/dist/vue.js',
        },
      },
    }
  ),
```

**Comment by rafaesc** [comment]
Great @philwolstenholme,

Left another solution

```js
webpackConfig: {
  module: require("./node_modules/@vue/cli-service/webpack.config.js").module
},
```

**Comment by elevatebart** [comment]
You can as well use the [vue-cli-plugin](vue-styleguidist/vue-cli-plugin-styleguidist).
Closing
