### ISSUE TITLE
<script lang="ts"></script> Not supported

### ISSUE THREAD

**Issue by kTelyakov** [vue-styleguidist/vue-styleguidist#1148]
**Current behavior**

When i'm trying to start styleguidist, he crashed with inexplicit error
```
You can now view your style guide in the browser:

  Local:            http://localhost:6060/
  On your network:  http://192.168.1.101:6060/

 FAIL  Failed to compile

./src/testDir/Hello.vue?vue&type=script&lang=ts& (./node_modules/ts-loader!./node_modules/vue-loader/lib??vue-loader-options!./src/testDir/Hello.vue?vue&type=script&lang=ts&)
TypeError: loaderContext.getOptions is not a function
 @ ./src/testDir/Hello.vue?vue&type=script&lang=ts& 1:0-158 1:174-177 1:179-334 1:179-334
 @ ./src/testDir/Hello.vue
 @ ./node_modules/vue-styleguidist/lib/loaders/styleguide-loader.js!./node_modules/vue-styleguidist/lib/client/index.js
 @ ./node_modules/vue-styleguidist/lib/client/index.js
 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./node_modules/vue-styleguidist/lib/client/index
```
PACKAGE.json
```
{
  "name": "someProject",
  "version": "1.0.0",
  "description": "",
  "main": "lib/index.js",
  "module": "lib/index.esm.js",
  "author": "",
  "license": "ISC",
  "sideEffects": [
    "*.scss",
    "*.css",
    "*.vue"
  ],
  "size-limit": [
    {
      "path": "lib/index.js"
    }
  ],
  "scripts": {
    "build": "npm run treeshake && rollup -c",
    "treeshake": "agadoo ./index.ts",
    "size-limit": "size-limit",
    "styleguide": "vue-styleguidist server",
    "styleguide:build": "vue-styleguidist build"
  },
  "devDependencies": {
    "@babel/core": "^7.14.3",
    "@rollup/plugin-alias": "^3.1.2",
    "@rollup/plugin-buble": "^0.21.3",
    "@rollup/plugin-commonjs": "^18.0.0",
    "@rollup/plugin-node-resolve": "^11.2.1",
    "@size-limit/preset-big-lib": "^4.11.0",
    "@vue/compiler-sfc": "^3.0.11",
    "agadoo": "^2.0.0",
    "autoprefixer": "^10.2.5",
    "babel-loader": "^8.2.2",
    "clone-deep": "^4.0.1",
    "husky": "^6.0.0",
    "image-webpack-loader": "^7.0.1",
    "rollup": "^2.45.2",
    "rollup-plugin-peer-deps-external": "^2.2.4",
    "rollup-plugin-postcss": "^4.0.0",
    "rollup-plugin-svg": "^2.0.0",
    "rollup-plugin-terser": "^7.0.2",
    "rollup-plugin-typescript2": "^0.30.0",
    "rollup-plugin-vue": "^5.1.9",
    "sass-loader": "^10.0.0",
    "size-limit": "^4.11.0",
    "ts-loader": "^9.2.3",
    "typescript": "^4.2.4",
    "vue": "^2.6.12",
    "vue-loader": "^15.9.7",
    "vue-loader-plugin": "^1.3.0",
    "vue-styleguidist": "^4.40.0",
    "vue-template-compiler": "^2.6.12",
    "webpack": "^4.46.0"
  },
  "peerDependencies": {
    "vue": "^2.6.11"
  },
  "dependencies": {}
}

```

Styleguide.config.js
```
const VueLoaderPlugin = require('vue-loader/lib/plugin')
module.exports = {
  components: 'src/testDir/*.vue',
  webpackConfig: {
    module: {
      rules: [
        // Vue loader
        {
          test: /\.vue$/,
          exclude: /node_modules/,
          loader: 'vue-loader'
        },
        { test: /\.ts?$/, loader: "ts-loader" },
        // Other loaders that are needed for your components
        {
          test: /\.scss$/,
          loader: 'style-loader!css-loader!sass-loader'
        },
        {
          test: /\.(gif|png|jpe?g|svg)$/i,
          use: [
            'file-loader',
            {
              loader: 'image-webpack-loader',
              options: {
                bypassOnDebug: true, // webpack@1.x
                disable: true, // webpack@2.x and newer
              },
            },
          ],
        }
      ]
    },
    plugins: [
      // add vue-loader plugin
      new VueLoaderPlugin()
    ]
  }
}

```

HELLO.vue
```
<template>
  <h1>HELLO! </h1>
</template>

<script lang="ts">
export default {

}
</script>

<style>

</style>  
```

**Comment by elevatebart** [comment]
What is this `vue-loader-plugin` dependency you are using? 
I do not see this anywhere in the docs of vue.

**Comment by elevatebart** [comment]
You can see here 
`./src/testDir/Hello.vue?vue&type=script&lang=ts& (./node_modules/ts-loader!./node_modules/vue-loader/lib??vue-loader-options!./src/testDir/Hello.vue?vue&type=script&lang=ts&)` the mention of `vue-loader-options!` which is the failing tool. I have never seen such an error before.

It would help a lot if you made a repository to reproduce.

Thank you in advance.

**Comment by zhijunw** [comment]
> **Current behavior**
> 
> When i'm trying to start styleguidist, he crashed with inexplicit error
> 
> ```
> You can now view your style guide in the browser:
> 
>   Local:            http://localhost:6060/
>   On your network:  http://192.168.1.101:6060/
> 
>  FAIL  Failed to compile
> 
> ./src/testDir/Hello.vue?vue&type=script&lang=ts& (./node_modules/ts-loader!./node_modules/vue-loader/lib??vue-loader-options!./src/testDir/Hello.vue?vue&type=script&lang=ts&)
> TypeError: loaderContext.getOptions is not a function
>  @ ./src/testDir/Hello.vue?vue&type=script&lang=ts& 1:0-158 1:174-177 1:179-334 1:179-334
>  @ ./src/testDir/Hello.vue
>  @ ./node_modules/vue-styleguidist/lib/loaders/styleguide-loader.js!./node_modules/vue-styleguidist/lib/client/index.js
>  @ ./node_modules/vue-styleguidist/lib/client/index.js
>  @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./node_modules/vue-styleguidist/lib/client/index
> ```
> 
> PACKAGE.json
> 
> ```
> {
>   "name": "someProject",
>   "version": "1.0.0",
>   "description": "",
>   "main": "lib/index.js",
>   "module": "lib/index.esm.js",
>   "author": "",
>   "license": "ISC",
>   "sideEffects": [
>     "*.scss",
>     "*.css",
>     "*.vue"
>   ],
>   "size-limit": [
>     {
>       "path": "lib/index.js"
>     }
>   ],
>   "scripts": {
>     "build": "npm run treeshake && rollup -c",
>     "treeshake": "agadoo ./index.ts",
>     "size-limit": "size-limit",
>     "styleguide": "vue-styleguidist server",
>     "styleguide:build": "vue-styleguidist build"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.14.3",
>     "@rollup/plugin-alias": "^3.1.2",
>     "@rollup/plugin-buble": "^0.21.3",
>     "@rollup/plugin-commonjs": "^18.0.0",
>     "@rollup/plugin-node-resolve": "^11.2.1",
>     "@size-limit/preset-big-lib": "^4.11.0",
>     "@vue/compiler-sfc": "^3.0.11",
>     "agadoo": "^2.0.0",
>     "autoprefixer": "^10.2.5",
>     "babel-loader": "^8.2.2",
>     "clone-deep": "^4.0.1",
>     "husky": "^6.0.0",
>     "image-webpack-loader": "^7.0.1",
>     "rollup": "^2.45.2",
>     "rollup-plugin-peer-deps-external": "^2.2.4",
>     "rollup-plugin-postcss": "^4.0.0",
>     "rollup-plugin-svg": "^2.0.0",
>     "rollup-plugin-terser": "^7.0.2",
>     "rollup-plugin-typescript2": "^0.30.0",
>     "rollup-plugin-vue": "^5.1.9",
>     "sass-loader": "^10.0.0",
>     "size-limit": "^4.11.0",
>     "ts-loader": "^9.2.3",
>     "typescript": "^4.2.4",
>     "vue": "^2.6.12",
>     "vue-loader": "^15.9.7",
>     "vue-loader-plugin": "^1.3.0",
>     "vue-styleguidist": "^4.40.0",
>     "vue-template-compiler": "^2.6.12",
>     "webpack": "^4.46.0"
>   },
>   "peerDependencies": {
>     "vue": "^2.6.11"
>   },
>   "dependencies": {}
> }
> ```
> 
> Styleguide.config.js
> 
> ```
> const VueLoaderPlugin = require('vue-loader/lib/plugin')
> module.exports = {
>   components: 'src/testDir/*.vue',
>   webpackConfig: {
>     module: {
>       rules: [
>         // Vue loader
>         {
>           test: /\.vue$/,
>           exclude: /node_modules/,
>           loader: 'vue-loader'
>         },
>         { test: /\.ts?$/, loader: "ts-loader" },
>         // Other loaders that are needed for your components
>         {
>           test: /\.scss$/,
>           loader: 'style-loader!css-loader!sass-loader'
>         },
>         {
>           test: /\.(gif|png|jpe?g|svg)$/i,
>           use: [
>             'file-loader',
>             {
>               loader: 'image-webpack-loader',
>               options: {
>                 bypassOnDebug: true, // webpack@1.x
>                 disable: true, // webpack@2.x and newer
>               },
>             },
>           ],
>         }
>       ]
>     },
>     plugins: [
>       // add vue-loader plugin
>       new VueLoaderPlugin()
>     ]
>   }
> }
> ```
> 
> HELLO.vue
> 
> ```
> <template>
>   <h1>HELLO! </h1>
> </template>
> 
> <script lang="ts">
> export default {
> 
> }
> </script>
> 
> <style>
> 
> </style>  
> ```
I have the same problem. Have you solved it

**Comment by elevatebart** [comment]
@zhijunw I would like to investigate this, can you share a minimum repository to reproduce?

If you need help to figure out how to do it, you can reach me on discord or answer here.

I feel there is a hidden issue here.
