### ISSUE TITLE
Instructions for using with projects build with vue-cli

### ISSUE THREAD

**Issue by jkarttunen** [vue-styleguidist/vue-styleguidist#115]
Now starting a project with vue-cli is troublesome, since installing vue-styleguidist fails to peerdependencies, that are already in the project, but installed using vue-cli scripts

**Comment by rafaesc** [comment]
Hi @jkarttunen,

You need to use the webpack config of your vue-cli project, if you run `vue inspect > output.js`, and copy the rules property of `output.js` file on `styleguide.config.js` , it works fine.

https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Configuration.md#webpackconfig

But I will create a new version to vue-cli 3, vue-styleguidist should get the webpack config automatic, in order to you can run vue-styleguidist with less settings

**Comment by philwolstenholme** [comment]
This `styleguide.config.js` line might be useful for Vue CLI 3 users:

```
webpackConfig: require('./node_modules/@vue/cli-service/webpack.config.js'),
```

It loads the webpack Config file that Vue's cli-service provides.

**Comment by rafaesc** [comment]
More alternatives: 

https://github.com/vue-styleguidist/vue-styleguidist/issues/114#issuecomment-383611759

**Comment by ay13** [comment]
Using `webpackConfig: require('./node_modules/@vue/cli-service/webpack.config.js'),` caused an error for me.

```
vue.runtime.esm.js?ff9b:587 [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

(found in <Root>)
```

**Comment by rafaesc** [comment]
@ay13,

Try with

```js
webpackConfig: {
  module: require("./node_modules/@vue/cli-service/webpack.config.js").module
},
```

**Comment by Ettapp** [comment]
@rafaesc As I'm using aliases if I juste do:
```js
module.exports = {
  webpackConfig: {
    module: require("./node_modules/@vue/cli-service/webpack.config.js").module
  },
}
```

I got errors like:
`Module not found: Can't resolve '@/path/to/Component' in '/home/me/Desktop/project/src/vue/dir'`

I tried to include alias by theses kind of ways:
```js
const conf = require("./node_modules/@vue/cli-service/webpack.config.js");

module.exports = {
  webpackConfig: {
    module: conf.module,
    resolve: conf.resolve
  },
}
```
and
```js
module.exports = {
  webpackConfig: {
    module: conf.module,
    resolve: {
      alias: conf.resolve.alias
    }
  },
}
```

Also did the same with only the conf from `vue.config.js`, with the same result: `Module not found`...

I'm currently looking for which rules to include or not, as this comment <https://github.com/vue-styleguidist/vue-styleguidist/issues/114#issuecomment-383611759> broke everything for me.

**Comment by rafaesc** [comment]
Perfect, try to update vue-styleguidist.

If you’re using vue-cli 3.x you can skip the webpack configuration on 1.7.8 version of vue-styleguidist.
