### ISSUE TITLE
Add an example for docgen-api or json output

### ISSUE THREAD

**Issue by wakaryry** [vue-styleguidist/vue-styleguidist#1151]
Hi, thanks for the nice work.

I installed docgen-api with npm. But when I use `parse`, it throws `Can't resolve` all kinds of modules.

I can not run docgen-api correctly.

I can use docgen-cli to out docs. But I do not need the doc. I just want the parsed object.

Could add an example with docgen-api or add an example for json output (just make the parsed object into json).

Thanks.

**Comment by elevatebart** [comment]
Hello @wakaryry 

Can you please describe what you what you are trying to do?
A repository would be super useful.

There are a lot of examples of use of docgen in the repo in the directory `packages/vue-docgen-api/tests` you could find inspiration there.

You can also generate any kind of file using `vue-docgen-cli`.

`templates` will allow you to customize the content from what comes out of docgen. Render json using `JSON.stringify()`.
`getDestFile()` will make it possible to change the name of the output file. Use the .json format you like to render the proper files.

I hope this helps.

**Comment by wakaryry** [comment]
Hi, since when I use `const vueDocs = require('vue-docgen-api')`，it will raise error: `can not resolve xxx module`. I can not make the `vue-docgen-api` run. 

What I need to do is saving the structure of the vue-component.

Such as the JSON:

```json
{
	"props": [
		{
			"name": "title",
			"type": "String",
			"desc": "Title for the cell."
		},
		// ...
	],
	"methods": [
		{
			"name": "xxxx",
			"desc": "xxxxxx"
		},
		// ...
	],
	"slots": [],
	"events": [],
	// ...
}
```

Now the question is that I can not make `vue-docgen-api` run. So I want an example which could run `vue-docgen-api`. Then I could do what I want in the project.

I try to do `const vueDocs = require('vue-docgen-api')` in the docgen example, but I says can not resolve haml-coffee、jazz、...

I can not make it run in project. I can get docs out via docgen example, but can not use the `vue-docgen-api` in the docgen example.

I just add `const vueDocs = require('vue-docgen-api')` in the docgen example, then it goes wrong.

**Comment by elevatebart** [comment]
Is this what you had in mind ?
https://github.com/elevatebart/docgen-api-example

**Comment by wakaryry** [comment]
@elevatebart Thanks a lot. It really helps me.

**Comment by elevatebart** [comment]
If you are satisfied with the answer, feel free to close at your convenience
