### ISSUE TITLE
Documentation for prop in mixin override same name prop documentation in _others_ components

### ISSUE THREAD

**Issue by 0m4r** [vue-styleguidist/vue-styleguidist#116]
If you have a bunch of components, and one of them includes a mixin, all the following components having a prop with the same name already defined in that mixin will have their documentation overridden with the one coming from the mixin.

So, for example, if in `test.mixin.js` you have
```
props: {
  /**
   * a prop from the mixin
   */
  test: {
    type: String,
    required: false,
   default: null
}
```

all the components with the same prop, parsed after this mixin is processed get as a  **Description** _a prop from the mixin_ instead of the _local_ description you might have added in the specific component - that does not use or reference the mixin.

**note**: 
- this happens by simply importing the mixin
- you need to add the  @mixin comment to the mixin code (see: https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Documenting.md#include-mixins)

a use case has been built here:
https://github.com/bwcgn/vue-styleguidist-test/tree/repro/mixin-and-documentation

The HelloWorld component includes a mixin with a prop named testProp, the local testProp documentation is overridden (but the same happens to the testProp of HelloWorld2 component but it does not include the mixin!) The BeforeComponent, instead, looks good.

![screencapture-localhost-6060-2018-04-18-12_54_45](https://user-images.githubusercontent.com/451638/38928070-fb33d3f0-4307-11e8-8db5-634fdecf5d08.png)

Not sure if this somehow relates to #7

**Comment by rafaesc** [comment]
Hi @0m4r,

I will review it

**Comment by rafaesc** [comment]
It fixed on version 1.7.4

**Comment by 0m4r** [comment]
hey @rafaesc I guess that based on this: https://vuejs.org/v2/guide/mixins.html 

> "For example, data objects undergo a shallow merge (one property deep), with the component’s data taking priority in cases of conflicts."

the way the doc works should be the other way around, so, local prop overriding the mixin prop.
It looks to me to be the opposite of what it is now. 

I have updated the repro use case here: https://github.com/bwcgn/vue-styleguidist-test
Let me know if I can help!

Thanks!

**Comment by rafaesc** [comment]
@0m4r Ready for version 1.7.5

**Comment by 0m4r** [comment]
@rafaesc when do you plan to release it?
