### ISSUE TITLE
Document on properties in functional components

### ISSUE THREAD

**Issue by tlyau62** [vue-styleguidist/vue-styleguidist#1165]
Is it possible to add documentations on properties in functional components like below.

```js
/**
 * @property {string} msg the message to display
 */
export default {
  functional: true,
  render(h, { data, props }) {
    return <div>{props.msg}</div>
  },
};
```

**Comment by elevatebart** [comment]
In vue 2 functional components you can have a `props` option that will be ripped off in production.
The answer is yes, but it might be a little verbose. 

There is an unexpected silver lining: Vue will validate your properties in dev at runtime... neat.

```js
export default {
  functional: true,
  props: {
    /**
	 * the message to display
	 */
    msg: {
      type: String,
      required: true,
    }
  },
  render(h, { data, props }) {
    return <div>{props.msg}</div>
  },
};
```

**Comment by tlyau62** [comment]
> In vue 2 functional components you can have a `props` option that will be ripped off in production.
> The answer is yes, but it might be a little verbose.
> 
> There is an unexpected silver lining: Vue will validate your properties in dev at runtime... neat.
> 
> ```js
> export default {
>   functional: true,
>   props: {
>     /**
> 	 * the message to display
> 	 */
>     msg: {
>       type: String,
>       required: true,
>     }
>   },
>   render(h, { data, props }) {
>     return <div>{props.msg}</div>
>   },
> };
> ```

Thanks elevatebart, but declaring the props this way will cause that missing out from the attributes.
It may not be good for some cases, such as transparent wrapper component which passes down its attributes to its child component.

**Comment by elevatebart** [comment]
I fail to understand your usecase. Could you give me an example?

**Comment by tlyau62** [comment]
Let's say this is the origin transparent wrapper component

```jsx
import Child from "./Child.vue";

/**
 * Validate on props.msg only.
 */
export default {
  functional: true,
  render(h, { data, props, scopedSlots }) {
    if (props.msg === "") {
      throw new Error("msg should not be empty string.");
    }

    return <Child {...data} scopedSlots={scopedSlots}/>;
  },
};
```

Now, if we need to document on props, we have to write like below,
and if there are more properties, says 10 more, we have to bind 10 more properties on the Child component,
because of the document.

```jsx
export default {
  functional: true,
  /**  the message to display */
  props: {
     msg: {}
  },
  render(h, { data, props, scopedSlots }) {
    if (props.msg === "") {
      throw new Error("msg should not be empty string.");
    }

    return <Child {...data} scopedSlots={scopedSlots} msg={props.msg}/>;
  },
};
```

**Comment by tlyau62** [comment]
Thanks for helping, the problem is solved
