### ISSUE TITLE
vue-docgen-api: @example tag starting with new line not parsed

### ISSUE THREAD

**Issue by distantnative** [vue-styleguidist/vue-styleguidist#1166]
**Current behavior**

`@example` tag where content starts on new line isn't parsed via `vue-docgen-api`

**To reproduce**

E.g. with a component like

```js
/**
 * The icon component can be used to
 * display any icon from our own icon set.
 * @public
 *
 * @example
 * <k-icon type="pencil" />
 */
export default {
```

the parsed data for `example` is

```
["examples"]=> array(1) { 
    [0]=> array(2) { 
        ["title"]=> string(7) "example" 
        ["content"]=> bool(true) 
    } 
}
```

**Expected behavior**

`examples.0.content` should be `<k-icon type="pencil" />`

**Comment by distantnative** [comment]
nooo, not stale 😅

**Comment by distantnative** [comment]
@elevatebart any chance that you could take a look? Would be much appreciated!

**Comment by elevatebart** [comment]
I hope to get to it this week, it's a busy time for cypress and I would hate to disappoint.

**Comment by distantnative** [comment]
Please don't close

**Comment by elevatebart** [comment]
good catch
