### ISSUE TITLE
Slow compiling

### ISSUE THREAD

**Issue by ay13** [vue-styleguidist/vue-styleguidist#117]
I am playing around with the basic example (https://github.com/vue-styleguidist/vue-styleguidist/tree/master/examples/basic) and it takes around 15 seconds from the moment I save until the styleguide demo is refreshed with the changes. Is this delay normal?

From the gif and description on the projects main page, I was led to believe that the refresh times would be rather quick. Am I missing a configuration option that is not part of the basic example?

**Comment by thenickname** [comment]
with the current doc compiler performance, developing or adjusting components from within styleguidist is barely possible. Because every tiny code change takes at least 15 secs (usually more) to be compiled and displayed. Makes for a major slow down in day-to-day work.

Could this be a misconfiguration issue? Something we did wrong while setting up styleguidist? Or is this a general performance issue?

**Comment by thenickname** [comment]
also, when hitting 'npm start' for the first time, initial startup time is about a minute

**Comment by rafaesc** [comment]
Hi @ay13 @thenickname,

It's strange, I couldn't replicate it.

When you start the project it's normal that take more time, but the next compilations are faster.

I need your machine's specifications

**Comment by thenickname** [comment]
Hey, thanks for the fast response. Not using typescript, no. Working on a Mac pro. Maybe it is our custom webpack conf. I should try it with a bare-bones styleguidist.

Our setup includes some adjustments to the pure styleguidist (so that components can properly load and all styles are displayed):

```javascript
// webpack.base.conf.js


var path = require('path')
var utils = require('./utils')
var config = require('../config')
var vueLoaderConfig = require('./vue-loader.conf')
var SpriteLoaderPlugin = require('svg-sprite-loader/plugin');

function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

module.exports = {
  entry: {
    app: './src/styleguide/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue': 'vue/dist/vue.esm.js',
      'ui-@': resolve('src'),
      'ui-src': resolve('src'),
      'ui-pages': resolve('src/pages'),
      'uilib':resolve('src/uilib'),
      'ui-styleguide':resolve('src/styleguide'),
      'ui-atoms': resolve('src/uilib/components/atoms'),
      'ui-molecules': resolve('src/uilib/components/molecules'),
      'ui-organisms': resolve('src/uilib/components/organisms'),
      'ui-layouts' : resolve('src/uilib/components/layouts'),
      'ui-templates': resolve('src/uilib/components/templates'),
      'ui-mixins': resolve('src/uilib/mixins'),
      'ui-modules': resolve('src/uilib/modules'),
      'ui-test': resolve('test'),
      'ui-fonts': resolve('../uilib/assets/fonts'),
      'ui-img': path.resolve(__dirname, '../src/uilib/assets/img'),
      'ui-icons': path.resolve(__dirname, '../src/uilib/assets/img/icons'),
    }
  },
  module: {
    rules: [
      {
        test: /\.(js|vue)$/,
        loader: 'eslint-loader',
        enforce: 'pre',
        include: [resolve('src'), resolve('test')],
        options: {
          formatter: require('eslint-friendly-formatter')
        }
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /ic_.*svg$/,
        use: [
          {
            loader: 'svg-sprite-loader',
            options: {
              symbolId: '[folder]/[name]',
              // extract : true,
              // spriteFilename : 'icons.svg'
            }
            //  + JSON.stringify({
            //     name: '[path][name]',
            //     prefixize: true
            // })
          },
          'svgo-loader'
        ]
        },
        {
             test: /\.(png|jpe?g|gif)(\?.*)?$/,
             loader: 'file-loader',
             options: {
               name: utils.assetsPath('img/[name].[hash:7].[ext]')
             }
           },
      {
        test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('media/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
  },
  plugins: [
    new SpriteLoaderPlugin(),
  ]
}
```

```javascript
// styleguide.config.js


const path = require( 'path' );

const config = {
    mixins : [
        './src/uilib/mixins/Atomic',
    ],
    webpackConfig : Object.assign(
        {},
        require( './build/webpack.base.conf.js' ),
    ),
    styleguideDir : '../doc/app/components',
    require : [
    // Components style
        path.join( __dirname, './node_modules/vue-multiselect/dist/vue-multiselect.min.css' ),
        path.join( __dirname, './src/uilib/assets/css/styles.scss' ),
        './styleguide.mock.js',
        path.join( __dirname, './styleguide.styles.scss' ),
    ],
    title : 'Component Lib',
    navigation : true,
    sections : [
        {
            name : 'README',
            content : './src/documentation.md',
        },
        {
            name : 'DesignTokens',
            content : './src/tokens/designtokens.md',
            components : './src/tokens/*/*.vue',
        },
        {
            name : 'Atoms',
            content : './src/uilib/components/atoms/atoms.md',
            components : './src/uilib/components/atoms/*/*.vue',
        },
        {
            name : 'Molecules',
            content : './src/uilib/components/molecules/molecules.md',
            components : './src/uilib/components/molecules/*/*.vue',
        },
        {
            name : 'Organisms',
            content : './src/uilib/components/organisms/organisms.md',
            components : './src/uilib/components/organisms/*/*.vue',
        },
    ],
    theme : {
        color : {
            sidebarBackground : '#08223f',
            border : '#f5f5f5',
            link : '#f5f5f5',
            linkHover : '#b2b2b2',
        },
        fontFamily : {
            base : '"HelveticaNeue"',
        },
        sidebarWidth : 280,
    },

    editorConfig : {
        theme : 'night',
    },
};

// Add additionnal scss loader for scss files
config.webpackConfig.module.rules.push( {
    test : /\.scss$/,
    use : [
        {
            loader : 'style-loader', // creates style nodes from JS strings
        },
        {
            loader : 'css-loader', // translates CSS into CommonJS
        },
        {
            loader : 'sass-loader', // compiles Sass to CSS
        },
    ],
} );

config.webpackConfig.module.rules.push( {
    test : /\.css$/,
    loader : 'style-loader!css-loader',
} );


module.exports = config;

```

**Comment by rafaesc** [comment]
Can you run `vue-styleguidist server --verbose`, and simply add a white space?

**Comment by ay13** [comment]
@rafaesc You can use this repo for an example.

https://github.com/ay13/vue-cli-ts-styleguidist

Spin it up using `npm run styleguide`

edit the example component here `/src/components/AppButton.vue`

**Comment by thenickname** [comment]
it would seem that the more components you have the slower compilation becomes (as if styleguidist is trying to recompile *every* component)

**Comment by anthonybruno** [comment]
For what its worth I've found actually generating an actual build was far faster than waiting for the server to compile.

**Comment by rafaesc** [comment]
Yes, I was thinking that the problem is in the hot reloading maybe it could be solved if there would be code splitting for each component, but I will research how fix it soon.

**Comment by viljamis** [comment]
@ramiroazar Interesting, I just tested removing all requires and for us that doesn’t seem to make any difference. I also tried removing all custom configuration from the styleguide, but that did not help.

**Comment by viljamis** [comment]
@ramiroazar @rafaesc So… I think I found one area that was causing slowness. We were using older version of Webpack (3.x.x) and with that, we also had to use some other older NPM dependencies as they had dropped support for Webpack 3.x. 

So now, after updating all of the dependencies in our system to their latest versions the delay with the edits is almost completely gone.

There’s still the initial delay of a few minutes when you first start up the project which would be nice to improve/get rid of, but at least things became usable again when editing components and any SCSS styles or JavaScript required in the styleguidist config.

**Comment by ramiroazar** [comment]
Thank you, @viljamis. Can verify that there are no compilation delays after upgrading to `webpack@4` Unfortunately, this particular project uses `nuxt@1`, which remains dependant on `webpack@3`. However, this should be resolved when `nuxt@2` is released, as it seems to be with `nuxt-edge@2`.

**Comment by rafaesc** [comment]
Thanks @Infeligo 
Yes, how you said, `vuedoc-loader` generates a slow compiling because uses `jsdoc-api`.
The good news is that I found another to way to improve considerably the parser without to use `jsdoc-api`, it should be between 80% to 90% faster, but it will ready for the next week. I hope to finish soon.

**Comment by briangruber** [comment]
Any updates on this? Thanks!

**Comment by patric-eberle** [comment]
@rafaesc I just updated to 1.8.3 and the performance seems to be much better now. THX!

**Comment by rafaesc** [comment]
@patric-eberle it sounds great!, although there still is technical debt in `vue-docgen-api`, I glad that the performance improves

**Comment by cswebdev** [comment]
its still very slow - the initial compiling and the first time open it in the browser.
with latest versions on a new created vue-cli3 setup with webpack 4.
We have a lot of components and some custom configs.

by the way: is there a reason why the complete documentation is rendered initially on content area? it would be much better for client performance if only the information i want to see is rendered instead of all.

thx

**Comment by patric-eberle** [comment]
@cswebdev A workaround can be `sections` so you can split up your documentation for faster rendering. See https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Components.md#sections

But lazyloading would have a better impact I guess.

**Comment by elevatebart** [comment]
version 3.0 is out and the parser is supercharged, can you please have a look at it ? Should make everybody's life better. I can check for better caching tools once I have your feedback ;)

**Comment by elevatebart** [comment]
please try v3 it is lighter and faster.
