### ISSUE TITLE
Object values better implementation

### ISSUE THREAD

**Issue by stephenjason89** [vue-styleguidist/vue-styleguidist#1186]
/**
         * Example
         * 
         * @type {object} data
         * @values not enough <----
*/

@values format it into a single line.
Complex object which has a lot of properties can be implemented with @example

like this

/**
         * Example
         * 
         * @type {object} data
         * @example
         
                 data: {
                        Category: {                     // Key will be used as model name
                            type: 'comboBox',
        
                            // Nested Mutation's connection (default: connect)
                            connection: 'connect',      // Optional
        
                            required: true,             // Force user to use input
                            method: 'categoryFilter',   // Method in graphql/{Model}.js
                            fieldName: 'categories',    // Override key as fieldName
                            variables: { scope: 'Product' },
                            attrs: {
                                label: 'Category*',
                                'item-text': 'name',
                            },
                        },
                        characteristics: {
                            type: 'select',
                            model: 'Category',          // Used to override key as model name
                            method: 'categoryFilter',
                            variables: { scope: 'Product', hasCharacteristics: {} },
                            expanded: 'characteristics',
                            attrs: {
                                label: 'Characteristics',
                                multiple: true,
                                'item-text': 'name',
                                chips: true,
                            },
                        },
                        for_freebies: {
                            type: 'select',
                            attrs: {
                                label: 'For Freebies?',
                                // Define own options
                                items: [
                                    { text: 'Yes', value: 1 },
                                    { text: 'No', value: null },
                                ],
                            },
                        },
              }

*/

As you can see, it is quite challenging to read and write these kind of stuff
Firstly because, there is no syntax highlighting
Second because @example is not made for these kind of situations.

We need to implement something better to document
Objects and all the fields uses & values

Thank you

**Comment by stephenjason89** [comment]
Up

**Comment by elevatebart** [comment]
Hello @stephenjason89,

Thank you for wanting to contribute to styleguidist.
Your ask is a little deeper than a simple flip switch.

- Within vue-docgen-api, we need to parse the multi-line @example tag
- Then with what we get in vue-styleguidist is severely more complex to display clearly (Imagine the block of code above displayed in a styleguide destined to designers).

I do not have time to build this right now, but I will look into it as soon as possible.

**Comment by stephenjason89** [comment]
@elevatebart Thank you for the reply and for this great package. 
          Will be patiently waiting. :)  Syntax highlighting on @example would be a nice addition.

**Comment by elevatebart** [comment]
I think I will follow TSDoc's implementation of `@example`
https://tsdoc.org/pages/tags/example/

do you think it would fit?

**Comment by stephenjason89** [comment]
@elevatebart I believe it won't be that helpful.
I am not sure if i am looking at the right one. 
But here's a screenshot of the link you sent.
![image](https://user-images.githubusercontent.com/3810177/140563817-4ad39a96-48b1-4bc0-9395-a81dbeb02b8c.png)

Pasting it on their playground results to this
![image](https://user-images.githubusercontent.com/3810177/140564833-efb207bd-31ae-4c69-b3db-20be25f5bfe6.png)

There's no syntax highlighting here. It is just inside a code block.


If you can implement something similar to the view code portion then it would be really helpful.

here's a screenshot taken from one of your examples
![image](https://user-images.githubusercontent.com/3810177/140564309-eba34b78-eba5-4769-a96b-3ad4bb06d5ec.png)

**Comment by elevatebart** [comment]
Good point, 

Let me clarify, I want to use the same syntax as TSDoc to keep it compatible.
This way, I can keep benefitting from the work Microsoft does on TSDoc. Even better, the example in the comments will be code highlighted in the code itself.
The rest of the examples would show syntax highlighting like the normal examples.

**Comment by stephenjason89** [comment]
Thank you @elevatebart . That would be awesome 🙂
Excited to test it out once it's ready 😁

**Comment by stephenjason89** [comment]
@elevatebart Hello,would like to gently follow up on this matter. Thank you so much
