### ISSUE TITLE
1.7.3 not working with vue-i18n

### ISSUE THREAD

**Issue by patric-eberle** [vue-styleguidist/vue-styleguidist#119]
I'm unable to get vue-i18n to work with vue-styleguidist 1.7.3. In the previous used version 1.4.6 the installation of the plugin already failed (probably because of extend incompatibility of the tool: https://github.com/kazupon/vue-i18n/issues/306). But the problem became extensive worse with the new vue-styleguidist, where it seems to enter an endless recursion.

With over 2000 watches I think this is a very wide spread plugin, that should be supported by vue-styleguidist.

**Comment by rafaesc** [comment]
Hi @patric-eberle,

I would like to review it with more detail, can you create a demo with this issue

Thanks

**Comment by patric-eberle** [comment]
Hi @rafaesc 

I prepared a demo branch for you: https://github.com/valantic/vue-template/tree/demo/vue-styleguidist_vue-i18n

**Comment by patric-eberle** [comment]
@rafaesc this sounds like a good solution to me. Will try to test it this week.

**Comment by patric-eberle** [comment]
@rafaesc I can confirm that you solution works. Thank you very much!
