### ISSUE TITLE
Syntax highlighting using @example

### ISSUE THREAD

**Issue by stephenjason89** [vue-styleguidist/vue-styleguidist#1196]
Is it possible to get the syntax highlighting to work with @example?

**Comment by stephenjason89** [comment]
Up

**Comment by elevatebart** [comment]
DO you have an example of `@example` ?

**Comment by stephenjason89** [comment]
Here :)
<img width="683" alt="image" src="https://user-images.githubusercontent.com/3810177/164371188-860784db-9fd6-4c13-bdcf-1ad4da9c12cd.png">

**Comment by elevatebart** [comment]
Unfortunately, vue-styleguidist cannot help with anything in your editor.

If you use vscode, you should try this vscode extension:
https://github.com/mjbvz/vscode-jsdoc-markdown-highlighting

**Comment by stephenjason89** [comment]
oh i'm sorry @elevatebart 
What i meant was, 
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/3810177/166143414-1d0762be-3deb-45f1-aefb-97d029a50e0d.png">

When it is rendered, there's no syntax highlighting
