### ISSUE TITLE
Interfaced type for object prop

### ISSUE THREAD

**Issue by projectec2020** [vue-styleguidist/vue-styleguidist#1199]
I am passing an object as prop and imported the type interface.
in index.ts, i have 
```
export interface videoItem {
    src: string;
    title: string;
    controls: boolean
}
```
and the prop as 
```
 /**
   * The item for media card.
   */
  @Prop({ required: true }) readonly item!: videoItem;
```
but the vue styleguidist showing `videoItem` as the type,
![image](https://user-images.githubusercontent.com/59991217/134121140-fffdfde6-4d40-4145-baf9-da98f413a04a.png)

I want to show all the type and variable in interface?

**Comment by bisminshamh** [comment]
any updates
