### ISSUE TITLE
Default value being shown as a function, when really it's a function that returns an object

### ISSUE THREAD

**Issue by philwolstenholme** [vue-styleguidist/vue-styleguidist#122]
This is my Vue prop:

```js
    thresholds: {
      type: Object,
      default: () => ({
        orange: 50,
        green: 80,
      }),
    },
```

But the styleguide is displaying my default value as 'Function'

**Comment by rafaesc** [comment]
Hi @philwolstenholme,

I don't sure if this an issue, because it shows

![image](https://user-images.githubusercontent.com/10201025/39148582-49e6354e-4702-11e8-8c39-a6db2992f860.png)

and it say that it accept a type of string .

PD: Thanks for the donation :D

**Comment by philwolstenholme** [comment]
No problem about the coffee/beer donation! :)

You're right about the function showing in the tooltip, I had spotted that, but I thought it might be clearer if the value returned by the function was shown instead.

We have to use functions for arrays and object default values in Vue components (https://github.com/vuejs/vue/issues/1032#issuecomment-120212888) but to the end user the useful information is the default value returned by the function, not the function itself.

I don't think this is a bug though, probably more of a feature request :)

**Comment by elevatebart** [comment]
We could try using buble to compile it then try executing it in isolation and if it succeeds return the value.
```js
try{
  src = buble.compile(defaultValueString)
  defaultValueString = new Function(src)()
}catch(){}
```
@rafaesc what do you think?

**Comment by elevatebart** [comment]
This one I fixed ;)
