### ISSUE TITLE
Component styleguides renders inside of component example

### ISSUE THREAD

**Issue by gustav-vidispine** [vue-styleguidist/vue-styleguidist#124]
Hi!

I've stumbled on to an issue where I just as normal have added a couple of MyVueComponent.md files corresponding to my .vue files and added a some example-code.

It works on reload but when i **click** on two specific components the Example-section renders all the whole documentation of every component inside it again.

If I remove these two specific components (have 18 total) everything works fine. 

An error is rendered: `bundle.e9a283cf.js:136 The use of 'app' element id in the template is deprecated. Please, update your template file to use 'rsg-root' as the container id.`

Working at first:
<img width="1316" alt="screen shot 2018-04-25 at 16 26 44" src="https://user-images.githubusercontent.com/32642972/39252235-7de32c40-48a5-11e8-8135-9d704c3caed9.png">

But when clicking on VdtTranscode in the nav (sometimes also other nav-links):
<img width="1325" alt="screen shot 2018-04-25 at 16 22 25" src="https://user-images.githubusercontent.com/32642972/39252001-f429cf22-48a4-11e8-996f-7227534478a6.png">

_(The images are somehat zoomed out in browser for better overview)_

Any suggestions?

VdtVidinetTranscode.md (with js syntax):
```js

// Shortened and simplified for example purposes
const item = {
    metadata: {
        id: "VX-1"
    }
}
const tags = ["__mp4", "__mov"];

new Vue({
  data(){
    return {
        item: item,
        tags: tags,
    }
  },
  template: `
    <div>
        <VdtVidinetTranscode
            :item="item"
            :tags="tags"
        />
    </div>
  `
})
```

Running 1.7.2, updated to 1.7.5 - same problem.

**Comment by rafaesc** [comment]
Hi @gustav-vidispine,

It's because how vue-styleguidist is compused by react, by default takes the node with `id="app"` to compose the styleguide. If you change the name of id, it should work fine. But if you can't change it inside of your component, other alternative it is to use the [renderRootJsx option](https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Configuration.md#renderrootjsx)

And create a file js, with this code:

```
export default previewComponent => {
  // https://vuejs.org/v2/guide/render-function.html
  return {
    render(createElement) {
      return createElement(previewComponent);
    },
    mounted() {
      // Change the id name
      const listApp = document.querySelectorAll('#app');
      setTimeout(() => {
        if (listApp.length) {
          [].forEach.call(listApp, (item) => {
            item.id = 'app2'
          })
        }
      }, 500);
    },
  };
};
```

Regards

**Comment by gustav-vidispine** [comment]
Man, yes ofc that was the case! Thank you! 😃
