### ISSUE TITLE
Question about props table type column in 4.x.x

### ISSUE THREAD

**Issue by iv-thomson** [vue-styleguidist/vue-styleguidist#1244]
Hello guys! Just recently upgraded to 4.x.x from 3.x.x and found out that types aren't displayed in their own column anymore, but are placed inside of a description column.
I'd like to move move it in separate column again, but can't see a way to do it. Is it even possible?
<img width="559" alt="vue-styleguidist_vue-styleguidist-example_-_CodeSandbox" src="https://user-images.githubusercontent.com/91368802/147735825-5da1abea-b5c9-4cab-ab5b-e182d218edbd.png">

I tried overwriting PropsRenderer in config's styleguideComponents option, but that didn't do anything (however it worked with some other rsg components)
```
styleguideComponents: {
    PropsRenderer: path.join(__dirname, 'src/app/styleguide/PropsRenderer.js'),
  },
```

Is there a way for me to bring back the old behavior, like in pic below?
<img width="313" alt="vue-styleguidist-old" src="https://user-images.githubusercontent.com/91368802/147735832-7432e675-2633-4403-9982-a3c29346089d.png">

**Comment by elevatebart** [comment]
What you are doing should work. if does not it is a bug.

Can you please create a simple repository where I can reproduce and fix it?

Thank you in advance.

**Comment by iv-thomson** [comment]
Thanks for the reply!
You can see the bug in this repo
https://github.com/iv-thomson/styleguidist-bug-example

**Comment by iv-thomson** [comment]
works perfectly now
thanks! :)

**Comment by iv-thomson** [comment]
Hi @elevatebart !
The problem with PropsRenderer is gone, but in the 4.43.2 there is the same problem but with StyleGuideRenderer. Which wasn't happening in the 4.43.1
I updated the repo https://github.com/iv-thomson/styleguidist-bug-example
Should I create a separate issue for that?

**Comment by elevatebart** [comment]
Let me have a looksie... and it would probably help for tracking and changelog to have another issue but I could create it.
