### ISSUE TITLE
example code copy dislocation

### ISSUE THREAD

**Issue by ChaoQunPeng** [vue-styleguidist/vue-styleguidist#1246]
**Current behavior**
example code copy dislocation

**To reproduce**
![1641128563](https://user-images.githubusercontent.com/23206231/147877026-dada70db-612a-4672-a951-70dd8e49d831.jpg)

**Expected behavior**
format is normal

**Comment by elevatebart** [comment]
Hello @ChaoQunPeng 

Thank you for coming here and sharing your troubles.

It looks like you are not using the same fonts as the original examples:
Would you mind sharing a bit more of your environment?

- Windows/Mac/Linux?
- Version of Node?
- Browser?
- Version of Styleguidist?
- Customizations from your styleguide.config.js?
  - rootJsx
  - require

The best chance of getting a fix is as always a minimum reproduction repository.

**Comment by ChaoQunPeng** [comment]
@elevatebart It's right! It's the font problem! Thanks!
