### ISSUE TITLE
Show compiled HTML

### ISSUE THREAD

**Issue by timhartmann** [vue-styleguidist/vue-styleguidist#126]
I love your tool a lot to create a solid design system. I like the concept, but I have a huge problem. So I would use your tool to create a design system for a leading news platform in germany. Finally my team will use for the website something more static instead of vue. So I need a static documentation in your tool - the compiled html like in Pattern Lab.

In Pattern Lab I write my component in mustache, but I can take a look at the compiled html in the frontend too. This is a must have for my team. Does it possible to get the compiled html in the frontend? 

I **do not** want to do it like this example here:
![bildschirmfoto 2018-05-04 um 17 45 31](https://user-images.githubusercontent.com/986401/39637339-f84654de-4fc2-11e8-964b-1b2b2a8cbf52.png)

I would like it more like this here:
![bildschirmfoto 2018-05-04 um 17 50 47](https://user-images.githubusercontent.com/986401/39637561-b3199104-4fc3-11e8-8507-2894640c7236.png)

![bildschirmfoto 2018-05-04 um 17 50 17](https://user-images.githubusercontent.com/986401/39637536-a2000150-4fc3-11e8-8936-859edd5db774.png)

**It is so important. Without this feature I can not use it for my team and the design system.**

**Comment by viljamis** [comment]
@timhartmann You mention that “Finally my team will use for the website something more static instead of vue.” — do you mean that the website itself would be built using completely different technology, or are you planning on rendering things server side with Vue? 

If Vue.js isn’t used at all in the end product, I think this would be the wrong tool to use?

**Comment by timhartmann** [comment]
I don not know how I can integrate it in Vue Design System :(
https://github.com/viljamis/vue-design-system

**Comment by viljamis** [comment]
For anyone else maybe coming here, see my / @rafaesc ’s answer in this issue: https://github.com/viljamis/vue-design-system/issues/77

**Comment by rafaesc** [comment]
@viljamis, thanks!
