### ISSUE TITLE
typescript prop types

### ISSUE THREAD

**Issue by dvh91** [vue-styleguidist/vue-styleguidist#1261]
Given this simple input:
```
<template>
</template>

<script lang="ts" setup>
interface IAddress {
    city: string
}

interface Props {
    name: string
    age: number
    address: IAddress
}

withDefaults(defineProps<Props>(), {
    name: 'vue'
})

</script>
```

The returned object from `parse` method in `vue-docgen-api` (v4.44.1), returns:

```
{
  "exportName": "default",
  "displayName": "sample",
  "description": "",
  "tags": {},
  "props": [
    {
      "name": "name",
      "required": true,
      "defaultValue": {
        "func": false,
        "value": "'vue'"
      }
    },
    {
      "name": "age",
      "required": true
    },
    {
      "name": "address",
      "required": true
    }
  ]
}
```

I've looked into the tests and looks like it's not expected to be returned?
https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/tests/components/setup-syntax/setup-syntax.test.ts#L29

Thanks!

**Comment by elevatebart** [comment]
Thank you @dvh91 it's my mistake.
I made a fix [here](https://github.com/vue-styleguidist/vue-styleguidist/commit/2346b64a8c53423ebe853e1f48cab3bb2aae4956).
Will release today
