### ISSUE TITLE
Support @vue/cli

### ISSUE THREAD

**Issue by gjuchault** [vue-styleguidist/vue-styleguidist#127]
As the new vue cli approches, it could be nice to make vue-styleguidist able to get the webpack config directly in `node_modules/@vue/cli-service`

**Comment by rafegoldberg** [comment]
@gjuchault– this oughta tide you over till support for `@vue/cli` v3 is rolled in to the `vue-styleguidist` core:

```diff
+ const WPK_CONF = require("@vue/cli-service/webpack.config.js")

```js
const WPK_CONF = require("@vue/cli-service/webpack.config.js")
module.exports = {
  webpackConfig: WPK_CONF,
  styleguideDir: './docs',
  // so on & so forth...
}
```

**Comment by rafegoldberg** [comment]
@gjuchault [per Even's comment](https://github.com/vuejs/vue-cli/issues/782#issuecomment-363191497) you can actually "require" your generated Webpack config directly right in to your `styleguide.config.js`, like this:

```js
const webpk = require("@vue/cli-service/webpack.config.js")
module.exports = {
  webpackConfig: webpk,
  styleguideDir: './docs',
  // so on & so forth...
}
```

That ought to tied you over until `vue-styleguidist` rolls out core `@vue/cli` v3 support.

**Comment by rafegoldberg** [comment]
@gjuchault [per Even's comment](https://github.com/vuejs/vue-cli/issues/782#issuecomment-363191497) you can actually "require" the generated Webpack config directly in to your `styleguide.config.js` like so:

```js
const webpackConfig = require("@vue/cli-service/webpack.config.js")

module.exports = {
  webpackConfig,
  // etc...
}
```

This ought to tied you over for now. Though I agree that `vue-styleguidist` should probably support the `@vue/cli` v3 service out of the box.

**Comment by wtfuii** [comment]
I think this is already fixed with #137 .. when are we going to see a new Version?  I need this fix. :)

**Comment by rafaesc** [comment]
@wtfuii I wanted to release first `pagePerSection` feature, but it's probably that it could delay, so tomorrow I will release `vue-cli`.

**Comment by zhangpengchen** [comment]
@rafaesc when will you release vue-cli?

**Comment by rafaesc** [comment]
@zhangpengchen @wtfuii it is ready on [1.7.8 version](https://github.com/vue-styleguidist/vue-styleguidist/releases/tag/v1.7.8)
