### ISSUE TITLE
Nuxt example: doesn't work?

### ISSUE THREAD

**Issue by vushe** [vue-styleguidist/vue-styleguidist#1271]
Hello,

I've tried Styleguidist's flavor with Nuxt.js, but can't see any signs of Nuxt.

For example, when I go to https://vue-styleguidist.github.io/nuxtjs/ and trying `NuxtLink` in examples, I get an error the component isn't registered. Also other checks like `console.log(this.$route)` or `document.querySelector('#__nuxt')` don't work.

If everything works as expected, what's the point of having Nuxt in this example?

![image](https://user-images.githubusercontent.com/15868217/151834320-78750144-1765-4847-b9b7-1128586740ee.png)

**Comment by elevatebart** [comment]
Hello @vushe,

This example project is meant to show how you would set up webpack to build your components. It is not setting up `NuxtLink`. But this could be a good addition if you find a good way to depict what the route change would trigger.

If you change the URL, the currently showcased component will go away. 

I am open to suggestions and PR.

**Clarification:** These examples are simple showcases to help users set the scaffolding up, they are not meant as maintained plugins.

**Comment by vushe** [comment]
Hello @elevatebart ,

thanks for prompt explanation! Yes, I can now see it's just an example and getting Nuxt working under Styleguidist can be not so easy. That's actually a pity, since, when you develop a Nuxt-based app, you sometimes want namely Nuxt's power behind code examples.

Let us close this issue. Yet we can always share possible ideas in this thread 👍🏻
