### ISSUE TITLE
Latest version 4.44.15 utilises a compromised colors package

### ISSUE THREAD

**Issue by azriel46d** [vue-styleguidist/vue-styleguidist#1274]
**Current behavior**

As soon as you bump up and clean the npm packages , the solution adopts a compromised version of `colors` a dependency to `cli-progress` 
Reference: https://github.com/Marak/colors.js/issues/285
To fix: bump up the version of `cli-progress` (https://github.com/npkgz/cli-progress/issues/116)
**To reproduce**
1.  Bump up and install latest
2.  run `npm run styleguide`

**Expected behavior**

**Comment by DanielRuf** [comment]
The compromised package was removed from npmjs kany days ago.

**Comment by DanielRuf** [comment]
The compromised package was removed from npmjs many days ago.

**Comment by DanielRuf** [comment]
The compromised package version was removed from npmjs many days ago. Version 1.4.0 is not affected.

Only clean versions are available. See https://github.com/npkgz/cli-progress/commit/1f0c40e87b15ef0f78a8a60ff6c70840be8b092b#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deL238 and https://www.npmjs.com/package/colors?activeTab=versions

Nothing to worry at the moment.

cli-progress 3.9.0 and newer (includes 3.10.0, SemVer selector ^) is already used, see https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-styleguidist/package.json#L38

This includes the automatic update to 3.10.0.

**Comment by elevatebart** [comment]
It still does not hurt to update but I it is less of an emergency.
