### ISSUE TITLE
vue-docgen-cli: Slots with dynamic name are not documented

### ISSUE THREAD

**Issue by J3m5** [vue-styleguidist/vue-styleguidist#1285]
Hi and thanks for this nice project!

**Current behavior**

Slots with a dynamic name are not documented in the generated  file when using vue-docgen-cli

**To reproduce**
Use a slot like this:
```vue
    <!-- @slot slot for prepend on input -->
    <slot :name="`prepend-${property}`"></slot>
```
Render: 
```md
## Slots

| Name  | Description                      | Bindings |
| --------  | -------------------------------- | ------------ |
| default | slot for prepend on input |                |
```

**Expected behavior**

Slots with dynamic names should be correctly documented

Edit

What I expected:

```md
| Name                          | Description                         | Bindings |
| ----------------------------- | ----------------------------------- | ----------- |
| `prepend-${property}` | slot for prepend on input     |               |
```

Or get the name in the comment
this for example: 
```vue
    <!-- @slot prepend[property] - slot for prepend on input -->
    <slot :name="`prepend-${property}`"></slot>
```
would return this:
```md
| Name                     | Description                      | Bindings |
| ------------------------- | -------------------------------- | ------------ |
|  prepend[property] | slot for prepend on input |                |

```

**Comment by elevatebart** [comment]
Remember that docgen is a static analysis tool.
The only thing I can look at is the code.

We could:
- hide the slot: cheapest
- say it has a dynamic name: still cheap (name shown would literally be `<dynamic>`)
- display the code in the name: I need to see how the code will look

**Comment by J3m5** [comment]
I edited the issue.

I'd vote for option 3 or a 4th option, specify the name in the comment.

**Comment by elevatebart** [comment]
Great idea !!

**Comment by elevatebart** [comment]
I think the safest is option 4 with a fallback to option 2. This way everything stays affordable and we don't have an insignificant blob of code in the `name` column 😄

**Comment by J3m5** [comment]
I totally agree!

**Comment by sawmurai** [comment]
Getting the code from the name property seems to be quite simple:

(just a prototype)
```js
// somewhere in the slotHandler:
const bindProp = templateAst.props.find(b => b.name === 'bind' && b.arg && b.arg.content === 'name');

const expr = bindProp.exp.content;
```

So, I would propose the following priority:

1. What is provided via the `@slot` comment 
2. The expression from inside the `:name` property

On the one hand, that is what I would expect as a user. On the other hand, the expression from inside the `:name` property will probably require additional context that can only be derived from the actual code. I would still prefer it over `<default>` as that is not unique and would lead to issues if you have more than one dynamic `:name`.

**Comment by elevatebart** [comment]
Thank you for your input @sawmurai 

Would you have time to create a quick PR? 
Even writing failing tests would help.

**Comment by sawmurai** [comment]
No problem, I added a PR. This will probably require some documentation update in the end, would it not? 

I went with @J3m5 's suggestion for the format of the name from a comment: 

```
@slot name - description till EOL
```
