### ISSUE TITLE
Project example (Typescript, Pug, SCSS, vue-class-component)

### ISSUE THREAD

**Issue by bogdanHorai** [vue-styleguidist/vue-styleguidist#129]
Hi! I created project with `@vue/cli` beta9 with typescript option

my components looks like

```html
<template lang='pug'>
  .AppErrorPage404
    h1.AppErrorPage404__header(v-html='$t(title)')
</template>
```
```js
<script lang='ts'>
import { Vue, Component, Prop } from 'vue-property-decorator';

@Component({
  name: 'AppErrorPage404',
})
export default class AppErrorPage404 extends Vue {
  @Prop({ default: 'error_404' }) title!: string;
}
</script>
```

can you add example for components with ts, pug, vue-class-component?

P.S. now a get this messages in console and empty generated view

Warning: Cannot parse src/components/AppErrorPage404/AppErrorPage404.vue: TypeError: Class extends value undefined is not a constructor or null

It usually means that vue-docgen-api does not understand your source code or when using third-party libraries, try to file an issue here:https://github.com/vue-styleguidist/vue-docgen-api/issues

**Comment by rafaesc** [comment]
Hi @bogdanHorai,

unfortunatly, for the moment vue-docgen-api doesn't [support pug](https://github.com/vue-styleguidist/vue-docgen-api/issues/13), and have a [partial support of typescript](https://github.com/vue-styleguidist/vue-docgen-api/issues/9).

I need more time to research how I can support it.

**Comment by upstroke** [comment]
Any news on that matter?
We habe the following setup for components:
component
- component.js
- component.pug
- component.scss
- component.vue

**Comment by elevatebart** [comment]
I believe everything is supported now but might be mistaken.
I will try creating an example with pug-ts-scss
