### ISSUE TITLE
getComponentPathLine not working

### ISSUE THREAD

**Issue by stephenjason89** [vue-styleguidist/vue-styleguidist#1292]
package version 4.44.19

```
getComponentPathLine(componentPath) {
            const component = componentPath
                .replace(/client\\components\\/, '')
                .replace('client/components/', '')
                .replace('.vue', '')

            const name = component
                .split('/')
                .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
                .join('')

            return `import ${name} from '${componentPath}';`
        },
```
if I console log the return statement, i can see that it is the right import. 

"Function that returns a component path line (displayed under the component name)."
It is actually displayed under the name

But since I have multiple files with the same name on other directories, it doesn't correctly import it.
Is this function supposed to be just a label for the filepath under the component name?
If so, is there a function where i can change the auto imported components path?

**Comment by stephenjason89** [comment]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/3810177/158637233-a9cf4396-ae58-44dc-a6d6-eb59b9ab6244.png">
Doesn't work


<img width="581" alt="image" src="https://user-images.githubusercontent.com/3810177/158637324-140d675d-e7ba-4b1c-8157-6c6093d3ace6.png">
This on the other hand, works perfectly

**Comment by stephenjason89** [comment]
Up

**Comment by elevatebart** [comment]
Hello @stephenjason89 

Sorry fo the late answer. The only place this function is used is here:

<img width="958" alt="Screen Shot 2022-06-30 at 2 43 45 PM" src="https://user-images.githubusercontent.com/5592465/176764098-16c71cef-dcb3-4474-8765-8dc037b6540d.png">

It is **not** used to set anything in the examples.

The idea is to give your users a quick Copy/Paste to import your component in theirs.

**Comment by elevatebart** [comment]
It is not working well though with multiple components in the same file.

[EDIT] after checking very deeply, vue-styleguidist does not work well with multiple components in the same file.

**Comment by stephenjason89** [comment]
Thank you for looking in on this @elevatebart
