### ISSUE TITLE
vue-inbrowser-compiler-demi@4.44.21 issue 

### ISSUE THREAD

**Issue by cthinkzz** [vue-styleguidist/vue-styleguidist#1295]
**Current behavior**

Hi I am working in one of the React Project, It seems like **vue-inbrowser-compiler-demi** has been updated recently. So I am getting below error whenever I try to do **npm install**
![image](https://user-images.githubusercontent.com/31088853/158979505-898dec6f-c11a-4443-b63f-02c06c6ebf7f.png)

**node version: 12.16.1**
**npm version: 6.13.4**

Any suggestions to fix this issue would be very helpful.
Thanks in advance.
**To reproduce**

**Expected behavior**

**Comment by elevatebart** [comment]
Are you working with a monorepo?

**Comment by elevatebart** [comment]
If you install vue-styleguidist or vue live, you are normally responsible for installing vue.

This is vue-Demi telling you it cannot find vue nor detect its version.

I should make this error more meaningful.

Can you try and share a repo where I could reproduce this error? If not, best advice is add vue to the dev dependencies of the project where you run styleguidist.

**Comment by elevatebart** [comment]
One thing that could be done here is to wrap this require in a try-catch like in vue-Demi. 

This way we could make this "error" silent and still have most of vue-styleguidist working.

I am surprised by the path where the compiler-Demi is installed. I must be missing an important detail.

If you take the time to open a PR I'd be delighted. 

Thank you for reporting anyway.

**Comment by kfw9257** [comment]
I'm also seeing a similar error with an Angular project that is a part of a monorepo.

![image](https://user-images.githubusercontent.com/4633553/159021148-491432ad-4e3a-410b-adc7-2afb6bc0f9db.png)

**Node version 14.13.0**
**NPM version 7.24.0**

**Comment by kfw9257** [comment]
Update: I was able to fix my issue by removing all storybook js dependencies from my package.json. I'm not using storybook in my app currently so it wasn't a big issue.

**Comment by cthinkzz** [comment]
> Update: I was able to fix my issue by removing all storybook js dependencies from my package.json. I'm not using storybook in my app currently so it wasn't a big issue.

Thanks for the input but I am using storybook in my project. So I can't really remove any storybook dependencies.
As @elevatebart suggested, I added vue as devDependency and it worked fine.

**Comment by cthinkzz** [comment]
> If you install vue-styleguidist or vue live, you are normally responsible for installing vue.
> 
> This is vue-Demi telling you it cannot find vue nor detect its version.
> 
> I should make this error more meaningful.
> 
> Can you try and share a repo where I could reproduce this error? If not, best advice is add vue to the dev dependencies of the project where you run styleguidist.

Thanks for the response. I am not using styleguidlist/vue-live. But I assume any one of my dependencies might be using these packages, but it worked fine when I added vue as devDependency.
One observation is project was working fine until it got latest release today for [https://www.npmjs.com/package/vue-inbrowser-compiler](url) 
![image](https://user-images.githubusercontent.com/31088853/159068493-2c26b1e0-82d1-41f5-a96f-d9e37deedd87.png)

**Comment by elevatebart** [comment]
can you do `npm ls vue-inbrowser-compiler` and post the result here?
This will help me know why you have a vue specific package installed in an Angular project.

version 4.44.22 should not need the installation of `vue` anymore.

**Comment by cthinkzz** [comment]
> can you do `npm ls vue-inbrowser-compiler` and post the result here? This will help me know why you have a vue specific package installed in an Angular project.
> 
> version 4.44.22 should not need the installation of `vue` anymore.

Thanks for the quick response. Yeah it's working fine now without 'vue'
