### ISSUE TITLE
Breaks backstopjs/casper

### ISSUE THREAD

**Issue by lancetharper** [vue-styleguidist/vue-styleguidist#13]
Just updated to 1.2 and with the inclusion of `webpage` in the dependencies, backstopjs/casper fails to run for visual regression tests. Backstop runs phantom (for now) and I think it requires a different version of it or something so this addition in my node_modules breaks it.

Was `webpage` meant to be added to devDependencies since it looks like it's only used for testing with phantom and not actually a dependency?

If not, I just want to at least make it known that if you use backstopjs for testing, updating to v1.2 will break it.

**Comment by rafaesc92** [comment]
It's true, I just moved it to a devDependencies.

I've published the fix under v1.2.3.
