### ISSUE TITLE
<router-link> flagged as 'Unknown custom element'?

### ISSUE THREAD

**Issue by JohnRSim** [vue-styleguidist/vue-styleguidist#131]
How do you pull in OOTB vuejs component?
I'm getting an error with one of my components that uses the vue router-link component - couldn't find anything in the documentation.

main.bundle.js:167 [Vue warn]: Unknown custom element: <router-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <WalletSubNavWidget> at src\renderer\components\widgets\WalletSubNavWidget.vue
       <Anonymous>
         <Root>

```
<template>
	<nav id="JSEA-topSubLvlNav" class="cf">
		<ul>
			<router-link v-bind:to="`/wallet`" tag="li" :class="{'active': activeNav === 'transfer'}">
				Transfer
			</router-link>
			<router-link v-bind:to="`/wallet/export`" tag="li" :class="{'active': activeNav === 'export'}">
				Export
			</router-link>
			<router-link v-bind:to="`/wallet/import`" tag="li" :class="{'active': activeNav === 'import'}">
				Import
			</router-link>
			<router-link v-bind:to="`/wallet/transactions`" tag="li" :class="{'active': activeNav === 'transactions'}">
				Transactions
			</router-link>
		</ul>
	</nav>
</template>

<script>
/**
 * @description
 * Wallet SubNav Widget Wrapper
 */
export default {
	name: 'WalletSubNavWidget',
	props: {
		/**
		 * Highlights Active Nav Item ['transfer', 'export', 'import', 'transactions']
		 */
		activeNav: {
			type: String,
			default: '',
		},
	},
};
</script>
```

**Comment by JohnRSim** [comment]
not sure what happened error no longer displaying.. ?

**Comment by JohnRSim** [comment]
Error no longer displayed but instead I'm seeing the tag in the html and not the component rendered html

```html
<router-link data-v-c696e552="" to="/dashboard" tag="li" class="active">
    Dashboard
</router-link>
```

**Comment by rafaesc** [comment]
@JohnRSim You have to install thirdparty plugin, here says how you can do it.
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Cookbook.md#how-to-add-data-dummy-and-third-party-plugins-to-the-style-guide

But it's probably you will get problems if you try to use vue-router in styleguide because, to render the styleguide it already uses hash.

Related
https://github.com/vue-styleguidist/vue-styleguidist/issues/108

**Comment by JohnRSim** [comment]
I updated my .babelrc to the following to test
```
{
	"presets": ["env", "stage-2"],
	"plugins": ["transform-runtime"],
	"comments": false
}
```
which works but as soon as I add global.requires.js into the config 
```
	require: [
		path.join(__dirname, 'styleguide/global.requires.js'),
		...
		...
	}
```
I get the following error even if global.requires.js is empty or just contains
```
import Vue from 'vue';
```

![image](https://user-images.githubusercontent.com/364208/39965562-73637ae4-5693-11e8-8837-390f6db4c777.png)

**Comment by JohnRSim** [comment]
I'll clone this repo 
https://github.com/vue-styleguidist/vue-styleguidist/tree/master/examples/vuetify

and see if I can replicate and figure out the difference..

**Comment by JohnRSim** [comment]
ok I found the issue I had this in the styleguide.config.js- 
in the webpackconfig.modules.rules
```
				{
					test: /\.js?$/,
					loader: 'babel-loader',
					exclude: /node_modules/,
					query: {
						cacheDirectory: true,
						presets: ['react', 'env'],
					},
				},
```

**Comment by andywd7** [comment]
Hi, I know this is closed but could someone please provide a clearer answer as to how to solve or bet around this problem? I have a component that uses `<router-link>` and need it to render as expected otherwise the documentation of the rendered code is incorrect.

Thanks in advance for any help, it's would be very appreciated.

**Comment by nicooprat** [comment]
@andywd7 You can mock the `<router-link>` component: https://github.com/vue-styleguidist/vue-styleguidist/issues/108#issuecomment-458358043

```js
// styleguide.global.requires.js
import Vue from 'vue'
Vue.component('RouterLink', {
  template: `<a><slot></slot></a>`
})
```

**Comment by marshallswain** [comment]
Thanks for the idea @nicooprat!  Just in case anybody could benefit from this, here's one that allows you to customize the tag:

```js
Vue.component('RouterLink', {
  props: {
    tag: { type: String, default: 'a' }
  },
  render(createElement) {
    return createElement(this.tag, {}, this.$slots.default)
  }
})
```

**Comment by elevatebart** [comment]
I will add both your recipes to the cookbook
