### ISSUE TITLE
`--config` flag is broken in vue-docgen-cli

### ISSUE THREAD

**Issue by ghost** [vue-styleguidist/vue-styleguidist#1310]
**Current behavior**

`-c` and `--config` flags are specified in the documentation for `vue-docgen-cli` (<https://vue-styleguidist.github.io/docs/docgen-cli.html#config>), but the `--config` flag doesn't work

**To reproduce**

- Clone <https://github.com/mi544/config-flag-bug>
- Run `yarn install`
- Run `yarn docs:broken`. No documentation is created (the `--config` flag is broken)
- Run `yarn docs:works`. Documentation is created successfully and is available in `/docs` 

**Expected behavior**

As specified in the documentation, both `-c` and `--config` flags should work the same. `--config` is expected to load the configuration file properly just as `-c` does it

**Comment by elevatebart** [comment]
That is a documentation issue indeed. I will fix it.

`-c` is an alias of `--configFile` instead of `--config` sorry.

**Comment by ghost** [comment]
Thank you for addressing this! `--configFile` works as expected!
