### ISSUE TITLE
Port 6060 is not freed after terminating vue-styleguildist process

### ISSUE THREAD

**Issue by hpb0412** [vue-styleguidist/vue-styleguidist#1322]
**Current behavior**

Vue Styleguidist doesn't free the port `6060` after being terminated by using `Ctrl+C`

Subsequence start will yield the message:  `Compiled successfully!` but no server starts.

**To reproduce**

- run `yarn styleguilde` observe:
```shell
yarn run v1.22.17
$ vue-styleguidist server
ℹ ｢wds｣: Project is running at http://localhost:6060/
ℹ ｢wds｣: webpack output is served from
ℹ ｢wds｣: Content not from webpack is served from /Users/xyz/project

You can now view your style guide in the browser:

  Local:            http://localhost:6060/
  On your network:  http://192.168.1.92:6060/

 DONE  Compiled successfully!
```

at this point, I am able to access `http://localhost:6060`

- press `Ctrl+C` to terminate process

- run command `lsof -PiTCP -sTCP:LISTEN` observe:
```shell
....
node      98985 xyztuv   24u  IPv4 0x..............b1      0t0  TCP *:6060 (LISTEN)
```

- rerun `yarn styleguide` observe only:
```
 DONE  Compiled successfully!
```

at this point, I am **not** able to access `http://localhost:6060`

**Expected behavior**

- port `6060` must be freed after termination
- subsequence `styleguilde` run successfully with website accessible

**Enviroment**

Mac Monterey 12.1
Iterm 2
All dependencies
```json
  "devDependencies": {
    "@babel/core": "^7.17.10",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/preset-env": "^7.17.10",
    "autoprefixer": "^10.4.7",
    "babel-loader": "^8.2.5",
    "css-loader": "^6.7.1",
    "postcss-loader": "^6.2.1",
    "sass": "^1.51.0",
    "sass-loader": "^12.6.0",
    "style-loader": "^3.3.1",
    "svg-sprite-loader": "^6.0.11",
    "vue": "^2.6.14",
    "vue-loader": "^15.9.8",
    "vue-style-loader": "^4.1.3",
    "vue-styleguidist": "^4.45.0",
    "vue-template-compiler": "^2.6.14",
    "webpack": "^5.72.0"
  }
```

**Comment by elevatebart** [comment]
Styleguidist never calls devServer.close() in the binary. This might be the cause. It sounds like a bug/regression in webpack-dev-server... I might be wrong on this.
