### ISSUE TITLE
Relative CSS imports break in external stylesheets

### ISSUE THREAD

**Issue by rafegoldberg** [vue-styleguidist/vue-styleguidist#133]
I have a (simplified) component structure like this:

```bash
src/
 ├ components/search.vue
 └ assets/
   ├ search-nullcase.svg
   └ search-zerocase.svg
```

In the search component's styles I import a few images: (I'm using Vue's established `webpackConfig.resolve` shorthand, but I also tried with relative imports to no avail.)

```vue
<style lang=scss scoped>
.Search {
  &--case-null {
    background-image: url('~@/assets/search-nullcase.svg');
    }
  &--case-zero {
    background-image: url('~@/assets/search-zerocase.svg');
    }
  }
</style>
```

When I run the `vue-styleguidist server` everything builds together and renders nicely:

```bash
docs/
 ├ index.html
 ├ build/
 ├ css/main.css
 └ img/
   ├ search-nullcase.svg
   └ search-zerocase.svg
```

The import path gets converted to a relative `img/[filename].[hash].svg` path, per the Webpack config:

```css
.Search--case-null {
    background-image: url('img/search-nullcase.svg');
}
.Search--case-zero {
    background-image: url('img/search-zerocase.svg');
}
```

Since the `server` injects CSS in inline style tags, the path resolves against the _document's_ URL and everything works as expected. But when I try loading the `vue-styleguidist build` (on GitHub pages, for example, or via a simple HTTP server) I run in to a snag. The `vue-styleguidist build` actually links to the external stylesheet in the `docs/css/` directory, rather than inlining the styles. The issue being that my relative `url()` now resolves against the _stylesheet's_ path, rather than the document root. And since the stylesheet gets built in to the `docs/css/` sub-directory, the resolved path is not correct. (Should be one level less deep: `../img/[filename].[hash].svg`, which works...)

I haven't been able to come up with a solution. Possibly I'm missing some key point? Or making a silly mistake? Please correct me/point me in the right direction.

**Comment by jonCliq** [comment]
Has anyone come up with a solution for this?

**Comment by jonCliq** [comment]
https://github.com/vue-styleguidist/vue-styleguidist/issues/289

**Comment by elevatebart** [comment]
Not yet. @jonCliq would you be open to share a repo where the problem can be found?
