### ISSUE TITLE
Importing children components. Module not found: Error: Can't resolve

### ISSUE THREAD

**Issue by whosdustin** [vue-styleguidist/vue-styleguidist#1340]
To start, I've been successful with all of vue-styleguidist up to this point. The moment I imported a component into another component I'm met with `Module not found`.

**Dependencies:**
```
"typescript": "~4.5.2",
"vue-loader": "^15.0.0",
"vue": "2.6.14",
"vue-property-decorator": "^9.1.2",
"vue-style-loader": "^4.1.3",
"vue-styleguidist": "^4.45.1",
"ts-loader": "^9.3.1",
"webpack": "^5.0.0",
```

Full error:
```sh
Module not found: Error: Can't resolve '../ui-comp-chip' in '/correct/path/to/component'
[tsl] ERROR in /correct/path/to/ui-comp/UiComp.ts(8,26)
      TS2307: Cannot find module '../ui-comp-child/UiCompChild.vue' or its corresponding type declaration
```

Below is the file directory with corresponding files that may paint a picture of what I am doing. For the sake of brevity, I've removed any information that is unnecessary to solve the problem.

```
lib/
├─ ui-comp/
│  ├─ index.ts
│  ├─ UiComp.ts
│  ├─ UIComp.Vue
├─ ui-comp-child/
│  ├─ index.ts
│  ├─ UiCompChild.ts
│  ├─ UiCompChild.vue

```

```ts
// ui-comp/UiComp.ts

import { Vue, Component, Prop } from 'vue-property-decorator';

import UiCompChild from '../ui-comp-child';

@Component({
  components: {
      UiChipAction,
  },
})
export default class UiComp extends Vue {}
```

```vue
// ui-comp/UiComp.vue

<template>
  <span>
      <ui-comp-child></ui-comp-child>
  </span>
</template>

<script lang="ts" src="./UiComp.ts"></script>
```

```ts
// ui-comp/index.ts

import UiComp from './UiComp.vue';
export default UiComp;
```

```js
// styleguide.config.js
module.exports = {
  ...
  components: [
    path.join(process.cwd(), 'path/to/files/', '**/*.vue')
  ],
  webpackConfig() {
    return {
      module: {
        rules: [
          {
            test: /\.ts$/,
            loader: 'ts-loader',
            options: { appendTsSuffixTo: [/\.vue$/] }
          },
          {
            test: /\.vue$/,
            loader: 'vue-loader'
          },
          {
            test: /\.scss$/,
            use: [
              'vue-style-loader',
              'css-loader',
              'sass-loader'
            ]
          }
        ]
      },
      plugins: [ new VueLoaderPlugin() ],
    }
  }
}
```

**Comment by elevatebart** [comment]
Can I ask for a reproduction repo?

You did all the work to describe it. The last step would help a ton with having a fix.

**Comment by whosdustin** [comment]
Hi @elevatebart thank you for responding so quickly. Unfortunately, I'm unable to share my working repo, but I was able to recreate the entire project in a very generic form.

A few things to note:
- The repo is using [Nx](https://nx.dev)
- Just clone the repo, `npm install` and run `nx serve ui-docs` will reproduce the errors I'm experiencing.
- Do to the nature of Nx you will notice some oddities such as the docs are in an entire directory than the components.
- All of the scripts are not in a `package.json` but are actually in a `project.json` 

Repo: https://github.com/whosdustin/v-styleg

Thank you for your help.

**Comment by whosdustin** [comment]
Hi again @elevatebart, 
I was concerned that it might be my setup (Nx) that may have been affecting the build. I decided to remove anything except the essentials to see if I still receive the error. 

Here is a more skeleton repo which still reproduces the error.
https://github.com/whosdustin/test-vstyle

**Comment by elevatebart** [comment]
hello @whosdustin,

The investigation is going well:
- The error you get points to the missing `shims-vue.d.ts`. Perhaps this file is in your project but not in scope of the `tsconfig.json`. 
- Once that's taken care of, I get another error: The loader does not resolve `../ui-child` to `../ui-child/index.ts`. I think it has to do with the `tsconfig`. Let me check.

**Comment by elevatebart** [comment]
All is good now.

https://github.com/whosdustin/test-vstyle/pull/1

**Comment by whosdustin** [comment]
Thank you so much! It's always the simplest things that one can miss. I appreciate you taking the time to help me.
