### ISSUE TITLE
loaderContext.getOptions is not a function

### ISSUE THREAD

**Issue by stephenjason89** [vue-styleguidist/vue-styleguidist#1349]
Hello @elevatebart ,
I don't know what happened but my styleguidist was perfectly working before.

Now, I am getting this and can't seem to find where everything broke
<img width="1715" alt="image" src="https://user-images.githubusercontent.com/3810177/177130646-942cce23-9993-4ac4-9977-2253f2e4a2b4.png">

Any help is deeply appreciated

**Comment by elevatebart** [comment]
This looks like a Webpack 5 loader used with webpack 4.
Updating your `unplugin` might fix it.

**Comment by stephenjason89** [comment]
@elevatebart thank you for the reply.
However, what fixed it for me was installing ts-loader 8.4.0 
ts-loader 9 produces the errors. 
It really is about webpack 5 and webpack 4 compatibility
