### ISSUE TITLE
Typescript Type Assertion Problem (Potential Bug)

### ISSUE THREAD

**Issue by stephenjason89** [vue-styleguidist/vue-styleguidist#1350]
Hello @elevatebart 
I have noticed that type assertion like this
<img width="601" alt="image" src="https://user-images.githubusercontent.com/3810177/177140225-125bb8a5-959a-4d00-a90b-94746d613b20.png">
works fine

but type assertion like this does not work and throws
<img width="585" alt="image" src="https://user-images.githubusercontent.com/3810177/177140301-7de7b448-7cf5-46fa-9417-1d5cade7ed8c.png">
<img width="779" alt="image" src="https://user-images.githubusercontent.com/3810177/177140370-45b43250-23c6-4459-9580-0646718a362a.png">

Thank you

**Comment by elevatebart** [comment]
If you want to use these kinds of type assertions, you have to set the [jsxInComponents](https://vue-styleguidist.github.io/Configuration.html#jsxincomponents) to false.

Babel does not accept both JSX and this type of assessment.

**Comment by stephenjason89** [comment]
Thank you @elevatebart .
That worked perfectly
