### ISSUE TITLE
Vue-CLI + Vue 3 "Happy Path" documentation

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vue-styleguidist/vue-styleguidist#1355]
I just saw that the issue for Vue 3 support was closed 4 days ago (https://github.com/vue-styleguidist/vue-styleguidist/issues/997). That's awesome!

There are a lot of issues and requests against this repo, but I wanted to make a request for a "Happy Path" to be prioritized.

* `npm install -g @vue/cli`
  * Globally install the Vue-CLI
* `vue create -d app-name`
  * Create a default (`-d`) Vue 3 project
* `cd app-name`
  * Change directory into your new Vue 3 project
* `vue add styleguidist`
  * Add Styleguidist. Because we are using `vue add`, Styleguidist should know to use the version of Webpack built in to Vue-CLI and not need any additional dependencies installed beyond `vue-cli-plugin-styleguidist`
* `npm run styleguide`
  * Start up the server, without any warnings or error messages like:
    * `DefinePlugin`
    * `Conflicting values for '__VUE_PROD_DEVTOOLS__'`
    * `TypeError: createElement is not a function`
    * `ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17`
    * `There is already an app instance mounted on the host container. If you want to mount another app on the same host container, you need to unmount the previous app by calling app.unmount() first.`

You could even chain all of these together, then walk away to make a sandwich, come back and the project is all set up:

`npm install -g @vue/cli && vue create -d app-name && cd app-name && vue add styleguidist && npm run styleguide`

To me, this seems like the most common use case, so it would make sense to prioritize it.

**Comment by elevatebart** [comment]
You are absolutely right and I am on it.

It is really hard to build realistic unit tests around the vue cli plugin system.

**Comment by TheJaredWilcurt** [comment]
For testing maybe a single "E2E" style smoke-test that does

`npm install -g @vue/cli && vue create -d test-app && cd test-app && vue add styleguidist && npm run build`

And if it throws an error, then there's a problem 🤷‍♀️

**Comment by elevatebart** [comment]
Yeah! that's true. 
I would have loved to be able to have this tested before publishing, though.

Anyway, we are back in business, and this command does work fine now 😄

Enjoy!

**Comment by TheJaredWilcurt** [comment]
Works great. Would be nice to emphasize Vue 3 compatibility in the docs now too, but closing this.
