### ISSUE TITLE
Entire configuration gets skipped if it fails for any reason.

### ISSUE THREAD

**Issue by shadow7412** [vue-styleguidist/vue-styleguidist#1357]
**Current behaviour**

If there is something wrong with the config file, it gets skipped instead of causing an error.

```javascript
// vue-cli-plugin-styleguidist/index.js:77
function getStyleguidist(args, api, options) {
  const confFilePath = api.resolve(args.config || './styleguide.config.js')
  let sgConf = {}
  try {
    sgConf = confFilePath && confFilePath.length ? require(confFilePath) : {}
  } catch (e) {
    // eat any error if config file is absent
  }
 //...
```

This seems to be so that if the file does not exist we revert to a default config. Fair enough.

But that exception handling doesn't stop there - if the import failed for any reason, it swallows the error and just uses the default instead. It would be more useful if the compilation stopped with an error message instead of ignoring the config file completely.

Note: This also occurs when the config file is specified using command line arguments. I'd argue that if the config file has been set, the compilation should unconditionally fail if the file doesn't exist.

**To reproduce**

1. Create a fresh project (or use any project, really).
2. Set the title, so we can see that it is being applied. If you compile now, all is fine.
3. Introduce a syntax error, bad import, or anything else that could cause an exception to the config file.
4. Compile again - and note that the title set in step 2 is now ignored.

**Expected behaviour**

A build failure with a useful error message when the config file exists, but is bad.

**Comment by elevatebart** [comment]
Wowowowow... I really dropped the ball on this one, apologies.

**Comment by shadow7412** [comment]
Haha, it happens :)

**Comment by elevatebart** [comment]
Just delivered a fix but forgot to link it... I need to be better at this

**Comment by elevatebart** [comment]
Fix delivered in version [vue-cli-plugin-styleguidist@4.45.1](https://github.com/vue-styleguidist/vue-styleguidist/releases/tag/vue-cli-plugin-styleguidist%404.45.1)
