### ISSUE TITLE
Include component which uses $store in the content markdown file

### ISSUE THREAD

**Issue by claudio147** [vue-styleguidist/vue-styleguidist#136]
I can't include a component which uses `$store` in the "s-welcomde.md" file (throws error message). If I include the component to a "e-button.md" file for e.g. (config see bellow) it works. 
Probably a bug?

Error message:
<img width="1373" alt="bildschirmfoto 2018-05-17 um 17 35 36" src="https://user-images.githubusercontent.com/12095490/40187951-19c09c10-59f9-11e8-9370-cd42859f09ef.png">

_styleguide.config.js_
` sections: [
    {
      name: 'Welcome',
      content: '',
      sections: [
        {
          name: 'Informations',
          content: 'app/styleguide/components/s-welcome.md',
        }
      ]
    },
    {
      name: 'Elements',
      components: 'app/components/e-button.vue',
    }`

**Comment by rafaesc** [comment]
Hi @claudio147,

maybe its a problem of an example in `s-welcome.md`, can you share the file .md

**Comment by claudio147** [comment]
hi @rafaesc , this is my `s-welcome.md` file:

----------- 
### Welcome to the component styleguide
Here you see all the project components.

For example pages go to
<a href="http://localhost:8080/styleguide" target="_blank">localhost:8080/styleguide</a><br>
To serve the Vue environment run:
``` Apache
$ npm run dev
```

#### Theme selector
```vue
<s-theme-selector/>
```
-----------

**Comment by rafaesc** [comment]
@claudio147 I think that I need more detail about of the project to resolve. You can create a demo with the issue or you can see this example with vuex integration: 
https://github.com/vue-styleguidist/vue-styleguidist/tree/master/examples/vuex

**Comment by elevatebart** [comment]
I believe the vuex example combined with the nuxt example can provide a clear solution
