### ISSUE TITLE
 TypeError: Cannot read property 'tap' of undefined. Vue2 

### ISSUE THREAD

**Issue by jay-p-b-7span** [vue-styleguidist/vue-styleguidist#1375]
"dependencies": {
    "@apollo/client": "^3.5.9",
    "@splidejs/splide": "^4.0.7",
    "@splidejs/vue-splide": "^0.3.5",
    "apollo-upload-client": "^17.0.0",
    "axios": "^0.27.2",
    "core-js": "^3.6.5",
    "graphql": "^16.3.0",
    "graphql.js": "^0.6.8",
    "lodash-es": "^4.17.21",
    "object-to-formdata": "^4.4.2",
    "portal-vue": "^2.1.7",
    "qs": "^6.10.3",
    "raw-loader": "^4.0.2",
    "shilp": "^0.1.0-beta.32",
    "shilp-vue": "^0.7.0",
    "text-mask-addons": "^3.8.0",
    "v-calendar": "^2.4.1",
    "v-mask": "^2.3.0",
    "v-tooltip": "^2.1.3",
    "vee-validate": "^3.4.14",
    "vue": "^2.6.11",
    "vue-dropdowns": "^1.1.2",
    "vue-infinite-scroll": "^2.0.2",
    "vue-moment": "^4.1.0",
    "vue-router": "^3.5.3",
    "vue-select": "^3.18.3",
    "vue2-datepicker": "^3.10.4",
    "vuejs-countdown-timer": "^2.1.3",
    "vuex": "^3.4.0",
    "vuex-persist": "^3.1.3"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "autoprefixer": "^9.8.8",
    "babel-eslint": "^10.1.0",
    "sass-loader": "^8.0.2",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "postcss": "^7.0.39",
    "sass": "^1.49.7",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.2.17",
    "vue-template-compiler": "^2.6.11"
  }

**Comment by elevatebart** [comment]
Hello @jay-p-b-7span,

1. Please be courteous in your tickets in the future if you want a chance for them to be fixed. I do all this work for free. Saying "hello" and "please" does not cost you much, but chows me that you care. 
2. In this half-cut `package.json` there seem to be no trace of vue-styleguidist so I do not see the connection between styleguidist and this.
3. If you need an answer quickly, creating a minimum reproduction repository on your GitHub account starting by forking [vue-styleguidist-example](https://github.com/vue-styleguidist/vue-styleguidist-example) could help.

Thank you for understanding.
