### ISSUE TITLE
did not recognize object of type "TSInstantiationExpression"

### ISSUE THREAD

**Issue by SamWangCoder** [vue-styleguidist/vue-styleguidist#1377]
My code just like this:
``` vue
<script lang="ts">
import { defineComponent } from 'vue';

interface RawData {
  readonly id: number
  tab: string
  order: string
  link?: string
}

export default defineComponent({
  props: {
    rawData: {
      type: Array<RawData>,
      default: () => [],
    },
  },
});
</script>
```

When I run `vue-docgen --watch`, got this error:
``` shell
[0] Error: Error parsing D:\Ysh\Repos\ysh-ui-proj\proj\ysh-ui\src\components\YshTabs\YshTabs.vue for @requires tags: did not recognize object of type "TSInstantiationExpression"
[0]     at D:\Ysh\Repos\ysh-ui-proj\proj\ysh-ui\node_modules\vue-docgen-cli\lib\getSources.js:136:27
[0]     at step (D:\Ysh\Repos\ysh-ui-proj\proj\ysh-ui\node_modules\vue-docgen-cli\lib\getSources.js:63:23)
[0]     at Object.throw (D:\Ysh\Repos\ysh-ui-proj\proj\ysh-ui\node_modules\vue-docgen-cli\lib\getSources.js:44:53)
[0]     at rejected (D:\Ysh\Repos\ysh-ui-proj\proj\ysh-ui\node_modules\vue-docgen-cli\lib\getSources.js:36:65)
[0] vue-docgen --watch exited with code 1
```
(vue3 + vite)

When I use `Array` as rawData`s type, it will runs good.

**Comment by elevatebart** [comment]
Do you set jsx to false in `docgen.config.js` ?

See [the reference to configure further](https://vue-styleguidist.github.io/docs/docgen-cli.html#config)

```js
// docgen.config.js

module.exports = {
  apiOptions: {
    jsx: false // tell vue-docgen-api that your components are not using JSX. We need this flag so TypeScript <type> syntax does not barf.
  },
}
```

**Comment by elevatebart** [comment]
The code is not exactly valid TypeScript either

Check it here: 
https://sfc.vuejs.org/

**Comment by SamWangCoder** [comment]
I try to move type definedion to `type.d.ts`, set `jsx` to `true` or `false`, get same error.
My code like this:

[sfc demo](https://sfc.vuejs.org/#eNpNUMFywiAQ/ZUdLuqMknuqdpz2C3otPaDZWGwCzEJqnQz/3gXT1Avwdh+7771RHLyX3wOKWmzDiYyP0Gl73ikRgxJ7ZU3vHUUYocHWWHxxjC3aCAlacj0s+PPiaebFm0cmv+nrq456JskqNzJPWfwpTJ6nh67cj3OXo7IAnpwPNZQ3AN2nzRjKmhoORPq2/qtNA2tYrmC3h/ePqZPKnc+0YgHb6u6TvTGI2PtOR2QEMI7TppQyb+6Jtbjb2/Tay0twluMqWtTU4KxmdUpwJBkr8Rkj26iq0J5yyJcgHZ0rfkkabDQ9Sgz95kjuGpB4sBJFKivlldmjbGQMvGzKzNiI1OoTzgGXnYS6cba7gWlqsEN/RMrlqI81hEjGnjN01CA9Fjpjv57/C0mkX7KatMk=)

**Comment by SamWangCoder** [comment]
Is my mistake, after read vue`s doc [typing-component-props](https://vuejs.org/guide/typescript/options-api.html#typing-component-props), it runs good! Thanks for your help!

my code
``` vue
<script lang="ts">
import { defineComponent } from 'vue';
import type { PropType } from 'vue';

interface RawData {
  readonly id: number
  tab: string
  order: string
  link?: string
}

export default defineComponent({
  props: {
    rawData: {
      type: Array as PropType<Array<RawData>>,
      default: [] as Array<RawData[]>,
    },
  },
});
</script>
```
