### ISSUE TITLE
how to use in js file

### ISSUE THREAD

**Issue by fshihu** [vue-styleguidist/vue-styleguidist#1378]
dist/map-manger/abase/MapManager.js

```js

export class MapManager {
    constructor(map) {
        this.markerHoverLayer = new MarkerHoverLayer(map,this);
        this.infoWindowLayer = new InfoWindowLayer(map,this);
        this.markerLayer = new MarkerLayer(map,this);
        this.polygonLayer = new PolygonLayer(map,this);
        this.mapObj = map;
    }

    removeHoverAndInfoWindow(){
        this.markerHoverLayer.remove();
        this.infoWindowLayer.remove();
    }
    mouseover(hover_marker){
        if(hover_marker){
            this.markerHoverLayer.render(hover_marker)
        }
    }
}
```

styleguide.config.js

```js
{
	name:'map',
	content: 'styleguide/docs/map-manger/class.md',
	components: 'dist/map-manger/abase/*.js',
	exampleMode: 'collapse', // 'hide' | 'collapse' | 'expand'
	usageMode: 'expand' // 'hide' | 'collapse' | 'expand'
}
```
is not work

**Comment by elevatebart** [comment]
How does this component work? 
Is this React? Svelte? Solid? 
Is this Pure JS? 
Is this related to a vue component?

vue-styleguidist parse documented patterns of writing VueJs components.
If you are looking for a JSDoc/TSDoc renderer you can use [ESDoc](https://esdoc.org), or [documentation](https://github.com/documentationjs/documentation)

**Comment by fshihu** [comment]
Esdoc is the feature I want, but how does it work with Vue-StyleGuidist

**Comment by fshihu** [comment]
I think I know what to do. Thank you

**Comment by elevatebart** [comment]
I believe what I would do is use those tools to generate markdown and integrate this markdown in the styleguide using the content option of a section.

**Comment by elevatebart** [comment]
I am glad you found a way ;)
