### ISSUE TITLE
Improve error reporting in examples

### ISSUE THREAD

**Issue by Infeligo** [vue-styleguidist/vue-styleguidist#138]
I have created [an example project](https://github.com/Infeligo/vsg-problem) (based on the Basic example), which is unable to render an example for Button component, displaying `Error: Line 1: Unexpected token <` message instead. Here is the example itself (defined in ```vue block):

```
<template>
    <div class="wrapper">
        <Button>{{ $t('greeting') }}</Button>
    </div>
</template>
<script>
const Vue = require('vue');
const VueI18n = require('vue-i18n');

Vue.use(VueI18n);

const i18n = new VueI18n({
    messages: {
        en: {
            greeting: "Hello!"
        }
    },
    locale: 'en'
});

export default {
    name: 'vue-i18n-demo',
    i18n
};
</script>
```

1. I am pretty sure that there the example is syntactically correct. I have created a separate component `I18nDemo` based on the example and it works. Why does Styleguidist show such a cryptic error message? Can this be improved?

2. Can I `require()` stuff like that in the example? Why doesn't it work?

**Comment by Infeligo** [comment]
So I did some digging into the problem and found out that this is not that easy to solve. The real problem is that VueStyleguidist does some code slicing/transformation and tries to compile it then. This may result in the situation when user's code is correct, but the transformed one is not.

In my case, the first problem was that I used `new VueI18n`. Inside of the Preview component there is a check that detects whether the example is a SFC or not like this: `code.indexOf('new Vue')`. In my example, this check caught the `new VueI18n` constructor call.

After I renamed the import, there was another issue. It seems that VueStyleguide transforms SFC into `new Vue(...)`-style component. In the process, it extracts all the `require()` statements and the `export default`, but not the stuff between them. This is why in my case the `i18n` constant gets missing. It would be nice to describe this limitation in the documentation (if I am correct in my findings).

**Comment by rafaesc** [comment]
Hi @Infeligo,

I don't recommend to use a plugin inside each component because it could generate unexpected problems if you want to use third-party plugins, it should be in the main of the vue app.

You see an example using `vue-i18n` and vue-styleguidist
https://github.com/vue-styleguidist/vue-styleguidist/tree/master/examples/vuetify

**Comment by elevatebart** [comment]
This looks very much outdated. @Infeligo can you please check if this works? If it is still an issue please feel free to reopen.
Keep in mind that styleguidist is more of a showcase than an actual complete sandbox
