### ISSUE TITLE
Allow users to enhance the Vue app instance in vue 3

### ISSUE THREAD

**Issue by elevatebart** [vue-styleguidist/vue-styleguidist#1381]
This is a follow up to #125

I will need to add another option: `enhancePreviewApp`.

Here is how you will use it:

```js
// styleguide.config.js
import { defineConfig } from 'vue-styleguidist'

export default defineConfig({
  enhancePreviewApp: 'styleguide/enhanceApp.js' // path of the file you want to define directives in
})
```

```js
// styleguide/enhanceApp.js
import directive from '@/directives'
import { defineEnhanceApp } from 'vue-styleguidist'

export default defineEnhanceApp((app) => {
  app.directive('directive', directive)
})
```

**Comment by elevatebart** [comment]
@didagu please follow this issue for follow-up on directives.

**Comment by didagu** [comment]
@elevatebart Alright, thanks for the update. I am looking forward to using it in the next available version.

**Comment by aleksre** [comment]
@elevatebart I can't seem to get this feature to work. It prints out the error:
```
Module parse failed: Unexpected token (1:14)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> Copyright (c) silverwind
| All rights reserved.
|
```
It's just a normal js file. We already use the `renderRootJsx` and `require` options for other files in the same folder and that works as expected, just this one doesn't work.

The error seems to be linked to actually importing `defineEnhanceApp`, because it goes away if I remove it without changing anything else and it also comes back if I import `defineEnhanceApp` from another file (like require.ts) even if I don't actually use it.

**Comment by didagu** [comment]
Hey @aleksre, I had the same problem. Below is the workaround that worked for me.

```
import loadable from './src/directives/loadable';

// workaround to use the function directly here from vue-styleguidist
// otherwise Module parse error occurs from webpack
function defineEnhanceApp(enhance) {
  return enhance;
}

export default defineEnhanceApp((app) => {
  app.directive('loadable', loadable);
});
```

**Comment by elevatebart** [comment]
@didagu 
You can skip the function altogether. 
It was meant to help write the code with the proper types.

It is returning exactly its params without modification.

```js
export default (app) => {
  app.directive('loadable', loadable);
}
```

**Comment by didagu** [comment]
alright, thanks @elevatebart.
Have you also noticed that each time one clicks on an item in the list of components on the left, the styleguide does not scroll to the exact position ?

**Comment by elevatebart** [comment]
I have not, would you please create an issue for that (a quick video would help too)
