### ISSUE TITLE
How to document a Component inside "script setup" blocks?

### ISSUE THREAD

**Issue by David-Mueller** [vue-styleguidist/vue-styleguidist#1399]
Hi there!

How to document it?
Slots, props and events are working fine. 
But how to set the basic Component description?

```
<script setup lang="ts">
/**
 * This should show up somewhere.
 */
...
</script>
```

**Comment by elevatebart** [comment]
hello @David-Mueller ,

really good question.

Right now, I don’t know. What do you suggest the API should be?

If you add a comment right at the beginning of the script block, do you think it would be clear enough?
You can always add a docs block but it’s not the same.

Another suggestion would be if you can have an empty defineProps() function call, a comment on the function call could be a good idea.

Food for thought.

**Comment by elevatebart** [comment]
There is always the solution of adding a second script block with an empty export default and comment this.

**Comment by elevatebart** [comment]
It feels clunky

**Comment by David-Mueller** [comment]
Heyhey,

I think I would either just use the first jsdoc block which is not associated with props, emits, slots or other things or look for an annotation like  "@ DisplayName" to identify the doc block which should be documenting the component...

not sure :D

The "commented default export" hack is helpful for now! (I agree, only a workaround)

**Comment by duclet** [comment]
I agree that the first comment block would make sense. Right now, the commented default export hack doesn't even work for me.

**Comment by crystalfp** [comment]
I'm not alone! Just thinking was my fault...
My `*.vue` file starts with `<script setup lang="ts">` so for me the right place is just after this line.

**Comment by adrienZ** [comment]
Hi :)

> There is always the solution of adding a second script block with an empty export default and comment this.

I didn't succeed to make it work but if you are using typescript, the signature of the component will change :/ 

While you are working on a proper implementation, Is there any workaround ? do you have an exemple of [script handler](https://vue-styleguidist.github.io/docs/Docgen.html#script-handlers) that sets `documentation.description` to the value of the first comment block ?

**Comment by duclet** [comment]
I didn't go too much further and just went with this in the configs. To also not need to do much processing, I went with this style of doc for the component:

```javascript
    /*@component
    This is the doc for the component.
    It does not have that * prefix for each line but you can probably easily fix parser.
    */
```

```javascript
    apiOptions: {
        addScriptHandlers: [
            function (
                documentation,
                componentDefinition,
                astPath,
                opt
            ) {
                const componentDoc = astPath.tokens.filter(token => token.type === 'CommentBlock' && token.value.includes('@component')).find(() => true);
                if (componentDoc) {
                    const lines = componentDoc.value.split('\n');

                    documentation.set('description', lines.filter(line => !line.includes('@component')).map(line => line.substring(componentDoc.loc.indent)).join('\n'));
                }
            }
        ]
    },
```

**Comment by crystalfp** [comment]
I have a <docs> block with the component description. It work, but you have to add an extension to `vite` to make it ignore this block and add a `templates: {component: . . .}` function to `docgen.config.js` If needed I can append everything here.

**Comment by David-Mueller** [comment]
FYI for us, the `<docs>...</docs>` block worked fine with a vite plugin:
```
export const vueDocsPlugin = () => ({
  name: 'vue-docs',
  transform(code, id) {
    if (!/vue&type=docs/.test(id))
      return;
    return `export default ''`;
  }
});
```

**Comment by elevatebart** [comment]
@duclet handling the comment in a separate handler is a great Idea. I think I will follow this architecture.

**Comment by dasmikko** [comment]
> I didn't go too much further and just went with this in the configs. To also not need to do much processing, I went with this style of doc for the component:
> 
> ```js
>     /*@component
>     This is the doc for the component.
>     It does not have that * prefix for each line but you can probably easily fix parser.
>     */
> ```
> 
> ```js
>     apiOptions: {
>         addScriptHandlers: [
>             function (
>                 documentation,
>                 componentDefinition,
>                 astPath,
>                 opt
>             ) {
>                 const componentDoc = astPath.tokens.filter(token => token.type === 'CommentBlock' && token.value.includes('@component')).find(() => true);
>                 if (componentDoc) {
>                     const lines = componentDoc.value.split('\n');
> 
>                     documentation.set('description', lines.filter(line => !line.includes('@component')).map(line => line.substring(componentDoc.loc.indent)).join('\n'));
>                 }
>             }
>         ]
>     },
> ```

This is pretty neat! How would I add support for stuff like `@displayName`?

Edit:
Nevermind, after some tinkering, I made a solution:

```js
apiOptions: {
        addScriptHandlers: [
            function (
              documentation,
              componentDefinition,
              astPath,
              opt
            ) {
                const componentDoc = astPath.tokens.filter(token => token.type === 'CommentBlock' && token.value.includes('@component')).find(() => true);
                if (componentDoc) {
                    const lines = componentDoc.value.split('\n');
                    const nameLine = lines.filter(line => line.includes('@displayName'))[0]
                    
                    if (nameLine) {
                        documentation.set('displayName', nameLine.replaceAll('@displayName ', ''))
                    }
                    documentation.set('description', lines.filter(line => !line.includes('@component') && !line.includes('@displayName')).map(line => line.substring(componentDoc.loc.indent)).join('\n'));
                }
            }
        ]
    },
```

**Comment by crystalfp** [comment]
Thanks @dasmikko !
With small adjustments it works perfectly. Add the following to `docgen.config.js`:
```
	apiOptions: {
		addScriptHandlers: [
            function (
                documentation,
                componentDefinition,
                astPath,
                opt
            ) {
                const componentDoc = astPath.tokens
			.filter(
				token => token.type === 'CommentBlock' &&
				token.value.includes('@component')
			)
			.find(() => true);
                if(componentDoc) {
			const text = componentDoc.value
				.replaceAll("\r", "")
				.replace(/@component */, "")
				.replace(/^[*\n ]*/, "")
				.replace(/[*\n ]*$/, "")
				.replaceAll(/\n *\* +/g, " ");
                        documentation.set('description', text);
                }
            }
          ]
	},

**Comment by dasmikko** [comment]
> Thanks @dasmikko ! With small adjustments it works perfectly. Add the following to `docgen.config.js`:
> 
> ```
> 	apiOptions: {
> 		addScriptHandlers: [
>             function (
>                 documentation,
>                 componentDefinition,
>                 astPath,
>                 opt
>             ) {
>                 const componentDoc = astPath.tokens
> 			.filter(
> 				token => token.type === 'CommentBlock' &&
> 				token.value.includes('@component')
> 			)
> 			.find(() => true);
>                 if(componentDoc) {
> 			const text = componentDoc.value
> 				.replaceAll("\r", "")
> 				.replace(/@component */, "")
> 				.replace(/^[*\n ]*/, "")
> 				.replace(/[*\n ]*$/, "")
> 				.replaceAll(/\n *\* +/g, " ");
>                         documentation.set('description', text);
>                 }
>             }
>           ]
> 	},
> ```
Cool! I'm just not sure how displayName is set in your example?

**Comment by crystalfp** [comment]
Not included for now. For me it is sufficient the title derived from the filename.
Anyway, I think to include a split of the string (text) on `@component` and then on `@displayName` to extract the contents.
Hope it helps.

**Comment by elevatebart** [comment]
Finally ! we got a definitive answer from the Vue team itself!
In PR #1575, I parse the `defineOptions()` function call as if it's an option defined component.

```js
/**
  * Overridden component description
  * @version 12.5.7
  * @author [Rafael]
  * @example path/to/example.md
  * @displayName Best Button Ever
  */
defineOptions({
  name: 'VSGButton'
})
```

**Comment by xiaoxiangmoe** [comment]
@elevatebart @David-Mueller 

```ts
/**
  * Overridden component description
  * @version 12.5.7
  * @author [Rafael]
  * @example path/to/example.md
  * @displayName Best Button Ever
  */
defineOptions({
  name: 'VSGButton'
})
```

This is not help for see jsdoc for the component self. We can use it instead

```vue
<script lang="ts">
/**
 * # My Button Component
 * To trigger an operation.
 * 
 * @deprecated Please use `MyButtonV2` instead.
 * 
 * @example
 * ```vue
 * <MyButton>Click Me</MyButton>
 * ```
 */
export default {};
</script>
<script setup lang="ts">
interface MyButtonProps {
  /**
   * Set button type
   */
  buttonType?: 'primary' | 'dashed' | 'link' | 'text' | 'default';
}
defineProps<MyButtonProps>();
</script>
<template>
  <button></button>
</template>
```
<img width="703" alt="image" src="https://github.com/vue-styleguidist/vue-styleguidist/assets/8111351/660c722d-7a27-4f21-a7c2-657859c286a1">
