### ISSUE TITLE
Order of documented components unpredictable switches

### ISSUE THREAD

**Issue by pvogel2** [vue-styleguidist/vue-styleguidist#1414]
--------------^ Click “Preview”!

Hello everyone, 
When I use the command line tool vue-docgen (configured to generate one output md file) the order of the documented components switches from time to time. I guess this is caused in the line
https://github.com/vue-styleguidist/vue-styleguidist/blob/65407ea8cb6f28a0157aea3883b488e60e927f16/packages/vue-docgen-cli/src/compileTemplates.ts#L57
when the Promise all creates a runtime condition for the order of the components.

I am right here or do I miss something? Maybe there is a way to keep the order of documented components.

Thx in advance!

**Comment by elevatebart** [comment]
Good catch,

I think we should order them alphabetically by default (following the component displayName, filename if none Is provided) and provide a configuration function to sort them at custom.

What is you take on this?

**Comment by pvogel2** [comment]
Hi elevatebart!
I now understand better what happenes, because in my case I have multiple single component files which are processed and the documentation is written in a single md outfile. So in fact in my case I think the problem happens at this line processing the singleMd.js case:
https://github.com/vue-styleguidist/vue-styleguidist/blob/65407ea8cb6f28a0157aea3883b488e60e927f16/packages/vue-docgen-cli/src/singleMd.ts#L91

As far as I understand the Promise.all creates an object with altering key order which then leads to altered array items when calling Object.values.
But anyway, in the end it is just the same problem.

And yes, I would think some kind of sorting should solve the problem. In this case there would be the property key as the only sortable information available I think. Or may be the cachedContent Object could be extended by a property (component name) for sorting?

**Comment by elevatebart** [comment]
I would pass to the function the whole component definition for 2 components expecting 0, -1 and +1 as a result.

Then I'd use array.sort to sort them before writing them down on the md file.

**Comment by pvogel2** [comment]
I started trying a very basic fix, see https://github.com/pvogel2/vue-styleguidist/tree/fix/ISSUE-1414-order-of-documented-components
I am not familiar with ts or vitest, so I am sure it can be improved (especially the testing), but its a start.
