### ISSUE TITLE
Volar's vue-component-meta package

### ISSUE THREAD

**Issue by TechAkayy** [vue-styleguidist/vue-styleguidist#1418]
Hi there, 

I just found one of Volar's package https://github.com/johnsoncodehk/volar/tree/master/vue-language-tools/vue-component-meta doing something very similar to what vue-docgen-api does. 

There could be an opportunity to leverage each other when doing the same thing, so leaving this note for the awesome maintainers of this repo. Thanks.

**Comment by elevatebart** [comment]
Hehe !!! You are absolutely right.

Checkout this example: https://github.com/vue-styleguidist/vue-styleguidist/tree/dev/examples/docgen-vite

This is how I would use `vue-comeponent-meta` to parse components 

https://github.com/vue-styleguidist/vue-styleguidist/blob/65407ea8cb6f28a0157aea3883b488e60e927f16/examples/docgen-vite/docgen.config.js#L17-L52

You can use it in `vue-docgen-cli`, or use it in `vue-styleguidist` in the same way using this config:
https://vue-styleguidist.github.io/Configuration.html#propsparser

You could even combine the findings of the 2 parsers if you needed to. This would make a meta robot worth sharing.

Tell me if this helps.

**Comment by TechAkayy** [comment]
Thanks bunch for the pointers @elevatebart :-) Appreciate it! Will continue my study & exploration!
