### ISSUE TITLE
Add option to disable JSDocs

### ISSUE THREAD

**Issue by Infeligo** [vue-styleguidist/vue-styleguidist#142]
Related to the problems described in #117, it would be nice to have an option to fully disable parsing of  JSDoc to improve performance. Ideally, this would be toggleable via CLI option so one could disable it for the server and still enable it in the final build.

**Comment by rafaesc** [comment]
Hi @Infeligo,

Good feedback, your idea is an alternative, but before to try with that, I would like to migrate from JSDoc to [doctrine](https://github.com/eslint/doctrine), I think that it could improve the performance.

At the same time, I try to research which modules are slowest

**Comment by Infeligo** [comment]
Thanks for response. I think you are right in your decision to try to fix this first. In the meanwhile, I have coped with my problem by commenting out certain lines in the `vuedoc-loader.js`. That works for me as a temporary solution.

**Comment by elevatebart** [comment]
@Infeligo we are trying to clean our bug pipe.
Can you try and see if the perf is better on 3.0 ? We made huge improvements (x20) to vue-docgen-api
