### ISSUE TITLE
Problem with docgen cli and the docgen api with utf-8 files

### ISSUE THREAD

**Issue by DrChemistry** [vue-styleguidist/vue-styleguidist#1425]
Hello, at my work we are are using vuedocgen-cli
We just want to generate markdowns files from our .vue files.
We are french and write our documetation in French, during the generation all our accents are not properly imported. It looks like the vuedocgen-api doesn't support utf-8.
Is there any way we can go around it ?
Here is our docgen config.
`const path = require('path')

module.exports = {
  componentsRoot: 'app-pwa/src/components/', // the folder where CLI will start searching for components.
  components: '**/nibe-*.vue', // the glob to define what files should be documented as components (relative to componentRoot)
	outDir : 'app-pwa/docs', // where files will be stocked
}`

**Comment by elevatebart** [comment]
Hello @DrChemistry ,

Thank you for this quick update.
I think this really is an oops on my side.

I am French as well (Grenoblois vivant a Chicago).
I am going to get right on it.

**Comment by elevatebart** [comment]
In the branch attached to this issue, I added a couple of examples of usage of utf8 encoding.

It seems to work on my machine (or in CI) so I wonder if maybe your setup is a little different.

Can you try to create a minimum reproduction for this issue?
The method:
- fork this repo
- add a new example that fails
- create a PR with the failing example

If you can't. Can you provide the OS, node version, versions of docgen and vue?
Can you also provide a component whose documentation fails to render?

Any information helps.

**Comment by DrChemistry** [comment]
Hello @elevatebart , i'm sorry for not responding.
You were right, and we found our problem.
Please keep making this amazing tool !
