### ISSUE TITLE
Example docgen-vite: MarkdownIt extension does not work with current `@vue/compiler-sfc`

### ISSUE THREAD

**Issue by susnux** [vue-styleguidist/vue-styleguidist#1437]
**Current behavior**
The return value of `parse` have been changed so this part of the example code (in the markdown extension) does not work anymore:
```js
const { descriptor } = parse(code)
if (descriptor) {
	const imports = Object.keys(descriptor?.script?.imports || {})
	return imports
}
```

instead it has to look like this, as you have to compile the script:
```js
const { descriptor } = parse(code)
const compiled = compileScript(descriptor, { inlineTemplate: true, id: `${idx}` })
if (descriptor) {
	const imports = Object.keys(compiled?.imports || {})
	return imports
}
```

**To reproduce**
* Check out the example and upgrade to `@vue/compiler-sfc` to `3.2.45`.
* Notice that `parse().descriptor.script` does not contain `imports`

**Expected behavior**
Imports are extracted successfully. (see above for a solution)

**Comment by jd1378** [comment]
the solution above is again broken in latest vue versions

and it only works when using `<script setup>`

and even then, I get `error: require is not defined
    at Proxy._sfc_render ....`

**Comment by jd1378** [comment]
How about using regex instead ?
```js
// from https://github.com/antonkc/MOR/blob/main/matchJsImports.md
const importRegex = /(?<=(?:[\s\n;])|^)(?:import[\s\n]*((?:(?<=[\s\n])type)?)(?=[\n\s\*\{])[\s\n]*)((?:(?:[_\$\w][_\$\w0-9]*)(?:[\s\n]+(?:as[\s\n]+(?:[_\$\w][_\$\w0-9]*)))?(?=(?:[\n\s]*,[\n\s]*[\{\*])|(?:[\n\s]+from)))?)[\s\n,]*((?:\*[\n\s]*(?:as[\s\n]+(?:[_\$\w][_\$\w0-9]*))(?=[\n\s]+from))?)[\s\n,]*((?:\{[n\s]*(?:(?:[_\$\w][_\$\w0-9]*)(?:[\s\n]+(?:as[\s\n]+(?:[_\$\w][_\$\w0-9]*)))?[\s\n]*,?[\s\n]*)*\}(?=[\n\s]*from))?)(?:[\s\n]*((?:from)?))[\s\n]*(?:["']([^"']*)(["']))[\s\n]*?;?/gi;
```

```js
const getImports = code => {
  const matches = code.matchAll(importRegex);
  const imports = [];
  for (const match of matches) {
    imports.push(match[6]);
  }
  return imports
}
```

**Comment by elevatebart** [comment]
Thank you both for reporting it. I need to fix the example indeed.

For work, I maintain https://design.cypress.io, a site that uses on the same toolset. It is open source so I invite you to go and have a look at the docs directory. It has an example that works.
