### ISSUE TITLE
<docs> block content rendered in the wrong place

### ISSUE THREAD

**Issue by crystalfp** [vue-styleguidist/vue-styleguidist#1439]
**Current behavior**
The content of a <docs> block is rendered after the horizontal rule that begins all component's documentation when rendered in a single file. For example:
```
---
# MovableResizableDialog

## Props
[...]

## Events
[...]

## Slots
[...]

---

Content of the docs block
# NextComponent
```

**To reproduce**
Compile the following vue file:
```
<docs>
Documentation for this component
</docs>
<script setup lang="ts">
const props = defineProps<{
  title: string;
}>();
</script>
<template>
<div>{{ props.title }}</div>
</template>
```
with this `docgen.config.js`:
```
module.exports = {
        components: "components/*.vue",
	componentsRoot: "src",
	outDir: "doc/vue",
	outFile: "components.md",
}
```

**Expected behavior**
I expect to have the <docs> block content just after the component name:
```
# MyComponent
Documentation for this component

## Props
[...]
```
Or at least before the horizontal rule at the end of the component section:
```
# MyComponent
[...]
Documentation for this component

---

# NextComponent
```
Thanks for considering!
mario

**Comment by crystalfp** [comment]
Well, solved by adding `templates: {component: . . .}` to `docgen.config.js`.
Had problems using require, so simply copied the component.js of the package inside the docgen file.

**Comment by elevatebart** [comment]
Just to confirm, is there still an undesired behavior?

Do you still expect a change in docgen-cli ?

**Comment by crystalfp** [comment]
No, thanks. The configuration solved my formatting problem.

The only remaining thing is to understand where to define all the variables used in the component() function. I tried with `/** @description: bla bla */` at the beginning of the vue file and it does not appears anywhere.
