### ISSUE TITLE
line break escaped for the props that are set as `model`

### ISSUE THREAD

**Issue by elevatebart** [vue-styleguidist/vue-styleguidist#1443]
This fix causes the line break element to be escaped for the props that are set as `model`. For example;

```js
/**
 * Provides a two-way data binding interface to the component
 * @model
 */
modelValue: {
  type: Boolean,
  default: false,
},
```

Sets the prop as a model which is also passed through to the documentation. But after this fix it gets escaped like this.

```diff
- | v-model | Provides a two-way data binding interface to the component<br/>`@model` true | boolean | -                                                          | false |
+ | v-model | Provides a two-way data binding interface to the component&lt;br/&gt;`@model` true | boolean | -                                                          | false |
```

...which results it to be rendered as a plain text
![image](https://user-images.githubusercontent.com/393186/207622920-ec643b5a-e985-4b17-b3ff-b9ba25434f26.png)

_Originally posted by @sevilyilmaz in https://github.com/vue-styleguidist/vue-styleguidist/issues/1433#issuecomment-1351504119_

**Comment by sevilyilmaz** [comment]
@elevatebart, I also realised that it escapes other cases.

```diff
- Defines size of the avatar block.<br/>This is a <a href="./#/page/Getting-started%2FPrinciples%2FComponents/documentation/" target="_blank">responsive prop</a> that can be defined per viewport.
+ Defines size of the avatar block.<br/>This is a &lt;a href="./#/page/Getting-started%2FPrinciples%2FComponents/documentation/" target="\_blank"&gt;responsive prop&lt;/a&gt; that can be defined per viewport.
```

Do you have any suggestion to pass a link to the documentation with `target` attribute until this issue gets fixed?

_P.S. For now, I use the old `mdclean` function that I put in my `docgen.config`_

**Comment by elevatebart** [comment]
@sevilyilmaz I am fixing the return bug.

Regarding the `target='_blank'` do you want to add this behavior to only one link?
I would prefer to avoid having too much html within the comments of the components if we can avoid it.

If what you are looking for is to make all external links open in a new window, I would do it is using a markdown-it/remark-rehype plugin. The markdown would stay the same but the html would point outwards.

[Check this out](https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer)

I hope this helps.

**Comment by sevilyilmaz** [comment]
I also wouldn't want to have/extend a whitelist or blacklist kind of a thing. I was expecting the markdown parser would allow to pass attributes to the elements as some of the parsers does, e.g `[text](URL){:target="_blank"}`.

If this would make things complicated or hard to maintain I'm fine the alternative that you provided.

**Comment by elevatebart** [comment]
You could use https://www.npmjs.com/package/markdown-it-kramdown-attrs
