### ISSUE TITLE
Lack of support for `defineExpose` in script setup synthax

### ISSUE THREAD

**Issue by adrienZ** [vue-styleguidist/vue-styleguidist#1447]
Hi :)

I see in the source code some [files](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/src/script-setup-handlers/setupExposedHandler.ts) and [tests](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/tests/components/setup-syntax/Progress.vue) about defineExpose but I also see some problems.

I mark this issue as feature request as the docs only mentions emits & props in setup synthax.
> From version 4.44.0, Vue Styleguidist allows to document the props & events defined with this syntax.

in `vue-docgen-api/tests/components/setup-syntax/Progress.vue` it uses a `defineExposed` function but in `vue-docgen-api/src/script-setup-handlers/setupExposedHandler.test.ts` it uses `defineExpose`.

I also tried to use defineExpose even tho it is not documented but it does not seems to work: https://github.com/adrienZ/styleguidist-define-expose-bug

This is frustrating for nice tool as styleguidist to not keep up with vue new features as this prevents migration to composition api :/

**Comment by elevatebart** [comment]
@adrienZ believe me the first one that is frustrated is me :D

It is a bug on my part. 
I had envisioned handling `defineExpose` in a different member than "methods" since one can expose more than a method. Unfortunately I never got around to it.

Intend to implement.

**Comment by adrienZ** [comment]
Thanks for this ! l'll try it later,  can i be helpful to write the docs ?

**Comment by elevatebart** [comment]
@adrienZ Yes please! 

EDIT And also, you rock if you do!
