### ISSUE TITLE
Multiple root elements in examples are no longer displayed

### ISSUE THREAD

**Issue by yellowsunday** [vue-styleguidist/vue-styleguidist#1458]
**Current behavior**

Previously, multiple root elements in examples were displayed. This was supported in the fix for issue #259

**To reproduce**

The Basic example includes this in the second example "Big pink button and small blue button:".
https://vue-styleguidist.github.io/basic/

```
<BestButton size="large" color="deeppink">
  Click Me
</BestButton>
<br />
<BestButton size="small" color="blue">
  Second button
</BestButton>
```

Currently it is only showing the pink button.

**Expected behavior**

All elements in the example code would be displayed.

Alternatively if this can no longer be supported, it would be really helpful if an error message could be displayed somewhere, to make it easier to find and fix existing examples that have this problem.

**Comment by elevatebart** [comment]
It is funny, we should have a unit test for that...
I really thought we did.
