### ISSUE TITLE
Error “React.createElement: type is invalid” when replacing style guide renderer

### ISSUE THREAD

**Issue by VincentSmedinga** [vue-styleguidist/vue-styleguidist#146]
I’m trying to change the layout as described [in the cookbook](https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Cookbook.md#how-to-change-the-layout-of-a-style-guide), but I keep getting a React error that I’m not familiar with.

I have:
- Installed "babel-plugin-transform-class-properties": "^6.24.1" and "babel-preset-react": "^6.24.1" as dev dependencies;
- Added "react" to "presets", and "transform-class-properties" to "plugins" in .babelrc;
- Inserted `styleguideComponents: { StyleGuideRenderer: path.join(__dirname, 'lib/styleguide/StyleGuideRenderer.js') }` into styleguide.config.js;
- Created /lib/styleguide/StyleGuideRenderer.js with the exact same content as in the cookbook;
- Made sure the babel-loader compiles the file in Webpack.

After restarting the server (no compile errors) and reloading the style guide, I’m getting “Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `StyleGuide`.” in the browser console.

However, the cookbook doesn’t mention needing to export or import anything.

I tried the same with the Wrapper component but got the exact same result – oddly enough mentioning StyleGuide as well, not Wrapper.

When opening `node_modules/vue-styleguidist/lib/rsg-components/StyleGuide/StyleGuideRenderer.js`, it seems like a compiled file and not at all like what I find [here](https://github.com/vue-styleguidist/vue-styleguidist/blob/v1.7.8/src/rsg-components/StyleGuide/StyleGuideRenderer.js) on GitHub.

Any help to find out what more I should do to make this work would be greatly appreciated.

And after that, can I use Vue components inside that StyleGuide template? (More precise: a [portal-vue](https://github.com/LinusBorg/portal-vue) `portal-target`? That’s why I’m trying to edit the rendered templates.

**Comment by rafaesc** [comment]
Hi @VincentSmedinga,

yes, I will update the cookbook. Did you try with this example?
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/examples/customised

Try to add this config
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/examples/customised/styleguide.config.js#L59-L67

The component `Wrapper` is deprecated, instead, try to use [renderRootJsx option](https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Configuration.md#renderrootjsx) to changed the layout of each preview example.

**Comment by elevatebart** [comment]
Hello @VincentSmedinga,

Sorry for not bugging you earlier, the cookbook has [moved a little](https://vue-styleguidist.github.io/docs/Cookbook.html#how-to-change-the-layout-of-a-style-guide).

The bug you are having seems to be linked to the babel config you are using. 
If you try doing the following at the beginning of your `StyleGuideRenderer` it should not send the error anymore.

```js
const React = require('react');
```
The reason you are having this weird bug is in  the internals of react. When jsx is compiled into js,
it uses a pragma and `return <div classname="test"/>` is transformed into `return React.createElement('div', {className:'test'});`.

You, therefore, need to import React even if it is not obvious. 
And you do, here, import React. 
`import React from 'react';` actually means `import { default as React } from 'react'`. Unless we use the `interop` or `unambiguous` flag of babel, the imported value is going to be React.default... undefined. 
If you really want to use import, use the typescript + react way: `import * as React from 'react'`.
This should fix it too.

I hope this helped a little.

**Comment by elevatebart** [comment]
Regarding `portal-vue`, you have 2 choices:
Register it globally using [this receipe](https://vue-styleguidist.github.io/docs/Cookbook.html#how-to-add-third-party-plugins-to-the-style-guide)

Or import it in one or two examples and use [this receipe](https://vue-styleguidist.github.io/docs/Cookbook.html#how-to-hide-some-components-in-style-guide-but-make-them-available-in-examples). Note that you can require anything in your examples including packages installed via npm or yarn.

**Comment by elevatebart** [comment]
Hey @VincentSmedinga, if you still have the issue, feel free to re-open it ;)
