### ISSUE TITLE
Default slot

### ISSUE THREAD

**Issue by entioentio** [vue-styleguidist/vue-styleguidist#147]
This works perfectly:
```
...Use this slot for text contents -->
        <slot name="text">Click me</slot>
        <div class="BasicButton_icon">
            <!-- @slot Use this slot for setting an icon -->
            <slot name="icon"></slot>
        </div>
...
```
...whilst the following renders component inside component; (see PRTSC)

```
...
<!-- @slot Use this slot for text contents -->
        <slot>Click me</slot>
        <div class="BasicButton_icon">
            <!-- @slot Use this slot for setting an icon -->
            <slot name="icon"></slot>
        </div>
...
```

![image](https://user-images.githubusercontent.com/10046841/41338483-9b934e8c-6ef2-11e8-9e65-a03683c2ae3d.png)

Did i do anything wrong with the slots implementation? Or is that a bug with default slots?

**Comment by elevatebart** [comment]
Hello @entioentio , we are trying to clean up the bug pipe. 
Can you tell me if you still reproduce with vsg 3.0. If you do, could you share the way you use those slots?

Thank you in advance

**Comment by stephsavoie** [comment]
@entioentio it should be working in version 3.0.  I currently use 3.0.9 and I uses default slots in many places and in different markup depth. 

it's even working in self-closing tag like below:
```
<!-- @slot this is a default slot-->
<slot />
```

**Comment by entioentio** [comment]
Hi @stephsavoie. I tried to install the project where it was failing, but I've run into dependency upgrade hell. I wanted to tried it once more when i have time to hopefully give some insightful feedback. I'll go with what you say. Thanks for taking care of the issue.
