### ISSUE TITLE
Dependency vulnerability

### ISSUE THREAD

**Issue by Salsatore89** [vue-styleguidist/vue-styleguidist#148]
Hi,
Npm audit is notifying a vulnerability in one of the dependencies of your package (v1.7.8):

![image](https://user-images.githubusercontent.com/4136148/41418978-3a29f7c2-6ff1-11e8-9a5a-54aaf6e9da76.png)

**Comment by rafaesc** [comment]
@Salsatore89 fixed on 1.7.9 version of vue-styleguidist. Regards
