### ISSUE TITLE
[vue-docgen-api]: Crash when model is not a raw object

### ISSUE THREAD

**Issue by Kolobok12309** [vue-styleguidist/vue-styleguidist#1481]
**Current behavior**

Currently if we have code like this, docgen is crashed.

```js
const getModel = (prop = 'modelValue', event = `update:${prop}`) => ({
  prop,
  event,
});

export default {
  model: getModel(),
}
```

Error in this code
https://github.com/vue-styleguidist/vue-styleguidist/blob/cdc08922eabf8264a3b963e04c38b6c7af33fee9/packages/vue-docgen-api/src/script-handlers/propHandler.ts#L513-L515

**To reproduce**

https://github.com/Kolobok12309/vue-docgen-cli-model-reproduce

**Expected behavior**

`return null` from function `getModelPropName` as stated in the comment

**Comment by elevatebart** [comment]
Such a beautifully crafted bug report it makes me wanna cry !!!

Thank you !
