### ISSUE TITLE
`vue-docgen-cli` can not use ESM config

### ISSUE THREAD

**Issue by susnux** [vue-styleguidist/vue-styleguidist#1494]
### Current behavior
On a project with `type: "module"` the config can not be parsed because module js can not be "required".

### To reproduce
1. Create simple config on a project with `type: "module"`
2. try to run `vue-docgen-cli`
3. See node error

### Expected behavior
Preferably: Support module js configs.
otherwise: Look also for `.cjs` named config files.

### Notes on how to fix
There are three ways to fix this:
1. Do not allow module js configs and look for config with `.cjs` extension
2. Make `extractConfig` async and use dynamic import (`import()`) which supports both: common js and module js, BUT this required `tsc` to be configured to `moduleResolution: "node16"` and as such at least node16 is required.
3. Make `vue-docgen-cli` ESM by default. Same as above, but instead of changing the module resolution set package to `type: "module"` and configure Typescript to at least `module: "es2016"`.

I would prefer *3* as it is cleaner and more "future-proof". I don not think this would be a real breaking change as it is only a CLI tool. The only breaking part would be that the lowest supported node version will increase to `12.17.0` (but that should be fine, even that version is EOL for some time).

I can directly provide a PR for option 2, but I can also provide a PR for option 3 if you wish :)

**Comment by elevatebart** [comment]
> I can directly provide a PR for option 2, but I can also provide a PR for option 3 if you wish :)

I would love that. Thank you !! 
I too noticed this issue. 
I was working around by using the following command specifying that the config file is here:

```node
yarn vue-docgen -c docgen.config.cjs
```

GOgogogo !!
