### ISSUE TITLE
Error while npm run build

### ISSUE THREAD

**Issue by troglotit** [vue-styleguidist/vue-styleguidist#15]
I get this error while trying to build `vue-styleguidist` itself, while trying to contribute to it. Both on yarn and npm v5. As this issue is not client/consumer side, it's not that high priority. If everything works for you, feel free to close the issue 😃 
```
Error in build/bundle.29e4e95d.js from UglifyJs
Unexpected token: operator (>) [build/bundle.29e4e95d.js:30719,19]
```

**Comment by rafaesc92** [comment]
Hi @troglotit.

It's strange. The procedure is to clone the repository, rename the .babel.lock to .babel, execute ``npm install`` and ``npm run build``, should already work. Please could you try with this latest version?

**Comment by troglotit** [comment]
Hi! 

Sorry for not including exact reproduction steps 😓  I forgot if it was `npm run build` or not.

But everything works right now! I'll open new/reopen this if I'll face this error again!

**Comment by rafaesc92** [comment]
Thanks @troglotit 👍
