### ISSUE TITLE
[vue-docgen-cli]: Hmr not worked for separated SFC

### ISSUE THREAD

**Issue by Kolobok12309** [vue-styleguidist/vue-styleguidist#1508]
**Current behavior**

For current component, hmr worked for `.vue`, but not for `.ts`

```vue
<template>
    <button class="button" :style="{ color: color, fontSize: fontSize }" @click.prevent="onClick">
      <!-- @slot Content of button -->
      <slot></slot>
    </button>
</template>

<script
  src="./index.ts"
  lang="ts"
></script>
```

```ts
// index.ts
/**
 * The only true button.
 */
export default {
  name: 'Button',
  props: {
    /**
     * The color for the button.
     */
    color: {
      type: String,
      default: '#333'
    },
  },
}

```

**To reproduce**

https://github.com/Kolobok12309/vue-docgen-cli-separate-hmr

**Expected behavior**

Worked hmr for all `.vue` dependencies like `<script src>`, `<style src>` and other

**Comment by elevatebart** [comment]
As of now, I don't watch dependencies of files but that sounds like a fun enhancement to implement.

Steps to get it to work:
- have `vue-docgen-api` return file dependencies
- add those dependencies to the watcher + fix the docs mapping to get the proper file to regenerate

**Comment by Kolobok12309** [comment]
If i use `components: './index.*'` instead of `components: './index.vue'` it worked, but think it's not normal
