### ISSUE TITLE
add required in vue-docgen-cli templates props

### ISSUE THREAD

**Issue by janceChun** [vue-styleguidist/vue-styleguidist#1527]
Is it possible to add required in [vue-docgen-cli](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-cli/src/templates/props.ts#L26) templates  props

**Comment by elevatebart** [comment]
It is indeed, I was thinking of adding it as add-on to the attribute.

...The more I use it the more impractical I find the table. 

We want to shove too much information on one line including the description, examples. 

Do you have any ideas for alternative designs?

**Comment by janceChun** [comment]
>
The component library we used before was vuese  which has a design that might offer you some reference. 
https://github.com/vuese/vuese/blob/monorepo/packages/markdown-render/lib/index.ts#L38

**Comment by elevatebart** [comment]
That is the design I was trying to avoid. 
HTML Tables are not well suited to present any long text (like a description or examples).
That's my opinion. And you can always decide to use your custom template.
