### ISSUE TITLE
Docs Tag Breaks Vue Build

### ISSUE THREAD

**Issue by rafegoldberg** [vue-styleguidist/vue-styleguidist#154]
I'm having issues using the `<docs/>` tag. I tried adding some additional examples to one of my single-file `.vue` components:

```
<docs>
Hello, here's a further usage example:

    <UiBoxImage>
  	  <UiHeading :level=2>Default Example Usage</UiHeading>
    </UiBoxImage>
</docs>
```

When I run styleguidist (`v1.7.11`) e'erything compiles as expected. But if I try to run the Vue dev server now I get the following error re: that `<docs/>` tag:

```
ERROR  Failed to compile with 1 errors
error  in ./src/components/UI/Box/Image.vue?vue&type=custom&index=0&blockType=docs&lang=md

 Module parse failed: Unterminated string constant (63:11)
 You may need an appropriate loader to handle this file type.
 |
 |
 > Hello, here's a further usage example!
 |
```

I vaguely understand how Vue's custom blocks work, so on some level I'd guess the issue is external. However, I know when I'd used older versions of `vue-styleguidist` those docs tag worked seamlessly without any extra configuration. Have I made some dumb mistake? Is there a new step that I'm missing?

And thanks for all the work here!

**Comment by rafaesc** [comment]
Can you create a repo with the issue, it will be easier to fix it. Regards

**Comment by rafegoldberg** [comment]
@rafaesc will do when I have a moment; mañana hopefully!

**Comment by rafegoldberg** [comment]
yo @rafaesc – k, so it took me a sec to get back to this; my apologies. but lo! Here's [a simplified repo to demonstrate the issue at hand](https://github.com/rafegoldberg/vue-styleguidist-docs-tag-issue). I threw it together pretty quickly so feel free to bug me with questions if/where things are unclear. But hopefully it's enough to give you a sense of what the problem is. And thanks in advance!

**Comment by rafegoldberg** [comment]
adding this basic-ass loader to my `vue.config.js:configureWebpack`** entry seems to solve whatever issues Vue was having with `<docs/>` custom blocks: 

```js
module: {
  rules: [
  { resourceQuery: /blockType=docs/,
    loader: require.resolve('./.docs.loader.js')
    },
  ]
}
```

I ripped the code for the loader directly out of the [Vue docs](https://vue-loader.vuejs.org/guide/custom-blocks.html):

```js
/**
 * @file: .docs.loader.js
 */
module.exports = function (source, map) {
  this.callback(
    null,
    `export default function (Component) {
      Component.options.__docs = ${
        JSON.stringify(source)
      }
    }`,
    map
  )
}
```

(Not sure how it'd be integrated into `vue-styleguidist` though — maybe as a kind of a fallback loader or something?)

**Comment by rafaesc** [comment]
Thanks for being so clear,
The fix, it should be in a plugin because with that you can customize vue cli webpack.

I think that @elevatebart already has [a plugin with vue-styleguidist](https://github.com/elevatebart/vue-cli-plugin-styleguidist) that could add this feature.

**Comment by rafegoldberg** [comment]
Hmm that's interesting. Will definitely look in to [said plugin](/elevatebart/vue-cli-plugin-styleguidist); thanks for pointing it out! That said, are you suggesting the custom docs block loader _remain_ external to the `vue-styleguidist` core? So anyone who installed the vanilla (i.e. non-plugin) version would continue to have issues with the docs tag?

I'd imagine this could cause some confusion, especially since the `<docs>` tag is highlighted _directly_ within Styleguidist's docs. Plus, requiring devs jump through a tertiary dependency seems like a sub-par solution. As such, I'd definitely push to internalize the loader for these custom blocks so everything "just works." (Or  alternately, I guess you could you could just update the `<docs>` to better outline the process around this feature...)

But the decision is yours; that's just my 2¢! (Not that you asked for it...) Anyway, closing this issue as resolved. Thanks for taking the time to walk me through this.

**Comment by rafaesc** [comment]
A plugin cli alternative is a good solution for a quick integration with `vue-cli`, however, it's necessary another solution for vue application without `vue-cli`. 

documentation should be updated because it will cause confusion, but feel free to send a PR. I don't know how vue-styleguidist could change the webpack config, maybe vue-styleguidist could export some loader or plugin, but maybe it is a weird idea because the problem of custom blocks it is the normal behavior of vue-loader, but the documentation could help to give a simple solution.

**Comment by rafegoldberg** [comment]
Ahhh, I gotchya – well I'll take a look at the relevant docs and possibly submit a PR when I get some time! Thanks again.
