### ISSUE TITLE
defineProps and defineEmits are undefined

### ISSUE THREAD

**Issue by futurfuturfuturfutur** [vue-styleguidist/vue-styleguidist#1555]
I am trying to define emits and props using Vue 3 macros defineProps and defineEmits like that:

```vue
<template>
{{ props.foo }}
</template>

<script setup>
import { onMounted } from "vue"

const props = defineProps({
  foo: String,
  required: false
})

const emit = defineEmits(["update"])

onMounted(() => {
  emit("update")
})
</script>

<style scoped lang="scss">
</style>
```

The problem is both emits and props are undefined after declaring, so now it's impossible to declare them like that.

**Comment by elevatebart** [comment]
Woops !!!

**Comment by elevatebart** [comment]
I still wonder what you expect to do with it.

**Comment by futurfuturfuturfutur** [comment]
Actually, I missed the repo to open the issue, sorry, it' supposed to be vue-live
I am using Preview component to render component and want to implement control of component states and events, so I can define them inside rendered component and handle them outside. For example, to debug events triggers or props passing of the component.

**Comment by elevatebart** [comment]
You did create it in the right repo, but I transferred it since the problem was upstream. 

I also forgot to add a 'withDefaults' function in there...

Tomorrow then.

I am very curious to see your workflow. If you can record a quick video to show me what you use it for it would help me make sure it always works.

Thank you for the hype!!

**Comment by futurfuturfuturfutur** [comment]
Yeah, I probably should explain what I am trying to achive more detailed.

I am messing around with my pet project. The idea is to implement workspace where you could create components with ability to import them into each other and use imported component as it is a real component. For example we can create form component, input component and button component and then import input and button components into form component, so form component could use its props and events to interact with them. As a result it gives the flow of atomic design, and beauty here is that after update of imported components all updates are rendered inside parent component as well. I don't know if it's really useful as development approach but I really like the vibe of that.

How I implemented it for now:
1. I handle success event of the render and push new render to array of all rendered components in the workspace
``` js
// Inside render wrapper
const handleSuccess = () => {
  emit("update:render", (props, context) => {
    context.attrs.code = code.value;
    return h(VueLivePreview, context.attrs, context.slots);
  });
};

// Inside workspace
<AppComponentFrame
      v-for="(component, index) in data.components"
      v-model:render="data.renders[component.id]"
      :renders="data.renders"
      ...
/>
```
2. Then if some component is imported inside another one I pass this render through requirements
``` js
const requiresForComponent = computed(() => {
  const components = props.data.imports.map((component) => {
    return {
      ["@/components/" + camelCase(component.name) + component.id + ".vue"]:
        props.renders[component.id],
    };
  });

  return Object.assign({}, ...components);
});
```
So I can emulate real life components imporing approach and use it like it is a real component somewhere inside workspace project importing it like:
```imoport componernName from "@/components/componentName.vue"```

For now I faced those issues:
1. Defined props and emits are not defined actually, so I can't use them inside parent component. I was implementing the same flow couple years ago, when this repo was supporing only vue 2 with options syntax and it works out of the box pretty well with 
```
props: {},
emits: []
```
It would be great to achieve same behavior with composition API syntax. As I can see your commits related to this issue define like dummy functions for defineProps and defineEmits not real life behavior of them.
2. It would be great to return with success event from render to wrapper parsed props and emits defined in component code, so wrapper could specify states and debug events. It is cool for documentation flow alike storybook. Again, I have implemented it in the past for vue2 using utils like that:
```js
// parseState.js
export default function getPropsAndEvents(code, options) {
  const regexpEvents = /(\$emit\(([^)]+)\))/g

  const events = [...code.matchAll(regexpEvents)]

  return {
    props: Object.entries(options.props).map((prop) => {
      return {
        name: prop[0],
        type: prop[1].type.name,
        default:
          typeof prop[1].default == "function"
            ? prop[1].default()
            : prop[1].default,
      }
    },
    events: events
      .map((event) => {
        let params = event[2].split(",")
        let eventName = params[0]
        eventName = eventName.substring(0, eventName.length - 1)
        eventName = eventName.substring(1)
        return eventName
      })
      .reduce(
        (unique, item) => (unique.includes(item) ? unique : [...unique, item]),
        []
      )
      .map((eventName) => {
        return {
          name: eventName,
        }
      }),
  }
}
```
Now I don't think it is a smooth enough implementation, but as an idea. Wrapper can handle success render and get parsed props and events defined in it, it's useful to document events and states. For example: button component defined prop :style and inside wrapper you can define state solid or bordered passed inside this prop and it's easy to just switch states and see what will happen.

Here is demo of my old implementation for Vue 2 options syntax
https://streamable.com/cgtlbp
