### ISSUE TITLE
"View Code" during development

### ISSUE THREAD

**Issue by NathanKleekamp** [vue-styleguidist/vue-styleguidist#157]
Is the "view code" section supposed to work during development?

When I build it, it works but not otherwise. Before I go through and create a reproduction repo, I just wanted to make sure. Thanks!

**Comment by rafaesc** [comment]
@NathanKleekamp yes it should work, you can send a case to review it

**Comment by NathanKleekamp** [comment]
I think there is something in our Webpack config that is conflicting with vue-styleguidist. Rather than trying to track that down and making sure vue-styleguidist works with our setup, I added a simplified `webpackConfig` to our `styleguide.config.js` and everything seems to work as expected now. I'm going to close this. Thanks for you hard work on this project!
