### ISSUE TITLE
`name` option set via `defineOptions` is not reflected in the URL

### ISSUE THREAD

**Issue by h0adp0re** [vue-styleguidist/vue-styleguidist#1575]
**Current behavior**

`name` option set via `defineOptions` is not reflected in the URL. Filename is used instead.

**To reproduce**

Use `defineOptions` in `<script setup>` (https://vuejs.org/api/sfc-script-setup.html#defineoptions) to define a custom `name` for a component.

**Expected behavior**

The custom `name` defined via `defineOptions` is used in the URL for the component.

**Comment by h0adp0re** [comment]
Thanks, @elevatebart! Can you estimate when will this be released?

**Comment by h0adp0re** [comment]
Or how to use this fix? I see it's released in `vue-docgen-api@4.73.0` but I don't seem to be able install that package in my project as a dev dependency and expect the issue to be solved?

---

Edit: It seems `npm update vue-docgen-api` did the trick. But the feature doesn't work still?

**Comment by elevatebart** [comment]
Let me try and add some e2e tests for docgen

**Comment by elevatebart** [comment]
checkout #1583
