### ISSUE TITLE
Type of prop is not extracted when declaring a prop without type field with undefined as unknown as PropType<...>

### ISSUE THREAD

**Issue by vidal7** [vue-styleguidist/vue-styleguidist#1578]
**Current behavior**

When declaring a prop

```ts
prop: undefined as unknown as PropType<number>
```

type is not extracted

```
{ name: 'prop' }
```

but when setting this same type in the type field, it works

```ts
prop: {
    type: undefined as unknown as PropType<number>
}
```

type is extracted correctly

```
{ name: 'prop', type: { name: 'number' } }
```

**To reproduce**

```ts
import { defineComponent, PropType } from 'vue';

export default defineComponent({
  props: {
    prop1: undefined as unknown as PropType<number>, // This is valid Vue syntax, but type is not extracted in docgen
    prop2: {
        type: undefined as unknown as PropType<number> // This is valid Vue syntax, and type is extracted in docgen
    }
  }
});
```

**Expected behavior**

Type is extracted correctly when type field is not present in prop declaration

**Comment by elevatebart** [comment]
OK that's a bug and I can fix it. So I will fix it.

Can you add a concrete use case where you would like this kind of syntax?

**Comment by vidal7** [comment]
> OK that's a bug and I can fix it. So I will fix it.
> 
> Can you add a concrete use case where you would like this kind of syntax?

Thank you @elevatebart. Yes. if you don't want a runtime type checks https://vuejs.org/guide/components/props.html#prop-validation but do want a compile time type check in TypeScript.

TypeScript won't let you cast a undefined type so that's why it is casted first as unknown.

**Comment by vidal7** [comment]
Wow! Thank you very much @elevatebart. That was very quick!
