### ISSUE TITLE
[vue-docgen-api] Unable to resolve props doc with union types and defineProps

### ISSUE THREAD

**Issue by jf-niji** [vue-styleguidist/vue-styleguidist#1579]
Hello,

I am using your library and I have a use case that it seems to be not supported. Using **union types** with **defineProps** generate the following error when running storybook:

```txt
[vite] Internal server error: Cannot read properties of undefined (reading 'length')
  Plugin: storybook:vue-docgen-plugin
```

The error occurs in this function: **getPropsFromLiteralType**

Here is a component that reproduce the error:
```vue
<template>
  <button type="button">
    {{ msg }}
  </button>
</template>

<script lang="ts" setup>
  import { computed } from 'vue'

  type BaseProps = {
    /**
     * The msg of the button
     */
    msg: string
  }

  type MyProps = BaseProps & {
    /**
     * primary or secondary button
     */
    primary?: boolean
    /**
     * size of the button
     */
    size?: 'small' | 'medium' | 'large'
  }

  const { primary = false, size = 'small', msg } = defineProps<MyProps>()
</script>
```

- **I'm using the experimental features of props destructuring but this issue is also true with `withDefault()` function**
- **Using interface does not generate any errors.**

**My question is**: Should you currently support this use case? Or this is a bug or new use cases to implement?

System info : 

```
  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 4.41 GB / 15.74 GB
  Binaries:
    Node: 20.0.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.51)  
    Internet Explorer: 11.0.19041.1566
```

Thank you.

**Comment by AlanKnightly** [comment]
I meet the same error today, I spend the whole day and have not figure it out...

**Comment by ryoji-yamauchi-blc** [comment]
I created a PR just to work around the error.
t only avoids errors, though, so the document is not automatically generated😓

https://github.com/vue-styleguidist/vue-styleguidist/pull/1604
