### ISSUE TITLE
Mixin with a .vue file is not displayed in the doc

### ISSUE THREAD

**Issue by vdcrea** [vue-styleguidist/vue-styleguidist#158]
Hi, and thanks to contributors for this great lib.

import a .vue file (not .js) as a mixin (even with relative path) hide it from the doc. Do you have any workaround for that ?

**Comment by vdcrea** [comment]
no worry, for now I added the doc in the text before, you can have ca look at my repo:
- mixins are here https://gitlab.com/vdcrea/vue-leaflet/tree/master/src/mixins
- here is a use of a mixin in a component https://gitlab.com/vdcrea/vue-leaflet/blob/master/src/components/core/LMap.vue#L21

**Comment by vdcrea** [comment]
Oups sorry, this is not relevant exemple. I will do a mixin with a .vue component to show.

**Comment by elevatebart** [comment]
@vdcrea 
We just released 3.0 and it should be way better now. Can you tell me if you still do not see your mixin?

**Comment by angelowolf** [comment]
Hello we have a base component, wich is used as a mixins in many other components. The template is only in the mixins. The mixins looks like this:
```
<template>
  <button v-tooltip.hover="tooltip" @click.prevent="$emit('click')" :class="`btn btn-${type} ${(size && ' btn-'+size)} ${clase}`" type="button">{{label}}</button>
</template>
<script>
  /**
  * Estructura base para todos los botones.
  * @mixin
  */
  export default {
    props: {
      /**
      * Clase que se le agrega al botón.
      */
      clase: {
        default: '',
        type: String
      },
      /**
      * El tipo de botón.
      * `primary, primary2, info, default, default2, danger, danger2, warning, warning2, success`
      */
      type: {
        default: 'primary',
        type: String
      },
      /**
      * El tamaño del botón.
      * `xs, sm, md, lg`
      */
      size: {
        default: 'sm',
        type: String
      },
      /**
      * Label a mostrar en el botón.
      */
      label: {
        default: '',
        type: String
      },
      /**
      * El texto a mostrar en el tooltip del botón.
      */
      tooltip: {
        default: '',
        type: String
      }
    }
  }
</script>
```

And this is an example of a componente that uses it:

```
<script>
import TrxButtonBase from './TrxButtonBase'

export default {
  mixins: [TrxButtonBase],
  props: {
    /**
    * Label a mostrar en el botón.
    */
    label: {
      default: 'Volver',
      type: String
    },
    /**
    * El tipo de botón.
    * `primary, primary2, info, default, default2, danger, danger2, warning, warning2, success`
    */
    type: {
      default: 'info',
      type: String
    },
    /**
    * El texto a mostrar en el tooltip del botón.
    */
    tooltip: {
      default: 'Volver',
      type: String
    }
  }
}
</script
``

The library only generates the docs for the mixin component.

**Comment by elevatebart** [comment]
Thank you so much, I will have a look.

Bart Ledoux
Twitter: @bartledoux
Github, Gitter, Discord: @elevatebart

**Comment by elevatebart** [comment]
Actually would you mind creating a repository where I can reproduce ?

Bart Ledoux
Twitter: @bartledoux
Github, Gitter, Discord: @elevatebart

**Comment by angelowolf** [comment]
Hello this is the [repository](https://github.com/angelowolf/styleguidist-mixins-demo)

The *TrxButtonBase* is the mixins component, and the others *TrxButtonXXX* are components that use the mixin.

In the picture you can only see the documentation of the mixin and not the other components.

![example_mixins](https://user-images.githubusercontent.com/15150124/52184094-9f9b5380-27ed-11e9-9dd7-fbf1b7c16a38.png)

Thanks!

**Comment by vdcrea** [comment]
@angelowolf as a workaround and as the template is not so long, did you try to change the .vue mixin to a .js mixin with your template in a render function (ex https://sebastiandedeyne.com/vue-templates-in-jsx/ )?

**Comment by elevatebart** [comment]
I am working on it. I just needed a concrete example. It will not take long. It was an issue of file resolution. 

NodeJs `require.resolve` never looks at `.vue` files by default. One has to tell it to do so.

**Comment by elevatebart** [comment]
I am done, I'll deliver tomorow morning with a fresher mind ;)
Thank you for the help.
