### ISSUE TITLE
styleguideDir config option ignored with Vue Cli 3

### ISSUE THREAD

**Issue by mattstrayer** [vue-styleguidist/vue-styleguidist#159]
Setting the `styleguideDir` inside of the `styleguide.config.js` file seems to be completely ignored while running `styleguide:build`. I also tested this in the vue cli 3 example project and was able to reproduce the results. The builds always end up in the `dist/` folder.

**Comment by elevatebart** [comment]
I will have a quick look

**Comment by elevatebart** [comment]
thanks @rafaesc

**Comment by rafaesc** [comment]
Yes @elevatebart, this had referenced with this issue: https://github.com/vue-styleguidist/vue-styleguidist/issues/162

So I had to fix this to resolve the other, however I still work in webpack3 support, in the night I will finish it with your PR merged. Thank to you

**Comment by rafaesc** [comment]
Fixed on version 1.7.13

**Comment by mattstrayer** [comment]
Hello! Thanks so much for the fix, it's now building the website as expected. It is, however, building to `node_modules/vue-cli-plugin-styleguidist/{styleguideDir}` directory instead of just `{styleguideDir}`

I'm going to take a look around, but I figured I'd let you know. 

Thanks again!

**Comment by rafaesc** [comment]
@mattstrayer, it appears when you use [vue-cli-plugin-styleguidist](https://github.com/vue-styleguidist/vue-cli-plugin-styleguidist).

I created an issue of that.

**Comment by mattstrayer** [comment]
Awesome, thanks!

**Comment by shawn-sandy** [comment]
Thanks much
