### ISSUE TITLE
Generation documentation of imported prop types

### ISSUE THREAD

**Issue by sevilyilmaz** [vue-styleguidist/vue-styleguidist#1590]
**The problem**

I import the prop types from another file. Therefore styleguidist does not read the documentation that are written there. Containing types in the SFCs might be fine with the simple ones. But when the component has many props or complex types it pollutes the file and it becomes a common practice to put the types in a separate file.

```ts
// MyComponent.types
export type Props = {
  /**
   * This prop does things
   */
  myProp?: string;

  /**
   * This prop does cool things
   */
  myOtherCoolProp?: SomeComplexTypeDefinedInThisFile
}
```

```ts
// MyComponent.vue
import type * as T from './MyComponent.types'

// This won't read the comments from the imported types
const props = defineProps<T.Props>();
```

**Proposed solution**

I don't have any proposal, sorry.

**Alternative solutions**

None

**Additional context**

Since Vue also started to [support the imported types on SFC macros](https://github.com/vuejs/core/pull/8083) it can be a common way to move the types in their own file.

**Comment by elevatebart** [comment]
I simply will start redirecting people to a library that takes another approach:

[`vue-component-meta`](https://github.com/vuejs/language-tools/tree/master/packages/vue-component-meta)

**Upside**: all will work with TypeScript.
**Downside**: Adding a description to a slot and its bindings is impossible.

**Comment by sevilyilmaz** [comment]
I really like how flexible vue-docgen-api is. Using vue-compoenent-meta will mean that I will need to use both. But in any case, thank you for the pointer.

Edit: I just saw [this PR](https://github.com/vue-styleguidist/vue-styleguidist/pull/1586) got merged. I'll give it another try.
Edit 2: It didn't work

**Comment by sevilyilmaz** [comment]
@elevatebart with the PR above actually works. The docgen was able to extract the documentation when I imported the types separately but it didn't work when I imported all of them. Here are examples, in case there is an easy fix:

```js
// works
import type { Props } from './Component.types';
const props = withDefaults(defineProps<Props>(), { size: 'medium' })

// doesn't work
import type * as T from './Component.types';
const props = withDefaults(defineProps<T.Props>(), { size: 'medium' })
```

**Comment by elevatebart** [comment]
OOOh I understand !!

Well yeah that should be possible. I am going to create a quick repro on a branch, see what I can do.
