### ISSUE TITLE
Extract slot and property documentation from `defineSlots`

### ISSUE THREAD

**Issue by rijenkii** [vue-styleguidist/vue-styleguidist#1597]
Vue 3.3 added a new macro, `defineSlots`, which allows to define and document slots and their properties.
Example:
```vue
<script setup lang="ts">
type SlotProps = {
    /** A random number. */
    x: number;
};

defineSlots<{
    /** Default slot. */
    default(props: SlotProps): unknown;
}>();
</script>

<template>
    <slot :x="3" />
</template>
```
[Link to the playground](https://play.vuejs.org/#eNp9UslOwzAQ/ZWRuUCFkkNvIVRiO8ABEHD0JaTTEnDGlhcIqvLvjJ2mLRX0YGk8783+VuLCmOwzoChE6WrbGA8OfTAzSU1rtPVwpVsDC6tbkCLL4y/ypTiTVOZDCJP547E1qvLIP4AyEpPF9ojA0RwXVVD+XIoVdNBLMVsloy/z3+GpEJs7fnEqvKs1LZpl9u40ccuryJWiZm6j0D4Y32hyUhSQkIhVSumvu+TzNuDp6K/fsP74w//uuuiT4tGiQ/vJk24wX9kl+gG+eb7Hju0N2Op5UMw+AD6h0yrEHgfaZaA5t73DS93epsU3tHxxN51HcuNQsdHI7BNfCr5DXNN/o2/bnWbTFCep5y2ON9y/OaiKlnwaz2l49f7bIDwr7R+tNg7Ox8T5ZAIXYCuasyYotK9oM5jkA9gVaxfLo+cniU/eEMY8rtzJcD0oARwD2/C1Po5NLFlsq58UEOiD9BfFvLPjk8PqYwHFvFB0PM5UCsj3pNT/ADHt+sE=). If you hover over the `#default` or `{ x }`, their documentation will appear in the popup.

**Comment by navishachiku** [comment]
Will the `method document in setup script` and `defineModel` be supported in the future?

```html
<script setup>
/**
 * Dothing
 * @param {string} val input
 */
function dothing(val) {
    /* code */
}
</script>
```

```html
<script setup>
/**
 * @model
 */
const modelValue = defineModel();
</script>
