### ISSUE TITLE
SetupOptionsHandler Comment error

### ISSUE THREAD

**Issue by codecomeon** [vue-styleguidist/vue-styleguidist#1606]
Current

https://github.com/vue-styleguidist/vue-styleguidist/blob/5436a5060a0c5b966481ee060bb714156d71d3e9/packages/vue-docgen-api/src/script-setup-handlers/setupOptionsHandler.ts#L10

Expect

setup options....

**Comment by elevatebart** [comment]
Could you re-open with more specific needs?
