### ISSUE TITLE
Yarn issue: YN0002: vue-docgen-api@npm:4.74.1 doesn't provide vue (pde4ae), requested by vue-inbrowser-compiler-independent-utils

### ISSUE THREAD

**Issue by spiltcoffee** [vue-styleguidist/vue-styleguidist#1608]
**Current behavior**

* Trying to use a project that depends on vue-docgen-api@4.38.1
* When using Yarn (`yarn -v` = 3.6.3), the following message appears:

```
$ yarn
...
➤ YN0002: │ vue-docgen-api@npm:4.74.1 doesn't provide vue (pde4ae), requested by vue-inbrowser-compiler-independent-utils
...

$ yarn explain peer-requirements pde4ae
➤ YN0000: vue-docgen-api@npm:4.74.1 doesn't provide vue, breaking the following requirements:

➤ YN0000: vue-inbrowser-compiler-independent-utils@npm:4.71.1 [e4bca] → >=2 ✘
```

**To reproduce**
package.json:
```json
{
  "dependencies": {
    "vue-docgen-api": "^4.56.4"
  }
}
```
Yarn:
```
$ yarn set version stable
$ yarn
```

**Expected behavior**

For `vue-docgen-api` to clearly define it's dependency on `vue`, likely as a `peerDependency`.
In this case, it could specify it as `>=2`, to match `vue-inbrowser-compiler-independent-utils`.

Similar to #1089

**Comment by elevatebart** [comment]
Thank you for posting.

I hate yarn.
I will fix this ASAP. 
Please use pnpm.

**Comment by spiltcoffee** [comment]
For complaining about an issue in the dependency graph? 😥

**Comment by elevatebart** [comment]
No, I hate yarn because it's bad a determining a dependency graph according to the rules of npm, because it's incredibly different and often incompatible from every other package manager and because it comes out of Facebook and Sebastian McEnzie both public personas that never seem to consider long term impact of their creations.

**Comment by elevatebart** [comment]
Also, it should be delivered now.

**Comment by spiltcoffee** [comment]
Oh, fair enough.

And thank you!
