### ISSUE TITLE
Unknown custom element even after `require`ing

### ISSUE THREAD

**Issue by kyleoliveiro** [vue-styleguidist/vue-styleguidist#161]
I have an `Accordion` component and `AccordionItem` component. I have set `skipComponentsWithoutExample: true`, and want to hide my `AccordionItem` from the docs, but I'm using it in the `Accordion`.

I'm getting the `[Vue warn]: Unknown custom element: <AccordionItem> - did you register the component correctly?` error, even after following the [instructions in the cookbook](https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Cookbook.md#how-to-hide-some-components-in-style-guide-but-make-them-available-in-examples).

Here is my example code in the `Accordion.md` file:

```
const AccordionItem = require('../accordion-item/accordion-item.vue');
<Accordion>
    <AccordionItem title="Panel 1">
        Panel content...
    </AccordionItem>
</Accordion>
```

If I `console.log(AccordionItem)`, I get back the component object as expected. But VSG does not recognise my component still.

**Comment by rafaesc** [comment]
@kyleoliveiro I have already updated doc.

https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Cookbook.md#how-to-hide-some-components-in-style-guide-but-make-them-available-in-examples
