### ISSUE TITLE
Vuecli3 example does not load  styles

### ISSUE THREAD

**Issue by siegerts** [vue-styleguidist/vue-styleguidist#162]
Styles do not load when cloning the vuecli3 example and running as-is.  I've also noticed this locally where the bundle is buillt correctly and components redendered (with no styles...).

**Comment by timefordroids** [comment]
I have the same issue.
vue-cli: 3.0.0-rc.3
vue-styleguidist: 1.7.12

**Comment by rafaesc** [comment]
Hi @siegerts @timefordroids, but I saw that styles are loaded

![image](https://user-images.githubusercontent.com/10201025/43090856-2daf245e-8e6e-11e8-82ee-5c97cca0b72d.png)

**Comment by siegerts** [comment]
I get the desired results when using `yarn styleguide` as you have above.  But, I do not get that result when building with `yarn styleguide:build`.

![image](https://user-images.githubusercontent.com/634958/43092884-8bc0f78a-8e7c-11e8-8f3c-aa0a7b760eca.png)

**Comment by rafaesc** [comment]
Fixed on version 1.7.13
