### ISSUE TITLE
Resolving import to radix-vue type fails 

### ISSUE THREAD

**Issue by dobby** [vue-styleguidist/vue-styleguidist#1649]
**Current behavior**
I created a storybook for a component but when I want to view the component in storybook the component fails to render because of an error in the docgen api plugin. During normal vue rendering (out of the context of storybook), this component work perfectly. 

The problem relates to an import of a radix library type:

import type { PrimitiveProps } from 'radix-vue'

This is the error I am getting:
 [plugin:storybook:vue-docgen-plugin] ENOENT: no such file or directory, open '../../../node_modules/radix-vue/dist/index.js' 

It seems to resolve to the wrong directory, I think the node_modules directory  is one directory higher then the ../ is going to.

**To reproduce**
The following github repo contains only the problem, if you start storybook and go to the button or card you will see the error.

It should resolve the dependency to radix-vue correctly.

**Comment by elevatebart** [comment]
I can'e find the repo link, would you please add it here?

**Comment by dobby** [comment]
https://github.com/dobby/vue-storybook

**Comment by dobby** [comment]
Strange I pasted the repo link when I created the issue
