### ISSUE TITLE
Front page ends up in a redirect loop

### ISSUE THREAD

**Issue by hannesaasamets** [vue-styleguidist/vue-styleguidist#165]
When navigating to the root page of the styleguidist, the router appends `/#/!/{{page-slug}}`. The slash between the pound and the exclamation point seems to be the culprit here, since when navigating manually to `/#!/{{page-slug}}`, the styleguide works correctly. When I preserve the log, the following is logged before the redirects:
```
CompileError {name: "CompileError", message: "import is not supported (1:0)", stack: "Error↵    at Node.initialise (http://localhost:606…//localhost:6060/build/main.bundle.js:116:160437)", loc: {…}, snippet: "1 : import Vue from 'vue';↵    ^^^^^^^^^^^^^^^^^^^^^^"}
```

I'm also willing to look into this if you've got any tips on which cave to search.

**Comment by rafaesc** [comment]
I will update the router in the next version, I hope that will resolve it

**Comment by elevatebart** [comment]
hey @hannesaasamets , I can't seem to reproduce on here. Can you cook up a quick repo?

**Comment by Ottkaarel** [comment]
Posting here on behalf of @hannesaasamets - we found the issue, it was the usage of vue-router as a mixin in styleguide.config, to generate some examples in the docs that utilize the router. Could it be possible to implement support for vue-router?

**Comment by elevatebart** [comment]
@ottmartens Do you think we should simply mock it? or make it abstract?

**Comment by elevatebart** [comment]
If you check out this issue https://github.com/vue-styleguidist/vue-styleguidist/issues/290 or have a look at the [cookbook routing receipe](https://vue-styleguidist.github.io/docs/Cookbook.html#use-vue-styleguideist-with-components-that-contain-routing) you will find a way around your issue. We have not excluded [adding an iframe mode](385) in the next major version.
