### ISSUE TITLE
Docgen fails to resolve radix-vue module 

### ISSUE THREAD

**Issue by dobby** [vue-styleguidist/vue-styleguidist#1653]
Current behavior
I created a storybook for a component but when I want to view the component in storybook the component fails to render because of an error in the docgen api plugin. During normal vue rendering (out of the context of storybook), this component work perfectly.

The problem relates to an import of a radix library type:

import type { PrimitiveProps } from 'radix-vue'

This is the error I am getting:
[plugin:storybook:vue-docgen-plugin] ENOENT: no such file or directory, open '../../../node_modules/radix-vue/dist/index.js'

It seems to resolve to the wrong directory, I think the node_modules directory is one directory higher then the ../ is going to.

To reproduce
https://github.com/dobby/vue-storybook
If you start storybook and go to the button or card you will see the error.

What should happen:
It should resolve the dependency to radix-vue correctly.

**Comment by enkot** [comment]
Can confirm:
"vue-docgen-api": "4.75.1" - works fine
"vue-docgen-api": "4.76.0" - import is broken

Looks like a regression after https://github.com/vue-styleguidist/vue-styleguidist/pull/1646

**Comment by dobby** [comment]
Excellent, can confirm. Will use version 4.75.1 for the moment.

**Comment by ndj91** [comment]
This is still an issue on macOS with the higher version.

Bumping this so it can be looked into.

**Comment by elevatebart** [comment]
Please send a repro, I don't know your situation and it would probably be resolved fast if I could diagnose.

If it matters to you, then it matters to me but I cannot work blind.
Thank you for understanding.
