### ISSUE TITLE
Option for copy snippet button on view code

### ISSUE THREAD

**Issue by Truemedia** [vue-styleguidist/vue-styleguidist#167]
This isn't exactly a deal breaker but just a nice to have.

I'm often copying code snippets from my styleguide (using default theme), but at the moment I have to carefully select the whole line and copy.

Would be nice to have a snippet copy button like on some sites where you just click the copy snippet button and the contents of the snippet are saved to your clipboard.

Would only save like a fraction of a second, but seconds add up and why not make things easier if it takes nothing away?

**Comment by elevatebart** [comment]
Sounds like a good idea, I wonder why react-styleguidist does not have it.

**Comment by elevatebart** [comment]
@rafaesc maybe as an otion using [clipboard.js](https://clipboardjs.com)

**Comment by MacZel** [comment]
@elevatebart I will work on this feature, and submit a PR over the weekend
