### ISSUE TITLE
Couldn't find preset "es2015" relative to directory error on nuxt example

### ISSUE THREAD

**Issue by easherma** [vue-styleguidist/vue-styleguidist#168]
when following doc instructions for setup

**Comment by easherma** [comment]
New to styleguidist, but I might suggest eventually refactoring the nuxt example to more closely follow their conventions, i.e. 
```
const { resolve } = require('path');
const rules = require('vue-webpack-loaders');

module.exports = {
	components: './components/**/[A-Z]*.vue',
	webpackConfig: {
		resolve: {
			extensions: ['.js', '.json', '.vue', '.ts'],
			alias: {
				'~': resolve(__dirname),
				'@': resolve(__dirname),
			},
		},
		module: {
			rules,
		},
	},
	showUsage: true,
	vuex: './store/index',
};
```

**Comment by elevatebart** [comment]
We would love a quick PR @easherma if you have time to set it up ;)

**Comment by easherma** [comment]
@elevatebart happy to once I feel confident enough with the repo

**Comment by elevatebart** [comment]
I think with the examples are now cleaner. You should have a run with it.
Please open a new issue if you meet this again.
