### ISSUE TITLE
PascalCase required, kebab-case rejected for component file names?

### ISSUE THREAD

**Issue by easherma** [vue-styleguidist/vue-styleguidist#169]
It seems to me that if I name my components kebab style they don't show up in the styleguide. Coud anyone shed some light on this? Thanks!

**Comment by elevatebart** [comment]
Hey Eric, to me that seems like a bug. As soon as I reproduce it, I will get it on the pipe.

**Comment by easherma** [comment]
@elevatebart I agree, I do think it's an issue. I'm trying it with another repo and having the same problem. I could help debug this if I could get pointed to the right part of the code to look at? My hunch is that it's related to however it parses the components filepath.

**Comment by elevatebart** [comment]
Hey @easherma,
What matters that the first letter of your file be a capital letter.
The lookup glob for components in the example is `src/components/**/[A-Z]*.vue`.

if you change it to 
`src/components/**/[A-Za-z]*.vue`your features will work.

**Comment by elevatebart** [comment]
Hey @easherma, did you have time to try out my solution?
Should I close this issue?

**Comment by easherma** [comment]
I think we’re good!
