### ISSUE TITLE
vue-docgen-api: wrong relative path to node_modules folder is resolved

### ISSUE THREAD

**Issue by simonvizzini** [vue-styleguidist/vue-styleguidist#1691]
**Current behavior**

Our Storybook build is currently failing with an `vue-docgen-api` error. Apologies in advance if this is a Storybook issue and not a direct vue-docgen-api issue. I'm trying to figure out where the problem lies so I hope you guys can point me in the right direction.

The error occurs *only* on our CI pipeline (Azure DevOps with a self-hosted Linux agent). Locally (on Windows) the build works fine. Unfortunately I have no way to test this on a local Linux machine, due to company policies only Windows is allowed.

Here is the error output:

````
> the-vue-app@1.4.0 build:storybook /apps/azdo-agent/agent3/_work/116/s
> storybook build --loglevel silly

@storybook/core v8.3.6

info => Cleaning outputDir: storybook-static
info => Loading presets
info => Building manager..
info => Manager built (139 ms)
info => Building preview..
info => Copying static files: public at storybook-static
vite v5.4.10 building for production...
transforming...
✓ 123 modules transformed.
x Build failed in 1.56s
=> Failed to build the preview
[storybook:vue-docgen-plugin] ENOENT: no such file or directory, open '../../../../node_modules/vue-component-library/dist/components/index.js'
file: ./src/modules/the-vue-app/components/form-inputs/OptionsFormField.vue
    at Object.readFileSync (node:fs:448:20)
    at getTypeDefinitionFromIdentifierFromModule (./node_modules/vue-docgen-api/src/script-setup-handlers/utils/tsUtils.ts:38:7)
    at Context.visitImportSpecifier (./node_modules/vue-docgen-api/src/script-setup-handlers/utils/tsUtils.ts:86:16)
    at Context.invokeVisitorMethod (./node_modules/ast-types/lib/path-visitor.js:283:51)
    at PVp.visitWithoutReset (./node_modules/ast-types/lib/path-visitor.js:158:32)
    at NodePath.each (./node_modules/ast-types/lib/path.js:88:26)
    at visitChildren (./node_modules/ast-types/lib/path-visitor.js:179:18)
    at PVp.visitWithoutReset (./node_modules/ast-types/lib/path-visitor.js:167:20)
    at visitChildren (./node_modules/ast-types/lib/path-visitor.js:204:25)
    at PVp.visitWithoutReset (./node_modules/ast-types/lib/path-visitor.js:167:20)
````

The module `vue-component-library` is our own private library that we just published to a private Nexus repository. We added this library to our first Vue application for the first time, and that's when the error started to occur on our CI. So it must be somehow related to our module, maybe we didn't setup our library build right.

The strange thing is that the relative path is off by one level. Somehow it is trying to import from `./src/node_modules` instead of `./node_modules`

I had a brief look at the offending `getTypeDefinitionFromIdentifierFromModule` function within `tsUtils.ts`, but since this is closely tied to `ast-types` functionality where some options are passed down a couple layers deep I couldn't really make out where this wrong path is coming from.

My hope is someone with better knowledge of the implementation could point me in the right direction.

Thanks a bunch in advance.

**To reproduce**

Unfortunately I can't provide a reproduction as the module that causes this error is private.

**Expected behavior**

Path to the `node_modules` folder is resolved correctly.

**Comment by elevatebart** [comment]
Hello @simonvizzini thank you for this ticket. It's always nice to see the 

I might be wrong. This looks like it would be a storybook issue.

Explanation:
- Storybook uses a bundler under the hood to show you what it can.
- It configures that bundler to resolve files properly
- It looks like whe doing the readFileSync, some alias might not be configured or not passed to docgen to find that file
- The fix is probably to update the way storybook calls the library.
- Without an actual reproduction I am afraid I cannot "know" that I have fixed it for real.

I hope these few points help you understand the situation a bit better.

**Comment by simonvizzini** [comment]
Hi @elevatebart, thank you for the quick response! I really wasn't sure who is responsible for resolving the node_module path and where. Thanks for your explanation, in that case I will create an issue on the Storybook Github.

I'll close this issue for now then.

Have a good day!
