### ISSUE TITLE
Update docs for styles/themes

### ISSUE THREAD

**Issue by lancetharper** [vue-styleguidist/vue-styleguidist#17]
The configuration [docs](https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Configuration.md#styles) mention styles and theme as options to customize the styleguide.

The cookbook link is a 404 -- are there docs for how to customize those located somewhere else? I can see a little bit of it in the buefy example, but would love to know what other options are available.

**Comment by rafaesc92** [comment]
Yes, on the weekend I'm going to upload an update of the package, including the documentation

**Comment by nicooprat** [comment]
Still can't find the default theme config, could you give us a link? Thanks.
