### ISSUE TITLE
Use only md

### ISSUE THREAD

**Issue by lgomes2m** [vue-styleguidist/vue-styleguidist#171]
Is there a way to render only .md files without .vue?

**Comment by elevatebart** [comment]
Would you like to still have vue components?
Use something like [vuepress](https://vuepress.vuejs.org/)?

Or you would like to render only the doc that is in .md files?
This would be ignoring the doc from the .vue files.

Can you expand a little on what you are trying to achieve and why ?
Thank you @lgomes2m ;)

**Comment by lgomes2m** [comment]
Hello @elevatebart,

I would like to render only the .md files.

But now that I resolved this issue:
https://github.com/vue-styleguidist/vue-styleguidist/issues/170

There is no need to render only .md anymore.

Thanks!
