### ISSUE TITLE
spread operator in component throwing syntax error

### ISSUE THREAD

**Issue by beirdostudio** [vue-styleguidist/vue-styleguidist#172]
Hello, I'm using vue styleguidist with nuxt, it's throwing a syntax error when spread operator is used in a component.
```bash
Syntax error: Unexpected token
```
```javascript
object = {...this.value}
```

**Comment by easherma** [comment]
Having the same problem.

**Comment by easherma** [comment]
may be related: 
https://github.com/vue-styleguidist/vue-styleguidist/issues/130

I don't know enough about it to say, but it seems like it has something to with babel config.

**Comment by patric-eberle** [comment]
@beirdostudio did you try to add `babel-polyfill` to the required section of the styleguide configuration? I use same webpack config for vue and vue-styleguidist but the polyfill was ignored by vue-styleguidist before:

```
require: [
    'babel-polyfill',
    ...
]
```

**Comment by elevatebart** [comment]
@beirdostudio @easherma Did you try it again in v3 ?

**Comment by elevatebart** [comment]
should be fine now.
