### ISSUE TITLE
How to document slots in a component with render function?

### ISSUE THREAD

**Issue by kyleoliveiro** [vue-styleguidist/vue-styleguidist#174]
Currently the only way to document slots, or so it seems, is to write a comment in the component's `<template>` like so:

```
<template>
  <!-- @slot Use this slot for text contents -->
  <slot></slot>
</template>
```

However, components that utilise a render function do not have a `<template>`. In these cases, how do we write documentation for slots?

**Comment by rafaesc** [comment]
Yes, it has reference with this issue:
https://github.com/vue-styleguidist/vue-styleguidist/issues/30

For at this moment, is not possible.

**Comment by aliaksandrkrasnou** [comment]
> @kyleoliveiro , the works are in progress [vue-styleguidist/vue-docgen-api#78](https://github.com/vue-styleguidist/vue-docgen-api/pull/78)
> I can keep you posted

@elevatebart Do you have any updates on this issue?

**Comment by elevatebart** [comment]
Hello @aliaksandrkrasnou 

I have a made a couple of tests to make sure these were working. I believe it does now.
See [this example](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/tests/components/grid-jsx/Grid.vue)

**Comment by elevatebart** [comment]
You can even have a look at [those unit tests](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/src/script-handlers/__tests__/slotHandler.ts)

**Comment by aliaksandrkrasnou** [comment]
@elevatebart thank you!

For jsx render function it's clear. But if I have a render function inside an object, where should I place slot and slot description text for documentation purposes? 
```
export default {
   render(h) {
     return h('div', [
       this.$scopedSlots.default(),
      ]);
    },
 };
```

**Comment by elevatebart** [comment]
Unfortunately, docgen never executes your code. So there is no way to detect what hides inside an executed function. We could have a flag in the comments where you can force the documentation: Even if no slot is detected, the documentation would still be written. 
More news soon

**Comment by elevatebart** [comment]
Here is how you can document your slot after this fix: 

```js
export default {
   render(h) {
     return h('div', [
       /** @slot It is the default slot */
       this.$scopedSlots.default(),
      ]);
    },
 };
```

Sorry it took me so long to fix it.

**Comment by elevatebart** [comment]
Hi @Stegosource 

Here is the unit test checking this behavior:

https://github.com/vue-styleguidist/vue-styleguidist/blob/cb05cac39e27c08308ca3087cdd69387e8e102f5/packages/vue-docgen-api/src/script-handlers/__tests__/slotHandler.ts#L150-L167

Please make sure you apply this syntax. If you do, can you share your `render` function?
I might have missed a couple of use cases.

**Comment by elevatebart** [comment]
`vue-docgen-api` is a static analysis tool. It looks for patterns in your code.
In this case, the pattern for slots is described in the script handler corresponding to slots.
It:
- finds the body of the render function, 
- looks for all `$slot` and `$scopedSlots`
- if they have a description adds them to the docs.

It does not resolve any variable so, in order to be detected, your slot call needs to be literal.
It does not execute your code, so it does not look anywhere else than in the body of the `render` function. 

Can you write another issue to get this new use case to work please?

**Comment by elevatebart** [comment]
Hi @stegosource,

Sorry, I got offline for a little while, I was busy getting married. I wrote a couple unit tests with your code this morning and the slots are detected fine.
The descriptions, though, are not detected as they are not leading comments to the member expressions. Instead those comments are linked to the wrapping assignment. 

I need to find a way to find the first containing indépendant expression of an AST node as this is where you would expect the comment to be if it is not on the member expression itself.

I will look into it this week. Can you open a new issue about it for me please ?

Thank you in advance,
Bart

**Comment by Stegosource** [comment]
Hey @elevatebart. First of all, congrats!!! That's awesome for you.

I'll post a new issue, but I'm in no hurry, so take all the time you need :)
