### ISSUE TITLE
How to console.log in README.md?

### ISSUE THREAD

**Issue by tony19** [vue-styleguidist/vue-styleguidist#176]
I noticed that `console.log` emits nothing inside the  `<script>` tag of a Vue-SFC doc (like shown in example below). Is there another method to log to the console?

<pre>
### Demo

```vue
&lt;template&gt;
  &lt;button @click="onClick"&gt;Click&lt;/button&gt;
&lt;/template&gt;

&lt;script&gt;
console.log('hello world'); // <-- not seen in terminal or browser console

export default {
  methods: {
    log(msg) {
      console.log(msg);     // <-- not seen in terminal or browser console
    }
  },
}
&lt;/script&gt;

```
</pre>

### Environment
 * `vue-styleguide`: 1.7.13 and 1.8.0
 * Node 10.5.0
 * macOS High Sierra 10.13.6

**Comment by elevatebart** [comment]
for now the code in md is evaluated in a sandbox. We could have this sandbox output console.logs to the browser, maybe it could be useful. I will look into it.

**Comment by elevatebart** [comment]
should be working fine now ;)
