### ISSUE TITLE
Possible to exclude component from docs from component itself?

### ISSUE THREAD

**Issue by genu** [vue-styleguidist/vue-styleguidist#184]
Is there a way to exclude a component from the documentation without explicitly including it the `ignore` section of the config?

Would it be possible to do that in the component itself as its being parsed by the styleguide?

**Comment by shawn-sandy** [comment]
I set  ` skipComponentsWithoutExample: true`, the downside is that it does require to make an `component-name.md` file for all the components you want displayed. Works for me!

https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Cookbook.md#how-to-hide-some-components-in-style-guide-but-make-them-available-in-examples
