### ISSUE TITLE
styleguide.config with .scss variables.scss

### ISSUE THREAD

**Issue by raulmelo** [vue-styleguidist/vue-styleguidist#189]
How do I add a stylesheet(scss) to load along with my styleguide?
I am using vue-cli-3
```
module.exports = {
  // set your styleguidist configuration here
  title: 'Default Style Guide',
  defaultExample: true,
  components: 'src/components/**/[A-Z]*.vue',
  webpackConfig: {
    module: {
      resolve: {
        extensions: ['.es6']
      },
      rules: [
        {
          css: {
            loaderOptions: {
              // pass options to sass-loader
              sass: {
                // @/ is an alias to src/
                // so this assumes you have a file named `src/variables.scss`
                data: `@import "@/variables.scss";`
              }
            }
          }
        }
      ]
    }
  }
}

```

**Comment by raulmelo** [comment]
@elevatebart help!

**Comment by elevatebart** [comment]
@raulmelo *coming on white horse to the rescue in a shining armor* ;) let me check that.

**Comment by elevatebart** [comment]
@raumelo, Styleguidist expects a set of rules exactly as a webpack config would create. Therefore, you should pass the loaders in this format: 
```js
var sass = encodeURIComponent(jsonToSassVars(sassGlobals));
var webpackConfig = {
    module: {
        rules:[
            {
                test: /.scss$/, 
                loader: "style!css!sass!prepend?data=" + sass
             }
        ]
    },
}
```
This being said, it should rely entirely on the vue.config.js config so that you guys do not have to write it twice. I found a bug though.
It seems that the scss variables are not loaded at runtime in the sass-loader. 
I will investigate.

**Comment by raulmelo** [comment]
error resolved?

**Comment by raulmelo** [comment]
error resolved?

**Comment by elevatebart** [comment]
Hello @raulmelo, I found out that with the vue cli 3, if you want to change the webpack config css, you have to use this doc [passing-options-to-pre-processor-loaders](https://cli.vuejs.org/guide/css.html#passing-options-to-pre-processor-loaders)
