### ISSUE TITLE
Improving skipComponentsWithoutExample option

### ISSUE THREAD

**Issue by viljamis** [vue-styleguidist/vue-styleguidist#193]
Currently, when using the `skipComponentsWithoutExample` option, it only works when you have the example in an external `.md` file. 

I feel like this option would be so much more helpful if it also worked with Vue.js single file components where you might *(or might not)* have the `<docs/>` section.

Any thought on this? :)

**Comment by elevatebart** [comment]
This sounds like a good idea. Since we try to follow react-styleguidist as close as we can, it seems like if it works with react it should work with us. I have not checked.

Do you think you could try out a quick PR?

**Comment by rafaesc** [comment]
I think that it's possible, I would like to take it

**Comment by elevatebart** [comment]
@rafaesc you were right it was fairly simple. see the vuecli3 example
