### ISSUE TITLE
<br/> tags not working in Markdown

### ISSUE THREAD

**Issue by kyleoliveiro** [vue-styleguidist/vue-styleguidist#195]
After upgrading from `1.7.13` to `1.8.5`, `<br/>` tags in my Markdown files have stopped rendering as newlines, and instead just render as "\<br/>" in plain text throughout my docs.

**Comment by kyleoliveiro** [comment]
Seems like `<br>` and `<br />` will work, but `<br/>` does not. This is a regression.

**Comment by elevatebart** [comment]
Hello @kyleoliveiro, I believe I fixed this. Can you check that the last version has this same bug?

**Comment by mob8607** [comment]
Hi guys, I have the problem that <br> is not working but <br /> is. Could this be related to this issue?
My used version is 2.1.2

**Comment by elevatebart** [comment]
Hey guys, since there was no news about it for a while, if you meet this error again, can you please open a new one?

Thank you,
