### ISSUE TITLE
Path to component instead of name

### ISSUE THREAD

**Issue by lancetharper** [vue-styleguidist/vue-styleguidist#2]
Both the left sidebar and the header that should show the component name display the absolute path to the component.

I've tried changing the webpack config and even used the 'vue-webpack-loader' as in the example and still can't get it to display properly.

I also noticed the default glob pattern of `src/components/**/*.vue` doesn't work (even though that's where my components are). If I define it as an option in the config with that same string it does work.

Props, JSDoc comments, and Readme (with the exception of #3) all seem to be working otherwise.

**Comment by rafaesc92** [comment]
Please share your repository, to review it, thanks!

**Comment by lancetharper** [comment]
I appreciate the help! We think this looks very promising.

https://github.com/rei/rei-cedar/tree/feature/styleguidist

**Comment by rafaesc92** [comment]
I see you have a great project!

Ok I just created a pull request, and update the documentation

Https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Documenting.md#usage-examples-and-readme-files

> **Note:** [vue-docgen-api](https://github.com/vue-styleguidist/vue-docgen-api) The default name of the component is the name of the .vue file. If you need a custom name configuration, type as an issue in [vue-docgen-api](https://github.com/vue-styleguidist/vue-docgen-api)

If you publish the styleguide of your project please share it in the readme

https://github.com/vue-styleguidist/vue-styleguidist#showcases

Regards

**Comment by Minasokoni** [comment]
@rafaesc92 Im running into the same issue 
![screen shot 2017-06-15 at 7 52 54 am](https://user-images.githubusercontent.com/1010168/27187294-a75f8c06-519f-11e7-9fe5-fa3ef092c1f5.png)

**Comment by happylittleboozer** [comment]
@lancetharper, @Minasokoni you can fix this by setting propsParser function in your styleguide.config.js. Like this:
```javascript
const path = require('path');

module.exports = {
  propsParser (filePath, source) {
    var props = require('vue-docgen-api').parse(filePath);
    // Set component displayName as component folder name
    props.displayName = path.basename( path.dirname( props.displayName ) );
    return props;
  }
};
```

**Comment by Minasokoni** [comment]
@happylittleboozer Thanks!

**Comment by rafaesc92** [comment]
Thanks to everyone, the solution is in [vue-docgen-api](https://github.com/vue-styleguidist/vue-docgen-api), I forgot to use [path.normalize](https://nodejs.org/api/path.html#path_path_normalize_path) to extract the file name, I'm going to update it

**Comment by rafaesc92** [comment]
The repository was updated.

The name of the component is equal to the property defined in the name component, this is required.

Upgrade to version 1.1.1
