### ISSUE TITLE
Full build of Vue for Styleguidist

### ISSUE THREAD

**Issue by hannesaasamets** [vue-styleguidist/vue-styleguidist#201]
Is it possible to use the **with-compile** mode for Styleguidist?

So far I tried the following configuration, but `Vue.compile` still returned undefined in examples (is there another indicator that the compile function is present?):
```
module.exports = {
  webpackConfig: {
    resolve: {
      alias: {
        vue$: path.resolve('node_modules/vue/dist/vue.esm.js'),
```

Just-in-case I also added the following with no effect:
```
module.exports = {
  dangerouslyUpdateWebpackConfig(webpackConfig, env) {
    webpackConfig.resolve.alias['vue$'] = path.resolve('node_modules/vue/dist/vue.esm.js');
    console.log('webpackConfig.resolve.alias:', webpackConfig.resolve.alias);
    return webpackConfig;
  },
```

**Comment by elevatebart** [comment]
Hello @hannesaasamets ,

What would this `with-compile` enable or do?

The alias you are trying to set up is already part of our [webpack.config](https://github.com/vue-styleguidist/vue-styleguidist/blob/master/scripts/make-webpack-config.js#L83) and is supposed to work.

**Comment by elevatebart** [comment]
@hannesaasamets, 
the simplest would probably for you to create a reproduction repo so that we can find out what is wrong with styleguidist. 
I hope we can help. 
It is possible even with our awesome lib that your use case is not yet handled. 
If you can describe more widely what youare trying to accomplish thatwould help a ton.

Thanks, 
Bart

**Comment by elevatebart** [comment]
Hello @hannesaasamets 
I hope you found the answer you are looking for. It seems like you did.
feel free to re-open if you have more details.

Thank you again for your interest.
Bart
