### ISSUE TITLE
Build fail for basic example 

### ISSUE THREAD

**Issue by marcustisater** [vue-styleguidist/vue-styleguidist#205]
I cloned the basic example https://github.com/vue-styleguidist/vue-styleguidist/tree/master/examples/basic and followed the guide.

After `npm install` and `npm run styleguide` I got prompt with this error `./src/components/Button/Button.vue?vue&type=script&lang=js&
Module build failed: Error: Cannot find module 'babel-core'`. I had this error a lot lately from open source projects. Any ideas why? 

node: 8.6.0
npm: 6.4.1
macOS

**Comment by elevatebart** [comment]
Hey @marcustisater , babel changed their naming conventions for their packages for their 7.0 release.

https://babeljs.io/docs/en/v7-migration#package-renames

We forgot to update the examples. We should probably fix them. They are just not meant to be running outside of the main repo.

Have you tried using the @vue/cli 3.0 and the styleguidist?

**Comment by marcustisater** [comment]
Yes, that worked. Thank you.
