### ISSUE TITLE
Absolute path with spaces & special characters causes compilation to fail

### ISSUE THREAD

**Issue by azriel46d** [vue-styleguidist/vue-styleguidist#209]
my project is located in a folder which has spaces in the path along the lines of
```
/mnt/c/users/Dropbox (name)/some folder/project
```
This causes vue-styleguidist not to work. 
As soon as the project is moved to say
```
/mnt/c/node
```
The components are read successfully

Environment:
Ubuntu for Windows (bash)

**Comment by elevatebart** [comment]
Seems to work nice on 3.13.3 + Windows 10 + PowerShell + vscode. If when you update it still does not work, can you please post a new issue.

Thank you ;)
