### ISSUE TITLE
Display components wrapped in Higher-Order components

### ISSUE THREAD

**Issue by hollandThomas** [vue-styleguidist/vue-styleguidist#212]
Hey,

I applied the Higher-Order Component (HOC) design-pattern (concept for react explained [here](https://reactjs.org/docs/higher-order-components.html)) like this: https://github.com/vuejs/vue/issues/6201#issuecomment-318009211

A component that makes use of such a HOC is no longer displayed by vue-styleguidist.

I suppose that vue-styleguidist needs a component to return an Object of the structure seen in the screenshot. A HOC of course returns a function instead, as seen in that screenshot as well.

![vue-styleguidist-hoc](https://user-images.githubusercontent.com/20690465/46478894-2b748300-c7ee-11e8-999a-e23ca6c470c6.PNG)

Is it possible to implement that feature? Thanks

Also, if possible, respect `/** */` inline documentations defined in HOC's.

**Comment by adamchenwei** [comment]
@hollandThomas you may just got into a rabbit hole, Vue actually has a surprising hard time for HOC https://github.com/vuejs/vue/issues/6201

**Comment by adamchenwei** [comment]
and in case if you interested in some learning https://github.com/shoestrong/learn-note/issues/8 (use translate of course)

**Comment by hollandThomas** [comment]
Luck has it that I'm meeting a chinese friend this evening. I think I just found him a nice little translation-job ;)

Thanks though in all honesty 👍

**Comment by elevatebart** [comment]
Hey @hollandThomas I will close this issue for now as I feel like Vue 3 is going to make it completely obsolete. Fell free to re-open it if you make a use case.
