### ISSUE TITLE
Warning on serve with function components

### ISSUE THREAD

**Issue by jkdrangel** [vue-styleguidist/vue-styleguidist#218]
I get a warning when i run the styleguidist with function components
```
Warning: Cannot parse src/components/atoms/alert-bar.vue: TypeError: Cannot read property 'lang' of null

It usually means that vue-docgen-api does not understand your source code or when using third-party libraries, try to file an issue here:
https://github.com/vue-styleguidist/vue-docgen-api/issues
```
This is a limitation from the project or I should apply some additional setting for this components?

**Comment by elevatebart** [comment]
I believe it is a limitation,
I used a work around: wrap your component in a real one.

**Comment by elevatebart** [comment]
Hey @jkdrangel, 

I believe the limitation does not exist anymore since , can you try it again?
This PR seems to have lifted it: https://github.com/vue-styleguidist/vue-docgen-api/pull/62

**Comment by elevatebart** [comment]
I am closing this as it seems to be fixed. Please do not hesitate to open a new issue if you  see it again.
