### ISSUE TITLE
migrate to react-codemirror2

### ISSUE THREAD

**Issue by scniro** [vue-styleguidist/vue-styleguidist#22]
react-codemirror has major [outstanding issues](https://github.com/JedWatson/react-codemirror/issues) and many users including myself suspect this package has been abandoned. I authored [react-codemirror2](https://github.com/scniro/react-codemirror2) and plan to actively maintain this as a successor moving forward. I encourage you try the new package in your project. Likewise, feel free to open up any issue should you encounter trouble and I'll be on it. Same with general suggestions/improvements - I'm aiming to build it up collaboratively so if you had any shortcomings with the original package please let me know.

**Comment by rafaesc** [comment]
Update already added
