### ISSUE TITLE
How to document custom directive?

### ISSUE THREAD

**Issue by ale-grosselle** [vue-styleguidist/vue-styleguidist#220]
Hi All,
In my project, i Have to document custom directives.

How could i do?

**Comment by elevatebart** [comment]
Hello @ale-grosselle, 

What would you want to document? The usage of a custom directive? It's instance? It is not possible with vue syleguidist as we do not document directives at all. 

How would you propose we about documenting them? Would you see any good way to do it?

Regards 
Bart
