### ISSUE TITLE
Components withs external props are not rendered

### ISSUE THREAD

**Issue by fsblemos** [vue-styleguidist/vue-styleguidist#222]
I have a component with a prop from an external file, for example:

```js
import { size } from './props';

export default {
  props: {
    name: String,
    size,
  },
};
```

If I remove the prop `size`or simply declare it normally (like `name`), it works.

The component it is not rendered even if I declare in the same file like this:

```js
const size = {
  type: String,
  default: 'medium',
};

export default {
  props: {
    name: String,
    size,
  },
};
```

**Comment by elevatebart** [comment]
hello @fsblemos,

vue-dogen-api being a static analysis tool, it cannot infer your types from code that is imported.
It would be wonderful if it did and might in the future. For now, it does not evaluate your code when getting the JSDoc. 
In my experience, it always has been more readable to explicit the types since those are type guards. I believe you can factor the defaults though. They are evaluated.

**Comment by elevatebart** [comment]
As you can see this issue https://github.com/vue-styleguidist/vue-docgen-api/issues/11 has not moved a lot recently. I am going to try to dig in.

**Comment by elevatebart** [comment]
Hello @fsblemos, Happy New Year,

I thought about your issue.
The only 2 kind of dependencies that vue styleguidist parses are [mixins](https://vuejs.org/v2/guide/mixins.html) and extends.
We can't parse all the dependencies of each component for performance and security reasons.

I think what you are trying to build is a [mixin](https://vuejs.org/v2/guide/mixins.html). 
This would allow you to build documentation for the logical [mixin](https://vuejs.org/v2/guide/mixins.html) itself on one end (with the pops that you need) and call it logically in your component.

I do not think we intend to make this specific use case work. 

I hope it helps,
Thank you again

**Comment by ljelewis** [comment]
Would it be possible to include the prop (without comments etc) at the very least?

Also, or alternatively, would it be possible to link to the mixin's documentation? Either at the specific prop (if the answer to my first question is yes) or perhaps listed in a different section of the component's page (e.g. "included mixins")?

**Comment by fsblemos** [comment]
@elevatebart very thank you for your thoughts! I understand the problem. 
About the mixins, lately I'm avoiding it and trying to do the same only with functions, because are easier to reason about and reuse. But that's ok, maybe I'll figure out an workaround to this.

**Comment by elevatebart** [comment]
@fsblemos, I made a quick PR to make sure those properties are detected. At least this way they can be documented.

**Comment by fsblemos** [comment]
Thank you @elevatebart! :tada:
