### ISSUE TITLE
Problem with pug extend

### ISSUE THREAD

**Issue by itpalert** [vue-styleguidist/vue-styleguidist#223]
Warning: Cannot parse components/*.vue: TypeError: A child of Block (Pug:2) is of type Extends, which is not supported by pug-code-gen. Please use pug-linker to preprocess this AST.

It usually means that vue-docgen-api does not understand your source code or when using third-party libraries

**Comment by elevatebart** [comment]
Hello @itpalert 

Sorry for the late response, Haappy new year.
I will transfer this issue in vue-docgen-api. if you do not mind ;)
