### ISSUE TITLE
Can not use vue-types package

### ISSUE THREAD

**Issue by pepesenaris** [vue-styleguidist/vue-styleguidist#237]
I'm trying to use https://github.com/dwightjack/vue-types to support more complex type definitions.
For example, given the following props definition:
```
props: {
    value: VueTypes.shape({
      line1: String,
      line2: String,
      state: String,
      city: String,
      postal_code: String,
      country: String
    }),
```
I get the error:
`Warning: Cannot parse web/js/vue-components/common/inputs/address-input.vue: TypeError: _vueTypes2.default.shape is not a function`.

I added the package name to the require array of the config:
```
require: [
    'vue-types',
// ... other locals files here
```
but the error persists.

What should I do?

I'm using "vue-styleguidist": "^1.7.12",

**Comment by pepesenaris** [comment]
Per [this issue](https://github.com/vue-styleguidist/vue-docgen-api/issues/23) I'm doing something like this to workaround the problem: 
```
import VueTypes from 'vue-types';
VueTypes.shape = VueTypes.shape || function(){};
```
It's quite ugly but I haven't find another way. :-(

**Comment by elevatebart** [comment]
Hello @pepesenaris 

Con you try again with vue-styleguidist 3.0 it should be working fine now

**Comment by pepesenaris** [comment]
Thanks for the response @elevatebart. We are using `vue-styleguidist` in a couple of projects right now at work. Let me see when we find a space in the pipeline to test this and I'll get back to you. Thanks.

**Comment by DavidReinberger** [comment]
Hey @elevatebart just to report, `vue-types` are now working correctly, however the props information is not parsed out and displayed correctly...

**Comment by elevatebart** [comment]
We now should be displaying the content of the function directly.
It is not perfect but is better than not displaying the prop at all ;)
