### ISSUE TITLE
Main content doesn't scroll

### ISSUE THREAD

**Issue by fernandoagarcia** [vue-styleguidist/vue-styleguidist#238]
Hey Guys, 

The main content container does not scroll. If I try to set overflow-y to the content container then the nav links don't work. This issue becomes more apparent when I have a longer prop list, components take up more vertical space or when I provide additional documentation on any given component. Any help is greatly appreciated.

**Comment by fernandoagarcia** [comment]
@elevatebart Actually this was totally my fault. I included a SCSS file that as conflicting with the styles of the Styleguide. So I created one just for the styleguide that included the style for the components but not my layouts.

**Comment by elevatebart** [comment]
thank you for your honesty
