### ISSUE TITLE
I keep getting: Cannot read property '1' of null

### ISSUE THREAD

**Issue by Timtech4u** [vue-styleguidist/vue-styleguidist#24]
Hi,

After installing and configuring package.json, I get this error:

Cannot read property '1' of null

npm ERR! Linux 4.4.0-93-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "styleguide"
npm ERR! node v8.4.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! saftims-ui@1.0.0 styleguide: `vue-styleguidist server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the saftims-ui@1.0.0 styleguide script 'vue-styleguidist server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the saftims-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     vue-styleguidist server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs saftims-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls saftims-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/timtech4u/flexiProjectz/saftims-ui/npm-debug.log

Also, my *.vue files are in varieties of folders. Thanks

**Comment by rafaesc** [comment]
Hi, unfortunately that message is not enough to solve the error, have you tried to follow this example?

https://github.com/vue-styleguidist/vue-styleguidist/tree/master/examples/basic

**Comment by Timtech4u** [comment]
Hi @rafaesc , I've been able to resolve that using the example. But I now get another error:

**Comment by rafaesc** [comment]
Maybe you can share your repository so I can help you

**Comment by leobrossault** [comment]
Hi ! I have the same error as Timtech4u : "Cannot read property '1' of null". It seems that the problem come from aliases which are defined in webpack, ex :

```javascript
webpackConfig: {
    resolve: {
        '~mixins': resolve('src/vue/mixins')
    }
}
```

and in components : 

```javascript
import componentBuilder from '~mixins/component-builder'
```

If I remove imports with aliases in my components, everything works fine.
Have you any idea about this problem ? Thanks !

**Comment by rafaesc** [comment]
Hi @leobrossault 

I think that you have to add the property '~mixins' inside 'alias', like this:

```js
webpackConfig: {
  resolve: {
    alias: {
      '~mixins': resolve('src/vue/mixins')
    }
  }
}
```
https://webpack.js.org/configuration/resolve/#resolve-alias

Cheers.
Rafael

**Comment by leobrossault** [comment]
Hi @rafaesc,

Thanks for your reply. But I tried and it didn't work.

Léo

**Comment by rafaesc** [comment]
Hi, @leobrossault,

It's strange. If you can share a little case with the error, I could help you.

**Comment by leobrossault** [comment]
It's ok, I have just to find the problem. My bad, the error come from a loader (It's a coincidence with aliases ...)

Thanks !
