### ISSUE TITLE
no tags -> TypeError('Invalid attempt to spread non-iterable instance')

### ISSUE THREAD

**Issue by elevatebart** [vue-styleguidist/vue-styleguidist#242]
brought in by adding extra properties to document events

**Comment by elevatebart** [comment]
@yu-cover thank you for reporting it.
This what I call CCCVDD no my end and a big oops.
(Ctrl-C Ctrl-V Driven Development)

Sorry to all of you.

**Comment by KouSyurei** [comment]
你好，请问你解决这个问题了吗？用的是什么方法呢？

**Comment by elevatebart** [comment]
Hey @KouSyurei Hope you understand a bit of english because I needed Google translate to get the chinese.
Good news is that the last version of vsg should not have the problem.
The problem was simply that this syntax is invalid:
``` js
	const args = [
		...(tags.arg || []),
		...(tags.argument || []),
		...(tags.param || []),
		...(tags || []),
	];
```
the solution I found was to remove the last line.

**Comment by yu-cover** [comment]
> 你好，请问你解决这个问题了吗？用的是什么方法呢？

@KouSyurei ，作者已经解决了， 拉一下最新的库
