### ISSUE TITLE
Nuxt Support

### ISSUE THREAD

**Issue by blowsie** [vue-styleguidist/vue-styleguidist#244]
There are still issues when using `vue-styleguidist` with nuxt, namely when using plugins that inject or when a component needs to access nuxt context.

As discussed here;
https://github.com/vue-styleguidist/vue-styleguidist/issues/215

Information on inject
---

> > Hello @blowsie , No I did not set an example for inject, as I do not know anything about what it is used for or how it works. Would you share a little what you know about it?
> 
> Even a link to the docs would be appreciated.
> 
> From my understanding, in short;
> Inject is a way for a plugin to extend the nuxt context by mutating this within a component.
> 
> For example the axios plugin, would expose an instance of axios inside a component as this.$axios
> 
> Official Docs
> https://vuejs.org/v2/api/#provide-inject
> https://nuxtjs.org/guide/plugins/
> 
> Related
> nuxt/nuxt.js#2233

---

Steps to reproduce
---

Simply add nuxt axios plugin and try and use in a component, with `this.$axios`

I think this could be added to the example as a simple test

**Comment by elevatebart** [comment]
Hello @blowsie ,
 to avoid doing real `axios` calls when you showcase your components, you should mock the api.
I added a little more content to the example to show how it could be working. 

I am sorry as I may disapoint a little. vue-styleguidist works perfectly with nuxtjs, because it's all vuejs. but it does not take nuxtjs modules into account (yet). 
We could build plugins together for that. 
For now, we will make do with the modified example and comment ;).

Hope it helps.
Bart

**Comment by blowsie** [comment]
Maybe you are missing the point here.  Its not an axios plugin problem.
Nuxt plugins are not supported, therefore vue-styleguidist does not work perfectly with nuxtjs

**Comment by elevatebart** [comment]
@blowsie I understand your point, modules could do many things in nuxtjs. They count on the exitence of the nuxtjs context, router and other tools. And you are counting on the existence of the nuxtjs modules in your components.
I chose not to pollute the lib with specifics of libraries. 
I will soon publish a way to add plugins both to the parser and the rendered. 
I am still figuring out the specifics. 

There WILL be a plugin for nuxt. 
FOR NOW nuxtjs components are just considered vuejs components. Every specifics of nuxt has to be manually mocked.

Hope this helps,
Bart
