### ISSUE TITLE
Add example how to host on Github pages

### ISSUE THREAD

**Issue by ilicmarko** [vue-styleguidist/vue-styleguidist#245]
This is a **suggestion**, I think most users will find it useful if there was an example of how to setup hosting styleguide on Github pages or Netlify.

It is really simple but a great addition to the docs.

Keep up the great work, awesome project.

**Comment by elevatebart** [comment]
It is a great suggestion. I myself struggled a little to find out how to do it.
I will add a page called `Deployment` in there.

**Comment by elevatebart** [comment]
I do not know how to deploy directly to netlify though, I will ask @shortdiv.

**Comment by nicooprat** [comment]
@elevatebart Netlify should be really easy by following their onboarding steps:

1. Link to Github account
2. Choose a repo & a branch
3. Set up build command `npm run styleguide:build` & folder to serve `styleguide`

Any info for Github pages? Never used it.

**Comment by elevatebart** [comment]
We are publishing examples here using GitHub pages. The process is rather simple as long as you know it exists.

1. Chose where to host the sources (a `docs` branch on your current repo or a `.github.io` repo)
1. turn "GitHub Pages" ON where you chose. To do that go to settings > options > GitHub Pages, the root of the chosen repo will be your `wwwroot`.
1. Last, automate the deployment process. There is an example in travis.yml.
