### ISSUE TITLE
[Feature Request] Add a config option to allow the sections to be transformed

### ISSUE THREAD

**Issue by jimmaaay** [vue-styleguidist/vue-styleguidist#247]
Hey, it'd be useful to have a config option which allows the sections passed to the React StyleGuide component to be transformed. This would then allow more customisation for how the documentation is shown. 

basic example (this would be added to styleguide.config.js) : 
```js
transformSections: (sections) => {
  return sections.map((section) => {
    section.name = `Example ${section.name}`,
    return section;
  });
}
```

If you want I can also provide another example, which is more related to the use case I would like. This would be where you can write your own JSDoc style comments against component properties and have them transformed.

I'll open a PR which has allowed me to do this locally

**Comment by rafaesc** [comment]
Hi @jimmaaay 

you can use `styleguideComponents` option.

https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Configuration.md#styleguidecomponents

**Comment by jimmaaay** [comment]
Hey @rafaesc 

It doesn't look like it allows you to edit the StyleGuide component using that way currently.

https://github.com/vue-styleguidist/vue-styleguidist/blob/master/scripts/make-webpack-config.js#L177

**Comment by rafaesc** [comment]
Well, you have to know that modifying Styleguide component can break the static page,for that reason it's filtered.

But you can access to component using `dangerouslyUpdateWebpackConfig` option

**Comment by jimmaaay** [comment]
Ahh didn't think of that. Thanks! 🙂
