### ISSUE TITLE
Vue.use is undefined

### ISSUE THREAD

**Issue by rmartins90** [vue-styleguidist/vue-styleguidist#25]
I need to run install() from a plugin in order to generate documentation examples but available vue class into .md files doesn't have .use() function. How can I achieve this?

**Comment by rafaesc** [comment]
Hi @rmartins90, I tried to explain how add vue plugins in the style guide, here:

https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Cookbook.md#how-to-add-mixins-or-third-party-plugins-to-the-style-guide

**Comment by rmartins90** [comment]
Great! Thank you for answer and for the excellent lib.

**Comment by rafaesc** [comment]
Thanks!

**Comment by rmartins90** [comment]
Sorry but this is not working properly. The following libs doesn't work (for example):
- https://github.com/euvl/vue-js-modal
- https://github.com/AStaroverov/v-media-query

**Comment by rafaesc** [comment]
Hi @rmartins90,

I have been able to use both libraries in this example, I hope that this can help you

https://github.com/rafaesc/vue-styleguidist-demo

Cheers,
Rafael
