### ISSUE TITLE
Unknown custom element even after explicit require

### ISSUE THREAD

**Issue by LeBenLeBen** [vue-styleguidist/vue-styleguidist#252]
I followed the docs on how to load components when `skipComponentsWithoutExample` is set to `true` in the config. I explicitly loaded my child component within `Grid.md` like this:

```vue
const Vue = require('Vue').default;
const GridItem = require('../GridItem/GridItem.vue').default;
Vue.component('grid-item', GridItem);

<grid>
  <grid-item :widths="['1/2', { md: '1/3' }, { lg: '1/4' }]">
    Item
  </grid-item>
</grid>
```

But Vue always throws the following warning:
> [Vue warn]: Unknown custom element: `<grid-item>` - did you register the component correctly? For recursive components, make sure to provide the "name" option.

Logging the imports return correct data. Also `Vue.options.components` return the availability of a `grid-item` element.

Am I doing something wrong or could there be a bug somewhere? I have the feeling that the Vue instance I explicitly require is different from the one used to render the Grid example.

Relates to #161

**Comment by elevatebart** [comment]
Hello @LeBenLeBen, 

It would help a ton if you could cook up a quick repro repo.
I could even add this to the e2e tests on every branch so that your case is guaranteed to always work.

Thank you in advance and sorry for not getting to you earlier.
This really seems like a bug.
Bart

**Comment by LeBenLeBen** [comment]
Oh snap, I was able to make it work the other day and forgot to update this issue, sorry for that.

The problem was caused by `const Vue = require('Vue').default;`, the value within the `require` should be lowercase.

**Comment by RyanHavoc** [comment]
Should the require be within the `.md` file itself?

I have a `Button` component and a `ButtonStatePresenter` component I want to keep hidden. So I've set `skipComponentsWithoutExample` to true and included this in my `Button.examples.md` file:

```
const Vue = require('vue').default
const ButtonStatePresenter = require('../_styleguide/ButtonStatePresenter.vue').default
Vue.component('ButtonStatePresenter', ButtonStatePresenter)
```

But I get the error you did:

```
[Vue warn]: Unknown custom element: <ButtonStatePresenter> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

Any ideas?

**Comment by LeBenLeBen** [comment]
Yes the require must be in the MD file, within the code block. Have you restarted the server? Also be sure to double check the path to your component. I think the require will fail silently if it cannot load the file.

**Comment by RyanHavoc** [comment]
> within the code block.

That's what I wasn't doing! Thank you. Working now.
