### ISSUE TITLE
Multiple jsx/vue blocks in markdown files are ignored, only the first renders. Docs blocks work fine.

### ISSUE THREAD

**Issue by JessicaSachs** [vue-styleguidist/vue-styleguidist#259]
When using markdown files to render your examples, only the first jsx or vue block is rendered. The other ones are not rendered.

When using `<docs>` tags in SFC, all of the jsx and vue blocks are rendered.

Markdown files should be able to render multiple jsx/vue blocks.

**Comment by elevatebart** [comment]
Hello @JessicaSachs , I can't seem to reproduce on simple cases would you mind sharing a quick .md file that fails ?
The basic example actually uses md files that have multiple snippets

**Comment by elevatebart** [comment]
If you find the issue again, please open a new one. As discussed, might be a user issue with hot reload.

**Comment by tornography** [comment]
Input:
![grafik](https://user-images.githubusercontent.com/878616/53885726-bd431f00-401e-11e9-91da-1978e279755d.png)

Output:
![grafik](https://user-images.githubusercontent.com/878616/53885834-f4b1cb80-401e-11e9-8cc6-d627c10820fe.png)

**Comment by elevatebart** [comment]
thank you @tornography for the repro.

**Comment by tornography** [comment]
Investigated a litte bit. It's caused by the standard behavior of vue, by just having one single root element. So wrapping those two components in a div resolved the problem.
But now the div is shown in the code example as well. A solution could be, to wrap content from a jsx code block in a div automatically, to make sure there is only one root element.

**Comment by elevatebart** [comment]
What if we make it a functional component ?

**Comment by JessicaSachs** [comment]
I'd actually meant in the Markdown file! @tornography and it turned out to be user issue where I was looking at a specific example block in isolation mode, where I _thought_ I was looking at the entire component and all of it's example blocks.

This is another example of a silent failure of the compiler to decide to "drop" the second example.

I'd much prefer one of the two:
1. An actual failure to compile
2. Wrapping the example in another anonymous component (your solution)
