### ISSUE TITLE
Making each component an individual page

### ISSUE THREAD

**Issue by gensmann** [vue-styleguidist/vue-styleguidist#26]
Just a suggestion :-)

Having many and rather larger components grouped together in a single project/repo, the one-page documentation can get rather long and confusing.

It would help a lot to be able to split up each component into individual pages, or add some sort of split line after each component, in the default theme/styling.

Also adding a setting for a different font-family for the headers, might make the sections separate a bit better.

**Comment by rafaesc** [comment]
Hi @gensmann, thanks for the suggestion!

Perhaps it could be an optional configuration. Let me evaluate it. I need to know how to make it simple to configure.

About adding different styles for the headers, I going to add to styleguidist.

Cheers.
Rafael

**Comment by rmartins90** [comment]
Any news on this? Docs page is getting really heavy on large projects.

**Comment by rafaesc** [comment]
Yes @rmartins90 , I see that it's necessary, I hope that I can work it and also the Typescript support in December.

Regards,

**Comment by alexatbaseagency** [comment]
Hi guys, yes please @rafaesc. On our project we have components with modifiers and guidance.

**Comment by rafaesc** [comment]
Yes @alexatbaseagency, I still want to resolve this issue, however, in this moment I am passing for some little bit problems, I will back in late January, but with more force.

Regards,

**Comment by rafaesc** [comment]
Hi guys,

Ok, the repository was updated.
I added a new property to you can add a navigation in the style guide
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Configuration.md#navigation

Also, I updated the example
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/examples/navigation/styleguide.config.js#L5

Upgrade to version 1.4.2,

I would like to improve it and maybe to make something similar as [docsify](https://docsify.js.org/#/) or [gitbook](https://www.gitbook.com/), but I'm not sure if it's necessary. Also, you can contribute.

Cheers,

**Comment by rafaesc** [comment]
Live example:
http://rafaelescala.com/vue-styleguide-navigation/

**Comment by KindWizzard** [comment]
Hello guys! Can you help me with highlighting active component name in the left menu bar? I can't find any use-full selector :(

**Comment by rafaesc** [comment]
@KindWizzard did you see this example?

https://github.com/vue-styleguidist/vue-styleguidist/blob/master/examples/navigation

**Comment by KindWizzard** [comment]
@rafaesc Yeah, sure. But look at the screenshot. Active section is "First". But the menu item "first" is not active (not highlighted and there is not any ".active" css selector on it)
<img width="556" alt="screen shot 2018-06-10 at 03 41 08" src="https://user-images.githubusercontent.com/7937220/41197258-3119ecf8-6c60-11e8-9cc7-049122c9a761.png">

**Comment by KindWizzard** [comment]
Expected behaviour:

<img width="558" alt="screen shot 2018-06-10 at 03 44 33" src="https://user-images.githubusercontent.com/7937220/41197275-ab0453c8-6c60-11e8-85e8-7c5ca735bd75.png">

**Comment by MiguelSavignano** [comment]
I think some component like Header or Footer it's useful render in individual page.

I't posible render a component in individual page with this trick.

styleguide.config.js
```js
const fs = require('fs')

module.exports = {
  configureServer(app) {
    app.get('/full-page', (req, res) => {
      res.status(200).sendFile('./public/full_page_examples.html', { root: __dirname });
    }),
  }
   sections: [
    {
      name: 'UI Components',
      components: 'src/components/**/*.vue'
    },
    {
      name: 'Full Page examples',
      sections: [
        {
          name: 'Header and footer',
          external: true,
          href: '/full_page_examples'
        }
      ]
    }
  ]
}
```

of course you need to create a static html with the bundle of vue page component.
