### ISSUE TITLE
Putting html comment besides root element causes TypeError

### ISSUE THREAD

**Issue by mob8607** [vue-styleguidist/vue-styleguidist#267]
Hi,

I am using the single file components and as soon as I put a html comment on the same level as the root element of my component, I get following error when I want to build the styleguide: `TypeError: Cannot read property 'children' of undefined`

Example:
```
<template>
  <!-- test -->
  <div> This is the root element of my component. </div>
</template>
```

**Comment by elevatebart** [comment]
It is very probably a bug. I will look into it asap. I will just move it to vue-docgen-api if you don't mind.

**Comment by elevatebart** [comment]
CLosing since we have https://github.com/vue-styleguidist/vue-docgen-api/issues/96
