### ISSUE TITLE
slot definition inside a scoped slot are not documented

### ISSUE THREAD

**Issue by stephsavoie** [vue-styleguidist/vue-styleguidist#268]
I'm trying to document slot in my code.  
I'm using vue-styleguidist version 3.0.9  and vue version 2.5.21

this is working fine as it's documented correctly by Vue Styleguidist:
```
<div class="search-container">
    <!-- @slot test item template -->
    <slot name="test"></slot>
    <!-- @slot default slot -->
    <slot />
</div>
```

But code below is not working, maybe because the slot is defined inside a `slot-scope` after having done some tests:
```
<template slot-scope="{item}">
  <!-- @slot Suggestion item template -->
  <slot name="suggestion" :item="item" :searchString="searchString">
    <li class="search-suggestion">
      <span class="suggestion">{{ item.value }}</span>
    </li>
  </slot>
</template>
```

Same issue occurs if template tag above is replaced with anything else (like a div tag).  Slot definition is simply ignored and no error at all anywhere.

Any clue or ways to get around this issue?

**Comment by elevatebart** [comment]
The issue is that the comment is attached to the root node.
A slot without a comment will not be documented.
So your comment not being picked up + slot not being documented if no comment = no doc. it is a bug in vue-docgen-api.
I will fix it.

**Comment by elevatebart** [comment]
This should be dealt with in 3.0.13 ;).
Thank you for the feedback

**Comment by elevatebart** [comment]
Hello @stephsavoie did you get to try the above version ?
