### ISSUE TITLE
Allow vue code blocks without script parts in examples markdown

### ISSUE THREAD

**Issue by sylvainpolletvillard** [vue-styleguidist/vue-styleguidist#269]
Hello, nice project !

I try to use vue code blocks in some examples markdown, but some of these code blocks do not contain a `<script>` tag. This currently causes a JS exception here: https://github.com/vue-styleguidist/vue-styleguidist/blob/master/src/utils/singleFileComponentUtils.js#L27

Example:

```
```vue
<template>
        <Field>
            <Input placeholder="Search..." type="search" icon="search"></Input>
        </Field>
</template>
\```
```

I think the `<script>` tag is not technically required in the SFC spec, if you only use globally declared components for example, or if you just want to regroup a bunch of HTML. So the script part should be optional.

**Comment by elevatebart** [comment]
Woopsie !! I fixed it in vue-docgen-api but not here ...
Will fix soon, or Pull Request welcome ;)
