### ISSUE TITLE
Vue example gives a syntax error

### ISSUE THREAD

**Issue by gensmann** [vue-styleguidist/vue-styleguidist#27]
The following example from the documentation

```js
const names = require('dog-names').all;

new Vue({
  data(){
    return {
      list: names
    }
  },
  template: `
    <div>
      <RandomButton :variants="list" />
    </div>
  `
})
```

is giving a syntaxt error in chrome

![image](https://user-images.githubusercontent.com/621948/30780192-b7897abe-a105-11e7-8242-252c798d4eed.png)

**Comment by rafaesc** [comment]
Hello, make sure you have installed the package in your project, finally the example should be in the markdown.

**Comment by gensmann** [comment]
I've fixed what i tried to do (render a list of available icons. However i must admin I'm not quite sure why/how this works, but it does. i wasn't aware that i could iterate using vue over a random variable not being part of a vue instace :-)

![image](https://user-images.githubusercontent.com/621948/30786511-695fb084-a177-11e7-9eb5-5f02cff2bc48.png)
