### ISSUE TITLE
Read Props/Methods from external-separate .js file

### ISSUE THREAD

**Issue by cub** [vue-styleguidist/vue-styleguidist#271]
Hi,
First, thanks for your work, i have tested many generators of documentation, yours is the best ;)

I have an issue, if I externalize the `<script>` like :
```html
// .vue file
<template>
  <div>Hi mom !</div>
</template>
<script src="./comp.ctrl.js"></script>
```

Vue-Styleguidist will find my component, display the template part but not the Props/Methodes part. If I put the content into the `<script>` no problem. I tried to change the regex of `components: 'src/components/**/[A-Za-z]*.vue'` to accept `.js` without success, there is a security to allow only .vue file.

Is there a way to parse properly the external .js file ? I want to keep in different files the html/vue and the js part.

**Comment by elevatebart** [comment]
Hello @cub ! vue-docgen-api for now does not load remote templates, styles or scripts. I think it is an interresting idea that I will explore in the days to come.

I will copy your issue to [vue-docgen-api](https://github.com/vue-styleguidist/vue-docgen-api) and close this one when done.

Thank you for taking the time to log it.

**Comment by elevatebart** [comment]
please follow https://github.com/vue-styleguidist/vue-docgen-api/issues/105
