### ISSUE TITLE
Impossible to import js mixins 

### ISSUE THREAD

**Issue by ale-grosselle** [vue-styleguidist/vue-styleguidist#273]
Hi, 
many thanks for your work!

Importing a js as mixin in my vue components, generates this error:

Warning: Cannot parse src/basic/button/Button.vue: Error: Neither 'mixins/Themeable.vue' nor 'mixins/Themeable.js', not even 'mixins/Themeable/index.js' or 'mixins/Themeable/index.ts' could be found in '/Users/alessandro.grosselle/Documents/projects/github-project/vue-styleguidedist/src/basic/button'

You can see a repo example here:
https://github.com/ale-grosselle/vue-styleguidedist

**Comment by elevatebart** [comment]
Thanks @ale-grosselle I will have a look.

**Comment by ale-grosselle** [comment]
@elevatebart I have update to 3.0.13, but the problem is still present: 
https://github.com/ale-grosselle/vue-styleguidedist
![image](https://user-images.githubusercontent.com/6173088/52899112-8e3b4980-31e6-11e9-88c3-bd25a4160d69.png)

**Comment by ale-grosselle** [comment]
@elevatebart the problem isn't fixed.
Please see my simple example:
https://github.com/ale-grosselle/vue-styleguidedist/blob/master/src/basic/button/ButtonMixin.vue

**Comment by ale-grosselle** [comment]
@elevatebart many thanks for the fix!
I'm testing your fix and everything works well except for something that I do not know if it's a bug:
If you import a mixins in a component without "name" attribute set, in the generated documentation the component name will be the minixin name.

![image](https://user-images.githubusercontent.com/6173088/52916682-e0fa2b80-32e2-11e9-954c-d9dec0500504.png)

![image](https://user-images.githubusercontent.com/6173088/52916693-00915400-32e3-11e9-8212-a0f414c13f3e.png)

Is correct?

**Comment by elevatebart** [comment]
This is interresting and is another bug. I will log it in vue-docgen as well.

**Comment by elevatebart** [comment]
https://github.com/vue-styleguidist/vue-docgen-api/issues/110
