### ISSUE TITLE
Prop with Multiple types always shows "array"

### ISSUE THREAD

**Issue by ale-grosselle** [vue-styleguidist/vue-styleguidist#277]
Hi, 
if you add multiple types using this syntax:
![image](https://user-images.githubusercontent.com/6173088/52914042-0592db00-32c4-11e9-97fa-dfd15ae44a2a.png)
In the documentation, it always show as array:
![image](https://user-images.githubusercontent.com/6173088/52914054-1b080500-32c4-11e9-93c4-3c9552f69d4f.png)

Please see this basic repository:
https://github.com/ale-grosselle/vue-styleguidedist, in details, this vue:
https://github.com/ale-grosselle/vue-styleguidedist/blob/master/src/basic/button/ButtonType.vue

**Comment by elevatebart** [comment]
This is a bug that has been there forever, fixing it should not be too hard.
I will transfer it to [vue-docgen-api](https://github.com/vue-styleguidist/vue-docgen-api) though.

**Comment by elevatebart** [comment]
Please follow this issue instead of the current one https://github.com/vue-styleguidist/vue-docgen-api/issues/108.

**Comment by ale-grosselle** [comment]
@elevatebart many thanks and, again, congratulation, great project!
