### ISSUE TITLE
events are not shown in documentation 

### ISSUE THREAD

**Issue by ale-grosselle** [vue-styleguidist/vue-styleguidist#279]
Hi!!
 
If you emit a parametric event (event Id provides from a variable), the event is never shown in the documentation.

![image](https://user-images.githubusercontent.com/6173088/52957519-2164b280-3392-11e9-9080-cc9b5b4d4f7c.png)
![image](https://user-images.githubusercontent.com/6173088/52957539-2fb2ce80-3392-11e9-8f66-bb722d8078a7.png)

If you want, see the example:
https://github.com/ale-grosselle/vue-styleguidedist/blob/master/src/basic/button/ButtonMixin.vue

If it can be useful, this behavior works in version 2.1.2

Less important but perhaps it can be related, I can't get default prop value from a constant:
![image](https://user-images.githubusercontent.com/6173088/52957735-a780f900-3392-11e9-9219-d3b3e0c479a7.png)

![image](https://user-images.githubusercontent.com/6173088/52957796-e1ea9600-3392-11e9-8b3e-3ecf106ae3da.png)

**Comment by elevatebart** [comment]
Once again a great remark from @ale-grosselle, I will transfer immediately to docgen ;)

Thank you again and well ... Sorry ^^.

**Comment by elevatebart** [comment]
please follow https://github.com/vue-styleguidist/vue-docgen-api/issues/113

**Comment by ale-grosselle** [comment]
Hi @elevatebart 
sorry if you still trouble me but I still have problems with event documentation.

We usually define eventName in a separated Enum files:
![image](https://user-images.githubusercontent.com/6173088/53237971-5de92480-3698-11e9-9634-ab9f47883abc.png)
Doing so, events are never shown:
![image](https://user-images.githubusercontent.com/6173088/53237984-65a8c900-3698-11e9-8864-a29a372a0366.png)

If it's difficult to access to enum value, in my opinion is acceptable to set event name as jsdoc:
![image](https://user-images.githubusercontent.com/6173088/53238073-a43e8380-3698-11e9-9184-c6868a98674d.png)

Code example:
https://github.com/ale-grosselle/vue-styleguidedist/blob/master/src/basic/button/ButtonMixin.vue

**Comment by elevatebart** [comment]
Hey @ale-grosselle, Even if I do not know your architecture I wonder how you actually hook on those events. Id est, if you have an event "error" you still have to have an `@error` on the parent component. Which means that those events are still hardcoded. 

I do believe that your use case makes sense even if I do not like it.

Would you please create an issue on https://github.com/vue-styleguidist/vue-docgen-api.
It would ask for the possibility to force recognition of an event that is not a litteral but has the @event JSDoc. I think it is a good solution for your issue.

thank you in advance, I will get on it as soon as you post the issue.

**Comment by ale-grosselle** [comment]
@elevatebart Thanks for the reply!
I am building a components library based on vue and for each event component i create an object key:value where I set the event string:
``
const eventsList = {'play': 'play', 'stop': 'stop'.}
``
In my opinion is the best mode to avoid string error (emit played instead of play for example). 
The eventname is stored into an object, get event string from it.

So actually unfortunately, parameter events are not managed

**Comment by elevatebart** [comment]
Absolutely, me not liking it was an opinion.
Once again, can you create an enhancement issue in vue-docgen-api and I will add the `@event` flag ASAP

**Comment by ale-grosselle** [comment]
Yes, now I am opening anche issue!
But only FYI, in previous version the library was able to get event name from jsdoc so Is could be a regressione instead of and enahace?

**Comment by elevatebart** [comment]
I agree let's fix the regression ;)

**Comment by anthonygore** [comment]
Hi, I'm having this issue as well. Using the CLI plugin v3.15.0

```js
import {EVENT_ERROR} from "./contants";
/**
  * Error event.
  * @type {string}
  */
this.$emit(EVENT_ERROR, ...) // doesn't work
/**
  * Error event.
  * @type {string}
  */
this.$emit("EVENT_ERROR", ...) // works
```
