### ISSUE TITLE
Extends support

### ISSUE THREAD

**Issue by rmartins90** [vue-styleguidist/vue-styleguidist#28]
It would be great to have documentation for props and methods of extended component.

**Comment by rafaesc** [comment]
Hi, @rmartins90,

I'm not sure of understanding which is the extended components

**Comment by rmartins90** [comment]
If you create a component extending another one would be cool to make parent props available on styleguidist - https://vuejsdevelopers.com/2017/06/11/vue-js-extending-components/

**Comment by ebess** [comment]
:+1:

**Comment by thenickname** [comment]
Hey, the same goes for mixins. It seems that props and other stuff from mixins is not documented in the component where the mixin is applied.

If you want, I can open a separate issue for this. But it seemed to me that documenting mixed in props, methods, etc. is similar to documenting Extends...

**Comment by rafaesc** [comment]
Hi,

I have already updated a new version with supporting of `extend`, on version 1.7.4.

You can read the documentation, here:
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Documenting.md#include-mixins-and-extends

Regards
