### ISSUE TITLE
Add new config option buildDir, rename styleguideDir

### ISSUE THREAD

**Issue by MacZel** [vue-styleguidist/vue-styleguidist#280]
It would be nice being able to specify source directory as well as build directory in configuration. That would make project structure cleaner by separating config files from source files.

I would suggest introducing new option: `srcDir` with default value `src` and rename `stylguideDir` to `buildDir` with corresponding default `build`

**Comment by elevatebart** [comment]
It is a great idea.
I stumbled about it myself much on my first use of vsg.
I think it would mean some changes in make-wepack-config.js but not too many.

Probably some chnages in the schema validation as well. 
We cannot rename an option though, too many people rely on it. 
The existing `styleguideDir` would continue working the same way but be deprecated.

@rafaesc What do you think ?

**Comment by rafaesc** [comment]
@MacZel but I don't sure about specifying source directory, because you have to specify the url the components that you want to document in `components` property

**Comment by MacZel** [comment]
@rafaesc what I meant by `srcDir` is a directory where the source files of the styleguide live, and not the components to be documented.

**Comment by davebgreen** [comment]
I'm experiencing with Vue Cli 3 and styleguideDir = 'designsystem/dist',  that when I run styleguide:build it also creates a /dist directory on the project root.   Problem then is this overwrites the build of the application itself (seems to just be a direct copy of files from VUE Cli /public folder).    Any clues as to why this may occur?

**Comment by joroe** [comment]
> I'm experiencing with Vue Cli 3 and styleguideDir = 'designsystem/dist', that when I run styleguide:build it also creates a /dist directory on the project root. Problem then is this overwrites the build of the application itself (seems to just be a direct copy of files from VUE Cli /public folder). Any clues as to why this may occur?

Has this been solved? I am experiencing the same problem.

**Comment by elevatebart** [comment]
I do not believe that it is fixed, would you mind opening another issue [here](https://github.com/vue-styleguidist/vue-styleguidist/issues/new?template=Bug_report.md)?
