### ISSUE TITLE
Prop readonly with Typescript

### ISSUE THREAD

**Issue by jserra91** [vue-styleguidist/vue-styleguidist#281]
We are currently creating a components library with typescript and we use styleguist to show de properties, slots, events, etc.

We find the error when put the property named "readonly" don't show in the styleguist. If renamed to "readonlyy" if it is displayed.

```  /**
   * readonly
   */
  @Prop({
    type: Boolean,
    default: false
  })
  readonly!: boolean;
```

styleguide.config.js

```
...
        {
          name: 'BASE',
          components: "./src/components/ea/base/**/[A-Z]*.vue",
        },
...
```

**Comment by elevatebart** [comment]
Read only is a typescript keyword. The Babel typescript parser used by vue-docgen-api seems to have a hard time parsing it. I will try and find a way around it. 

In the meantime, if you can’t wait, you can use camel case readOnly.

Thank you for the heads up

**Comment by elevatebart** [comment]
Hey @jserra91 If you remove the `!` after readonly it will work too. 
I posted a bug to @babel/parser so that they deal with it on their side.

I think I can creat a quick PR that would fix it ;)

**Comment by jserra91** [comment]
Thx @elevatebart :)

**Comment by elevatebart** [comment]
Closing since merged in babel ;)
