### ISSUE TITLE
[Feature] Generate only markdown to plug into docute or Vuepress

### ISSUE THREAD

**Issue by dobromir-hristov** [vue-styleguidist/vue-styleguidist#283]
Could we use VSG to generate just markdown files, that we can then plug into Vuepress or something like Docute or Docsify? From what I understood, it is not possible at the moment.

https://github.com/vue-styleguidist/vue-docgen-api/issues/38 might be connected to this, as such a CLI tool using the ouput from the API might be what I am asking for?

Thanks!

**Comment by rafaesc** [comment]
@dobromir-hristov well, vue-docgen-api borned to be used in vue-styleguidist, although it could be included, there already is a tool.

https://gitlab.com/vuedoc/md

I don't sure if it's useful for you

**Comment by elevatebart** [comment]
@rafaesc I think we could add this to vue-docgen what do you think ?

**Comment by elevatebart** [comment]
as a response to https://github.com/vue-styleguidist/vue-docgen-api/issues/38

**Comment by rafaesc** [comment]
@elevatebart well, yes, I would like to research which would be the best markdown format to be used in Vuepress, Docute or Docsify. maybe we can do something fine.

**Comment by elevatebart** [comment]
@dobromir-hristov per our talk on discord, please tell us if you need help.
If you do not have time for it no big deal. 
It seems like an exciting project. 
Thank you for taking it on.

**Comment by dobromir-hristov** [comment]
I will try to research what `md` format would fit best all the popular documentation generators. From what I know from experience, they all use `markdown-it` as a parser.
