### ISSUE TITLE
unable to make file-loader to work

### ISSUE THREAD

**Issue by MacZel** [vue-styleguidist/vue-styleguidist#289]
Example `webpackConfig` part taken from my `styleguide.config.js`

```
webpackConfig: {
    context: path.resolve(__dirname, ""),
    module: {
        rules: [
            {
                test: /\.vue$/,
                loader: 'vue-loader'
            },
            {
                test: /\.(styl|stylus)$/,
                use: [
                    'style-loader',
                    'css-loader',
                    {
                        loader: 'stylus-loader',
                        options: {
                            import: [
                                path.resolve(__dirname, "../app/src/assets/stylus/globals.styl"),
                                resolve("src/styles/styles.styl"),
                            ]
                        }
                    }
                ]
            },
            {
                test: /\.svg$/,
                loader: "html-loader",
            },
            {
                test: /\.(ico|jpg|png)$/,
                loader: "file-loader",
            },
            { 
                test: /\.ts$/, 
                loader: 'ts-loader', 
                options: { 
                    appendTsSuffixTo: [/\.vue$/]
                } 
            },
            { 
                test: /\.tsx$/, 
                loaders: [
                    {
                        loader: "babel-loader"
                    },
                    {
                        loader: "ts-loader",
                        options: {
                            appendTsxSuffixTo: [/\.vue$/],
                            transpileOnly: true
                        }
                    }
                ]
            },
        ]
    },
    plugins: [new VueLoaderPlugin()],
    resolve: {
        extensions: ['.ts', '.tsx', '.js', '.vue', '.vuex', '.json'],
        alias: {
            "@": path.resolve(__dirname, "../app/src"),
        },
    }
}
```

**Comment by elevatebart** [comment]
Hello @MacZel, 
What do you mean by "unable to work"?
Did you see an error message? File not found? Was a directory ignored?

**Comment by MacZel** [comment]
No error message at all. Directory is the same as where I keep svg icons. Svgs are being loaded with html-loader. Unfortunately can't make file-loader to work. It seems like webpack is omitting the rule with file-loader.

**Comment by elevatebart** [comment]
Are you saying that none of the images appear ?

**Comment by MacZel** [comment]
Yes, exactly. Tried to find something similar in vsg examples, unfortunately none of them use file-loader to load images.

**Comment by elevatebart** [comment]
You might have to tell webpack where to find these images.

Have you tried using the option `assetsDir`
https://vue-styleguidist.github.io/Configuration.html#assetsdir

It is used to tell webpack where to load the images from.

Hope it helps

**Comment by MacZel** [comment]
I'm already using this option in my config. Images are located at the same directory as Svgs, so this should work for both..

**Comment by elevatebart** [comment]
Have you tried using it without styleguidist ?

**Comment by elevatebart** [comment]
The only thig styleguidist does is using your webpack config to load the components. So if ti works without styleguidist it shoudl work with as well.

**Comment by MacZel** [comment]
I was able to find a solution. file-loader and url-loader both work.
To load a file you need to pass webpack rule:
```js
{
    test: /\.(ico|jpg|png)$/,
    loader: "file-loader",     // or url-loader
},
```
create script at eg. `loadImages.js`.
In this file you need to import every file:
```js
import img_1 from './assets/image.png'
import img_2 from './assets/image.jpg'
import img_3 from './assets/image.ico'
```
then pass this script in Vue Styleguidist config file option `require`.
```js
require: [
    resolve("loadImages.js"),
],
```
Dunno if this was obvious. Hope this will help somebody in the future.

Tested lots of other suggested solutions from SO and github issues, but this way only seems to work.
