### ISSUE TITLE
How do I document events?

### ISSUE THREAD

**Issue by klarkc** [vue-styleguidist/vue-styleguidist#29]
According the docs http://usejsdoc.org/tags-event.html we can use @fires and @event tags to refer to event documents, but It seems that the compiler ignores these entries.

**Comment by rafaesc** [comment]
Hi @klarkc,

The repository was updated.
I tried to explain how to add events in the style guide, here:
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Documenting.md#code-comments

Also, I updated the example
https://github.com/vue-styleguidist/vue-styleguidist/tree/master/examples/basic
http://rafaelescala.com/vue-styleguide/#input

Upgrade to version 1.2.8,

Cheers
