### ISSUE TITLE
Multiple hot-reloading source create Maximum call stack error

### ISSUE THREAD

**Issue by gjuchault** [vue-styleguidist/vue-styleguidist#290]
Hello,

Using vue-styleguidist from scratch, I had hot-reload error:

```
Uncaught RangeError: Maximum call stack size exceeded
    at hotAddUpdateChunk
```

![image](https://user-images.githubusercontent.com/678848/53303452-b8d27580-386a-11e9-92d3-e8221a30cd46.png)

It appears to be linked to https://github.com/webpack/webpack-dev-server/issues/87 / https://github.com/webpack/webpack/issues/5655

By removing the plugin https://github.com/vue-styleguidist/vue-styleguidist/blob/master/scripts/make-webpack-config.js#L147 I was able to make Hot Reload works.

I guess combining:
- https://github.com/vue-styleguidist/vue-styleguidist/blob/master/scripts/make-webpack-config.js#L147
- https://github.com/vue-styleguidist/vue-styleguidist/blob/master/scripts/create-server.js#L13
- https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/config/dev.js#L11

Makes the Maximum Call Stack.

I did not open a PR to remove the plugin line as you specifically said [here](https://github.com/vue-styleguidist/vue-styleguidist/blob/master/scripts/make-webpack-config.js#L94) that the HMR plugin should be after HTMLPlugin, but it seems to be working locally.

**Comment by gjuchault** [comment]
Temporary solution:

```

**Comment by gjuchault** [comment]
Temporary solution:

Add this in `styleguide.config.js`

```js
module.exports = {
    // ...
    dangerouslyUpdateWebpackConfig(webpackConfig) {
        let filteredFirstHMR = false;

        webpackConfig.plugins = webpackConfig.plugins.filter(plugin => {
            if (plugin.constructor.name === 'HotModuleReplacementPlugin' && !filteredFirstHMR) {
                filteredFirstHMR = true;
                return false;
            }

            return true;
        });

        return webpackConfig;
    }
}
```

**Comment by elevatebart** [comment]
Hello @gjuchault, are you using vsg with the @vue/cli 3 ?
If yes, you should probably use the [plugin](https://github.com/vue-styleguidist/vue-cli-plugin-styleguidist). 
If you do, and it is what is failing, can you please open a request on this repo?

**Comment by gjuchault** [comment]
No, I'm not using it with @vue/cli 3

**Comment by elevatebart** [comment]
Hello Gabriel, I do not get your référence to @vue/cli-service of you are not using the CLI...
Would you please set up a repository so that I can reproduce and fix it ? I myself had HMR issues with a router with only * as a route. I understand your frustration.

Thank you in advance.

**Comment by JessicaSachs** [comment]
I'm also getting this @elevatebart... I'm using Vue's CLI Service and a pretty basic setup.

**Comment by elevatebart** [comment]
@JessicaSachs Yes pretty please !! :)

**Comment by elevatebart** [comment]
Actually @gjuchault, @JessicaSachs was on an older version of the cli-plugin. 
To help solve your issue, can you share what your `package.json` looks like ?
I am especially interested in the devDependencies section.

do not hesitate to ping me on discord ;)

**Comment by elevatebart** [comment]
Hello Gabriel, 
@gjuchault do you have a minute today to try reproducing it for me?
Or at least give me an idea of the contents your `package.json` file ?

**Comment by gjuchault** [comment]
@elevatebart Sorry I was a bit busy the last few days. 
To get to this issue, I didn't use the vue-cli plugin.

My package.json (removed desc, etc.)
```json
{
  "name": "ui",
  "version": "1.0.0",
  "scripts": {
      "dev": "vue-styleguidist server",
      "build": "vue-styleguidist build"
  },
  "devDependencies": {
    "vue-styleguidist": "^3.0.16"
  }
}
```

My styleguide.config.js (removed theming part, and some booleans)
```js
const path = require('path');

module.exports = {
    components: 'src/components/**/*.vue',
    require: [path.join(__dirname, 'src/index.js')],
}
```

On load, it says:
```
Loading webpack config from:
/Users/gjuchault/monorepo/packages/ui/node_modules/@vue/cli-service/webpack.config.js
```

**Comment by elevatebart** [comment]
vue-styleguidist needs a `webpack.config.js` to work out your components.

As you can see in the error message above, styleguidist is picking up the `@vue/cli-service` webpack config.
This means that the `@vue/cli-service` package did get installed in your repository. It is part of the vue cli 3. Unless you specify otherwise in `vue.config.js`, this `webpack.config.js` contains an extra HMR plugin that needs to be removed. If you do not remove it, you will get this HMR feedback loop.

Vue-cli-plugin-styleguidist will remove this extra HMR for you. if you wish to not use the `@vue/cli-service/webpack.config.js`, you should set the option webpackConfig in your `styleguide.config.js` file.

I hope this helps.
Bart

**Comment by gjuchault** [comment]
@elevatebart Thansk for the information. You can close the issue. I think it could be nice to specify it in the documentation (either in a FAQ or something)

**Comment by elevatebart** [comment]
You are right, we could add it to the cookbook. It can be very helpful to go through.
Maybe a troubleshooting page. Please do not hesitate to send a pull requests to the docs.
Did it work ?

Thank you for your interest.

**Comment by gjuchault** [comment]
It works very well by using the vue cli plugin :)

**Comment by gaconkzk** [comment]
hi @gjuchault,  I'm having same problem, using the cli plugin `vue-cli-plugin-styleguidistwith vue-cli 3
my vue.config.js:
```js
const path = require("path")

function resolve(dir) {
  return path.join(__dirname, dir)
}

module.exports = {
  chainWebpack: config => {
    config.module
      .rule("svg")
      .exclude.add(resolve("src/assets/icons"))
      .end()
    config.module
      .rule("icons")
      .test(/\.svg$/)
      .include.add(resolve("src/assets/icons"))
      .end()
      .use("svg-sprite-loader")
      .loader("svg-sprite-loader")
      .options({
        simbolId: "icon-[name]",
      })
      .end()
  },
  css: {
    loaderOptions: {
      sass: {
        data: `
            @import "@/assets/tokens/tokens.scss";
            @import "@/assets/tokens/tokens.map.scss";
            @import "@/styles/styles.scss";
          `,
      },
    },
  },
}
```
I have to add your `dangerouslyUpdateWebpackConfig` function into styleguide.config.js for work around.
Did you have any better solution?
Very appreciated.

**Comment by elevatebart** [comment]
Hello @gaconkzk

Do you have repository with a reproduction? Can you share your package.json ?

**Comment by ffxsam** [comment]
@elevatebart I'm having this issue too. Let me know what you need from me.

**Comment by elevatebart** [comment]
Hey @ffxsam do you use the vue cli ?
