### ISSUE TITLE
Required attribute for props not populating

### ISSUE THREAD

**Issue by mattwaler** [vue-styleguidist/vue-styleguidist#294]
When adding a required attribute to a components props, it doesn't seem to populate in the guide. I've provided screenshots and repo link below.

Repo: [personal-site](https://github.com/mattwaler/personal-site)

![code](https://user-images.githubusercontent.com/32300026/53653228-dc097600-3c18-11e9-85cb-a131958df162.png)

![app](https://user-images.githubusercontent.com/32300026/53653231-dd3aa300-3c18-11e9-9233-cb161de1c4aa.png)

**Comment by elevatebart** [comment]
Hello @mattwaler this is true, for clarity reason.

In order to more easily see required properties, we leave it empty when it is not required. 
Since it can only be required or not required, if it is not **yes**, it is **no**. 
What is your use case? Does it have to be explicit?

**Comment by mattwaler** [comment]
Hello @elevatebart!

Your explanation makes sense, and I probably shouldn't have been so dumb as to not try the setting the prop to true before submitting the issue.

I personally would like be able to change that behavior and have false show all the time, my OCD would not be able to handle having every other field filled out except for required 🙃 .

Maybe this should be documented somewhere, and possibly customizable within the configuration file?

Regardless, I am absolutely loving this project, thank you for it! (currently using with Nuxt and it has been a breeze).

**Comment by elevatebart** [comment]
Thank you @mattwaler your praise means a lot.
As soon as I am done with the creation of the monorepo I will go into a documentation frenzy and give a bit of trouble shooting.

You can send a quick PR. If you find the perfect place to to document it.
