### ISSUE TITLE
Adding example code gives error in console

### ISSUE THREAD

**Issue by lancetharper** [vue-styleguidist/vue-styleguidist#3]
When I try to add a component example, these errors appear in the console:

![screen shot 2017-06-14 at 3 46 31 pm](https://user-images.githubusercontent.com/4389981/27157982-4e18bd10-5119-11e7-8e6b-6289d3236aaf.png)

I've tried naming the file the same as the component.vue and as Readme.md. The 'show code' shows the code snippet correctly, but the component is not rendered. (possibly related to #3)

**Comment by rafaesc92** [comment]
OK, I've published the fix under v1.0.10.
Please try it and let me know if it works.
