### ISSUE TITLE
Change name components in the section

### ISSUE THREAD

**Issue by jserra91** [vue-styleguidist/vue-styleguidist#319]
Hi,

It's possible change (or edit with styleguide.config.js) the name of components in the sections?

For example:

```
./src
    |
     \> /base
           |
           \>  /input-text
           |           |
           |            \> /src
           |           |       \> Inputtext.vue
           |            \> index.ts
           \> /button
                     |
                      \> /src
                     |       \> Button.vue
                       \> index.ts
           ...
```
Each component contains the name attribute.
```
...
@Component({
  name: 'pepito-button'
})
...
```
And in the styleguide.config.js contains the rute of components (vue and readme).
```
...
      name: "Componentes",
      content: "./src/guidelines/Components.md",
      sectionDepth: 3,
      sections: [
        {
          name: "BASE",
          components: "./src/base/**/src/[A-Z]*.vue",
          ignore: [
            "./src/base/dropdown/src/DropdownItem.vue",
            "./src/base/dropdown/src/DropdownMenu.vue",
            "./src/base/form/src/FormItem.vue",
            "./src/base/select/src/Option.vue",
            "./src/base/select/src/OptionGroup.vue",
            "./src/base/step/src/Step.vue"
          ]
        },
...
```
The request consists in not showing **pepito-button** in the styleguist menu but show "button" or "inputtext" (without prefix).

Thank you

**Comment by elevatebart** [comment]
There is 2 parts to your question.

### Part 1: Can I customize names of my component?
Indubitably. Try this.

```js
/**
 * @displayName better pepito-button
 */
 export default {
  name: 'pepito-button'
}
```

### Part 1: Why is the name property in the decorator `@component`?
It should be, if it is not then it is a bug.

```js
@Component({
  name: 'better pepito-button'
})
 export default {
  name: 'pepito-button'
}
```

**Comment by elevatebart** [comment]
Are you using class style components or config object defined components ?

**Comment by jserra91** [comment]
Yes but my problem is when I invoke the component (for example pepito-button) in the html, I use "<pepito-button>...</pepiton-button> (tag defined with "name" variable in the @component decorator) and the Styleguist print "pepito-button" label in the section.

I need a way to erase the prefix "pepito" and leave 'button' alone (in the menu section).

**Comment by elevatebart** [comment]
> Yes but my problem is when I invoke the component
How do you "invoke" the component? 
Are you talking about an example in the Markdown or in a default example?

A reproduction repo would be incredibly helpful.

You can clone this dude https://github.com/vue-styleguidist/buefy-styleguide-example
and do a couple of updates. I will do it myself.

Thank you for taking the time.

**Comment by elevatebart** [comment]
Actually wait a little bit before cloning, the repo is really out of date.
