### ISSUE TITLE
Problem when installing newest version of `vue-cli-plugin-styleguidist`

### ISSUE THREAD

**Issue by wmartins** [vue-styleguidist/vue-styleguidist#321]
**Current behavior**

Recently I got a really strange behavior in my build pipeline, saying the following message:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for vue-docgen-api@^3.9.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'vue-styleguidist'
npm ERR! notarget 
```

**To reproduce**

```bash
mkdir project
npm init -y
npm install --save-dev vue-cli-plugin-styleguidist@^3.9.2
```

**Expected behavior**

I exepected to be able to install this package.

**Further investigation**

It seems like `vue-docgen-api` wasn't published in the latest changes:

```bash
npm info vue-docgen-api  | grep latest                 
latest: 3.8.2
```

If you need any other info, just let me know.

**Comment by marshallswain** [comment]
If you install dependencies for your VueCLI project with Yarn, you'll be able to install `vue-cli-plugin-styleguidist`.

**Comment by wmartins** [comment]
@marshallswain, the problem is that I'm running this in a CI environment, so, no interactivity to choose the different version.

The only way I could make it work was to force the installation of a fixed version of `vue-styleguidist`. For example:

```bash
npm install --save-dev vue-styleguidist@3.8.3 vue-cli-plugin-styleguidist@3.8.3
```

**Comment by elevatebart** [comment]
I am on it, I had a little fight with lerna yesterday and I thought I had won apparently Lerna is a very resilient beast... Appropriate I guess.

**Comment by elevatebart** [comment]
I appreciate you guys waiting 3.9.3 is out and should be better

**Comment by wmartins** [comment]
Thanks for your effort @elevatebart!

Lerna can be painful sometimes, happy you won that fight!
