### ISSUE TITLE
Slot definition inside a v-else are not documented

### ISSUE THREAD

**Issue by seanzi86** [vue-styleguidist/vue-styleguidist#322]
**Current behavior**

If you add a `@slot` comment inside an element which has a v-else then this is not included in the documentation.

```
<tbody v-else>
    <tr class="is-empty">
        <td :colspan="columnCount">
            <!-- @slot Replaces table body when `data` array prop is empty -->
            <slot name="empty"></slot>
        </td>
    </tr>
</tbody>
```

**Expected behavior**
I would expect the slot to appear inside the documentation alongside the others defined in the comments.

**Comment by elevatebart** [comment]
Hello @seanzi86 
Just to confirm what I suspect is the bug, is your v-else on the root of your template?
```html
<template>
  <comp v-if="condition">
    my comp
  </comp>
  <comp2 v-else>
    <slot/>
  </comp2>
</template>
```

If it is the case, the `vue-template-compiler` is a bit uncool with me here. It is not parsing this template correctly and only parsing the first iteration.

I have created a PR to have it tested [here](https://github.com/vue-styleguidist/vue-styleguidist/pull/324)

**Comment by seanzi86** [comment]
Hello @elevatebart 
Thanks for the quick reply.

Currently I am just testing out using the [buefy](https://buefy.org) components.
The v-if is switching out the table body depending on if data is present.
Below is a cut down snippet

``` jsx
<template>
    <div class="b-table" :class="{ 'is-loading': loading }">
        <div class="table-wrapper">
            <table>
                <thead>
                </thead>
                <tbody v-if="visibleData.length">
                </tbody>
                <tbody v-else>
                    <tr>
                        <td>
			    <!-- @slot The missing slot -->
                            <slot name="empty"/>
                        </td>
                    </tr>
                </tbody>
                <tfoot>
                </tfoot>
            </table>
        </div>
    </div>
</template>
```

The component in question can be seen [here](https://raw.githubusercontent.com/buefy/buefy/dev/src/components/table/Table.vue)

**Comment by elevatebart** [comment]
Great catch !! I did not know that was the way if structure were handled in vue flavored ASTs.
Thank you so much. It is testes and it works now.
