### ISSUE TITLE
Document slots

### ISSUE THREAD

**Issue by rmartins90** [vue-styleguidist/vue-styleguidist#33]
It's possible to add slots to props, methods & events table?

**Comment by rafaesc** [comment]
Hi @rmartins90,

The repository was updated.
I tried to explain how to add slots in the style guide, here:
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Documenting.md#slots-documentation

Also, I updated the example
https://github.com/vue-styleguidist/vue-styleguidist/tree/master/examples/basic
http://rafaelescala.com/vue-styleguide/

Upgrade to version 1.3.1,

Cheers
