### ISSUE TITLE
v1.2.9 not working due to 'UglifyJs Plugin Invalid Options'

### ISSUE THREAD

**Issue by svewag** [vue-styleguidist/vue-styleguidist#34]
After switching to v1.2.9 the build breaks with the following error:

> { [Error: Validation Error
> 
> UglifyJs Plugin Invalid Options
> 
> options.parallel should be boolean
> options.parallel should be integer
> options.parallel should match exactly one schema in oneOf
> ]
>   err:
>    [ { keyword: 'type',
>        dataPath: '.parallel',
>        schemaPath: '#/properties/parallel/oneOf/0/type',
>        params: [Object],
>        message: 'should be boolean' },
>      { keyword: 'type',
>        dataPath: '.parallel',
>        schemaPath: '#/properties/parallel/oneOf/1/type',
>        params: [Object],
>        message: 'should be integer' },
>      { keyword: 'oneOf',
>        dataPath: '.parallel',
>        schemaPath: '#/properties/parallel/oneOf',
>        params: {},
>        message: 'should match exactly one schema in oneOf' } ] }
> /path/node_modules/vue-styleguidist/bin/styleguidist.js:33
> 		throw err;
> 		^

It seems that the reason for this is a newer version of "uglifyjs-webpack-plugin".
There is a new build out since a few hours: "1.0.0-beta.3" and your package load this as a dependency due to the semver '^1.0.0-beta.2'

**Comment by svewag** [comment]
Here is the error within  "uglifyjs-webpack-plugin": https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/139

**Comment by svewag** [comment]
> { parallel: true } work fine but { parallel: { cache: true } } throws an error:

in this file it is used and therefore breaks
https://github.com/vue-styleguidist/vue-styleguidist/search?utf8=%E2%9C%93&q=parallel&type=

**Comment by svewag** [comment]
Maybe you should fix the version of "uglifyjs-webpack-plugin" to beta-2?

**Comment by rafaesc** [comment]
Thanks @svewag! I updated the repository

Upgrade to version 1.2.10
