### ISSUE TITLE
Is there a way to show a list of options available for a prop?

### ISSUE THREAD

**Issue by CalebJTSmith** [vue-styleguidist/vue-styleguidist#345]
I have a few components with props that are basically an enum of options, but usually have 6-10 different options to choose from. They remind me of the button props for `appearance` like you see here: 

![image](https://user-images.githubusercontent.com/3040113/54722337-4e8fb680-4b32-11e9-91a2-3aa6a18aaf90.png)

I can lay them out in the description for the prop, but I'd like to split them to give more of a quick glance at what could be available to use. Is this an option at all?

I almost wonder if there is a way that it can read the validation of the prop to justify if its an enum and to grab that list. Like all of my validation runs likes `validator: value => ['button', 'a'].includes(value),`

**Comment by elevatebart** [comment]
What about something that would work with [propTypes](https://github.com/znck/prop-types) ?

**Comment by elevatebart** [comment]
Hello @CalebJTSmith 

I have something almost ready for 4.0.0 inspired by the documentation of buefy. 
Would you mind having a look and telling me if it fits the need?

https://deploy-preview-628--vue-styleguidist.netlify.com/basic/
