### ISSUE TITLE
@displayName not working?

### ISSUE THREAD

**Issue by rinobatin** [vue-styleguidist/vue-styleguidist#357]
I modified Button.vue in ./examples/basic (commit 5f959c8) by adding `@displayName BestButton`. However, the menu entry and heading still display "Button".

```
/**
 * The only true button.
 * @displayName BestButton
 * @example ../../../docs/ButtonIgnored.md
 * @example ../../../docs/Button.md
 */
export default {
	name: 'Button',
      .....
```

**Comment by elevatebart** [comment]
Thanks, @rinobatin. I think this is my mistake. I get confused between the `tags` member and the root.

We had the following:

```js
{
  tags:{
    displayName: "the name"
  }
}
```

while I was expecting

```js
{
  displayName: "the name"
}
```

sorry again, the fix is coming.

**Comment by rinobatin** [comment]
Thanks @elevatebart! Are you going to release a patch soon?

**Comment by elevatebart** [comment]
Yes either today or tomorrow 

Bart Ledoux
Twitter: @bartledoux
Github, Gitter, Discord: @elevatebart

**Comment by rinobatin** [comment]
Given this example:

```js
/**
* @displayName Best Button
*/
```

Error is thrown from here [globalizeComponent.js](https://github.com/vue-styleguidist/vue-styleguidist/blob/909684f54c0627d96465e92e77f22d14e787b04b/packages/vue-styleguidist/src/utils/globalizeComponent.js#L15) because "Best Button" is not valid component name. 

```
if (configComponent) {
  Vue.component(displayName, configComponent)
}
```
