### ISSUE TITLE
Windows line ending in styleguidist.js causing build error in version 1.2.10

### ISSUE THREAD

**Issue by AlexQwerty** [vue-styleguidist/vue-styleguidist#36]
In vue-styleguidist/bin/styleguidist.js, the first line has a Windows line ending.  Need to change format of file to have Unix line endings. (error found in MacOS Sierra)

**Comment by paulgv** [comment]
Having the same issue, it's the same problem that was previously reported here: https://github.com/vue-styleguidist/vue-styleguidist/issues/1

Here's the error message when trying to build the Styleguide:

```
yarn run v1.2.0
$ vue-styleguidist build
env: node\r: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by rafaesc** [comment]
Hi,

Ok, I've published the fix under v1.2.11.
Please try it and let me know if it works.

**Comment by paulgv** [comment]
Issue is fixed in v1.2.11 :) thanks!

**Comment by rafaesc** [comment]
Thank all :)

**Comment by graemetait** [comment]
Hmm, has this crept back in?  I'm on 1.3.2 and have this issue.
