### ISSUE TITLE
Parse method fail when $emit event is passed via a variable

### ISSUE THREAD

**Issue by bpeab** [vue-styleguidist/vue-styleguidist#363]
**Current behavior**

We are using `vue-docgen-api` without `vue-styleguidist` and it's working correctly in almost every use case. Recently, we came across the following `TypeError: Cannot read property 'node' of null` error which is fired with the `parse` method.

**To reproduce**

After some investigation, the problem comes with the following code block:

```js
// ...
created() {
   // ...

  _.each(this.$listeners, (listener, key) => {
      this.marker.addListener(key, () => {
        this.$emit(key, listener);
      });
    });
 
   // ...
}
```

Note that everywhere else, the parse method works perfectly. Now, if we replace `this.$emit(key, listener)` with `this.$emit(key.toString(), listener)` it works. That's weird because I checked the type of `key`, and in either cases, it returns `string`.

**Expected behavior**

The `parse` method should work no matter what the code is (if correctly written, of course) and especially if the component works perfectly as expected.

**Comment by elevatebart** [comment]
Hello @bpeap,

I think I made a mistake in `resolveIdentifier`

In static analysis, I try determining the value of the event identifier by resolving the declaration of the var in the first parameter. 

See [this file](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/src/script-handlers/eventHandler.ts#L50) to understand how.

Unfortunately I forgot to protect when `resolveIdentifier` returns null. 
[This line](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/src/script-handlers/eventHandler.ts#L56) will then fail.

**Comment by elevatebart** [comment]
Feel free to open a PR adding a return if the event variable name cannot be resolved

**Comment by bpeab** [comment]
Hello @elevatebart,

Thanks for you quick response.

Oh I see. I won't have the time today but I'll try to do this tomorrow morning and submit the PR as soon as I've resolved it.
