### ISSUE TITLE
spread operator is causing parsing to skip documentation for block/section

### ISSUE THREAD

**Issue by AlexQwerty** [vue-styleguidist/vue-styleguidist#37]
Using the example below and knowing that this is part of a larger vue.js file... when trying to document the private methods, we find that if any of the methods begin with the spread operator (...), the whole entire block is ignored. Placement does not matter as the method could be in the beginning, the middle or the end.

Example:
```
    // == Methods
    methods: {
      /**
       * Description of method below
       *
       * @public 
       */
      ...mapActions('app', {
        doSomething: true
      }),

      /**
       * Description of method below
       *
       * @public 
       */
      onInputHandle () {
        // this is a method and has code in it
      },
   }
```

**Comment by easherma** [comment]
https://github.com/vue-styleguidist/vue-styleguidist/issues/130

**Comment by elevatebart** [comment]
I think this issue is obsolete, if you find it again, please lo another issue ;) 
Thank you ;)
