### ISSUE TITLE
vue-docgen-api cannot parse component with template functional

### ISSUE THREAD

**Issue by renanbronchart** [vue-styleguidist/vue-styleguidist#377]
**Current behavior**

When launch yarn styleguide command, component functional (<template functional></template>) cause error :
```
Warning: vue-docgen-api cannot parse src/components/Button/Button.vue: SyntaxError: Unexpected token, expected ";"
```

**To reproduce**

I have the vue-styleguidist@3.11.4

**Expected behavior**

I would like template functional is parse by vue-docgen-api

Thank you very much by advance

**Comment by elevatebart** [comment]
Hey @renanbronchart ,

Can you share the code of the component that is returning this Syntax error?

The best of the best would be to
- fork this repo
- add an example of non-working template to the [packages/vue-docgen-api/tests](https://github.com/vue-styleguidist/vue-styleguidist/tree/dev/packages/vue-docgen-api/tests) folder
- write one or two tests
- create a Pull Request from the new repo to this one

In the tests we already are testing for one version of the functional template.
Hope to help you soon ;)

Bart

**Comment by elevatebart** [comment]
This very much looks like the script of the component you are sending to `vue-docgen-api` cannot be parsed by babel because of a `;`. 

Does your Button component run?

**Comment by elevatebart** [comment]
Hello again @renanbronchart, 

Do you still have the issue ?

**Comment by renanbronchart** [comment]
Hello @elevatebart .
Sorry about the wait.

Yes I have still this issue.
This problem appear only when use functional component

**Comment by elevatebart** [comment]
@renanbronchart please set up a quick reproduction repo

**Comment by elevatebart** [comment]
Can you please share the code of your component?

**Comment by elevatebart** [comment]
Hello @renanbronchart, 

I would be happy to give you a hand. Please reach to me on discord.
There are some components here that are functional and working fine.

Bart

P.S.: If your bug still happens on 3.13.5 please reopen this issue after sharing the code for your component.

**Comment by schjetne** [comment]
This still seems to be an issue with certain `<template functional>` Vue components. I'm having the same problem. Here's the entire component that fails:

```vue
<template functional>
  <div
    :class="{
      [$style.root]: true,
      [$style.error]: props.error,
      [$style.focused]: props.focused,
      [$style.hasIcon]: props.icon,
      [$style.disabled]: props.disabled
    }"
    >
    <label
      :class="{
        [$style.label]: true,
        [$style.labelFloating]: props.focused || (typeof props.value !== 'undefined' && props.value !== ''),
        [$style.labelAlwaysFloating]: props.labelAlwaysFloating || props.prefix || props.disabled,
      }"
      :for="props.id"
      >{{ props.label }}</label>
    <div
      :class="$style.inputGroup"
      >
      <SvgIcon
        v-if="props.icon"
        :name="props.icon"
        :class="$style.icon"
        />
      <div
        v-if="props.prefix"
        :class="$style.prefix"
        >{{ props.prefix }}</div>
      <div
        :class="$style.input"
        ><slot/></div>
    </div>
    <div
      :class="$style.errorMessage"
      >{{ props.errorMessage }}</div>
  </div>
</template>

<script>
/**
 * Wrapper for input elements
 */
export default {
  name: 'InputWrapper',
  status: 'ready',
  release: '0.0.1',
  props: {
    /**
     * Should display error?
     */
    error: {
      type: Boolean,
      default: false
    },
    /**
     * True if input label should always be "up there"
     */
    labelAlwaysFloating: {
      type: Boolean,
      default: false
    },
    /**
     * String for label text
     */
    label: {
      type: String,
      required: true
    },
    /**
     * Should the input be focused?
     */
    focused: {
      type: Boolean,
      default: false
    },
    /**
     * Should the input be disabled?
     */
    disabled: {
      type: Boolean,
      default: false
    },
    /**
     * Prefix string for input field
     */
    prefix: String,
    /**
     * Prefix icon for input field
     */
    icon: {
      type: String,
      default: ''
    },
    /**
     * String with relevant error message
     */
    errorMessage: {
      type: String,
      default: ''
    },
    /**
     * Input value
     */
    value: {
      required: true
    },
    /**
     * Input ID
     */
    id: {
      type: [String, Number],
      required: true
    },
  },
}
</script>

<style lang="scss" module>
/* Removed styles as they are irrelevant */
</style>

<docs>
  `` `jsx
  <input-wrapper label="Label" value="–" id="sdf">
    Docs section should have an example that is shown in the documentation.
  </input-wrapper>
  `` `
</docs>
```

This happens when trying to include functional components in [Vue Design System](https://vueds.com/).

**Comment by elevatebart** [comment]
Thanks @schjetne,

I suggested a fix in the linked PR.
I think it will be delivered today.

**Comment by schjetne** [comment]
Wonderful! Thank you!
