### ISSUE TITLE
svg loader

### ISSUE THREAD

**Issue by serzz1990** [vue-styleguidist/vue-styleguidist#38]
I use a vue-svg-loader to connect icon, but it is intercepted by the built-in file-loader and at the output of the base64
```js
{
        test: /\.icon\.svg$/,
        loader: 'vue-svg-loader'
}
```

**Comment by elevatebart** [comment]
Since I use svg loader myself, I believ it works.
Please ping me on vue-land (discord) and I will help you set it up ;)
If you still have the issue, please create another one. the old issues tend to be forgotten too easily.

Cheers
