### ISSUE TITLE
Component is not inheriting theme fontFamily

### ISSUE THREAD

**Issue by feitla** [vue-styleguidist/vue-styleguidist#381]
**Current behavior**

Previewed component is not inheriting theme font-family, and default user agent font is being used instead of the theme font-family

**To reproduce**
https://github.com/feitla/vuecli3
![image](https://user-images.githubusercontent.com/2625677/56447182-9f263b00-62bb-11e9-9acb-a47530e6411b.png)

![Screen Shot 2019-04-19 at 3 05 21 PM](https://user-images.githubusercontent.com/2625677/56447369-b87bb700-62bc-11e9-9ac4-09de92ece6f7.png)

**Expected behavior**
The rendered example/components should use the theme fontFamily "Source Sans Pro", instead of the user agent font "Times"

**Comment by elevatebart** [comment]
Hello @feitla 

Thank you for the two PR, docs are always the hardest to maintain alone.

Regarding your issue:
The showcased components appear in the same way they would on a real website. The `theme` configuration applies to the style guide, the container, not the content. I will update the description in the docs as it is not explained.

To apply a font-family to all components, you can use an external CSS file. 
Use the [require](https://vue-styleguidist.github.io/Configuration.html#require) options.
You won't even need the `theme` configuration anymore. Let me create PR to illustrate what I mean.

Bart
