### ISSUE TITLE
Add support for Yup

### ISSUE THREAD

**Issue by rafaelramalho19** [vue-styleguidist/vue-styleguidist#39]
[Yup offers schema validation for Vue components](https://github.com/jquense/yup). 
Would be great to have it integrated with vue-styleguidist as maybe an extension?

I would be glad to submit a PR adding support for this, but need to check how to make this optional

**Comment by rmartins90** [comment]
Would be awesome to be able to specify `@schema` on props comments specifying a JSON with schema or Yup's describe() object directly.

**Comment by rafaelramalho19** [comment]
Also, should it be added to a new table column called "Schema" or should it merge with the "type" one?

**Comment by rafaesc** [comment]
I just reviewed it, it's interesting the proposal. It would be a nice idea for a pull request.

Lately, I haven't been able to upload an update, on the weekend, I will work with the slot documentation

**Comment by rafaelramalho19** [comment]
Working on this today :)

**Comment by rafaelramalho19** [comment]
@rafaesc @rmartins90 would this approach be reasonable for you guys? 
https://cl.ly/180C240Y1R3q

**Comment by rmartins90** [comment]
Looks good. How are you planning to represent array of objects schema?

**Comment by rafaelramalho19** [comment]
Maybe it should show a "Array(Object)" and a button to open a modal showing detailed information about the object?

**Comment by rafaesc** [comment]
Do you have any demo of how someone can implement it in .vue file, for that he can see that column https://cl.ly/180C240Y1R3q?, it's interesting.

**Comment by rafaelramalho19** [comment]
Not yet @rafaesc, I inspected the elements to make that :P

As soon as I have time I'll do a quick demo

**Comment by rafaesc** [comment]
Don't worry @rafaelramalho19,

Only I wanted to know how it could show in a file .vue

```html
<script>
  import yup from 'yup-vue';

  export default {
    props: {
      propObject: yup.object().shape({
        name: yup.string().required(),
        age: yup.number().required().positive().integer(),
        email: yup.string().email(),
        website: yup.string().url(),
      }),
      propBool: yup.boolean().default(true),
      propFunc: yup.func(),
      propNumber: yup.string().required(),
      propObject: yup.object(),
      propString: yup.string().default('example'),

    }
  }
</script>
```

**Comment by rafaelramalho19** [comment]
@rafaesc I have an example on my fork. It's inside /examples/yup.

Feel free to look at it :D

**Comment by elevatebart** [comment]
I like the idea, we could add an extra layer of validation as a loader on top of the vue-styleguidist.
It would probably be better to intgrate it inside the props.

something like 
```
...props:{
  /**
   * @schema ./schemas/color.js
   */
  color: String,
  /**
   * @schema ./schemas/percentage.js
   */
  percentage: Number
}
```

But I am not sure it should be inside of vsg. I would prefer for it to be a separate loader.
Transforming Yup rules into English would be painful work that could be done in the description.

Thoughts ?

**Comment by blowsie** [comment]
This got closed, was the feature finished of cancelled?

**Comment by rafaelramalho19** [comment]
I closed it because it became stale. I opened this issue 3 years ago 😄

**Comment by blowsie** [comment]
Doesnt answer the question though! implemented or cancelled?
