### ISSUE TITLE
vue-docgen-api cannot parse warning in a typescript project

### ISSUE THREAD

**Issue by dmitriydementor** [vue-styleguidist/vue-styleguidist#394]
**Current behavior**

Project is compiled via webpack correctly, but when I run styleguidist it throws wierd errors. Stacktrace points to line where there is no such code.

> Warning: vue-docgen-api cannot parse resources/assets/js/components/common/Datepicker.vue: SyntaxError: Unexpected token, expected "}" (13:18)

Here is this line in the component:

![image](https://user-images.githubusercontent.com/11924055/56659702-80061f80-66a6-11e9-9ede-bb8f15c00697.png)

**To reproduce**

https://github.com/dmitriydementor/styleguidist-error-example

Check this example repo and run npm run watch to check webpack build and then run npm run styleguide

**Expected behavior**

Building styleguide without errors

**Comment by elevatebart** [comment]
Hey @dmitriydementor 

I believe I found the issue. By default docgen expects your code to be JSX capable. It thinks your `<any>` are HTML tags and fails there parsing. 

Replace `(<any>window)` with `(window as any)` and you should be fine. 
There is 2 issues you have found:

1. The error line the parser gives is wrong, this will be fixed very soon
1. There is no way to disable the JSX capabilities. I will need to add a new option 'nojsx' in the `styleguide.config.js`.

Thank you for posting here,
If you prefer to create the option yourself a PR is most welcome.

Bart

**Comment by dmitriydementor** [comment]
Hey @elevatebart 

I replaced `(<any>window)` with `(window as any)` and it helped. 

But there are more errors are showing. The most frequent is

> SyntaxError: Unterminated JSX contents

I've updated https://github.com/dmitriydementor/styleguidist-error-example with components that cause new errors, maybe it will help you fix the `nojsx` issue.

Also as you can have noticed, most of components take csrfToken from window global object's property which Laravel injecting like this:

`'_token': (window as any).Laravel.csrfToken`

It causes that when I open styleguide server on http://localhost:6060/ it throws 
![image](https://user-images.githubusercontent.com/11924055/56720755-28ba8a80-674c-11e9-8ec4-b69ec89bc326.png)

Maybe you can point how to mock this property only for styleguide?

**Comment by elevatebart** [comment]
If you want to define anything in the global scope, the best is to write it in a new `csrf.js` file:

```js
window.Laravel.csrfToken = 'FAKE_TOKEN';
```

Then require the new file in your styleguide using the [require](https://vue-styleguidist.github.io/Configuration.html#require) option.

Tell me if it helps.


P.S.: The option is going to be called `jsxInComponents` and will be `true` by default.
Just set it to false in your `styleguide.config.js` and you should be fine.

```js
{
jsxInComponents:false
}
```

**Comment by elevatebart** [comment]
https://vue-styleguidist.github.io/Configuration.html#jsxincomponents

**Comment by dmitriydementor** [comment]
@elevatebart Yes `jsxInComponents: false` helped but issue with csrf token is still present

I've created separate file laravel-mock.js

`
console.log('csrf');

window.Laravel.csrfToken = {
    csrfToken: ''
};
`
and required it in styleguide.config.js like this:

`
require: [
        './laravel-mock'
    ],
`
![image](https://user-images.githubusercontent.com/11924055/56807183-c12d3980-6836-11e9-9b35-c62ad5cd7ce2.png)

But error in console didn't gone, also there is no 'csrf' logged in console, so this file maybe is not loaded.

![image](https://user-images.githubusercontent.com/11924055/56808897-4286cb00-683b-11e9-9e4e-0559138871d9.png)

**Comment by elevatebart** [comment]
The `styleguide.config.js` changes are not watched. So if you change anything in styleguide.config.js, make sure to stop styleguidist and restart it.
In order to illustrate my point, I added an example in the examples section. 
You can see what I had in mind. 

Hope it helps

**Comment by dmitriydementor** [comment]
@elevatebart , yes it helped, thanks. Styleguide compiles successfully, but the new error appears in console

![image](https://user-images.githubusercontent.com/11924055/57071160-422a7c00-6ce2-11e9-9554-f62c6726ed19.png)

Here is the Notification adapter code 

``` 
/**
 * import vue instance
 */
import { vm } from '../app'
import * as T from '../interfaces/common/Notification'

/**
 * Notification Class based on vue-toastr plagin:
 * https://github.com/s4l1h/vue-toastr
 * All options which can be used if you create object or call the method:
 * https://github.com/s4l1h/vue-toastr#new-toast-message-with-options
 */
export default class Notification {
    public commonOptions: T.NotificationOptions

    /**
     *
     * @param {any} options
     */
    constructor(options = null) {
        let defaultCommonOptions = {
            clickClose: true,
            timeout: 1500,
            progressbar: true,
            position: 'toast-top-right',
            preventDuplicates: false,
        }

        this.commonOptions = Object.assign(defaultCommonOptions, options)
    }

    /**
     *
     * @param {string} msg
     * @param {object | null} options
     * @return {void}
     */
    public success(msg: string = 'Uw gegevens zijn opgeslagen!', options: object | null = null) {
        let defaultOptions = Object.assign(
            {
                title: 'Success',
                msg: msg,
                type: 'success',
            },
            this.commonOptions
        )

        options = Object.assign(defaultOptions, options)

        vm.$toastr.Add(options)
    }

    /**
     *
     * @param {string} msg
     * @param {object | null} options
     * @return {void}
     */
    public error(msg = 'Wops something went wrong!', options: object | null = null) {
        let defaultOptions = Object.assign(
            {
                title: 'Error',
                msg: msg,
                type: 'error',
            },
            this.commonOptions
        )

        options = Object.assign(defaultOptions, options)
        vm.$toastr.Add(options)
    }

    /**
     *
     * @param {string} msg
     * @param {object | null} options
     * @return {void}
     */
    public warning(msg = 'Are you sure?', options: object | null = null) {
        let defaultOptions = Object.assign(
            {
                title: 'Warning',
                msg: msg,
                type: 'warning',
            },
            this.commonOptions
        )

        options = Object.assign(defaultOptions, options)
        vm.$toastr.Add(options)
    }
}
```

And then in RemovList file this adapter is being imported and created like this:

```
import Notification from '@/adapters/NotificationtAdapter'
const Alert = new Notification()
```

During writing this reply I tried to define alert as a property of component because before it was declared in global scope of component file right after imports. And it worked. So this issue can be closed.
