### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by robcresswell** [vue-styleguidist/vue-styleguidist#400]
Multiple links in the docs refer to `https://vue-styleguidist.github.io/Components.html`, when they should refer to `https://vue-styleguidist.github.io/Examples.html`

For example, the sections documentation https://vue-styleguidist.github.io/Configuration.html#sections has a dead link.

**Comment by elevatebart** [comment]
Good catch thank you!!

Could you write a Pull Request ?

**Comment by robcresswell** [comment]
Sure thing

**Comment by elevatebart** [comment]
I used https://www.brokenlinkcheck.com/ and fixed most of the issues I found. Hope this is all better.
Thank you for reporting it.

**Comment by robcresswell** [comment]
Oh man, thanks! Sorry I didn't have time to do make a PR
