### ISSUE TITLE
"VIEW CODE" doesn't update when page changes

### ISSUE THREAD

**Issue by donaldshen** [vue-styleguidist/vue-styleguidist#404]
**Current behavior**

when people switch page, the "VIEW CODE" block doesn't update

**Expected behavior**

the "VIEW CODE" block should update when page route changes

![Kapture 2019-04-30 at 16 58 15](https://user-images.githubusercontent.com/19591950/56951026-5b5bed00-6b69-11e9-8142-235b2f462e9e.gif)

**Comment by elevatebart** [comment]
Hello @donaldshen 

That's a spikey one you found there.
Can you share your `styleguide.config.js` file and the version you are on ?

Thank you in advance.
Bart

**Comment by donaldshen** [comment]
The whole project: https://github.com/FEMessage/el-data-tree

vue-styleguidist is locked at 3.11.4. Can't figure out why the latest version keeps crashing at the demo page

**Comment by elevatebart** [comment]
I think I 've found the issue here. More news tomorrow

**Comment by elevatebart** [comment]
the easy fix is to use the [simpleEditor](https://vue-styleguidist.github.io/Configuration.html#simpleeditor) flag. Since React Styleguidist is now using prism, It will make everything work better.

I will try fixing it in codemirror.
