### ISSUE TITLE
Failed to execute 'appendChild' on 'Node': This node type does not support this method

### ISSUE THREAD

**Issue by dharmatv** [vue-styleguidist/vue-styleguidist#407]
I integrated Vue-styleguidist with my project I am getting errors when I wrote readme file with single vue file like 

```vue
<template>
  <ac-collection
    ref="ac_collection"
    :url="collection.url"
    :method="collection.method"
    :ac_cursor="{}"
    :params="collection.params"
    :loading_image="collection.loading_image"
    :sort_key="collection.sort_key"
  >
    <template #header>
      <header class="border p-2 mb-2">Ac collection header</header>
    </template>

    <template #body="{ data }">
      <b-row>
        <b-col v-for="item in data" :key="item.id" class="ac__item" :lg="6">
          <b-card :title="item.name" class="mb-2">
            <b-card-text>{{ item.body }}</b-card-text>
          </b-card>
        </b-col>
      </b-row>
    </template>

    <template #footer>
      <footer class="border p-2 mt-2">ac collection footer</footer>
    </template>
  </ac-collection>
</template>

<script>
export default {
  name: 'ac-collection',
  components: {
    acCollection
  },
  data() {
    return {
      collection: {
        url: "https://jsonplaceholder.typicode.com/posts/1/comments",
        loading_image:
          "https://loading.io/spinners/dual-ring/lg.dual-ring-loader.gif",
        ac_cursor: {
          postId: 1
        },
        method: "GET",
        params: {
          headers: {
            "Custom-Header": "My custom header"
          }
        },
        sort_key: "name"
      }
    };
  },
  mounted() {
    this.$refs.ac_collection.set_ajax();
    console.log(this.$refs);
  }
};
</script>

<style>
</style>
```
 and styleguide.config.js

```js
module.exports = {
	// webpackConfig: require('./build/webpack.base.config.js'),
    require: [
        './styleguide/scripts.js',
        './styleguide/styles.css',

        // Bootstrap
        './node_modules/bootstrap/dist/css/bootstrap.css',
        './node_modules/bootstrap-vue/dist/bootstrap-vue.css',
    ],
    showUsage: true
};

```

script.js file

```js
import Vue from 'vue'
// import _ from 'lodash';

import BootstrapVue from 'bootstrap-vue'
// import VueCodemirror from 'vue-codemirror'
// import 'vue-awesome/icons'
// import Icon from 'vue-awesome/components/Icon'
// import Multiselect from 'vue-multiselect';
// import VueCoreImageUpload from 'vue-core-image-upload'

// // Flat Picker
// import flatPickr from 'vue-flatpickr-component';
// import 'flatpickr/dist/flatpickr.css';

// import VueTimeago from 'vue-timeago';
// import vueTimeagoEnUs from 'vue-timeago/locales/en-US.json';

// Vuelidate Form validator
import VeeValidate from 'vee-validate';

// Import All appup Components
import * as Appup from '../src/index';

// Import mixins to be used globally
// import {Commons} from '@/mixins/commons'
// Vue.mixin(Commons);

Vue.use(BootstrapVue);
// Vue.use(VueCodemirror);
// Vue.use(flatPickr);
Vue.use(VeeValidate);
// Vue.use(VueTimeago, {
//     name: 'vue-timeago',
//     locale: 'en-US',
//     locales: {
//         'en-US': vueTimeagoEnUs
//     }
// });

// Vue.component('icon', Icon);
// Vue.component('vue-multiselect', Multiselect);
// Vue.component('vue-core-image-upload', VueCoreImageUpload);

// Register Components
for (let compKey in Appup) {
    Vue.component(Appup[compKey].name, Appup[compKey])
  }

// Use Axios as the default $http service for all Ajax requests
// Vue.prototype.$http = require('axios').create({
//     config: {
//         headers: {
//             'Content-Type': 'multipart/form-data'
//         },
//         crossDomain: true
//     }
// });

```

please find out screenshot for errors

https://snag.gy/ENBTZm.jpg

https://snag.gy/ySL1sC.jpg

Please help me anyone

**Comment by elevatebart** [comment]
Hey @dharmatv, Have you tried removing the empty style tag, it could be that it is not well protected inside of vsg.

**Comment by dharmatv** [comment]
hello @elevatebart i tried without style tag again i am getting different errors 

SyntaxError: Missing initializer in const declaration

Please find out below screenshot for errors 

https://snag.gy/hMsfYZ.jpg

**Comment by elevatebart** [comment]
Hello @dharmatv 

Can you copy paste the messages that you get instead of snapshots of errors?
The best is always to create a repo where the error happens and send the link to it

After trying your component out, I think you forgot to import `acCollection`. 
Else, how does it get injected in your component? 

I hope this helps.

Bart

**Comment by dharmatv** [comment]
Errors: 

```
Preview.js?f0fa:67 SyntaxError: Missing initializer in const declaration
    at new Function (<anonymous>)
    at evalInContext (evalInContext.js?f56c:19)
    at Preview.evalInContext (Preview.js?f0fa:243)
    at Preview.executeCode (Preview.js?f0fa:161)
    at Preview.componentDidMount (Preview.js?f0fa:83)
    at commitLifeCycles (react-dom.development.js?61bb:17334)
    at commitAllLifeCycles (react-dom.development.js?61bb:18736)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:199)
    at invokeGuardedCallback (react-dom.development.js?61bb:256)
(anonymous) @ Preview.js?f0fa:67
vue.esm.js?a026:628 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Anonymous>
       <Root>
warn @ vue.esm.js?a026:628
vue.esm.js?a026:9082 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
:6060/favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by dharmatv** [comment]
I import the accollection component in globally at script.js file please check above file.

**Comment by elevatebart** [comment]
Hello @dharmatv 

I did not explain it well, I apologize for it.
Using VueJs, to have a component available in your templates, you can do one of two things, 
 - either register acCollection globally. Which is what you are doing in require.js
 - or import your component locally and add it to the `components` member of your config object like
```js
{
  components:{
    acCollection
  }
}
``` 

In here acCollection is considered a variable or a constant. If it is not declared nor imported, it will be undefined. This means that your register the acCollection to undefined. 

Solution: remove the `components` member of your `acCollection.vue`. If it is already globally registered no need to precise that it is registered locally.

Hope it helps.

**Comment by dharmatv** [comment]
Hello @elevatebart 

i am registering component as globally in script.js file. but again i am getting same errors,

**Comment by dharmatv** [comment]
Hello @elevatebart Thanks for your reply, and sorry for the late response. can you please find out below attachement(.zip) for repo

I don't have time to create new repo in sand box, please don't mind
[styleguide.zip](https://github.com/vue-styleguidist/vue-styleguidist/files/3201902/styleguide.zip)

**Comment by elevatebart** [comment]
Hello @dharmatv 

I created a repo here https://github.com/elevatebart/styleguide-gravatar that reproduces your issue.
I traced it back to react-styleguidist 9.1 and the fact that they stopped loading all components everywhere. Unfortunately react-styleguidist loads components `const my-component$0 = require('my-component')`. The dash seems to break it all.

I will try to remove it in your code in a `fix` branch.

Bart

**Comment by elevatebart** [comment]
If you look at the name field of the gravatar component in the fix branch it does not have a dash anymore instead its name is acGravatar and it works.
I will do a special treatment on components to have this fixed.
In the meantime, you can try removing the dahses.

Bart
