### ISSUE TITLE
Updating past 3.12.0 produces typeerror preview component

### ISSUE THREAD

**Issue by andywd7** [vue-styleguidist/vue-styleguidist#411]
**Current behavior**

When updating my vue-styleguidist devDependency to anything higher than 3.12.0 I get the error below in the browser. 3.12.0 builds fine with no errors. 

TypeError: Cannot read property 'default' of undefined
    in Preview (created by Context.Consumer)
    in PreviewWithComponent (created by Playground)
    in div (created by ParaRenderer)
    in ParaRenderer (created by Styled(Para))
    in Styled(Para) (created by Playground)
    in Playground (created by Examples)
    in article (created by ExamplesRenderer)
    in ExamplesRenderer (created by Styled(Examples))
    in Styled(Examples) (created by Examples)
    in Examples (created by Section)
    in section (created by SectionRenderer)
    in SectionRenderer (created by Styled(Section))
    in Styled(Section) (created by Section)
    in Section (created by Sections)
    in section (created by SectionsRenderer)
    in SectionsRenderer (created by Styled(Sections))
    in Styled(Sections) (created by Sections)
    in Sections (created by StyleGuide)
    in main (created by StyleGuideRenderer)
    in div (created by StyleGuideRenderer)
    in StyleGuideRenderer (created by Styled(StyleGuide))
    in Styled(StyleGuide) (created by StyleGuide)
    in StyleGuide
This may be due to an error in a component you are overriding, or a bug in React Styleguidist.
If you believe this is a bug, please submit an issue.

I've looked through what was released in 3.13.0, the next version, and it seems to be related to the LocallyRegisterComponent change. But I'm not clear how or what needs to be done to fix it?

**To reproduce**

[Download the repo here](https://github.com/andywd7/netace) and build it. Error should present itself when viewed in the browser.

**Expected behavior**

It should build fine with no errors.

**Comment by elevatebart** [comment]
Hello @andywd7, I just cloned your repo, then run `npm ci` then `npm run styleguide` and I do not see your error in the browser.

I am on a Mac with High Sierra, running the build with vscode on node 10.

What are the list of command you suggest I use? 
Can you tell me if you remove node_modules and re-install does it still fail?
What version of `npm` are you using?

**Comment by elevatebart** [comment]
I see that you do not have a `styleguide.config.js`. Therefore, every config is taking the defaults. 
The way we search for components by default is "components" or "Components". On windows, it has a tendency to be very bridle. We can't change it because it would break some mac users configurations. I suggest as a first step, that you add this file back with the following content:

```js
module.exports = {
	components: 'src/components/**/[A-Z]*.vue'
}
```

It helped me build your repo as at first `styleguide:build` was broken.
Tell me if it helps.

**Comment by andywd7** [comment]
Hi @elevatebart,
The `styleguide.config.js` file is in the config folder. You have to `npm run styleguide` to hopefully get the error.

I'm on a Mac with Mojave running with vscode on node v10.15.0. I have tried removing node_modules and package-lock.json. I'm using npm 6.4.1. I will try the process again and get back to you to double check my setup and the error.

Thank you

@andywd7

**Comment by andywd7** [comment]
@elevatebart,

Just to check, did you change the `vue-styleguidist` version to `3.13.0` or `3.13.1`? This is the working repo so I left it as 3.12.0.

I downloaded the repo separately again changed the `vue-styleguidist` version to `3.13.0` did `npm i` and then `npm run styleguide` and still get the same error!?

Thanks

**Comment by andywd7** [comment]
Just noticed you get what looks like the same error in the Section example if you click the [Second file](https://vue-styleguidist.github.io/sections/#/Documentation/Files/Second%20File) item in the side navigation.

**Comment by elevatebart** [comment]
Thank You, Thank You !! 🙏 this helps a lot. I will investigate.

**Comment by elevatebart** [comment]
and the last delivered seems to be [3.13.1](https://www.npmjs.com/package/vue-styleguidist)
