### ISSUE TITLE
Cannot document separate .js files

### ISSUE THREAD

**Issue by struers-mpk** [vue-styleguidist/vue-styleguidist#42]
I am using Vue mixins, plugins etc. which are .js files. I need to document them as well, but it does not work. Trying to add section Mixins to styleguide.config.js 
`  sections: [
    {
      name: "Introduction",
      content: "README.md",
    },
    {
      name: "UI Components",
      components: "src/components/**/[A-Z]*.vue",
    },
    {
      name: "Mixins",
      components: "src/mixins/*.js",
    },`

This ends up with an error:
Failed to compile.
./node_modules/vue-styleguidist/lib/index.js
Module build failed: ReferenceError: message is not defined
    at Array.map (<anonymous>)
    at Array.map (<anonymous>)

Works fine if it is "src/mixins/*.vue". Any suggestions?

**Comment by rafaesc** [comment]
Hi @struers-mpk 

I tried to explain how to add mixins, here:
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Documenting.md#include-mixins
