### ISSUE TITLE
Error: import or require() statements can be added only by editing a Markdown example file

### ISSUE THREAD

**Issue by mtlehtin** [vue-styleguidist/vue-styleguidist#421]
Hi!

I updated vue-styleguidist from 2.1.2 to 3.13.4. After the update requiring json-data for the documentation examples in the markdown does not work. The example below works on 2.1.2 but is broken on 3.13.4. I did not notice any comments related to this in the release-notes.

My markdown looks something like this:

  ```vue
const tableData = require('./tabledata.json')

  <div>
    <my-fancy-table
      :data="tableData" />
  </div>
  ```

**Current behavior**

Does not render the component, but it renders an error:

"Error: import or require() statements can be added only by editing a Markdown example file"

**Expected behavior**

Should render the component with required sample data.

**Comment by elevatebart** [comment]
Have you tried, stopping and restarting styleguidist?
The hot reloading engine might be a little stupid.

This being said, I just added an [example where I test this exact feature](https://github.com/vue-styleguidist/vue-styleguidist/pull/425).
Bad news for both of us, it works.

Would it be possible for you to share a repo where you reproduce this issue?
I would as well love to know what version of Node you are running and what OS you are using. 
Thank you in advance

**Comment by jangarcia** [comment]
I have the same problem since updating to 3.11.0, which contains an update of the react-styleguidist dependency to 9.0.4. Our problem seems to be related to [this issue (https://github.com/styleguidist/react-styleguidist/issues/1278), and the root cause seems to be [this npm bug](https://npm.community/t/packages-with-peerdependencies-are-incorrectly-hoisted/4794), see [this comment](https://github.com/webpack/webpack/issues/8656#issuecomment-456713191). In short, the npm bug results in a wrongly hoisted acorn peer dependency. There seem to be some workarounds that are mentioned in the links and that you may want to try out, involving manually installing a specific acorn version in the root package.json or simply using yarn instead of npm.

**Comment by elevatebart** [comment]
I believe if you delete your package-lock.json and you node_modules folder, then re-install the whole thing can fix it.

**Comment by mtlehtin** [comment]
Hi! Thanks for the answers. I tried these:

- deleted package-lock.json and re-install
- updated eslint and jest which were using older acorn version
- updated acorn@6.1.1 to my package.json

package-lock and node_modules deleted in each case. None of these helped. The problem still exists.

My project is based on [VueDS.com](https://vueds.com/) boilerplate-project.

Original:
```bash
+-- eslint@4.19.1
| `-- espree@3.5.4
|   +-- acorn@5.7.3
|   `-- acorn-jsx@3.0.1
|     `-- acorn@3.3.0
`-- jest@23.6.0
  `-- jest-cli@23.6.0
    `-- jest-environment-jsdom@23.4.0
      `-- jsdom@11.12.0
        +-- acorn@5.7.3  deduped
        `-- acorn-globals@4.3.0
          `-- acorn@6.0.2
```

After jest and eslint update:
```bash
+-- eslint@5.16.0
| `-- espree@5.0.1
|   `-- acorn@6.1.1
`-- jest@24.8.0
  `-- jest-cli@24.8.0
    `-- jest-config@24.8.0
      `-- jest-environment-jsdom@24.8.0
        `-- jsdom@11.12.0
          +-- acorn@5.7.3
          `-- acorn-globals@4.3.2
            `-- acorn@6.1.1
```

After acorn@6.1.1 update:
```bash
+-- acorn@6.1.1
+-- eslint@4.19.1
| `-- espree@3.5.4
|   +-- acorn@5.7.3
|   `-- acorn-jsx@3.0.1
|     `-- acorn@3.3.0
+-- jest@23.6.0
| `-- jest-cli@23.6.0
|   `-- jest-environment-jsdom@23.4.0
|     `-- jsdom@11.12.0
|       +-- acorn@5.7.3
|       `-- acorn-globals@4.3.2
|         `-- acorn@6.1.1  deduped
+-- vue-styleguidist@3.13.5
| +-- acorn@6.1.1  deduped
| +-- buble@0.19.7
| | `-- acorn@6.1.1
| +-- react-styleguidist@9.1.2
| | `-- acorn@6.1.1
| `-- vue-docgen-api@3.13.5
|   `-- pug@2.0.3
|     +-- pug-code-gen@2.0.1
|     | `-- with@5.1.1
|     |   +-- acorn@3.3.0
|     |   `-- acorn-globals@3.1.0
|     |     `-- acorn@4.0.13
|     `-- pug-lexer@4.0.0
|       `-- is-expression@3.0.0
|         `-- acorn@4.0.13
+-- webpack@4.32.2
| `-- acorn@6.1.1  deduped
`-- webpack-bundle-analyzer@3.3.2
  `-- acorn@6.1.1
```

**Comment by elevatebart** [comment]
Would you mind sharing your package.json?

Bart Ledoux
Twitter: @bartledoux
Github, Gitter, Discord: @elevatebart

**Comment by RyanHavoc** [comment]
I also have the exact same issue. Anything after version 3.10.2.

**Comment by elevatebart** [comment]
@RyanHavoc Would you mind setting up a minimum reproduction repo and put the link here.
That would help a lot fixing the issue.

Bart

**Comment by RyanHavoc** [comment]
@elevatebart Sure. I've created this: https://github.com/RyanHavoc/vue-sg

Note the example in the cookbook for accessing components in markdown files: https://vue-styleguidist.github.io/docs/Cookbook.html#how-to-hide-some-components-in-style-guide-but-make-them-available-in-examples

I see this: 
![image](https://user-images.githubusercontent.com/824169/58279520-861b1900-7d96-11e9-8405-c4a3d2a607fe.png)

If I remove the `Vue` require I get the error everyones talking about here.

![image](https://user-images.githubusercontent.com/824169/58279608-be225c00-7d96-11e9-9b5c-7b3b8537bbf5.png)

**Comment by elevatebart** [comment]
I found the issue and it was easy to fix ;)
Thank you @RyanHavoc for setting up the repro

**Comment by RyanHavoc** [comment]
@elevatebart Great! When will the fix be released?

**Comment by RyanHavoc** [comment]
@elevatebart Hmm... tried updating the file you changed locally for me and now I get this error on the command line when trying to start the styleguide:

![image](https://user-images.githubusercontent.com/824169/58283278-ccc14100-7d9f-11e9-8a3f-96a0b7bb8e9d.png)

Same repo...

**Comment by elevatebart** [comment]
This is to be expected. From the ReadMe file, AppButton.vue can't be found.

You could replace it by `require('./AppButton.vue').default`.

According to the [doc](https://vue-styleguidist.github.io/docs/Components.html#loading-and-exposing-components), all components are loaded by default unless you use the [magic option to only load the local one](https://vue-styleguidist.github.io/Configuration.html#locallyregistercomponents).

**Comment by elevatebart** [comment]
This

```js
const Vue = require('vue').default
const AppButton = require('AppButton').default
Vue.component('AppButton', Button)

<Card>
  <AppButton />
</Card>
```

becomes this 

```js
const AppButton = require('./AppButton').default
Vue.component('AppButton', AppButton)

<Card>
  <AppButton />
</Card>
```

should be this

```js
<Card>
  <AppButton />
</Card>
```

**Comment by RyanHavoc** [comment]
This is in opposition to the documentation though? 

https://vue-styleguidist.github.io/docs/Cookbook.html#how-to-hide-some-components-in-style-guide-but-make-them-available-in-examples

And If I just have:

```
<Card>
  <AppButton />
</Card>
```

I the readme, the button doesn't render:

![image](https://user-images.githubusercontent.com/824169/58284876-82da5a00-7da3-11e9-8599-320073e5fa3f.png)

**Comment by elevatebart** [comment]
You are absolutely right I need to update this recipe of the cookbook.
Did step 2 make it work?

**Comment by RyanHavoc** [comment]
@elevatebart I'm afraid not. This is what I see:

![image](https://user-images.githubusercontent.com/824169/58285031-e1073d00-7da3-11e9-84f6-ff44a183fab2.png)

![image](https://user-images.githubusercontent.com/824169/58285061-f11f1c80-7da3-11e9-8fa4-275aef5ed6bc.png)

![image](https://user-images.githubusercontent.com/824169/58285090-ff6d3880-7da3-11e9-804e-b978ef67a1f2.png)

![image](https://user-images.githubusercontent.com/824169/58285159-1c097080-7da4-11e9-926a-6d72c14f5383.png)

![image](https://user-images.githubusercontent.com/824169/58285208-2e83aa00-7da4-11e9-8e8a-c66d70025c14.png)

**Comment by elevatebart** [comment]
Good point, I forgot about the hiding of components.

**Comment by elevatebart** [comment]
I created a new PR for it:

https://github.com/vue-styleguidist/vue-styleguidist/pull/428

**Comment by RyanHavoc** [comment]
Great. Thanks for you time on this. Any idea when this will be merged and available as a new version?

**Comment by elevatebart** [comment]
Tonite is bae’s b-day so probably tomorrow 

Bart Ledoux
Twitter: @bartledoux
Github, Gitter, Discord: @elevatebart

**Comment by mtlehtin** [comment]
Nice! Thank you guys!

**Comment by RyanHavoc** [comment]
@elevatebart What timezone are you in? Just wondering if there's an ETA on the merge.

**Comment by elevatebart** [comment]
Chicago is CT, merge is incomming
