### ISSUE TITLE
slot detection breaks with v-else

### ISSUE THREAD

**Issue by donaldshen** [vue-styleguidist/vue-styleguidist#430]
**Current behavior**
```
<!-- @slot whatever -->
<slot name="foo" v-else></slot>
<!-- some code  -->
<!-- @slot still doesn't work -->
<template v-else><slot name="bar"></slot></template>
```
neither foo nor bar slots being shown in the style guide. seams like @slot cannot work under any v-else block

**Expected behavior**
For a scoped slot to work under v-else

**Comment by donaldshen** [comment]
the same as #322

**Comment by elevatebart** [comment]
Hello @donaldshen, I updated the vocabulary you used as it does not respect the Code of Conduct.

**Comment by elevatebart** [comment]
I will investigate this afternoon

**Comment by elevatebart** [comment]
I believe updating the parser of vue-docgen-api with vue3 solved this issue. Can you confirm?
If not, please feel free to re-open.
