### ISSUE TITLE
Gracefully catch errors in the Preview.js component

### ISSUE THREAD

**Issue by dhruvkb** [vue-styleguidist/vue-styleguidist#435]
When a use makes a syntax error in CodeMirror, Preview.js breaks down and gives a full-page error message rendering the whole page unusable.
![image](https://user-images.githubusercontent.com/16580576/58512483-d214f600-81ba-11e9-8b5c-2f8b5b92d8bf.png)

The same action performed in React Styleguidist results in the following output.
![image](https://user-images.githubusercontent.com/16580576/58512366-924e0e80-81ba-11e9-8f8e-458c6a0c0c1f.png)

The React styleguide allows users to rectify their error and even if not, go through the rest of the styleguide without any major hassle. The Vue styleguide must be reloaded and thus the user loses their state in the process.

**Comment by elevatebart** [comment]
Overall, styleguidist is using react-styleguidist engine and should not break in the way you describe.

Can you try again in the last version and try isolating a case that would make it break?

Maybe with the same `Push Me` button component?

**Comment by dhruvkb** [comment]
The output I showed was with the the latest version of Vue CLI and Vue Styleguidist in a fresh project. You can even see the same behaviour at https://vue-styleguidist.github.io/basic/ and compare it with the behaviour at https://react-styleguidist.js.org/examples/basic/.

**Comment by elevatebart** [comment]
I am wondering what you are seeing? Maybe you could make a video for me or a giphy
![cap](https://user-images.githubusercontent.com/5592465/58591364-b72e9a00-822b-11e9-8126-7c427ee702c8.gif)

**Comment by elevatebart** [comment]
I just figured it out this invalid char was a 0... I will try fixing it.
