### ISSUE TITLE
Components aren't showing up when they use require statements

### ISSUE THREAD

**Issue by JessicaSachs** [vue-styleguidist/vue-styleguidist#436]
**Current behavior**

When a component uses any require statement in its `script` block, the code is executed, but the component description or Preview is never rendered in Styleguidist.

**To reproduce**
Create a component that requires a file, instead of imports it.

https://github.com/JessicaSachs/vsg-import-issue/blob/master/src/components/ExternalRequire.vue

**Expected behavior**

The component should appear in styleguidist.

**Comment by JessicaSachs** [comment]
Cross checking with my Prod styleguidist deploy, all of our components that use require statements in their script blocks are broken.

I'm going to keep going back in VSG versions until I find one where this isn't broken.

**Comment by elevatebart** [comment]
found the bug
