### ISSUE TITLE
devServer.port from webpack.config conflicts with sockjs

### ISSUE THREAD

**Issue by patric-eberle** [vue-styleguidist/vue-styleguidist#452]
**Current behavior**

I import my `webpack.config.js` into the `styleguide.config.js`. The same webpack configuration is also used to run Vue in dev mode. The configuration sets the `devServer.port` to `8080` (or, depending on projects, to an other port). When opening the vue-styleguidist in the browser with this configuration, requests get blocked by CORS policy when made to `localhost:8080/sockjs-node` from port `localhost:6060`. I think the requests are made by vue-styleguidist, because we don't use `sockjs`.

![Bildschirmfoto 2019-06-10 um 10 33 16](https://user-images.githubusercontent.com/10571945/59183089-950e1380-8b6b-11e9-8f33-79e7697604fe.png)

**To reproduce**

You can use the following branch to test this: https://github.com/valantic/vue-template/tree/feature/4.0

Since I found a workaround on our side for this, you need to change `const devPort = hasStyleguide ? 6060 : 8080;` in `webpack.config.js` to `const devPort = 8080` to see the described issue.

Note: we don't use `vue-cli`!

**Expected behavior**

localhost ports are handled correctly by vue-styleguidist when importing a webpack.config.js with devServer config, so that requests from vue-styleguidist code does not cause CORS policy errors.

**Comment by patric-eberle** [comment]
Arg... I just realized, that I had an additional `http-server` running in the background, which seems to have caused the `404`. But without it I still get a `net::ERR_CONNECTION_REFUSED` error based on the same configuration issue.

![new-error](https://user-images.githubusercontent.com/10571945/59184737-0a2f1800-8b6f-11e9-8c45-72cc951db082.png)

**Comment by elevatebart** [comment]
Did you know that using the [serverPort](https://vue-styleguidist.github.io/Configuration.html#serverport) option, you could change the port in use? We purposely decided not to resolve the port as of now to be able to keep one window open and to avoid forgetting to kill it an have 4 styleguidist running at once. 

We (react-styleguidist) might revisit this decision though. Just not in major version 3.
Thank you for sharing.
Bart

**Comment by patric-eberle** [comment]
OK, that's fine with me. It's not a critical blocker anyway.
