### ISSUE TITLE
Event description can be lost if the same event is emitted more than once in the source

### ISSUE THREAD

**Issue by yellowsunday** [vue-styleguidist/vue-styleguidist#459]
**Current behavior**

If your source code calls $emit with the same event name multiple times, the event description in earlier comments will be replaced by the comment for later $emit calls. If the later comment contains a new description this would be good, but the problem is if there is no comment, then an empty description is used.

**To reproduce**

Very simply:

```
methods: {
    doSomething () {
        /** 
         *  Description of event
         * @property {boolean} event payload description
         */
        this.$emit("something", true);       
        this.$emit("something", true);
    }
}
```

**Expected behavior**

The description in the first comment should be preserved and included in the final docs. Instead it is cleared (because the second $emit has no comment/description) - [here in the code](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/src/script-handlers/eventHandler.ts#L93).

In contrast, the property in the description *is* preserved and appears in the docs, which looks correct.

Thanks!

**Comment by elevatebart** [comment]
Should be fixed soon.

**Comment by yellowsunday** [comment]
thank you!
