### ISSUE TITLE
TypeScript casting in prop types should be ignored

### ISSUE THREAD

**Issue by ffxsam** [vue-styleguidist/vue-styleguidist#465]
**Current behavior**

```ts
props: {
  blockData: {
    type: Array,
    default: () => [],
  } as PropOptions<SocialNetwork[]>,
}
```

Styleguidist generates this for the docs:

![image](https://user-images.githubusercontent.com/12532733/59708239-f4060500-91c9-11e9-90c0-48e223b9c2e6.png)

**Expected behavior**

It should ignore TypeScript annotations after the curly braces. Unfortunately, in Vue 2.6+ with TypeScript, array prop types are broken, and if you don't include the `as` typecast, it breaks type-checking in the component.

**Comment by ffxsam** [comment]
Possibly related to #413

**Comment by elevatebart** [comment]
@ffxsam What would be the ideal result of the parsing of this Prop? 
`SocialNetwork[]`

**Comment by ffxsam** [comment]
@elevatebart Yep, exactly.  There's also this format which works:

```ts
    blockData: {
      type: Array as PropType<SocialNetwork[]>,
      required: true,
    },
```

So it's a bit of a parsing trick there. 😄
