### ISSUE TITLE
Can not import multiple files with same name

### ISSUE THREAD

**Issue by bodograumann** [vue-styleguidist/vue-styleguidist#471]
**Current behavior**

When trying to import two modules with the same file name in a vue sfc example the compiled code is invalid. Error: `SyntaxError: Identifier 'examples$0' has already been declared (4:6)`.

**To reproduce**
I have created a new project with `vue create -b`  and all features disabled here:
https://github.com/bodograumann/vue-styleguidist-import-test

Then I ran `vue add styleguidist` and added a simple example to `AppButton.vue`:

	```vue
	<template>
	  <app-button color="orange">Push Me</app-button>
	</template>
	<script>
	import examples1 from "./examples.js";
	import examples2 from "../examples.js";
	export default {};
	</script>
	```

**Expected behavior**
Both imports should be usable.

**Comment by elevatebart** [comment]
Ooops ! good catch.

A solution might be to randomize this item: https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-styleguidist/loaders/examples-loader.js#L96

Thank you for reporting it.
