### ISSUE TITLE
method document doesn't work as expected

### ISSUE THREAD

**Issue by flyinglove** [vue-styleguidist/vue-styleguidist#476]
I am trying to document a method in a component, and i did it as below: 
```
/**
         * Search Methods
         * 
         * @param {number} type
         * @public
         */
    search(type = 2){}
```
When I click the related 'props methods, events...', the parameter doesn't show at all.
but when i change my function to `search()`, then it works fine.
It seems like this plugin doesn't support es6's default parameter.

**Comment by elevatebart** [comment]
It is indeed incompatible, docgen can't find the name of the param... 
I will fix by noon CST
