### ISSUE TITLE
Slots are not documented unless component has doc-comments in script part

### ISSUE THREAD

**Issue by docnoe** [vue-styleguidist/vue-styleguidist#48]
If a component does not have any props or public methods/events, the slots are not being evaluated.

```html
<template>
  <div>
    <!-- This slot will not be documented -->
    <slot></slot>
  </div>
</template>

<script>
  export default {
    name: 'i-only-have-a-template'
  }
</script>
```
A workaround is to add empty props, but then an empty table is rendered with just the head

```html
<template>
  <div>
    <!-- This slot WILL be documented -->
    <slot name="foo"></slot>
  </div>
</template>

<script>
  export default {
    name: 'i-only-have-a-template',
    props: {}
  }
</script>

```
Results in something like this:

Prop name | Type | Default | Description
-- | -- | -- | --

Slot | Description
-- | --
foo |  This slot WILL be documented

**Comment by rafaesc** [comment]
Hi @docnoe 

This issue has already fixed, regards

https://github.com/vue-styleguidist/vue-styleguidist/issues/45
