### ISSUE TITLE
All code blocks are interpreted, even when they may be intentionally invalid

### ISSUE THREAD

**Issue by luludan** [vue-styleguidist/vue-styleguidist#484]
**The problem**

Sometimes I need to write an example in markdown that I want in a code block, but I don't want it to be interpreted, it might have a reference which can't be included in the styleguide or may just have some psuedo-code that wont actually compile

**Proposed solution**

I'm not entirely sure on what the perfect solution might be. Perhaps a suffix could be added to the code block's type i.e.

```md
```vue-norender
...some vue code that is not syntactically correct
```

which would still show correct syntax highlighting for vue but would load the interactive playground

**Alternative solutions**

**Additional context**

**Comment by elevatebart** [comment]
Hello @luludan , you can use the [static modifier](https://vue-styleguidist.github.io/docs/Documenting.html#usage-examples-and-readme-files) this way, your code is not going to be rendered.

You can as well find an example of static code rendered in [this example](https://vue-styleguidist.github.io/basic/#counterbutton) just above the counter button.

I hope it helps

**Comment by luludan** [comment]
Ah thank you! I Didn't manage to find that in the docs.

Thanks for your fast response too 👍
