### ISSUE TITLE
Cyclic dependencies are not resolved correctly

### ISSUE THREAD

**Issue by bodograumann** [vue-styleguidist/vue-styleguidist#486]
**Current behavior**

If there is a cyclic dependency between the modules, it can occur, that a component is not loaded correctly.

In particular I have a component library and there are non-cyclic dependencies between the different components resolved via a central `index.js` (or `index.ts`) file.

I encountered this problem in a vue-cli application while using vue-cli-plugin-stylegudist. There I found, that the built version works fine, afaict. Then I reproduced it in a standalone version and here even the built version seems to be having the problem, only that then no error messages are emitted.

**To reproduce**
I created this demo based on the basic example:
https://github.com/bodograumann/vue-styleguidist-cycle-test

The error is:

```
 [Vue warn]: Unknown custom element: <Component2> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
 
 found in
 
 ---> <Component3> at src/components/Component3/Component3.vue
        <Anonymous>
          <Root>
```
The dependencies are:
![Screenshot_20190704-172831](https://user-images.githubusercontent.com/1223583/60678490-f1233980-9e84-11e9-958f-63a42062a136.png)
The given example is the furthest I could reduce the code.

Note that cyclic dependencies between definitions in modules are usually fine when using webpack, because they will only be accessed after instantiation.

This is further illustrated by the fact, that actually using the components in another package by accessing the `index.js` file does not yield any problems. Only the styleguide is defective.

**Expected behavior**

All examples are rendered correctly.

**Comment by elevatebart** [comment]
Hello @bodograumann 

Thank you for your interest for vue-styleguidist. 
I see in you error message that Vue is asking for a `name` field for recursive components. 
Why did you not add it?

After cloning your repo, if the Component2.vue becomes this, styleguidist is back on track...

```vue
<template>
  <div>&lt;Component2 /&gt;</div>
</template>

<script>
import { Component1 } from "../index.js";

export default {
  name: "comp2",
  components: {
    Component1
  }
};
</script>
```

**Comment by elevatebart** [comment]
You can, of course, choose a better `name` for your component ;)

**Comment by bodograumann** [comment]
Curious. I was originally using typescript class-based components and only changed it to plain javascript components for the reproduction, to make it as simple as possible. Originally the component name was taken from the class name. I will continue tracing the problem, as soon as I find the time.

**Comment by bodograumann** [comment]
So I had another look at the reproduction and at your suggestion.

I’m afraid I can not confirm that setting the `name` helps. On the contrary, when I add the name to `Component2` as you suggested, both the example for `Component2` and `Component3` do fail with the same error:

```
[Vue warn]: Unknown custom element: <Component2> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Anonymous>
       <Root> localhost:6060:37:21
[Vue warn]: Unknown custom element: <Component2> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Component3> at src/components/Component3/Component3.vue
       <Anonymous>
         <Root>
```

What you saw can be explained with HMR-magic. If you start up the styleguide devserver for my original reproduction the example for `Component3` does not render. When you then add a name to `Component3`, only that part of the documentation is reloaded. That is the same situation as if there was no `Readme.md` for `Component2`. In that case the error also disappears.

**Comment by elevatebart** [comment]
I come with good news and bad news:
# Bad news
Vue styleguidist has very little control over this issue since it is entirely delegated to the vue-loader. 

# good news
There is [wunderbar explication in the docs](https://vuejs.org/v2/guide/components-edge-cases.html#Circular-References-Between-Components) of how to solve it and you will see that it is incredibly easy.

You simply have to use the `import()` function from webpack and node:

I created a quick PR on the reproduction repo to show you how.

Hope this helps,
Bart

**Comment by bodograumann** [comment]
Thanks for your help. I was of course hoping that there was a general solution in `vue-styleguidist`.

Well, guess I have to workaround the issue every time it occurs.
