### ISSUE TITLE
Can not parse projects with multiple App.vue?

### ISSUE THREAD

**Issue by sangyeol-kim** [vue-styleguidist/vue-styleguidist#491]
The directory for my Vue project is:

```
- src
   - assets
      - sass
      - media
   - common
      - components
         - Button
            - index.vue
         - Button
            - index.vue

   - entry
      - intro
         - components
         - App.vue
      - game
         - components
         - App.vue
```

vue-styleguidist parses the src/common component normally.

But it seems that the src/entry part can not be parsed.

How do I use vue-styleguidist in a structure where there is a separate App.vue like src/entry?

**Comment by elevatebart** [comment]
In vue-styleguidist, all components are registered globally by default.
If you have multiple instances of the same component, in this case app.vue, you should probably use the option [locallyRegisterComponents](https://vue-styleguidist.github.io/Configuration.html#locallyregistercomponents). This way, each component is registered only in its own examples. 
If you want to call other components in your examples, you will have to [register them yourself this way](https://vue-styleguidist.github.io/docs/Cookbook.html#how-to-hide-some-components-in-style-guide-but-make-them-available-in-examples).

**Comment by sangyeol-kim** [comment]
Thanks for the advice! I'll close the issue.
