### ISSUE TITLE
If divide a section, the side bar does not appear.

### ISSUE THREAD

**Issue by sangyeol-kim** [vue-styleguidist/vue-styleguidist#492]
If i write like A Code, a sidebar appears on the left, but if break the section, the sidebar does not appear.

A Code
```
module.exports = {
    components: 'src/components/**/[A-Z]*.vue'
};
```

devide section code
```
module.exports = {
    title: 'Vue Style Guide',
    sections: [
        {
            name: 'src',
            showSidebar: true,
            sections: [
                {
                    name: 'common',
                    showSidebar: true,
                    sections: [
                        {
                            name: 'Button',
                            components: () => ['./src/common/components/Button/**/*.{vue, js}'],
                            exampleMode: 'collapse',
                            usageMode: 'expand',
                            showSidebar: true
                        },
                        {
                            name: 'Chatbot',
                            components: () => ['./src/common/components/Chatbot/**/*.{vue, js}'],
                            exampleMode: 'collapse',
                            usageMode: 'expand',
                            showSidebar: true
                        }
                    ]
                }
            ]
        }
    ]
};
```

![cap](https://user-images.githubusercontent.com/26738287/60785418-e40c9000-a18d-11e9-852d-8c44460f0d34.PNG)

**Comment by elevatebart** [comment]
Hello @sangyeol-kim ! there are a couple of issues in your config:

1 - `showSidebar` is a top-level option only. If forced to false, it will hide the `sideBar` entirely. No need to specify it for each section.
2 - Why do your `components` fields have to be functions? They should be a string but I am curious about your need for having it as a function. Maybe it can be done as an enhancement.
As a consequence of 2, no components show up in your sections and the system defaults to finding the components it can.

**Comment by sangyeol-kim** [comment]
Thank you for answer.

I simply split the section as follows but the slidebar is not displayed.

```
const commonPath = './src/common/components';
const pageEntryPath = './src/page-entry';

module.exports = {
    sections: [
        {
            name: 'SRC',
            sections: [
                {
                    name: 'Common',
                    components: `${commonPath}/**/*.vue`
                },
                {
                    name: 'Page-Entry',
                    components: `${pageEntryPath}/game/**/*.vue`
                }
            ]
        }
    ]
};
```

**Comment by elevatebart** [comment]
Hey @sangyeol-kim , after looking a little in the arcane of react-styleguidist, it turns out that if you have only one top-level section, the menu disappears. 
I believe it's a bug.
In the meantime, just add an extra top-level section and your menu will appear.

**Comment by elevatebart** [comment]
The described behavior is managed right [here](https://github.com/styleguidist/react-styleguidist/blob/d1e528fd71de2edb9850c76cd76bc268e3677398/src/client/rsg-components/TableOfContents/TableOfContents.js#L44) feel free to add an issue.

**Comment by sangyeol-kim** [comment]
@elevatebart right! It seems to be a bug. thank you for your reply.

**Comment by elevatebart** [comment]
@sangyeol-kim you can chime in this PR if you need it merged quickly

**Comment by sangyeol-kim** [comment]
Ok, Thank you @elevatebart
