### ISSUE TITLE
Functional component prop `value` displayed alongside v-model prop, when `@model` used in comment

### ISSUE THREAD

**Issue by river-honer** [vue-styleguidist/vue-styleguidist#493]
**Current behavior**

![s-select-table](https://user-images.githubusercontent.com/41007222/60800927-f8d92b80-a16d-11e9-9252-1dd7123fe574.png)
![s-select-code](https://user-images.githubusercontent.com/41007222/60801140-5f5e4980-a16e-11e9-83ab-dca1fac53ff6.png)

In the table of props, I am getting the `value` prop still, even though I'm using the `@model` tag and the v-model prop is showing.

This is a functional component.

**Expected behavior**

I expect the `v-model` prop to show but the `value` prop to not show.

**Comment by river-honer** [comment]
Solved with this in styleguide.config.js
```
propsParser(filePath, source) {
        const component = vda.parse(filePath)
        // remove second instance of value if v-model
        if (component.props) {
            if (component.props.value && component.props['v-model']) {
                delete component.props.value;
            }
        }
        return component;
    },
```

**Comment by elevatebart** [comment]
Thank you for the report.
Interesting fix you got here ;) 
Hope you will not need it soon.

I should have it repaired by the end of the week.

**Comment by river-honer** [comment]
Thanks for your quick reply. Don't really need it fast at all as my workaround works just fine. But thanks for working on it. Would be interested to start my first pr but we are pretty busy. However I'm liking V-Styleguidist. I wrote a crazy parser for my inline use of attributes, which are over the top.

**Comment by elevatebart** [comment]
I just found the issue. 
It is a combination of both `propHandlers`.
The script `propHandler` detects the `@model` but the template `propHandler` does not.
Template handler then creates a new prop.

Give me a minute.

**Comment by elevatebart** [comment]
fixed ;)

**Comment by river-honer** [comment]
Thank you :)
