### ISSUE TITLE
styleguidePublicPath option seems ignored

### ISSUE THREAD

**Issue by nicooprat** [vue-styleguidist/vue-styleguidist#494]
**Current behavior**

I'm using vue-cli. The [`styleguidePublicPath`](https://github.com/vue-styleguidist/vue-styleguidist/blob/bd5162ab0cc19b7b280410ac0f2805e75e309884/packages/vue-styleguidist/scripts/schemas/config.js#L301) option seems ignored as I can't get Webpack to listen to a specific path.

When running `npm run styleguide`, the console still displays: `Local: http://example.com:6060/` without appending the option. 

I don't even get the same line that vue-cli displays: `Network: http://example.com/`

**To reproduce**

Here's a preview of my config:

```js
module.exports = {
  serverHost: `example.com`,
  styleguidePublicPath: '/styleguide',
  printServerInstructions(config, { isHttps }) {
    console.log(config) // everything looks ok
  },
}
```

**Expected behavior**

I need multiple dev servers running and I'm using different publicPath for each one. I got Vue running to `/v2` for example, but I can't achieve the same with styleguidist. I'm expecting styleguidist to run on `http://example.com/styleguide`.

Is there option that I didn't see or misused? Thanks.

**Comment by elevatebart** [comment]
As seen [here](https://github.com/vue-styleguidist/vue-styleguidist/blob/62b9264735622b3e63191956951ceba43732ddc4/packages/vue-styleguidist/scripts/make-webpack-config.js#L127) the styleguidePublicPath is only used while using command `styleguidist build`.

If you want to have 2 different instances of styleguidist running at the same time at dev time, I suggest that you use 2 different [serverPorts](https://vue-styleguidist.github.io/Configuration.html#serverport)

If this is still not enough for you, you can try to use [dangerouslyUpdateWebpackConfig](https://vue-styleguidist.github.io/Configuration.html#dangerouslyupdatewebpackconfig) to update the standard publicPath at dev time. You would be in unknown territory though.

**Comment by nicooprat** [comment]
Thanks, I also tried this:

```js
  dangerouslyUpdateWebpackConfig(webpackConfig, env) {
    webpackConfig.devServer.public = `example.com/styleguide`
    webpackConfig.devServer.publicPath = '/styleguide'
    webpackConfig.output.publicPath = '/styleguide'
    return webpackConfig
  },
```

Still the same output in the console though, and the styleguide is still unreachable. I'll try using ports but I'm not sure I can.

**Comment by elevatebart** [comment]
This will not change anything in the terminal output but will respond to `http://localhost:6060/styleguide` successfully.

``` js
dangerouslyUpdateWebpackConfig(webpackConfig) {
	webpackConfig.devServer = webpackConfig.devServer || {}
	webpackConfig.devServer.publicPath = '/styleguide'
	webpackConfig.output.publicPath = '/styleguide'
	return webpackConfig
},
```

I might take a minute to update the urls sent back through the terminal. 
You should not need those Urls though.

**Comment by nicooprat** [comment]
Ok, thanks, I'll give it another try once it's merged.
