### ISSUE TITLE
curious about the vue-styleguide custom option.

### ISSUE THREAD

**Issue by sangyeol-kim** [vue-styleguidist/vue-styleguidist#496]
Q1. Can I add an extension name to the left slide bar? For now, simply output the vue component name.

Q2. Can I extract annotations, etc. inside parsed files? If possible, I want to register certain keywords within the component and parse them by keyword.

Thank you.

**Comment by elevatebart** [comment]
Hello @sangyeol-Kim
Q1: you can customize each component but you might have to understand React to do it.
See the customized example

Q2: the docgen api does the extraction of all annotations. If you want to use it directly it is entirely possible.

On a side note, I think that it would be easier for me to answer your questions on discord. My handle is my GitHub userid so I should not be hard to find ;)

I hope it helps

**Comment by sangyeol-kim** [comment]
@elevatebart Thanks for the advice! I'll close the issue.
