### ISSUE TITLE
Doc generation of mixin props

### ISSUE THREAD

**Issue by lancetharper** [vue-styleguidist/vue-styleguidist#5]
I have a mixin that adds props to the component. Is it possible for those props to also be documented with the component they are added to?

**Comment by lancetharper** [comment]
Moving to https://github.com/vue-styleguidist/vue-docgen-api/issues/2

**Comment by rafaesc92** [comment]
I'll add an optional extra setting to import the mixins. Thanks @lancetharper

**Comment by rafaesc92** [comment]
I just updated the documentation to add mixins.

[mixins configuration](https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Configuration.md#mixins)

**Comment by lancetharper** [comment]
Does this work for mixins that aren't global?

**Comment by rafaesc92** [comment]
You can use the mixins in the component and render, but for now, they will not be documented, I have to evaluate how to do it, it could take a little time.
