### ISSUE TITLE
"Copy to clipboard" fails in Chrome

### ISSUE THREAD

**Issue by yellowsunday** [vue-styleguidist/vue-styleguidist#500]
Clicking the "Copy to clipboard" button on the path line fails in Chrome, with an error in the console:

```
Uncaught (in promise) undefined
clipboardCopy	index.js:57
onClick	PathlineRenderer.js:34
callCallback	react-dom.development.js:149
```

It looks like [this issue in react-styleguidist](https://github.com/styleguidist/react-styleguidist/issues/1290), which was fixed by bumping clipboard-copy to v3.

**Comment by elevatebart** [comment]
Thank you for reporting it.
