### ISSUE TITLE
Array/Object props type shown is 'func'

### ISSUE THREAD

**Issue by hagi4u** [vue-styleguidist/vue-styleguidist#51]
Hi, i found some problem.
please see my example code

### 1. Array type, default return is function
```
props: {
...
  /**
    * images
    */
   images: {
      type: Array,
      default: function () {
        return [
          {
            url: 'https://instagram.com',
            image: 'https://placehold.it/300x300',
            text: '텍스트'
          }
        ]
      }
    }
...
}
```

This code is shown usage

Prop name | Type | Default | Description
-- | -- | -- | --
images | func | Function | images

### 2. Array type, default value is array
```
   images: {
      type: Array,
      default: [
        {
          url: 'https://instagram.com',
          image: 'https://placehold.it/300x300',
          text: '텍스트'
        }
      ]
    },
```

This code is shown usage

Prop name | Type | Default | Description
-- | -- | -- | --
images | array | [{"url":"https://instagram.com","image":"https://placehold.it/300x300","text":"텍스트"}] | images

but if i wrote (2) code, has error
```
[Vue warn]: Invalid default value for prop "images": Props with type Object/Array must use a factory function to return the default value.
```

as you known that Props type is Object/Array default value necessary factory function

please check issue
thanks.

**Comment by rafaesc** [comment]
Hi @hagi4u,

Yes, in the next version I will fix it.

**Comment by rafaesc** [comment]
Hi @hagi4u 

You can already update to version 1.3.7,

Regards
