### ISSUE TITLE
"VIEW CODE" doesn't update occasionally when page changes

### ISSUE THREAD

**Issue by donaldshen** [vue-styleguidist/vue-styleguidist#514]
@3.16.3
#404 still happens sometimes. below you can see 'basic' & 'format' section share the same "VIEW CODE"
![bug](https://user-images.githubusercontent.com/19591950/61773861-36a1a980-ae28-11e9-93ac-0e4e6f25a899.gif)

**Comment by elevatebart** [comment]
Hey @donaldshen thank you for sharing,

Do you see anything that those components have in common? 
Do they both have a name field?
Are they examples for the same component?

On my end, I have a hard time reproducing it on the `sections` example

**Comment by donaldshen** [comment]
They are examples for the same component, which is 'count-down', and it has a name field which is 'count-down'

**Comment by donaldshen** [comment]
Those examples are written in markdowns and illustrate how to use some props. e.g.
### basic.md
```vue
<template>
  <count-down :seconds="59" />
</template
```
### format.md
```vue
<template>
  <count-down :seconds="59" :hours="1" format="hh:mm:ss" />
</template
```

**Comment by elevatebart** [comment]
I reproduce !! now to know what the reason is...
