### ISSUE TITLE
VueLoaderPlugin Error

### ISSUE THREAD

**Issue by aaronguernsey** [vue-styleguidist/vue-styleguidist#525]
**Current behavior**

Forgive me if this has been posted before, I didn't find the same issue or one that could solve my problem.

When upgrading vue-cli-plugin-styleguidist above version 3.15.0 the `vue-cli-service styleguidist` command errors out, and I cannot compile the development project.

The exact error looks as such:
```
ERROR  Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.
Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.
```

Thanks in advance. Really digging the project, and I'm still able to proceed at a locked version of 3.15.0 if that helps matters 😄 

**To reproduce**

If using vue-cli-plugin-styleguidist version 3.16.0+ the script `vue-cli-service styleguidist` errors out. I have also tried upgrading all dependencies to the latest versions, and the error still persists.

The modified styleguidist weback config for our project is:
```
// Imports
const path = require('path')
const {
    VueLoaderPlugin
} = require('vue-loader');

// Other configurations...

// Our awesome webpack config
    webpackConfig: {
        resolve: {
            alias: {
                '@': path.join(__dirname, './src/**')
            }
        },
        plugins: [new VueLoaderPlugin()],
        module: {
            rules: [{
                    test: /\.vue$/,
                    exclude: [/node_modules/, path.join(__dirname, './src/assets/fonts')],
                    loader: 'vue-loader',
                },
                {
                    test: /\.js?$/,
                    exclude: [/node_modules/, path.join(__dirname, './src/assets/fonts')],
                    loader: 'babel-loader',
                    query: {
                        cacheDirectory: true,
                        presets: ['react', 'env']
                    }
                },
                {
                    test: /\.pug$/,
                    exclude: [/node_modules/, path.join(__dirname, './src/assets/fonts')],
                    loaders: ['pug-loader']
                },
                {
                    test: /\.(css?|scss)?$/,
                    exclude: [path.join(__dirname, './src/assets/fonts')],
                    loader: 'css-loader!sass-loader'
                },
                {
                    test: /\.(woff(2)?|ttf|eot|otf)(\?v=\d+\.\d+\.\d+)?$/,
                    use: [{
                        loader: 'file-loader'
                    }]
                }
            ]
        }
    }
```

**Expected behavior**

Versions 3.15.0 and below work properly, and the project compiles, hot reloads, and otherwise functions as normal. So, currently, I've locked `vue-cli-plugin-styleguidist` at version `3.15.0` and everything runs as expected.

**Comment by elevatebart** [comment]
Thank you so much! It really means a lot to hear.

A couple of questions first:
- How are you launching styleguidist? `vue-cli-service styleguidist` or plain old `styleguidist serve`
- Did you try removing the `webpackConfig` from the `styleguide.config` entirely? with the vue-cli it is meant to be entirely automated.

I am trying to see where the fail could have been and isolate the commit that broke it for you.
I have made two changes to the plugin:
- [fix(plugin): custom webpack config](https://github.com/vue-styleguidist/vue-styleguidist/commit/2cf491c16c09a610c78b62639107c0502640dd5c#diff-cbfb8406e65783289cdd9ddeb86f719f)
- [docs: document the new styleguidePublicPath option ](https://github.com/vue-styleguidist/vue-styleguidist/commit/18c7efc0bdc9dff7847a4bba6cadc081ee3ed20d#diff-cbfb8406e65783289cdd9ddeb86f719f)

I believe the first one to be the culprit. 

Thank you for your interrest

**Comment by aaronguernsey** [comment]
Thank you for the quick response! 

- I am using `vue-cli-service styleguidist` to launch styleguidist
- I removed the custom `webpackConfig`, but it resulted in an error due in a `vue-loader` error unable to find and compile the correct `.vue` files, which presumably is because the project requires `vue-loader`.

I'm away from my work computer, but I will be sure to check these out tomorrow and see if that resolves the issue.

**Comment by elevatebart** [comment]
Beware of the poor management (by vue-styleguidist) of the cache.
I need to work on that right after I finish fixing hot module reload for the plugin.

**Comment by elevatebart** [comment]
Hey @aaronguernsey 

Could you post the error you had when removing the `webpackConfig` from styleguidist.config.js?
Normaly, the plugin should be taking the `@vue/cli` webpack config. There should not be any need for additional configuration in `styleguide.config.js`

**Comment by aaronguernsey** [comment]
Hey @elevatebart! Thanks for the help so far.

When I upgrade to the latest release (`3.19.0+`), everything works properly without the `webpackConfig`. The same results occur when I lock to version `3.15.0`. Maybe the previous error was a caching issue? 

If I add the `webpackConfig` back, I get the original VueLoader error above. To be clear, we do not have a custom webpack for the `@vue/cli`; we just added a custom webpack config to `styleguide.config.js`. The reason behind this, I cannot remember off the top of my head, unfortunately.

**Comment by elevatebart** [comment]
I see one difference between your config and the standard one: The exclusion of the font folders.
Which would not be needed anymore since you are using the plugin. 
I can tell you that before 3.16.0, the `webpackConfig` in `styleguide.config.js` was simply ignored.

If the styleguide renders without any customization, would you should keep it this way?

Please tell me when you remember the reason for this customization.

Thanks

**Comment by aaronguernsey** [comment]
Hey @elevatebart!

We used the customization for using pug templates, file loader, and excluding fonts. However, it all appears to work fine without the `webpackConfig`. So maybe this can be closed?

Thank you for the help.

**Comment by elevatebart** [comment]
No problem ;)
