### ISSUE TITLE
styleguidePublicPath option overrides webpack's publicPath option

### ISSUE THREAD

**Issue by kgilden** [vue-styleguidist/vue-styleguidist#529]
**Current behavior**

https://github.com/vue-styleguidist/vue-styleguidist/pull/497 broke configurations which did not rely on `styleguidePublicPath`, but instead used webpack's `publicPath` option.

**To reproduce**

Use the following configuration.

```
{
  // NB! Do NOT set styleguidePublicPath 
  webpackConfig: {
    devServer: {
      // ...
      publicPath: '/example/',
    },
  },
}
```

**Expected behavior**

The styleguide should be accessible from `http://example.com/example/`. So `vue-styleguidist` should respect the public path coming form `webpack`, if `styleguidePublicPath` is not set. Or at least there should be a note about this in [the changelog](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/CHANGELOG.md#3160-2019-07-15).

**Comment by elevatebart** [comment]
You are absolutely right, I should fix it right away.
