### ISSUE TITLE
How to mock vuex getters/setters in styleguidist? label:"help wanted"

### ISSUE THREAD

**Issue by natasher** [vue-styleguidist/vue-styleguidist#53]
I wrote a component (vue+vuex) in which I need to mock Vuex methods. The forms are added dynamically and inside styleguidist the getters tries to read from object that doesn't exists yet (undefined). Is there any way to mock/stub Vuex store?

e.g.
`
  computed: {

    ...mapGetters( 'BaseModule', [
      'getCurrentFieldValue'
    ]),

    textFieldValue: {

      get () {
        return this.getCurrentFieldValue( this.fieldName )
      },
      set ( value ) {
        this.setCurrentFieldValue({
          name : this.fieldName,
          value: value,
        })
      }
    }
  },
`

**Comment by rafaesc** [comment]
Hi @natasher,

yes, you can add a store in styleguide.config.js, like this:
https://github.com/vue-styleguidist/vue-styleguidist/blob/v1.3.1/examples/basic/styleguide.config.js

Regards!

**Comment by rafaesc** [comment]
Hi @natasher,

 I just added a new example with vuex, using getters and mutations
https://github.com/vue-styleguidist/vue-styleguidist/tree/master/examples/vuex

I hope that it helps you, regards
