### ISSUE TITLE
Can you make working example of using vuex state variable in component in examples/basic ?

### ISSUE THREAD

**Issue by struers-mfr** [vue-styleguidist/vue-styleguidist#54]
Hello,
I fork this repo and run it in dev mode, because I want to get working example of how to use vuex state variables used in vue components in styleguide, but the example of vuex store that is in the repo is never used in any component.
So I try to add it to one component (here you can find the fork https://github.com/struers-mfr/vue-styleguidist) and I struggle with it, the value that is shown in vuex bindings in vue inspector is "(error during evaluation)" and in console i get the message "Uncaught TypeError: Cannot read property 'getters' of undefined"
Can you point what is wrong in my attempt, or can you add working example of usage in vue-styleguidist examples?

**Comment by rafaesc** [comment]
Hi @struers-mfr,

I reviewed your fork, and in this part you forgot import the getters function
https://github.com/struers-mfr/vue-styleguidist/blob/master/examples/basic/src/store/index.js#L3

But I just added a new example with vuex, using getters and mutations
https://github.com/vue-styleguidist/vue-styleguidist/tree/master/examples/vuex

Regards
