### ISSUE TITLE
Sidebar is empty and filter isn't working?

### ISSUE THREAD

**Issue by puyt** [vue-styleguidist/vue-styleguidist#561]
**Current behavior**

After installing this plugin and running the build as explained in the docs my sidebar is empty and the filter isn't working.

The sidebar is also empty on the provided exampes.

**To reproduce**

See https://vue-styleguidist.github.io/basic/

![Screenshot from 2019-08-16 21-57-26](https://user-images.githubusercontent.com/3668615/63194770-28365e80-c071-11e9-9e38-31954120e793.png)

**Expected behavior**

Sidebar should be filled with components and the search bar should filter the list.

**Comment by elevatebart** [comment]
Thank you, I am going to fix it right away

**Comment by elevatebart** [comment]
It is a bug I introduced in react-styleguidist 9.1.14... sry

**Comment by puyt** [comment]
Thanks for fixing it :+1:
