### ISSUE TITLE
Component documentation example not working on Function

### ISSUE THREAD

**Issue by patric-eberle** [vue-styleguidist/vue-styleguidist#57]
Using vue-styleguidist@1.3.5 and vue@2.5.2

I copied your example for the component documentation (https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Documenting.md). But the converter seems to break, when it comes up to the default for the function prop (onClick). It looks like `unquote(string)` is expecting a string but gets a `Function`.

```
function unquote(string) {
  return string.replace(/^['"]|['"]$/g, ''); // => Cannot read property 'replace' of undefined
}
```

**Comment by rafaesc** [comment]
Hi @patric-eberle,

I don't really sure to understand, can you share a repository with the problem?

Thanks!

**Comment by Knovour** [comment]
Same problem at 1.3.7

if I set `default` as function in props, the `unquote` function will receive undefined

eg: 
```js
label: {
	type: Array,
	default: () => []
}
```

This will work
```js
label: {
	type: Array,
	default: []
}
```

**Comment by patric-eberle** [comment]
@rafaesc like @Knovour  I also tested with the latest release and got the same result.

I've set up a branch, where you can test the issue yourself: https://github.com/patric-eberle/vue-playground/tree/feature/vue-styleguidist

In the component `BrokenDocumentation.vue` just uncomment the `default` on `corruptDefinition` to see the issue.

One place to start to investigate could probably be the following:

```js
renderDefault(prop) {
  // ...
  if (defaultValueBlacklist.indexOf(prop.defaultValue.value) > -1) {} // This test looks invalid to me. The defaultValueBlacklist contains strings, but "undefined" is no string
  // ...
}
```

**Comment by rafaesc** [comment]
Hi there,

this issue is similar to this:
https://github.com/vue-styleguidist/vue-styleguidist/issues/60

You can already update to version 1.3.8

Regards,
