### ISSUE TITLE
In live examples, support "deep" selectors in scoped styles

### ISSUE THREAD

**Issue by yellowsunday** [vue-styleguidist/vue-styleguidist#578]
**The problem**

The in-browser documentation examples don't support the special [deep selectors](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors) ("::v-deep", ">>>" or "/deep/") in their scoped styles. Instead, all the parts of the selector string are scoped.

It'd be nice to be able to show readers of the documentation how to apply custom styling to DOM elements generated by the component, by using these selectors. It'd also be useful as a way of testing that the supported overrides work in the live example.

It's not a scenario that is very common, as normally you'd want to keep component implementation details internal, but it does happen occasionally - e.g. in a Table component that allows users of the component to specify custom classes for the TR/TD elements it generates so they can style them.

**Proposed solution**

Supporting one or more of the 'deep' syntaxes, to allow the documentation examples to work.

From quickly hacking in the vue-inbrowser-compiler's [styleScoper](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-inbrowser-compiler/src/styleScoper.ts), this seemed to work, though I don't fully understand all of that function's code:

```
        // if non-rule delimiter
        if (selector.match(/^\s*(@media|@keyframes|to|from|@font-face)/)) {
            return selector + after;
        }
        // new code:
        // don't scope the part of the selector after ::v-deep
        if (selector.match(/::v-deep/)) {
            var [fullMatch, group1, group2] = selector.match("(.*)::v-deep(.*)");
            selector = group1;
            after = group2 + after;
        }
        // rest of existing function...
```

Thanks for your work on this library!

**Comment by elevatebart** [comment]
Hey @yellowsunday,

You are halfway done ! This is a great solution.
Just 2 little steps to a mergeable Pull Request

1. Clone(Fork) the current repo
1. Change the styleScoper function
1. If you are nice, add a quick unit test describing the use case you added

Thank you in advance,
Bart
