### ISSUE TITLE
How to document event and slot

### ISSUE THREAD

**Issue by mgesmundo** [vue-styleguidist/vue-styleguidist#586]
Hello,
I'm so happy to use this awesome project (v 3.23.1) to document my own. I need to add a comment like this:

```js
 /**
  * Computing event
  * 
  * @event computing
  * @type { boolean }
  * @property { boolean } status Computing status
  */
function () {
  // some function that not has a line code with this.$emit
}
```

to a function that not explicitly call $emit.

Another problem is how to document a slot like this:

```js
  /**
   * @slot Some comment
   */
  render () {
    return this.$scopedSlots.default({
      ready: this.ready,
      computing: this.computing,
      compute: this.compute
    })
  }
```

Thank you for any suggestion.
All the best!

**Comment by elevatebart** [comment]
Hello @mgesmundo 

You can find [some docs](https://vue-styleguidist.github.io/docs/Documenting.html) on the website about how to accomplish this. But it is missing how to document slots in render functions. 

If you want to learn more since all those cases are tested, you should look in the test cases linked [here](https://github.com/vue-styleguidist/vue-styleguidist/tree/dev/packages/vue-docgen-api/tests/components).

Overall, you touched the big breaking change of vsg 3.

**Comment by mgesmundo** [comment]
Hello @elevatebart 
thank you for your answer. I read all docs without a solution. I will try to investigate to find a solution and I will reopen this if I will find one.
Thank you.

**Comment by elevatebart** [comment]
Hey @mgesmundo it is always very sad to see someone give up :-(.

Would you be open to creating a repo where I can reproduce your use case?

Thank you in advance.

**Comment by mgesmundo** [comment]
Hello @elevatebart,

using the default demo button created using `vue add styleguidist`, the event `updating` is missing into documentation:

```js
methods: {
  /** Triggered when button is clicked
   * @event click
   * @type {Event}
   */
  /** Event for Alligator's example
   * @event gator
   * @type {Event}
   */
  handleClick(e) {
    this.$emit('click', e)
    this.$emit('gator', e)
  },
  /** Some comment for the event (lost by Styleguidist)
   * @event updating
   * @type {Boolean}
   */
  onUpdate () {
    // some external method, for example from a method
    // (bind to the Vue instance) provided by a standard js class
  }
}
```

For the `slot` into a renderless component use this:

```vue
<script>
/**
 * Some awesome component.
 */
export default {
  name: 'Demo',
  data () {
    return {
      compiling: false
    }
  },
  methods: {
    compile () {
      // some task
    }
  },
  render () {
    /**
     * This comment is missing into the documentation.
     * How I can expose compiling, and compile?
     * @slot
     */
    return this.$scopedSlots.default({
      compiling: this.compiling,
      compile: this.compile
    })
  }
}
</script>
```

**Comment by elevatebart** [comment]
Let's start with the events,
Have you tried this?

```js
methods: {
  handleClick(e) {
    /** Triggered when button is clicked
     * @event click
     * @type {Event}
     */
    this.$emit('click', e)

    /** Event for Alligator's example
     * @event gator
     * @type {Event}
     */
    this.$emit('gator', e)
  }
}
```

I guess I should probably clarify the documentation a little about that.
In order for docgen to see your documented events, you have to document them when they are triggered.

**Comment by mgesmundo** [comment]
The documentation is clear: the missing event is `updating `

```js
  /** Some comment for the event (lost by Styleguidist)
   * @event updating
   * @type {Boolean}
   */
  onUpdate () {
    // some external method, for example from a method
    // (bind to the Vue instance) provided by a standard js class
  }
```

Anyway: yes I usually use the syntax you provided. The previous code i pasted is automatically generated using `vue add styleguidist` and works fine in any case.

**Comment by elevatebart** [comment]
Oh !!! you mean that the event is not explicitly called in the onUpdate function but implicitly if update is called.
Am I understanding it correctly?

**Comment by elevatebart** [comment]
For scoped slots in the render function a couple of tests were missing.

I added a few items in docgen so that your example can be used properly

**Comment by elevatebart** [comment]
See the attached PR

**Comment by mgesmundo** [comment]
Great! 🥇

**Comment by mgesmundo** [comment]
> Oh !!! you mean that the event is not explicitly called in the onUpdate function but implicitly if update is called.

Yes. The "classic" code `this.$emit('update', value)` is not present into the `onUpdate` function body.

**Comment by elevatebart** [comment]
In the parent component, would you still do the following?

```html
<documentedComponent @update="functionCalledWhenUpdateStarts()"/>
```

**Comment by mgesmundo** [comment]
Yes

**Comment by elevatebart** [comment]
Hey @mgesmundo ,

Sorry for the long wait, I am finally unstacking all issues here.

In the code shared below, it looks that you are commenting a method. 
The comment block is attached to the method. 

```js
/** Some comment for the event (lost by Styleguidist)
   * @event updating
   * @type {Boolean}
   */
  onUpdate () {
    // some external method, for example from a method
    // (bind to the Vue instance) provided by a standard js class
  }
```

Would you be open to instead have an `@fires` tag? 
That tag would refer to the event that would be defined somewhere else, probably at component level. 

`Update` is fired by the documented component and is completely implicit? If not what triggers the firing of the event?
Given the name of the method, it seems like the current component/method listens to this event instead of firing it:

```vue
<MyComponent @update="onUpdate()" />
```

I want to understand your use case, before I do any changes to the code.

**Comment by mgesmundo** [comment]
Hello Barthélémy,
I apologize for the long wait: I completed a full-time urgent work for my boss!
Well: for the `@fires` tag I think that it is a good solution.
The `update` event is fired by the documented component (method imported from another file).
Thank you and sorry again!

**Comment by elevatebart** [comment]
I was thinking something like this, but it completely misses the arguments passed to the event.

```js
 /** 
   * Some comment for the event (lost by Styleguidist)
   * @fires updating
   * @arg { String } name updated property name
   * @arg newValue new value that we want to update
   */
  onUpdate (name, newValue) {
    // some external method, for example from a method
    // (bind to the Vue instance) provided by a standard js class
  }
```

How would you think we should document arguments?

```js
 /** 
   * Some comment for the function
   * @fires updating
   * @arg { String } name updated property name
   * @arg newValue new value that we want to update
   */
 /** 
   * Some comment for the event just after the function block
   *
   * @event updating
   * @property { String } - the first prop given by the event
   */
  onUpdate (name, newValue) {
    // some external method, for example from a method
    // (bind to the Vue instance) provided by a standard js class
  }
```

I was thinking something like this as an optional additional block. would this be cool?

**Comment by elevatebart** [comment]
I could as well try digging into function calls but it could be bad for performance.

**Comment by elevatebart** [comment]
I will need to look at functions as soon as Vue 3 comes in. The composition API is full of functions.

**Comment by wh1tew0lf** [comment]
Hello @elevatebart, the same question, but for Vue functional components: https://vuejs.org/v2/guide/render-function.html#Passing-Attributes-and-Events-to-Child-Elements-Components
There is no `this.$scopedSlots` just context. Do you know is there a workaround to document slots for Vue functional components? There is an example of my render function:
```
// @slot 1
render(createElement, context) {
  // @slot 2
  return createElement(`h${context.props.level}`, context.data, context.children);
}
```
I tried to put jsDoc comment at slot1 and slot2 places, but no results. So if you have please update me, that would be great

**Comment by elevatebart** [comment]
Hi @wh1tew0lf, 

Thank you for the heads up!
This is a code pattern that is not handled yet by the library. 
Would you mind creating a new issue for it?

Just copy and paste what you have written here and I will treat it ASAP.

**Comment by wh1tew0lf** [comment]
@elevatebart sure, it is https://github.com/vue-styleguidist/vue-styleguidist/issues/837
