### ISSUE TITLE
vue-docgen-api can't parse default function value

### ISSUE THREAD

**Issue by MrGaoGang** [vue-styleguidist/vue-styleguidist#589]
hello, when i use `vue-docgen-api` to parse vue component, i set vue component `props`, such as

```js
 array: {
      type: Array,
      default() {
        return [1, 2, 3]
      }
    },

```
i get the default value is `null`, but when i set 

```js
 array: {
      type: Array,
      default: function() {
        return [1, 2, 3]
      }
    },

```

i get the defalut is 
``` js
 function() {
        return [1, 2, 3]
      }
```

i don't know whether this is a bugs,if this, please fix it,thanks!

**Comment by elevatebart** [comment]
Hey @MrGaoGang this indeed seems like a bug in the [propHandler](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/src/script-handlers/propHandler.ts).

I believe it is an easy fix. If you want to start working on a fix, you can fork the current repo, create a unit test for this specific case and use vscode + the jest extension to walk though the code and see where it fails. 

To help you, I wrote [an article on alligator.io](https://alligator.io/js/traversing-ast/). It is a bit generic but can give you pointers on how to navigate the code.

**Comment by MrGaoGang** [comment]
> Hey @MrGaoGang this indeed seems like a bug in the [propHandler](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/src/script-handlers/propHandler.ts).
> 
> I believe it is an easy fix. If you want to start working on a fix, you can fork the current repo, create a unit test for this specific case and use vscode + the jest extension to walk though the code and see where it fails.
> 
> To help you, I wrote [an article on alligator.io](https://alligator.io/js/traversing-ast/). It is a bit generic but can give you pointers on how to navigate the code.

that's great, thank you very much!
