### ISSUE TITLE
Array/Object props don't get parsed properly

### ISSUE THREAD

**Issue by clareoneill** [vue-styleguidist/vue-styleguidist#60]
I updated to v1.3.7 and am still having issues with Array and Object props.

## Array and Object props, types explicitly set and default values are functions:

```
props: {
  propObject: {
    type: Object,
    default: function () {
      return {
        text: 'Etiam porta sem malesuada magna mollis euismod.'
      };
    }
  },
  propArray: {
    type: Array,
    default: function () {
      return [1, 2, 3, 4];
    }
  }
}
```

The app errors before rendering:
`Uncaught (in promise) TypeError: Cannot read property 'replaceChild' of null`

## Array and Object props, types are excluded and default values are functions:

```
props: {
  propObject: {
    default: function () {
      return {
        text: 'Etiam porta sem malesuada magna mollis euismod.'
      };
    }
  },
  propArray: {
    default: function () {
      return [1, 2, 3, 4];
    }
  }
}
```

The app is rendering but prop usage is this:

| Prop name | Type | Default |
| --- | --- | --- |
| propObject | func | Function |
| propArray | func | Function |

I would expect to be able to define a type and default value, and for the prop usage to be:

| Prop name | Type | Default |
| --- | --- | --- |
| propObject | Object | { text: 'Etiam porta sem malesuada magna mollis euismod.'} |
| propArray | Array | [1, 2, 3, 4] |

**Comment by hagi4u** [comment]
+1

In addition, 
I trace to call stack, i found this

###Code
```
moduleInfo: {
      type: Object,
      default () {
        return {};
      }
    },
```

###Call stack
```

```

**Comment by rafaesc** [comment]
Hi there,

Thanks for the issues cases

You can already update to version 1.3.8,
Also, I added test cases here:
https://github.com/vue-styleguidist/vue-docgen-api/blob/master/src/utils/__tests__/getProp.js#L233

feel free to reopen this issue if it still can't work

Regards
