### ISSUE TITLE
Wierd conflict with Nuxt.js

### ISSUE THREAD

**Issue by Knovour** [vue-styleguidist/vue-styleguidist#61]
1. Download the Vuex example and install packages.
2. Install `nuxt@next`
3. `rm -rf node_modules; rm package-lock.json`
4. Use `npm i` reinstall again.
5. `npm run styleguide`

`this.$store` will become undefined.

- node 9.2.1
- npm 5.6.0

**Comment by rafaesc** [comment]
Hi @Knovour,

Can you send a PR with the nuxtjs example in the branch nuxtjs?
https://github.com/vue-styleguidist/vue-styleguidist/tree/nuxtjs/examples/nuxtjs

So, I could solve the issue and at the same time give an example.

Regards

**Comment by rafaesc** [comment]
Thanks @Knovour,

There was a problem with the dependencies of vue's versions between vue-styleguidist and nuxtjs

Upgrade to version 1.3.9
