### ISSUE TITLE
Unable to import scss file from .md file

### ISSUE THREAD

**Issue by damyo** [vue-styleguidist/vue-styleguidist#623]
I created a project with 'vuecli-noplugin'.
Everything else works fine, but when I write a style tag in an .md file and try to import another scss file into it, I get an error.
The resolve path (@) doesn't seem to work exactly.
Here is my setup and code:

```js
// styleguide.config.js
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin
const path = require("path")

module.exports = {
  styleguideDir: 'dist/ui',
  pagePerSection: true,
  exampleMode: 'expand',
  usageMode: 'expand',
  sections: [
    ...
  ],
  webpackConfig: {
    plugins: process.argv.includes('--analyze') ? [new BundleAnalyzerPlugin()] : []
  },
  codeSplit: true,
  skipComponentsWithoutExample: true,
  require: [
    path.join(__dirname, "src/assets/css/common.scss")
  ]
}
```

```
// example.md
```js
<template>
  <div>
    <button
      class="example"
      @click="openModal"
    >
      My Button
    </button>
  </div>
</template>

<script>
export default {
  methods: {
    openModal() {
      console.log("open")
    }
  }
}
</script>

<style lang="scss" scoped>
@import "@/assets/css/something.scss"
</style>
```ㅤ
```

This error message occurs.
`Refused to apply style from 'http://localhost:6060/@/assets/css/something.scss' because its MIME type ('text / html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

---

resolve path (@) works fine inside a script tag.
However, the scss format is not interpreted within the style tag (the error does not occur).

I searched for related issues here, added css-loader, style-loader, sass-loader, sass-resource-loader, vue-style-loader, etc. to webpackConfig.module.rules, but it didn't work.

Is there anything I missed?
Currently, I'm using `import "@/assets/css/something.scss";` in a script tag as a temporary measure.
Help.

**Comment by elevatebart** [comment]
Hello @damyo, 

Unfortunately, styleguidist only supports pure javascript, JSX and pure CSS in the examples. 
This allows for removing the need for a server running in the back end while compiling the events.

The scss you are trying to use here is loaded s pure css in a style tag which throws the error that you see.

If you want to load the same SCSS file globally, there is a [require option](https://vue-styleguidist.github.io/Configuration.html#require). As long as you have a `node-sass` in your dependencies, styleguidist should pick up on it.

On another note, I would like you to avoid using the `vuecli-noplugin` example as it will break HMR (and I have no way to fix it). I should be more clear in the readme for it. You should rather install the plugin using `vue add styleguidist`.

the issue for reference : https://github.com/vue-styleguidist/vue-styleguidist/issues/290
