### ISSUE TITLE
Destroy Preview Vue component when leaving the page

### ISSUE THREAD

**Issue by yellowsunday** [vue-styleguidist/vue-styleguidist#627]
**The problem**

Preview examples don't trigger the Vue destroy lifecycle when you navigate away (within the styleguide, e.g. to another component page).

This would be useful for developers to verify that the teardown of the component is working as expected, and sometimes also for user-friendliness to avoid leftover things in the styleguide, e.g.:

- Open modal dialogs or other DOM elements outside of the normal component root, that may get left behind
- Global listeners that should be removed when the component is destroyed may end up being repeatedly registered/triggered when the page is revisited
- Global data e.g. in Vuex that should be cleaned up or reset when the component is destroyed.

**Proposed solution**

Could the Preview component call .$destroy on the Vue instance when it unmounts?

Thank you!

**Comment by elevatebart** [comment]
Hello @yellowsunday that is a great idea.

I believe that should be marked as a bug as each component is supposed to live in isolation from one another.

Would you be open to creating a Pull Request?

Thank you again.

**Comment by yellowsunday** [comment]
Yes, I can try it anyway, maybe later this week.

**Comment by elevatebart** [comment]
I believe it is done and delivered ;)
