### ISSUE TITLE
javascript 3rd party code example of usage in .md file brake other components examples

### ISSUE THREAD

**Issue by struers-mfr** [vue-styleguidist/vue-styleguidist#63]
Hello,
I experienced problem with readme.md file, that I including on the top of styleguide.
I have an example of how to use 3rd party extension for translations calling javascript function, but the styleguidist try to make from it example of live code playground.
Is there any option to avoid making it live code playground in .md file but still have the javascript code formating?

**Comment by rafaesc** [comment]
Hi @struers-mfr,

yes, you can add this to the code example that you don't want to convert to live example
````md
To render an example as highlighted source code add a `static` modifier:

```jsx static
<Button>Push Me</Button>
```
````

https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Documenting.md#usage-examples-and-readme-files

Regards!
