### ISSUE TITLE
Add yarn.lock or package-lock.json to the examples

### ISSUE THREAD

**Issue by cisen** [vue-styleguidist/vue-styleguidist#636]
**The problem**

Without lock file， the examples can‘t compile successfully.

**Proposed solution**

Add yarn.lock or package-lock.json to the examples

**Comment by elevatebart** [comment]
Hello @cisen, I chose to not use a `yarn.lock` in those examples because it was very hard to maintain.

The dependencies are not perfectly stable but that should not pose any problems when you `npm install`.

Can you please specify which example does not compile succesfully?

**Comment by cisen** [comment]
Updating vue-styleguidist to version 4.0.4，those examples are compiled successfully.Thanks!
