### ISSUE TITLE
TypeError: fileExistsCaseInsensitive is not a function

### ISSUE THREAD

**Issue by shuwanghu** [vue-styleguidist/vue-styleguidist#639]
![image](https://user-images.githubusercontent.com/32955341/69109443-c0017980-0ab2-11ea-83d7-b3cd5913bc2b.png)

**Comment by victory-v** [comment]
the same error

**Comment by LuXDAmore** [comment]
Same problem here

**Comment by alex-belyaev** [comment]
same here

**Comment by elevatebart** [comment]
could you guys tell me if it fixed it for you ?

**Comment by elevatebart** [comment]
So sorry for the snafu Babel and typescript are not playing nice with me.
In other words I thought I got clever and failed.

**Comment by victory-v** [comment]
@elevatebart Unfortunately, I still have this error

**Comment by elevatebart** [comment]
sorry @victory-v still need to wait for delivery woops again

**Comment by elevatebart** [comment]
follow delivery process [here](https://travis-ci.com/vue-styleguidist/vue-styleguidist/builds/137197875)

**Comment by elevatebart** [comment]
@victory-v should be good now ;-)

**Comment by victory-v** [comment]
@elevatebart yes, finally it works! Thanks for your work and quick fixes!
