### ISSUE TITLE
Auto-open browser

### ISSUE THREAD

**Issue by awmottaz** [vue-styleguidist/vue-styleguidist#64]
I would like to have a CLI option to open the browser automatically when the server is ready. Something like this, inspired by the Webpack DevServer API:

```
vue-styleguidist server --open
```

**Comment by rafaesc** [comment]
Hi @awmottaz,

I tried to add [opn](https://github.com/sindresorhus/opn) to open a browser, but I couldn't. Maybe needed another package.

It would add in this line.
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/bin/styleguidist.js#L129

Can you send a PR?

regards,

**Comment by awmottaz** [comment]
Hey @rafaesc, I create PR #73 for this

**Comment by rafaesc** [comment]
Thanks for the PR!

I published it in 1.4.5 version.

Regards!
