### ISSUE TITLE
Extract values into props fields

### ISSUE THREAD

**Issue by r4fx** [vue-styleguidist/vue-styleguidist#640]
I'm not sure if it is a feature request or I can prepare my own code be using the API in right way...

Currently when `vue-docgen-api` parse component props it doesn't extract values from variables, consts, etc. 

For example, in code below prop `size` has a default value, this value is defined in imported const `SIZE_MD`:

```javascript
<script>
import { SIZE_MD } from '../../config/constants';

export default {
  props: {
    size: {
      type: String,
      required: false,
      default: SIZE_MD,
    },
  },
};
</script>
```

So my question is, is it possible for `vue-docgen-api` to extract such values without hardcoding it using tags from JSDoc ?

**Comment by elevatebart** [comment]
This is not an easy task I think. If we want to avoid evaluating the code, looking up the values of constants in separate files could be complicated.

Are you interrested in investigating how to?

**Comment by r4fx** [comment]
yes sure I can try :)

**Comment by moezif-dev** [comment]
this is also something I am interested in, please let me know if I can help with the investigating :)
