### ISSUE TITLE
Can't setup vuex store

### ISSUE THREAD

**Issue by victory-v** [vue-styleguidist/vue-styleguidist#648]
Hi, I need help. I have a typescript project with vue-styleguidist and I can't get how can I make my store work. I did everything according to your example with the only difference this it is with typescript.

This is my styleguide.config.js:
```
const path = require('path');

module.exports = {
  renderRootJsx: path.join(__dirname, 'styleguideConfig/styleguide.root.js')
};
```
my styleguide.root.ts:
```
import Vue from 'vue';
import {i18n} from '../src/i18n';
import VueI18n from 'vue-i18n';
import Vuelidate from "vuelidate";
import VueRouter from 'vue-router';
import {routesPaths} from '@/router';
import Vuex from 'vuex';
import store from '../src/store/store';

Vue.use(Vuex);
Vue.use(VueI18n);
Vue.use(Vuelidate);
Vue.use(VueRouter);

const router = new VueRouter({routes: routesPaths});

Vue.component('router-link', {
  props: {
    tag: { type: String, default: 'a' }
  },
  render(createElement) {
    return createElement(this.tag, {attrs: {href: '#'}}, this.$slots.default)
  }
});

export default (previewComponent: any) => {
  return {
    router,
    store,
    i18n,
    render(createElement: any) {
      return createElement(previewComponent)
    }
  }
}
```
Here "store" is store.ts file. 
i18n and router are working fine. But not the store.
When I run vue-styleguidist, I get errors in console:
`[Vue warn]: Cannot find element: #app`
`[Vue warn]: Error in render: "TypeError: Cannot read property 'getters' of undefined"`

The last one I get for each usage of `this.$store.getters`. The same for mutations.
In the same time, in the live styleguide example the component with store is working as expected despite the errors. There's no trace of store in vue-devtools for this component but in 'vuex' tab I see all mutations and state.

If you have any idea what is wrong it will be very helpful!

**Comment by elevatebart** [comment]
Hello @victory-v 

I have never tried this configuration before. 
Would you mind creating a quick almost empty repo with it?

I will fork it and see what is going wrong.
It might still be a bug ;)

Thank you in advance.

**Comment by elevatebart** [comment]
Here is what I came up with https://github.com/elevatebart/vuecli3-vuex-ts

**Comment by victory-v** [comment]
Thanks again for your help and your work!
Your example helped me realize that I have some issues somewhere deeper than styleguide configuration. 
I didn't need `Vue.use(Vuex);` in my config but the real problem was in my mutation. There was some silly legacy code inside and after some refactoring it was OK.
So the summary is that the problem was on my side but in the same time the error regarding getters really confused me so I couldn't find it out quickly.
