### ISSUE TITLE
“Open isolated” doesn’t work with spaces in heading

### ISSUE THREAD

**Issue by mixn** [vue-styleguidist/vue-styleguidist#65]
Hey Rafael. :)

First of all, thank you for vue-styleguidist, it really makes life easier and enjoyable. 👍 

I noticed that opening `sections` in isolation doesn’t work when the `name` of a section includes *spaces*.

An example:

```
{
  name: 'Introduction',
  content: 'path/to/intro.md',
},
```

will open flawlessly when ![screen shot 2017-12-21 at 23 32 47](https://user-images.githubusercontent.com/672237/34277722-49e3e354-e6a7-11e7-9c7b-0dd3aa41fb4c.png) is clicked. The URL will result in `http://localhost:6060/#!/Introduction`.

With a `name`d section like

```
{
  name: 'JavaScript Guidelines',
  content: 'path/to/js-guidelines.md',
},
```

this is *not the case*. Nothing will happen when clicked and the URL will result in `http://localhost:6060/#!/JavaScript Guidelines`.

I’d love to take a look at this myself, maybe will this weekend or next week, but need to finish a lot of work before the end of the year first. :) 

Thank you and hope this makes sense! :)

**Comment by rafaesc** [comment]
Hi @mixn,

Upgrade to version 1.4.0,

Also, I added a sections example:
https://github.com/vue-styleguidist/vue-styleguidist/tree/master/examples/sections

Regards
