### ISSUE TITLE
Props spread in from external package aren't documenting

### ISSUE THREAD

**Issue by cbaxter713** [vue-styleguidist/vue-styleguidist#668]
**Current behavior**

I have a core component library that I publish to npm, and then extend those core components in a Nuxt project that I am building out.  To do that I import each core component from node_modules into my project base components, and spread the core component props in, in order to keep the props in sync.  Example:

```
<template>
    <zr-button class="base-button" v-bind="$props">
        <slot></slot>
        <base-icon v-if="icon"
                   class="btn-icon"
                   :icon="icon">
        </base-icon>
    </zr-button>
</template>

<script>
  import ZrButton from '@zaneray/vue-components/components/base/ZrButton.vue';

  /**
   * Button component that leverages the Zaneray BaseButton documented at https://zr-vue.netlify.com/#/Base%20Components/ZrButton
   */

  export default {
    name: "BaseButton",
    components: {
      ZrButton
    },
    props: {
      ...ZrButton.props,
      /**
       * Icon to display in the button.
       */
      icon: {
        type: String
      }
    }
  }
</script>
```

This BaseButton component documentation then renders as so:
<img width="717" alt="Screen Shot 2019-12-06 at 1 56 22 PM" src="https://user-images.githubusercontent.com/6816493/70355781-354da800-1830-11ea-8820-cc9ce73d73ec.png">

...where the `icon` prop is documented, but the props spread in from ZrButton are not documented. 

The spread props are properly available for use on on the BaseButton component, even though they are not documented.

 I am using the latest version of Vue Styleguidist: `4.1.1`

**To reproduce**
In a Vue component that is documented with VSG, import another Vue component from a library like https://www.npmjs.com/package/@zaneray/vue-components .  Spread the props of the imported component into the props of the component you are documenting, and see that the spread props do not make it through to the documentation

**Expected behavior**
I would expect that the props spread in from the imported component are documented in VSG just like normal props would be.

**Comment by elevatebart** [comment]
I am just being curious here, note that I still intend to figure something out for the 
In this case specifically why didn't you [extend using the `extends` option](https://vuejs.org/v2/api/#extends) the `BaseButton`.

**Comment by cbaxter713** [comment]
@elevatebart I didn't know about the `extend` option.  That definitely fits what I am trying to do.  However it looks like using the `extend` option instead of spreading the props still does not pull in the ZrButton props to the documentation.  Is that what you have addressed in this PR? https://github.com/vue-styleguidist/vue-styleguidist/pull/671

**Comment by elevatebart** [comment]
Hey @cbaxter713,
You are now finding the same issue as #606.

I am not finished with #671 yet but I plan to create an option in your styleguide.js around the lines of `validExtendedComponent(fullPath:string):boolean`
The process is not fine tuned yet so don't take my word for it.

Do you think this would be understandable?

In styleguide.config.js
```js
module.exports = {
  name: 'zaneray styleguide',
  components: 'src/components/*.vue',
  // ...
  validExtendComponent: (fullPath) => 
    // avoid looking at components that you cannot parse
    !/node_modules/.test(fullPath) || 
    // keep the components from your library
    /@zaneray\/vue-components/.test(fullPath)
}
```

**Comment by elevatebart** [comment]
How about `validExtend` as the name of the option?

**Comment by cbaxter713** [comment]
@elevatebart got it.  Yeah `validExtend` sounds better. I think that config would work great!

**Comment by elevatebart** [comment]
I will settle with `validExtends` to have same spelling as the `extends` option.

I still need to work on documenting and testing the new option.
I believe I can deliver by tomorrow morning.

Hope that's cool !

**Comment by cbaxter713** [comment]
Sounds great, thanks for the speedy work on this.  Excited to see the change!

**Comment by cbaxter713** [comment]
@elevatebart do you know when the work of that PR (https://github.com/vue-styleguidist/vue-styleguidist/pull/671) will be released?

**Comment by elevatebart** [comment]
You can try it now in 4.2.0

**Comment by jcchrrr** [comment]
@elevatebart 
The validExtends feature is a great idea but I cant make it works.
I extended a vuetify component in mine and the validExtends function return correctly **true** when i test it.


here is my styleguide.config.js
```
validExtends(fullFilePath) {
	return (
		/[\\/]node_modules[\\/]vuetify[\\/]lib[\\/]/.test(fullFilePath) ||
		!/[\\/]node_modules[\\/]/.test(fullFilePath)
	)
},
```

But the inherited props doesn't appear in my component view, do you have an idea ?

**Comment by elevatebart** [comment]
Hello @jcchrrr 

As seen below, if vue-docgen-api fails to parse a component, it "eats the error".
I believe I should return some kind of warning using a logger. 

https://github.com/vue-styleguidist/vue-styleguidist/blob/4382a8fc2cabd460542d64231db2052ce2ae83c0/packages/vue-docgen-api/src/script-handlers/extendsHandler.ts#L40-L59

Some components are simply out of reach of pure static analysis for now since they are completely packed up at runtime using functions and composition.

To help me help you best could you answer this question: 
Which vuetify component are you extending? (how can I reproduce your situation?)

**Comment by elevatebart** [comment]
For instance, docgen-api can't parse this as a Vue component yet:

https://github.com/vuetifyjs/vuetify/blob/432c4db29a521323e0c2b40a6a164cc99c0fbcb3/packages/vuetify/src/components/VBtn/VBtn.ts#L38-L43

mostly because of the use of `baseMixins.extend<options>().extend({` instead of the expected `Vue.extend(`.

Would you be open to trying your hand at a Pull Request?

**Comment by jcchrrr** [comment]
Hello @elevatebart 
I'm trying to extend a VTextField component,

```
<script>
import { VTextField } from 'vuetify/lib'

export default {
	name: 'MyComponent',
	extends: VTextField,
...
```

**Comment by elevatebart** [comment]
You would probably start around where we determine if an export is a component or not:

https://github.com/vue-styleguidist/vue-styleguidist/blob/4382a8fc2cabd460542d64231db2052ce2ae83c0/packages/vue-docgen-api/src/utils/resolveExportedComponent.ts#L13-L33

**Comment by jcchrrr** [comment]
Ahah, I'll look a this

**Comment by elevatebart** [comment]
If you do not mind, though, I will create anoter request to be able to prarse vuetify export format.

**Comment by elevatebart** [comment]
Hey @cbaxter713 

Did you have time to try the validExtends option ?

I am eger to know if it worked ;-)

**Comment by jcchrrr** [comment]
> You would probably start around where we determine if an export is a component or not:
> 
> https://github.com/vue-styleguidist/vue-styleguidist/blob/4382a8fc2cabd460542d64231db2052ce2ae83c0/packages/vue-docgen-api/src/utils/resolveExportedComponent.ts#L13-L33

@elevatebart the weird thing is this function return true, so the vuetify component is correctly read like a correct component right ?

**Comment by elevatebart** [comment]
Hey @cbaxter713

Did you have time to try the `validExtends` option ?

Can't wait to know if it helped ;-)

**Comment by cbaxter713** [comment]
@elevatebart yes sorry for the delay.  I have implemented that option and it is working great for documenting the components that I am extending.  The components that I am extending are from my own package that I am publishing to npm, and they are just straight Vue components.

Thanks again for making that change!

**Comment by elevatebart** [comment]
\o/ this is what I live for have fun with the lib.

Bart
