### ISSUE TITLE
vue-docgen-api cant find v4.2.0

### ISSUE THREAD

**Issue by rikbrowning** [vue-styleguidist/vue-styleguidist#674]
npm install of vue-styleguidist gives the following error:
![image](https://user-images.githubusercontent.com/1380376/70562581-ace64480-1b5a-11ea-9f7c-1d952c94dc7f.png)

I get that this was just released but unsure why I can get the latest version of vue-styleguidist and not vue-docgen-api.

**Comment by elevatebart** [comment]
You probably ended up right in the middle of delivery.
Can you clean your npm cache and try again ?

**Comment by rikbrowning** [comment]
Just tried again there now, cleared cache and just tried installing it directly and got the following:
![image](https://user-images.githubusercontent.com/1380376/70624826-19ab1e80-1bef-11ea-9ca4-53b83a6e5ac9.png)

**Comment by elevatebart** [comment]
This here says 4.2.0 is the latest version 

https://www.npmjs.com/package/vue-docgen-api

Do you have an .npmrc file in your repo ?

**Comment by elevatebart** [comment]
Have you tried insalling vue-docgen-api in another repo ?

**Comment by rikbrowning** [comment]
Yes, this seems to be an issue with our artifactory not proxying out correctly, sorry for the hassle.
