### ISSUE TITLE
Styleguide build fails fails when optional `assetsDir` setting is not set

### ISSUE THREAD

**Issue by dominik-bln** [vue-styleguidist/vue-styleguidist#675]
**Current behavior**

When we don't set the optional `assetsDir` config in `styleguide.config.js` our build fails with the following error message:

```bash
$ ./node_modules/.bin/vue-styleguidist build
Building style guide                                          0%ValidationError: CopyPlugin Invalid Options

options should NOT have fewer than 1 items

ValidationError: CopyPlugin Invalid Options

options should NOT have fewer than 1 items
```

**To reproduce**

Run the styleguide build without the `assetsConfig` dir setting. The culprit seems to be the following line:

https://github.com/vue-styleguidist/vue-styleguidist/blob/4382a8fc2cabd460542d64231db2052ce2ae83c0/packages/vue-styleguidist/src/scripts/make-webpack-config.ts#L144

**Expected behavior**

The build succeeds or reports that the config setting is required.

**Comment by elevatebart** [comment]
hello @dominik-bln 

This issue is similar to:
https://github.com/styleguidist/react-styleguidist/issues/1493

I will get it fixed today
