### ISSUE TITLE
Allow use of export default baseMixins.extend().extend({

### ISSUE THREAD

**Issue by elevatebart** [vue-styleguidist/vue-styleguidist#676]
In vuetify (and other libraries), people do not use `Vue.extend`, they use `somthingimportant.helloWorld().whynotHereasWell.extend` to create their components in typescript. 

vue-docgen-api could simply still parse it.

Update [resolveExportedComponent.ts](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/src/utils/resolveExportedComponent.ts) to accept anything before the `.extend({`

CC @jcchrrr

**Comment by elevatebart** [comment]
Responding to #668 

@jcchrrr how did you determine that the isComponent was returning true ?

**Comment by jcchrrr** [comment]
@elevatebart I logged inside the function to try to understand, and I saw that isComponentDefinition return true 🤔

**Comment by elevatebart** [comment]
Does it return true for the vtextfield component ? I need to try it when I get to the office. It would be magic, but not Impossible.

**Comment by jcchrrr** [comment]
Hmm yes, I think 😄
I'm investigating how and why

**Comment by elevatebart** [comment]
Just created this test and it is not passing... sad, but no magic yet.

https://github.com/vue-styleguidist/vue-styleguidist/blob/33bee62ad52da2595a7484a5efadb9049604bc92/packages/vue-docgen-api/src/utils/__tests__/resolveExportedComponent.ts#L78-L81

**Comment by jcchrrr** [comment]
Hello @elevatebart i wrote the ast definition based on your test for a vuetify component in the "isComponentDefinition"

```
// export default baseMixins.extend().extend({})
|| (bt.isCallExpression(node)
	&& bt.isObjectExpression(node.arguments[0])
	&& bt.isMemberExpression(node.callee)
	&& node.callee.property.name === 'extend'
	&& bt.isCallExpression(node.callee.object)
	&& bt.isMemberExpression(node.callee.object.callee)
	&& bt.isIdentifier(node.callee.object.callee.object)
	&& node.callee.object.callee.property.name === 'extend'
	&& node.callee.object.callee.object.name === 'baseMixins')
```

When i run the tests it seems ok, but then i compile, and yarn test with a component extended from vuetify and nothing change. The component is correctly extended (when i check with vue devtools) but the extendeds props aren't dislayed in the props section.
Do you have an idea ?

**Comment by elevatebart** [comment]
Great Job @jcchrrr 
You are off to a great start.
Do you have a repository where you have started the work?

It would probably be easier for communication if we worked on code together.

Here is how I would go about it

1. Create the tests for vue-docgen-api
  - create unit test as writeen above
  - create an end 2 end test where you try to parse a complete VTextField and see what it returns
2. Make each of those tests pass properly. 
  - I suggest using the [jest plugin for vscode](https://github.com/jest-community/vscode-jest) to debug your tests. you can set breakpoints and inspect variables.
  - You can also use the [ast-explorer](https://astexplorer.net) to see what the AST looks like on the inside when parsed with babel.
3. Test it with an extended component and see if it works since this is your final use case

**Comment by elevatebart** [comment]
Regarding the change to `resolveExportedComponent.ts`, I was thinking of something more generic. Anything that is exported and that ends the expression in `.extend({name:"MyComponent"})` would be parsed as a valid component.

The following component would be valid for instance.

```js
export default mama.mia().I.am().MARIO.extend({
  name: 'SuperMarioComponent',
  props: {
    hat: Object
  }
})
```

This would mean probably having a function dedicated to detecting this kind of situation, which would loop on each sub-member of the expression until reaching the last item.
Then looking at the function call, check that it has only one param and this param is a `bt.ObjectExpression`.
As a plus we could check that the function called is named `extend` but I fear that people would alias this function too.

Our only goal here is to determine what we should statically analyze. not to decide what is the correct way of writing a Vue component.

Hope this helps

**Comment by jcchrrr** [comment]
Thanks, seems clear.
First I'll fork properly the repo, then I'll write a function to loop on component to reach an extend property name.
And then i'll try to create an end 2 end test to parse a VTextField but I don't really know how and where I have to do this. I not really used Jest until now.

**Comment by elevatebart** [comment]
I don't think you need to loop anything yet. 
Checking that the method call is named extend is a "nice to have". 
It might even be a not so nice to have because it would limit what components are parsable.

I would probably just put this expression in https://astexplorer.net/ and see what is returned

```javascript
export default baseMixins.extend().toto.extend({name:'testComponnent'})
```

I believe you will be surprised by what you find out.

**Comment by jcchrrr** [comment]
Yes I find this site to write the previous definition, it is very useful 😄
So finally maybe we juste have to check this ?

```js
bt.isCallExpression(node)
&& bt.isObjectExpression(node.arguments[0]
```

**Comment by elevatebart** [comment]
Pretty much yes !

The end 2 end tests for docgen have nothing fancy. It's still using jest but instead of mocking everything, you give a full component to the full API.

Look inside this folder [vue-docgen-api/tests](https://github.com/vue-styleguidist/vue-styleguidist/tree/dev/packages/vue-docgen-api/tests) all the end to end tests are here and are run when you run the following command in your console. Once again you can debug each of those tests

```sh
yarn run test:jest api/tests
```

**Comment by elevatebart** [comment]
Create another folder here and call it `vuetify` add a vuetify component and try parsing it.

**Comment by jcchrrr** [comment]
> Pretty much yes !

in that way all of this code in `resolveExportedComponent` seems deprecated ?
```js
// export default Vue.extend({})
|| (bt.isCallExpression(node)
	&& bt.isMemberExpression(node.callee)
	&& node.callee.property.name === 'extend'
	&& ((bt.isIdentifier(node.callee.object) && node.callee.object.name === 'Vue')
		// or export default (Vue as VueConstructor<Vue>).extend({})
		|| (bt.isTSAsExpression(node.callee.object)
			&& bt.isIdentifier(node.callee.object.expression)
			&& node.callee.object.expression.name === 'Vue')))
```

**Comment by elevatebart** [comment]
exactly

**Comment by elevatebart** [comment]
@jcchrrr How are you doing with the feature ?

**Comment by elevatebart** [comment]
Most importantly do you need help?

**Comment by jcchrrr** [comment]
Hello @elevatebart ,
I was working on the E2E test for vuetify, but I had difficulties to create it. The blocking point is to  make a vuetify component working with TS. I have not really use it until now and I'm not yet reaching the right way to define the Vuetify component.
Regarding to Vuetify testing docs, we have to use a localvue to mount a component, but the TS definitions are blowing up and i'm not familiar with this. So, i'm stuck in here 😆

**Comment by elevatebart** [comment]
What I had in mind is something far simpler.


1. Copy-paste one of the folders in vue-docgen-api/tests/components
2. Replace the contents of a component by one of vuetify components (any)
3. Rename the test file in the same folder that you Copy-pasted and modify the tests accordingly

I hope this help,

It would probably be easier to discuss this with a pull request. How soon can you create one ?

**Comment by jcchrrr** [comment]
@elevatebart  #685

**Comment by elevatebart** [comment]
This seems done ;)
