### ISSUE TITLE
Compile fail

### ISSUE THREAD

**Issue by Akimotorakiyu** [vue-styleguidist/vue-styleguidist#684]
**Current behavior**

![图片](https://user-images.githubusercontent.com/31165554/71615833-27503480-2bee-11ea-81c0-4d3b74550b92.png)

**To reproduce**
```sh
vue add styleguidist
yarn styleguide
```

**Expected behavior**

PASS

**Comment by elevatebart** [comment]
Hello @Akimotorakiyu I was AFK for a few days. 
Can you tell me what version of vue-styleguidist and what version of Babel are used?
This definitely looks like a bug but I can't seem to reproduce it easily.

**Comment by elevatebart** [comment]
Can you share the contents of your dependencies and devdependencies from your `package.json` ? 
Since I am worried about a version conflict between babel, not resolved well by yarn, this would be incredibly helpful.
Thank you in advance

**Comment by elevatebart** [comment]
@Akimotorakiyu are you still seeing this bug?
Do you use TSX (typescript+JSX) components? I do not have an integration test for that.

**Comment by Akimotorakiyu** [comment]
@elevatebart 

I'm sorry that I haven't replied to you.
I'm so busy recently that I don't have the heart to analyze it carefully.
I'll give you an answer tonight.
so sorry.

**Comment by elevatebart** [comment]
Just curious here, what do you use TSX for in this component ? 
I do not see any tsx transformable code in here.

**Comment by elevatebart** [comment]
how about using ts or js instead ?

**Comment by Akimotorakiyu** [comment]
At the beginning, it was implemented using TSX.

Later, although the tag of TSX was no longer needed, but the value of Lang had not been changed.
