### ISSUE TITLE
router not replacing url for fullscreen view

### ISSUE THREAD

**Issue by drewalth** [vue-styleguidist/vue-styleguidist#686]
**Current behavior**

The component fullscreen view works fine if you did not previously click a sidebar item. However, clicking a component link in the sidebar, then clicking the fullscreen icon for the selected component redirects to a 404. Looks like the router is not replacing the UR, see attached screenshots.

###### good url

![image](https://user-images.githubusercontent.com/16584198/71636800-b2332e00-2bf2-11ea-9f01-40adafd75415.png)

###### bad url

![image](https://user-images.githubusercontent.com/16584198/71636806-c5de9480-2bf2-11ea-9966-f8934dc3d346.png)

**To reproduce**

Click a component link in the sidebar, then click the components fullscreen button.

**Comment by elevatebart** [comment]
Thanks @drewalth 

I will need to fix that as soon as I come back from the holidays.

**Comment by elevatebart** [comment]
This bug is in react-styleguidist and is probbly my fault anyways. I will sugget a fix to rsg ASAP.
Thank you for reporting.

**Comment by elevatebart** [comment]
already fixed there, https://github.com/styleguidist/react-styleguidist/issues/1492

**Comment by drewalth** [comment]
Sweet! Impressed by the response time.

Cheers.

**Comment by elevatebart** [comment]
rsg still needs delivery though, they messed up their conventional changelog
