### ISSUE TITLE
pug options specified in webpackConfig get overwritten

### ISSUE THREAD

**Issue by adamvleggett** [vue-styleguidist/vue-styleguidist#688]
If webpackConfig contains data options for pug-loader/pug-plain-loader, these get overwritten with

`{ filename: "..." }`

**Comment by elevatebart** [comment]
Hello @adamvleggett 

What do you see that makes you say that these options get overwritten?
Is it the errors you see in the console?
Is it what is rendered?
The parsed slots do not come out?

Thank you for your report

**Comment by elevatebart** [comment]
Hello @adamvleggett 

I want to help you. For that, I need a few more details on what you see.
I hope you have a few minutes to add them.

**Comment by elevatebart** [comment]
Hello @adamvleggett 

As you can see here, I only use pug as a pure compiler. 
This is probably what should be fixed.
I should add an option to docgen-api to provide the option set to the pug API.

https://github.com/vue-styleguidist/vue-styleguidist/blob/cf3a2096ffedb8327917274535d8326fd6bceb76/packages/vue-docgen-api/src/parse-template.ts#L23-L30

If you are interrested in proposing a PR, 
I can help you push it along ;-)

**Comment by adamvleggett** [comment]
@elevatebart Excuse me, I was on vacation and forgot to follow up when I got back. You are correct that the problem is resolved if I add the missing params to the `pug.render` line in vue-docgen-api alongside `filename`.

**Comment by elevatebart** [comment]
thank you @adamvleggett

**Comment by adamvleggett** [comment]
@elevatebart  should I open an issue against vue-docgen-api?

**Comment by elevatebart** [comment]
Oh, sorry!!!! I thought it had fixed itself. Would you be open to create a PR.

**Comment by adamvleggett** [comment]
@elevatebart I can do that, but it may be a couple weeks before I get a chance to familiarize myself with the code and figure it out.

**Comment by elevatebart** [comment]
if you need to jump on a call and peer program on it with me, ping me on discord. It seems like a simple enough bug that it would not take more than a 15 min call.

**Comment by adamvleggett** [comment]
@elevatebart ok what's your ID?

**Comment by elevatebart** [comment]
elevatebart#1057

**Comment by adamvleggett** [comment]
Discord says "Hm, didn't work. Check that spelling is correct".

**Comment by elevatebart** [comment]
ElevateBart#1057 ???
if not, got to this channel https://discordapp.com/channels/325477692906536972/538786416092512278
I usually am on there. We could start the discussion there.

**Comment by elevatebart** [comment]
Maybe the caps matter
