### ISSUE TITLE
Feature Request: Collapsible Sidebar Sections

### ISSUE THREAD

**Issue by drewalth** [vue-styleguidist/vue-styleguidist#689]
**The problem**

Sections with a lot of components get very tall and dominate the nav.

**Proposed solution**

For sections that have more than X components, make them collapsible by default. Or in the sections config, `collapsible: true` which either enables or disables an accordion style functionality.

**Additional Notes**

Maybe this already and exists and I just haven't found it yet? Anyway, will try to take the initiative on this and open a PR. 

**Additional context**

![image](https://user-images.githubusercontent.com/16584198/71914502-f2d10100-3136-11ea-8f99-27057ec73d78.png)

![image](https://user-images.githubusercontent.com/16584198/71914649-480d1280-3137-11ea-9484-34c6cf81c9e7.png)

![image](https://user-images.githubusercontent.com/16584198/71914659-4cd1c680-3137-11ea-8af4-f56c0faf2aa5.png)

**Comment by elevatebart** [comment]
wooo that's a big old list of components. 
Give me a minute I need to update one dependency of styleguidist (react-styleguidist) where I just added this feature exactly: [tocMode](https://react-styleguidist.js.org/docs/configuration.html#tocmode)

**Comment by Aias** [comment]
Upgraded from 4.2.2 to 4.4.3 and noticed that, where previously only the selected section was bolded, now *every* section up the hierarchy is bolded. So I've gone from:

- Section A
    - Section A.1
        - Section A.1.1
        - **Section A.1.1 (Selected)**
    - Section A.2
- Section B
    - Section B.1

To this mess:

- **Section A**
    - **Section A.1**
        - **Section A.1.1**
        - **Section A.1.1 (Selected)**
    - **Section A.2**
- Section B
    - Section B.1

Where only the hierarchies that are totally independent are unbolded. The `.rsg--selected` class is being applied to every top-level grouping up the chain, which is then inherited by all the subsections, even if they're not selected. Is this something in my own setup or is anyone else seeing this?

**Comment by elevatebart** [comment]
I don't think it is anything wrong with your setup.
I believe this is my fault. It's just my fault on [react-styleguidist](https://github.com/styleguidist/react-styleguidist). I made a fix and it had unforeseen consequences.
I will send a PR to rsg as soon as I can (probably tomorrow night Central US Time)
