### ISSUE TITLE
Description for slot-props

### ISSUE THREAD

**Issue by sense-it-gmbh** [vue-styleguidist/vue-styleguidist#693]
**The problem**

When documenting scoped slots there is no way to describe the slot-props.

**Proposed solution**

Provide the ability to add a description (and examples) for slot props via the `@slot` comment. For example:

```vue
<template>
  <div>
    <!--
      @slot Description for the default slot
      @prop {string} value1 The message that is very important
      @prop {number} value2 A number that has no meaning
    -->
    <slot
        v-bind:value1="value1"
        v-bind:value2="value2"
    ></slot>
  </div>
</template>

<script>
export default {
  name: 'my-component',
  data: () =>({
    value1: 'a very important message',
    value2: 9000
  })
}
</script>
```

**Alternative solutions**

**Additional context**

**Comment by elevatebart** [comment]
Hello @sense-it-gmbh 
it is indeed a good question. 
slot bindings are not exactly props (though they share their syntax).
They are called bindings but they work exactly the same way.

you can find an example of documentation here the spaces and tabs have no importance nd in this case I should really fix them in the example.

https://github.com/vue-styleguidist/vue-styleguidist/blob/2c4cd4582fcc11e41350e7c88aa74fe86e8ec9e1/packages/vue-docgen-api/tests/components/scoped-slot/Wrapper.vue#L1-L9

I hope this helps.
Bart

**Comment by elevatebart** [comment]
I forgot about this one as well
https://vue-styleguidist.github.io/basic/#scopedslot

**Comment by sense-it-gmbh** [comment]
@elevatebart that's exactly what i need and it works well. Unfortunately I wasn't able find it in the [docs](https://vue-styleguidist.github.io/docs/Documenting.html#slots).
