### ISSUE TITLE
Automatic component inclusion for examples?

### ISSUE THREAD

**Issue by RyanHavoc** [vue-styleguidist/vue-styleguidist#697]
https://vue-styleguidist.github.io/docs/Cookbook.html#how-to-hide-some-components-in-a-style-guide-but-make-them-available-in-examples

In terms of making components available for examples. Is there a way to include a component automatically? So I don't have to do:

```
const Vue = require('vue').default
const Button = require('./Button.vue').default
Vue.component('Button', Button)
```

Every time?

**Comment by RyanHavoc** [comment]
I found the solution to this myself by using `styleguide.global.requires.js`.

**Comment by BrevAlessio** [comment]
Hey @RyanHavoc, can you explain your solution briefly? I'm facing the same problem. Thank you.

**Comment by RyanHavoc** [comment]
@BrevAlessio I figured it out from: https://vue-styleguidist.github.io/docs/Cookbook.html#use-vue-styleguideist-with-components-that-contain-routing

My `styleguide.global.requires.js` looks like:

```
import Vue from 'vue';
import DisplayVariable from './DisplayVariable';

Vue.component('DisplayVariable', DisplayVariable);
```
