### ISSUE TITLE
Async Setup before initializing examples

### ISSUE THREAD

**Issue by sense-it-gmbh** [vue-styleguidist/vue-styleguidist#708]
On my project I'm using components that are communicating with a REST-API with required authentication.

When providing examples they will fail due missing authentication (of course because no user ever logged in).

Im planing to provide a ro-version of the API with demo-data that gets reset every day with hardcoded login for a demo user.

Since logging in is an async HTTP request I can not simply set up the login in the root example file of styleguidist, since the export is synchronous (race-condition: maybe the login is fast enough, maybe setting up the vue instance is faster).

**Question:** Is there a way to perform async setup tasks before launching the example code?

*Usually i would do this in main.js:*

```js
import Vue from 'vue'
import { client } from 'my-api'
import App from '@/App'

let login = false

client.login({
  username: 'testuser',
  password: '12345678'
})
  .then(() => { login = true })
  .finally(() => {
    new Vue(
      render: h => h(App)
    ).$mount('#app')
  })
```

**Comment by elevatebart** [comment]
Hello @sense-it-gmbh 

It is not possible for now.
I could see it be made possible by changing the `Preview.js` file.

https://github.com/vue-styleguidist/vue-styleguidist/blob/cf3a2096ffedb8327917274535d8326fd6bceb76/packages/vue-styleguidist/src/client/rsg-components/Preview/Preview.js#L148-L161

I am usually against needing access to an API when demoing Front-End components as it is a good way to have an extra (not very useful) dependency.
I would advocate for mocking data wherever you can to avoid having to do those calls.

You are not the first one to ask for that though.
Would you be interrested in looking into how to do it?

Thank you !

**Comment by sense-it-gmbh** [comment]
Thats exactly the piece of code that i meant. I understand your point and i could try to mock a demo-Vuex store for the examples. I think that would be a good approach.
