### ISSUE TITLE
Add Support for Single File Component Format in Usage Examples

### ISSUE THREAD

**Issue by mrjones2014** [vue-styleguidist/vue-styleguidist#71]
While you can implement more complex usage examples by instantiating a Vue instance via the 
`new Vue({ ... })` syntax, it would be great to have support for the Single File Component format. This doesn't necessarily have to be within markdown; since the JS within the markdown is parsed to a component anyway, you could simply allow *.vue files to be used as the usage example.

**Comment by rafaesc** [comment]
Hi @mrjones2014,

Yes, good idea, however I don't think that .vue files will be examples, because it wouldn't be easy to identify which it's an example or ui component. maybe there would be a new format in the markdown like.

``````
````vue
<template></template>
<script></script>
````
``````

It's a possibility.

Regards

**Comment by mrjones2014** [comment]
@rafaesc if could you point me in the right direction to the markdown parser, I could work on this and submit a pull request.

**Comment by rafaesc** [comment]
Hi @mrjones2014,

For sure, all responsibility of examples render is in 
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/src/rsg-components/Preview/Preview.js

In this line execute the component
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/src/rsg-components/Preview/Preview.js#L179

The reading of example is developed, in this line
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/src/rsg-components/Preview/Preview.js#L15

But its necessary to use with this package htmlparser2
Like this example
https://github.com/vue-styleguidist/vue-docgen-api/blob/master/src/utils/getSlots.js#L11

For the moment, I am busy, so it's possible that in the future can do it

Regards,

**Comment by mrjones2014** [comment]
@rafaesc I've implemented this and submitted pull request #79

**Comment by rafaesc** [comment]
Out in 1.4.6!

**Comment by mrjones2014** [comment]
@rafaesc  when will this be made available on npm?
