### ISSUE TITLE
Extract mixin information from library (node_modules)

### ISSUE THREAD

**Issue by sense-it-gmbh** [vue-styleguidist/vue-styleguidist#711]
**The problem**

Consider the following setup:

1. Lib `a` defines a mixin `mx` and provides docs via `vue-styleguidist`
2. Lib `b` uses `mx` from lib `a`

Components in lib `b` can access and include the mixin, they receive the desired functionality and work well. *However* in the docs the props and functions from the mixin are not documented despite they where documented in lib `a`.

**Proposed solution**

If comments are preserved during bundling (default with `vue-cli-service build --target lib`) they could be extracted from the bundle in order to provide the missing documentation parts.

In my case webpack preserves the comments and code very well, only the export is changing:

```js
/**
 * My mixin description....
 */
export const myMixin = {}
```
becomes:
```js
/**
 * My mixin description....
 */
var myMixin = {}
// [...]
/* concated harmony reexport myMixin */__webpack_require__.d(__webpack_exports__, "myMixin", function() { return myMixin ; });
```

**Alternative solutions**

Provide the documentation information within the export through a well defined interface. <-- This doesn't sound nice at all!

**Additional context**

Maybe duplicate of #606 ?!

**Comment by elevatebart** [comment]
You main issue is that the lib you are trying to load is ignored. For performance and readability, extending anything from the node_modules is ignored by default.

You can override this ignore using the [validExtends](https://vue-styleguidist.github.io/Configuration.html#validextends) option who can tell docgen and therefore styleguidist what it is allowed to parse as an extend or a mixin.

**Comment by sense-it-gmbh** [comment]
Unfortunately docgen is still ignoring the mixin. I tested my RegEx and it returned true for the paths I want to allow to be parsed, still the docs from the mixin are missing. I think the reason is that the export generated by webpack is not recognized by docgen.

**Comment by elevatebart** [comment]
It looks like you might need to overrride this function: 

https://github.com/vue-styleguidist/vue-styleguidist/blob/db2676a4751b432f3c83b6f7369397c2e65bd456/packages/vue-docgen-api/src/utils/resolveExportedComponent.ts#L13-L26

**Comment by elevatebart** [comment]
The library used is compiled with webpack.
From what I know the main use case for webpack is to target the browser directly. 

Could you somehow access the source code? 
Could you change the compilation to use [rollup](https://github.com/rollup/rollup) or [parcel](https://github.com/parcel-bundler/parcel) to compile ES modules? 
In other words, in order to know what to parse and what to document, vue-docgen-api needs to find the `module.exports` or the `export` keyword. If not, it plain and simple ignores your components.

I hope this helps a little 

vue-docgen-api is a static analysis tool. It avoids executing code because it would be slow and most of the time useless for finding documentation.

**Comment by sense-it-gmbh** [comment]
The source-files are bundled with the lib-package itself so I could access them. However since I'm using the webpack aliases in the source files the paths will not resolve properly. Since its a @vue/cli library I'm bound to webpack somehow.

I think I found a solution that works for my use case. I will remove the webpack aliases in some places and access the sources directly. Unfortunately this will create two instances for every mixin used that way.

**Comment by elevatebart** [comment]
Having two instances of each plugin does not sound like a sustainable way of doing things. 
Maybe we can try and find what defines a webpack export (reverse engineering) and accept this as a valid export.
This would be brittle but could work for your case.

Have you checked out https://github.com/chrisvfritz/hello-vue-components/
It is full of great practices about building and publishing component libraries.
I believe it might contain the answer here.

**Comment by sense-it-gmbh** [comment]
Its not two instances of one plugin but two instances of one mixin. Its not a good pattern but I don't see any major problems.

The way webpack export ist not too complex and I don't think it will be brittle. Though there might be inconsistencies between different webpack major-versions.

For webpack 4 it will create a `var <<nameOfTheExport>>` that has all the documentation. This variable is exported later with the following line:

```
/* concated harmony reexport <<nameOfTheExport>>*/__webpack_require__.d(__webpack_exports__, "<<nameOfTheExport>>", function() { return <<nameOfTheExport>> ; });
```

hello-vue-components is pretty interesting, thank you for your suggestion. But for now we will rely on the default library configuration of vue-cli-service.

**Comment by sense-it-gmbh** [comment]
@elevatebart the solution I came up with now is pretty much what you suggested. This has even more advantages than just being able to share docs for mixins across multiple libraries:
* Plain es6 modules, no boilerplate, no need to consume c2js in webpack/rollup
* Better debugging (no need for sourcemaps)
* More fine-control on usage of transpilers like babel (requires vue.config.js: `transpileDependencies` though)
* Ability to split Webpack-chunks (not possible on c2js/umd builds as far as i know)


*What I'm doing now:*
1. Use the Webpack-Copy-Plugin
2. Copy the required directories from 'src' to 'lib'
3. Use callbacks to refactor all import/require/export...from statements
   * determine relative path for each aliased import
   * adjust folder structure to our needs
4. [optional] Use the Webpack-Clean-Plugin to remove the 'lib' contents before the build
5. [optional] Use the Webpack-Clean-Plugin to remove the 'demo.html' from dist after build
6. Access everything via `my-package-name/lib/components` ... `my-package-name/lib/mixins` ... `my-package-name/lib/utils`
   * for shorter syntax I'm using a webpack alias: `'myLib@/': 'my-package-name/lib/'` -> `myLib@/components`, `myLib@/mixins`, `myLib@/utils` 

---

**/build/paths.js**:
```js
const path = require('path')

module.exports = {
  dist: path.resolve(__dirname, '..', 'dist'),
  src: path.resolve(__dirname, '..', 'src'),
  tests: path.resolve(__dirname, '..', 'tests'),
  lib: path.resolve(__dirname, '..', 'lib')
}
```

**/build/transform.js**:
```js
const path = require('path')
const fs = require('fs')

const paths = require('./paths')

const regImportsStatic = /(import|export)\s*((?:(?!from).|\n|\r)*)\s*from\s*(["'])(@\/.*?)\3/i
const regImportsStaticGlobal = /(import|export)\s*((?:(?!from).|\n|\r)*)\s*from\s*(["'])(@\/.*?)\3/ig

const regImportsDynamic = /(import|require)\((['"`])(@\/.*?)\2\)/i
const regImportsDynamicGlobal = /(import|require)\((['"`])(@\/.*?)\2\)/gi

function translateAlias (filePath, alias) {
  // replace alias with its absolute path
  const absoluteSrc = alias.replace('@', paths.src)

  // relative path from the file to the import-src
  let relativeSrc = path.relative(filePath, absoluteSrc)
    // normalize separator to '/'
    .replace(/\\/g, '/')
    // remove first '../' since import without ending is interpreted as directories
    .replace(/^\.{2}\//, '')

  // add './' so imports will always be recognized as relative path
  return `./${relativeSrc}`
}

function transformAliasDynamic (content, filePath) {
  const imports = content.match(regImportsDynamicGlobal)

  if (Array.isArray(imports)) {
    for (const importStmt of imports) {
      const [
        ,
        type,
        quote,
        pathAliased
      ] = importStmt.match(regImportsDynamic)

      const relativeSrc = translateAlias(filePath, pathAliased)

      content = content.replace(importStmt, `${type}(${quote}${relativeSrc}${quote})`)
    }
  }

  return content
}

function transformAliasStatic (content, filePath) {
  const imports = content.match(regImportsStaticGlobal)

  if (Array.isArray(imports)) {
    for (const importStmt of imports) {
      const [
        ,
        type, // import|export
        importList,
        quote,
        pathAliased
      ] = importStmt.match(regImportsStatic)

      const relativeSrc = translateAlias(filePath, pathAliased)

      content = content.replace(importStmt, `${type} ${importList} from ${quote}${relativeSrc}${quote}`)
    }
  }

  return content
}

module.exports.transformAlias = function transform (content, filePath) {
  // convert file-content to string
  content = content.toString()
  // convert dynamic imports with `const x = import('...')`
  content = transformAliasDynamic(content, filePath)
  // convert static imports with `import { x } from '...'`
  content = transformAliasStatic(content, filePath)

  return content
}

module.exports.transformPath = function transformPath (targetPath, absolutePath) {
  // just remove the src from the target path; else lib folder will be like '/lib/src/**/*'
  return targetPath.replace(/[/\\]src/, '')
}
```

**/vue.config.js**
```js
const path = require('path')

const CopyPlugin = require('copy-webpack-plugin')
const { CleanWebpackPlugin } = require('clean-webpack-plugin')

const {
  transformAlias: transform,
  transformPath
} = require('./build/transform')
const paths = require('./build/paths')

const styleguide = require('./styleguide.config')

let publicPath = '/'
if (
  process.env.npm_lifecycle_event === 'serve:docs' ||
  process.env.npm_lifecycle_event === 'build:docs'
) {
  publicPath = styleguide.styleguidePublicPath
}

const externals = /^((?:!?vue-i18n.*)|(?:vue)|(?:core-js)|(?:!?vuetify.*))$/i
let done = false

module.exports = {
  chainWebpack: config => {
    // only add plugins on the first iteration (there will be 3)
    if (!done) {
      done = true
      config.plugin('cleanup')
        .use(CleanWebpackPlugin, [{
          // delete contents of lib before build
          cleanOnceBeforeBuildPatterns: [path.join(__dirname, 'lib', '**', '*'), `!${paths.dist}`],
          // delete demo.html after building
          cleanAfterEveryBuildPatterns: ['demo.html'],
          dry: false,
          verbose: false,
          cleanStaleWebpackAssets: false,
          protectWebpackAssets: true,
          // needed, otherwise it will skip 'lib' because its not below 'dist'
          dangerouslyAllowCleanPatternsOutsideProject: true
        }])
        .before('vue-loader')

      const copyArg = {
        from: './src/@(components|directives|format|locales|mixins|utils|assets)/**/*',
        to: paths.lib,
        ignore: ['*.md', '*.example.vue'],
        copyUnmodified: true,
        transform,
        transformPath
      }

      // with `vue-cli-service build --target lib` the copy plugin listed by `vue inspect` is missing
      if (config.plugins.has('copy')) {
        config.plugin('copy')
          .tap(([args]) => {
            if (!args) {
              args = []
            }

            args.push(copyArg)

            return [args]
          })
      } else {
        config.plugin('copy')
          .use(CopyPlugin, [[copyArg]])
      }
    }
  },
  configureWebpack: {
    externals: process.env.NODE_ENV === 'production' ? externals : {},
    resolve: {
      alias: {
        '#': paths.tests
      }
    },
    plugins: [
    ]
  },
  lintOnSave: false,
  publicPath: publicPath,
  pluginOptions: {
    i18n: {
      localeDir: 'locales',
      enableInSFC: false
    }
  }
}

```

As far as it concerns me this issue is solved.

**Comment by elevatebart** [comment]
Thank you for sharing!! 
Great work!
