### ISSUE TITLE
components support the file entry of .js

### ISSUE THREAD

**Issue by lefreet** [vue-styleguidist/vue-styleguidist#713]
hello, in my project,  to unify entry for every component, like this

<img width="691" alt="WX20200116-163731@2x" src="https://user-images.githubusercontent.com/25679627/72507286-941a2e80-387e-11ea-935e-7034a6fe0d44.png">

every component's entry is `index.js`, so that we can import it by name convenient. so when i try import them to `styleguidist` => `components: '........./components/**/index.js'`, and it no use

so, has some way to import all of name, because that i don't know team members how to named the entry `.vue` file.

now i try to use `components: function () {  glob('........./components/**/index.js') }` and then resolve the 'index.js' to see how it import the `.vue` entry file. it's dirty

**Comment by elevatebart** [comment]
Hello @lefreet 

You have an uncommon case here.
I do not know if this is a common pattern.

Could you explain again why documenting only `.vue` files did not work in your case?

styleguide.config.js
```js
module.exports = {
	// find all vue files in components to render their documentation
	components: 'src/components/**/[A-Z]*.vue',
	// make sure the path line goes to what you expect
        getComponentPathLine(componentPath) {
		const path = path.dirname(componentPath)
		const name = path.basename(path)
		return `import ${name} from '${path}';`
	},
	// tell styleguidist where to find the readme
	getExampleFilename(componentPath) {
		return componentPath.replace(/\.vue?$/, '.examples.md')
	}
}
```

I see one issue here: What should happen if you have more than one component in a directory?

Did I understand your request right?

**Comment by elevatebart** [comment]
After looking closely at the code of styleguidist, your example should work.

What do you see that does not work? Is it default names of components in the examples?

**Comment by elevatebart** [comment]
Perfect, that helps a lot. 
The problem is that by default docgen ignores all imports from node_modules.
Try using [validExtends](https://vue-styleguidist.github.io/Configuration.html#validextends) like so in your `styleguide.config.js`

```js
{
   // but it not find any file
    components: '../node_modules/@idev0/wutip/src/controls/**/index.js' // my project with lerna
   // allow docgen to import files from your library
   validExtends(fullFilePath) {
    return (
      /[\\/]@idev0[\\/]wutip[\\/]/.test(fullFilePath) ||
      !/[\\/]node_modules[\\/]/.test(fullFilePath)
    )
    }
}
```

**Comment by lefreet** [comment]
@elevatebart i try it and not done.

with out the `validExtends` 's disturb, I change the `components: ../packages/wutip/src/controls/ebi-input/index.js`(by lerna)

i see some code in `vue-docgen-api`. that the really entry of my component  is by `import`, like this

```js
import EbiInput from './input.vue'
```
so the entry is 'input.vue'. but i find that it's got a `componentDefinitions` with `size === 0` in `parse-script.js`.

and more, the `resolveIdentifier.js` is only visit the `ast` with `visitVariableDeclaration` or `visitClassDeclaration`. is some wrong here ?

**Comment by lefreet** [comment]
so, it's mean that the `components` is only get the file directly,  not allow a file depend another file ?

**Comment by lefreet** [comment]
i will use the `glob && parse string` to resolve it for the time being.  and look forward to a better solution for it,  thanks.

**Comment by elevatebart** [comment]
> and more, the resolveIdentifier.js is only visit the ast with visitVariableDeclaration or visitClassDeclaration. is some wrong here ?

Yes, it's likely missing a part. 
Would you like to experiment trying it out making a PR?

I would totally see as well `resolveExportedComponent` returning more.
We could leverage `resolveRequired` to parse transient documentation.

resolveExportedComponent would return component babel nodes and ImportedVarSets like below

https://github.com/vue-styleguidist/vue-styleguidist/blob/db2676a4751b432f3c83b6f7369397c2e65bd456/packages/vue-docgen-api/src/utils/resolveRequired.ts#L12-L14

Then we would return the documentations of these IEV as if they were those of the current file.

**Comment by elevatebart** [comment]
I believe I have the beginning of a solution in this PR: #718
