### ISSUE TITLE
Windows line ending causing build error in version 1.4.3

### ISSUE THREAD

**Issue by BrockReece** [vue-styleguidist/vue-styleguidist#72]
Looks like we have the same issue as #36 again.

```
yarn run v1.3.2
$ vue-styleguidist server
env: node\r: No such file or directory
error Command failed with exit code 127.
```

Your `.editorconfig` file looks correct, I wonder why your IDE is ignoring it?

**Comment by rafaesc** [comment]
Hi @BrockReece,

Its a problem, because every time I'm going to publish a new version, always I have to convert from dos to unix.
Please upgrade to version 1.4.4.

Thanks!

**Comment by BrockReece** [comment]
Would this be something that a CI could do for you?

**Comment by rafaesc** [comment]
Yes, in fact, it is something that I should have done,
But I keep doing it manually, 

Thanks for your help, I can develop this task in CI.
But I need help to this issue
https://github.com/vue-styleguidist/vue-styleguidist/issues/64

**Comment by BrockReece** [comment]
Possibly, I will have a proper look later and let you know.

**Comment by rafaesc** [comment]
Excellent, thanks!
