### ISSUE TITLE
Extract $emit from template

### ISSUE THREAD

**Issue by protium-dev** [vue-styleguidist/vue-styleguidist#725]
## Description

For some basics components, I just use `$emit('onClick', $event)` from the template.

## Proposal 
Search for `$emit` inside the template and extract the name of the event emitted.

## Expected result
Generates automatically the docs for `$emit` used within templates.

**Comment by elevatebart** [comment]
Hello @protium-dev 

You are right, it is the intention of docgen, I just never got around to do it.
Describing the events when combined with slots and props is promised to not be that easy.

I suggest a format along the lines of this

```html
<template functional>
  <!-- @prop {string} id name attribute of the button -->
  <!-- 
    @event {string} click happens on click of the button 
    @property {string} id name attribute of the button
  -->
  <button :name="props.id" style="background:pink" @click="$emit('click', props.id)">
    <!-- @slot name of the button -->
    <slot/>
  </button>
</template>
```

The two comment blocks would be independent of course.
Do you think this would be OK?

**Comment by protium-dev** [comment]
Yes I could totally use that. But I would like vue-styleguidist to extract this info without requiring doc comments so I can avoid to document them like `@event {Event}` to get them parsed.
I took a look to the source code, if you guide me a bit I could work on this and drop a PR :)
