### ISSUE TITLE
Getting an error since version 4.5.2

### ISSUE THREAD

**Issue by JonasNiestroj** [vue-styleguidist/vue-styleguidist#731]
**Current behavior**

While compiling the styleguide im receiving this error: 

`13% building 31/42 modules 11 active /Users/jonas/Documents/source/forge/frontend/node_modules/react-dev-utils/node_modules/sockjs-client/lib/entry.js(node:4274) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'events' of undefined
    at Object.vuedocLoader (/Users/jonas/Documents/source/forge/frontend/node_modules/vue-styleguidist/lib/loaders/vuedoc-loader.js:83:29)
(node:4274) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4274) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**To reproduce**

I dont really know how to reproduce the error. I just upgraded vue-styleguidist from version 4.2.1 to the newest one 4.7.2.
I tried the other versions of vue-docgen-api (In which the error seems to be) and its working till 4.5.0. The error appears in version 4.5.2.

**Expected behavior**

The normal behavior is that i can serve the styleguide without an error.

**Comment by JonasNiestroj** [comment]
Just discovered how to reproduce the error. If you create a .vue file with only a docs section the error appears. Is this the expected behavior?

**Comment by elevatebart** [comment]
Hello @JonasNiestroj 

This is not the expected behaviour. I was not expecting someone to make a `.vue` file with only docs though ;-).
I will test and try preventing the error.

**Comment by JonasNiestroj** [comment]
> Hello @JonasNiestroj
> 
> This is not the expected behaviour. I was not expecting someone to make a `.vue` file with only docs though ;-).
> I will test and try preventing the error.

Hello @elevatebart 
Thank you for your answer.
Maybe a short explanation: I have Vue files with only docs, because I want to show the different button styles and i don't need a component for that. Maybe im doing it in the wrong way.

**Comment by elevatebart** [comment]
Hello Jonas,

You did not do wrong, I would probably have used a markdown file myself because I know haw the system works on the inside. I would have to add the markdown as content instead of components in the section definition of your styleguide.config.js.

I still intend to make docs only vue file work ;)

Bart Ledoux

Join me on LinkedIn
Or as @elevatebart on Discord, Twitter and Github
