### ISSUE TITLE
Description ignored when props have similar names

### ISSUE THREAD

**Issue by lancetharper** [vue-styleguidist/vue-styleguidist#74]
```
props: {
    /**
     * Number of columns (1-12) the column should span.
     */
    span: {
      type: [String, Number],
    },
    /** Sm breakpoint and above */
    spanSm: {
      type: [String, Number],
    },
}
```

![screen shot 2018-01-12 at 4 07 07 pm](https://user-images.githubusercontent.com/4389981/34900202-bd48bfec-f7b2-11e7-8802-9e9a52b82cb4.png)

### If there are more, only the description of the first is ignored.

```
props: {
    /**
     * Number of columns (1-12) the column should span.
     */
    span: {
      type: [String, Number],
    },
    /** Sm breakpoint and above */
    spanSm: {
      type: [String, Number],
    },
    /** Md breakpoint and above */
    spanMd: {
      type: [String, Number],
    },
}
```
![screen shot 2018-01-12 at 4 11 56 pm](https://user-images.githubusercontent.com/4389981/34900279-70172e42-f7b3-11e7-86b2-2c3315c68323.png)

### It's also order dependent because putting `span` after `spanSm` works.
```
props: {
    /** Sm breakpoint and above */
    spanSm: {
      type: [String, Number],
    },
    /**
     * Number of columns (1-12) the column should span.
     */
    span: {
      type: [String, Number],
    },
    
}
```
![screen shot 2018-01-12 at 4 15 58 pm](https://user-images.githubusercontent.com/4389981/34900339-eb76fce8-f7b3-11e7-9c2f-91344f35e724.png)

**Comment by rafaesc** [comment]
Hi @lancetharper,

update vue-styelguidist on last version, because it was fixed.

Regards!

**Comment by lancetharper** [comment]
I'm on 1.4.6 (latest on npm) and it is still broken

**Comment by rafaesc** [comment]
Ok, I will work on that.

Regards!

**Comment by rafaesc** [comment]
Hi @lancetharper,

I couldn't replicate the problem, you can clone this project because I think that it was fixed 

https://github.com/rafaesc/vue-styleguidist-demo/tree/fix-74

On branch "fix-74",

I forgot that also you have to update `vue-styleguidist` and `vue-docgen-api` with version latest,

Please tell me if the problem still appears,

Regards

**Comment by lancetharper** [comment]
I updated to 1.4.8 this morning and this seems to have been fixed.

Thanks!
