### ISSUE TITLE
build overwrites index.html in dist

### ISSUE THREAD

**Issue by joroe** [vue-styleguidist/vue-styleguidist#742]
**Current behavior**
styleguide:build copies/overwrites index.html from /public to /dist
(with styleguideDir beeing default 'styleguide' or any other folder)

**To reproduce**
setup a fresh vue app and vue-styleguidist
yarn build
yarn styleguide:build

**Expected behavior**
no changes in /dist

**Comment by elevatebart** [comment]
Do you use the vue cli? Did you use the plugin?

**Comment by joroe** [comment]
yes
`"vue-cli-plugin-styleguidist": "^3.25.0"`

**Comment by elevatebart** [comment]
This line is fixing the bug you are seeing
https://github.com/vue-styleguidist/vue-styleguidist/blob/cca6bb4866714e9e1f9646d7dbed16436fa0cf72/packages/vue-cli-plugin-styleguidist/index.js#L83

#615

**Comment by elevatebart** [comment]
Can you lease upgrade to 4.0.2 (at least) and test again?
I think you will like the ui improvements that were made.

**Comment by elevatebart** [comment]
@joroe, did updating fix your bug?

**Comment by joroe** [comment]
It did and I forgot to close this. Thanks!
