### ISSUE TITLE
Docgen cannot find imported dependencies in custom webpack 'modules' paths

### ISSUE THREAD

**Issue by yellowsunday** [vue-styleguidist/vue-styleguidist#743]
**Current behavior**

When the styleguide parses a .vue containing an import statement that references a file relative to a custom source directory that was defined in the webpack config "resolve.modules", it cannot find it and prints an error of the form:

> Neither 'foo/bar.js.vue' nor 'foo/bar.js.js(x)' or 'foo/bar.js/index.js(x)' or 'foo/bar.js/index.ts(x)' could be found in '/media/path/to/src/components'

**To reproduce**

I encountered this with a webpack config that had 'modules' in the webpack config with two absolute file paths, the first to the source directory and the second to the node_modules. The Vue component was importing a JS util file using a path relative to the source directory. 

In this case, I found that editing `node_modules/vue-docgen-api/dist/utils/documentRequiredComponents.js` made the error go away:

```
     // added opt.modules as 3rd argument
      pathResolver = makePathResolver_1.default(originalDirName, opt.alias, opt.modules);
```

I tried to reproduce it with the Basic example, and it was similar though not precisely the same - I modified the examples/basic/styleguide.config.js with:

```
    webpackConfig: {
        resolve: {
            modules: [
               path.resolve(__dirname, "../"),   // i.e. the 'examples' folder
               path.resolve(__dirname, "../../node_modules"),
               // also had to add this to fix startup errors
               path.resolve(__dirname, "../../packages/vue-styleguidist/node_modules")
            ],
            alias: ...etc
        }
    }
```
and the Button.vue to use:  `import loggerMixin from 'basic/src/mixins/loggerMixin'`

This time it seems to get fixed by passing in the opt.modules in the `packages/vue-docgen-api/dist/script-handlers/mixinsHandler.js`. I guess this might be because it's actually a mixin being imported instead of a simple JS.

**Expected behavior**

No console error is printed.

I'm a little surprised that I haven't run into this before, but perhaps it's more usual for projects to define an alias to their source folders instead of adding them to the module paths.

Thanks in advance for looking at this!

**Comment by elevatebart** [comment]
Hey @yellowsunday 

It looks like a pretty straight forward bug you already have found ;)
I completely missed this "module" in the code

https://github.com/vue-styleguidist/vue-styleguidist/blob/cca6bb4866714e9e1f9646d7dbed16436fa0cf72/packages/vue-docgen-api/src/utils/documentRequiredComponents.ts#L24-L28

If you find the time, since you found the bug I think you should get the glory.

Do you have time for a quick PR?

**Comment by elevatebart** [comment]
And it is the result of a recent refactoring I did for 4.5 #713

**Comment by yellowsunday** [comment]
Great thanks! Hopefully the PR is ok now. The commit message is harder than the fix :) BTW, the CONTRIBUTING.md mentions a 'npm run commit' helper script that doesn't seem to be there, is it just out-of-date docs?

**Comment by elevatebart** [comment]
it is just out of date docs. Will fix it this morning
