### ISSUE TITLE
vue-docgen-api + property decorator: @ignore doesn't work

### ISSUE THREAD

**Issue by ftes** [vue-styleguidist/vue-styleguidist#748]
**Current behavior**
```
@Component
export default class HelloWorld extends Vue {
  /**
   * Message.
   * @ignore
   */
  @Prop() private msg!: string;
}
```
![image](https://user-images.githubusercontent.com/2614732/74236141-e0675b80-4cd0-11ea-95d5-71cd78611f70.png)

**To reproduce**

https://github.com/ftes/vue-dogen-property-decorator-ignore-issue/blob/master/src/components/HelloWorld.vue#L40

**Expected behavior**

The prop should not appear in the generated props table because it is `@ignore`d.

**Comment by elevatebart** [comment]
@pocka, In vue styleguidist, this is handled in the vuedoc-loader.

https://github.com/vue-styleguidist/vue-styleguidist/blob/a9016033f548493486a20ccc32aa7c6ceec02bac/packages/vue-styleguidist/src/loaders/vuedoc-loader.ts#L97-L101

Would you mind dealing with `@ignore` in your loader too?

**Comment by pocka** [comment]
@elevatebart No, `vue-docgen-loader` should implement it too. Is `@ignore` applied to only props, not to methods or events?

**Comment by elevatebart** [comment]
I believe it should work on **props**, **events** and **slots**.
As of today, it only works for **props** on vue-styleguidist.
 
**Methods** are most often internals of components and should not be documented for external usage.

I think VSG 5 should have a story to implement `@ignore` for slots and events.

What do you think?

**Comment by elevatebart** [comment]
I could as well implement it in vue-docgen's next major version to ignore it all there.

**Comment by pocka** [comment]
Okay, I'm going to add support for `@ignore` for props, slots, and events. Also, it would be great if vue-styleguidist does `@ignore` slots and events, IMHO.

> I could as well implement it in vue-docgen's next major version to ignore it all there.

I like the idea!

**Comment by pocka** [comment]
I've just published `vue-docgen-loader@1.4.0`, which includes support for `@ignore` JSDoc tag for props and events. Not for slots since `SlotDescriptor` has no `tags` property (I don't know it's intended or not).

**Comment by elevatebart** [comment]
docgen 4.8 allows you to add tags to slots documentation ;-)

**Comment by ftes** [comment]
Wow, I'm blown away by the response speed @elevatebart @pocka.
A big thanks to both of you.
