### ISSUE TITLE
Vue packages version mismatch

### ISSUE THREAD

**Issue by zhuqingguang** [vue-styleguidist/vue-styleguidist#762]
**Current behavior**

I'm trying to use styleguide in one package of my **monorepo**, but I encounter a question:
```bash
Vue packages version mismatch:


- vue@2.6.9 (/Users/guang/Documents/ks/kuaishou-frontend-admin/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/Users/guang/Documents/ks/kuaishou-frontend-admin/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
```
**To reproduce**

**Expected behavior**

**Comment by elevatebart** [comment]
Great question

This is usually because two of you r package ask for different versions of Vue and the vue compiler.
I would probably look for the string `2.6.9` in all the yarn.lock or package-lock.json and in the package.json and replace it with 2.6.10.

Tell me if it helps ;-)

**Comment by zhuqingguang** [comment]
Thank you very much, it works!
