### ISSUE TITLE
Some components don't appear since v4 - work fine with 3.26.2

### ISSUE THREAD

**Issue by dflock** [vue-styleguidist/vue-styleguidist#772]
**Current behavior**

I have a collection of components that I'm using with styleguidist. These all render fine with v3.26.2, but if I upgrade to any post v4 version of styleguideist, 3 of the components disappear from the styleguide.

There are no errors in the browser console when viewing the styleguide.

**To reproduce**

Yeah, this is a really good question - I'm not sure what's different about those three components.

If I run the styleguide build with `--verbose` using both v3 and v4, this is the output:

[styleguideist-3-build.log](https://github.com/vue-styleguidist/vue-styleguidist/files/4269794/styleguideist-3-build.log)
[styleguideist-4-build.log](https://github.com/vue-styleguidist/vue-styleguidist/files/4269795/styleguideist-4-build.log)

These logs are mostly the same, with a few small differences, but it's not clear to me what's causing them.

How can I debug this further?

**Expected behavior**
I expect all my components to render, or a simple error message telling me which ones get skipped and why.

**Comment by elevatebart** [comment]
if a component does not parse correctly in docgen it will be ignored...

**Comment by elevatebart** [comment]
@dflock have you tried having only one of these components in your design system?

**Comment by elevatebart** [comment]
Hello @dflock, 

The way I would go about it is

1. Try each component with vue-docgen-api parser only. 
get inspiration from this codesandbox by @pocka
https://codesandbox.io/s/vue-docgen-api-html-comment-4zgc3

2. Remove the docs from each of those components and render them in the styleguide in isolation.

Can you share your disappearing component's code somehow?

**Comment by elevatebart** [comment]
If you install the last version, I fixed the implementation of the logger... it was broken.

**Comment by dflock** [comment]
Thanks - I will try all of those things tomorrow and let you know how I get on.

**Comment by dflock** [comment]
So, I updated to the latest version, with the verbose fixes (thankyou!) - and I now get warnings for the components that don't show up. The warning are all very similar:

```
Warning: Error parsing src/components/One.vue: SyntaxError: Unexpected token (2:14)

Warning: Error parsing src/components/Two.vue: SyntaxError: Unexpected token, expected "," (3:14)

Warning: Error parsing src/components/Three.vue: SyntaxError: Unexpected token, expected "," (3:12)

Warning: Error parsing src/components/Four.vue: SyntaxError: Unexpected token, expected "," (3:18)
```

Odd that they're (almost) all on line 3? :thinking: 

If we look at the first 25 lines of one of these components, it looks like this:

```vue
<template lang="html">
  <div :class="routeName" class="basic-crud-list">
    <page-header
      v-if="showHeader"
      :route-name="routeName"
      :route-icon="routeIcon"
      :show-action-menu="true"
    >
      <template #action-menu-items>
        <b-dropdown-item-button @click="refreshTable()">
          <fa :icon="['far', 'sync']" fixed-width />
          {{ `Refresh ${$t(routeName + '.label')} list` }}
        </b-dropdown-item-button>
        <auto-refresh :route-name="routeName" />
        <b-dropdown-item
          v-if="$hasAuth(itemRouteNameNew, 'routeRoles') && allowNewItem"
          :to="{
            name: itemRouteNameNew || itemRouteName,
            params: itemRouteParams
          }"
        >
          <fa :icon="['far', routeIcon]" fixed-width />
          {{ `${$t(listRouteName + '.new')}...` }}
        </b-dropdown-item>
      </template>
    </page-header>
```

Which I can't really see anything wrong with?

- All of these components have had prettier & eslint run on them with zero issues, etc...
- I still get the same warnings and nothing showing up if I rename the components .md files, just to rule that out.
- If I change the `styleguide.config.js` to only inclyde on of these, I just get a blank styleguide; I still get the sidebar, etc... - just no component.
- The files only contain ascii chars, no invisible gremlins.

Going to see if I can figure out the docgen parser thing now.

**Comment by elevatebart** [comment]
Hello @dflock,

That is progress indeed.
It is very possible that the error you are getting come exclusively from the script.

What is on the first lines of the script of those 4 components?

**Comment by dflock** [comment]
I don't see anything obviously wrong with the script sections either. Here are the first 5 lines of each:

### one.vue (SyntaxError: Unexpected token (2:14)):
```vue
<script>
import { EventBus } from '@/EventBus'
import HelpIcon from '@/components/help/HelpIcon'
import ProcessHistorySectionStats from './ProcessHistorySectionStats.vue'
import ProcessHistoryDeriveErrors from './ProcessHistoryDeriveErrors.vue'
import PageHeader from '@/components/common/PageHeader.vue'
```

### two.vue (Unexpected token, expected "," (3:14)):
```vue
<script>
/**
 * Configurable list component.
 */
import { EventBus } from '@/EventBus'
import PageHeader from '@/components/common/PageHeader.vue'
```

### three.vue (Unexpected token, expected "," (3:12)):
```vue
<script>
/**
 * Display an individual row filter rule
 */
export default {
  name: 'RowFilterRule',
  props: {
```

### four.vue (SyntaxError: Unexpected token, expected "," (3:18)):
```vue
<script>
import {
  abstractField,
  validators,
  component as VueFormGenerator
} from 'vue-form-generator'
import { popupHelpMixins } from '@/mixins/popupHelp'
```

**Comment by dflock** [comment]
If I replace the code of `component.vue` in your codesandbox for vue-docgen-api, I get an eslint error, which looks similar:

![Screenshot_2020-03-02_16-50-54](https://user-images.githubusercontent.com/47756/75732444-58f58280-5ca7-11ea-887a-f572934bbac2.png)

Could be co-incidence - but my build logs from earlier have complaints from acorn that also look similar?

**Comment by dflock** [comment]
OK, here if a fork of that codesandbox, with code from two.vue in component.vue: https://codesandbox.io/s/vue-docgen-api-html-comment-ixbfy

Here's what's in the console:

```
{ SyntaxError: Unexpected token, expected "," (3:16)
    at Object.raise (/sandbox/node_modules/@babel/parser/lib/index.js:7013:17)
    at Object.unexpected (/sandbox/node_modules/@babel/parser/lib/index.js:8384:16)
    at Object.expect (/sandbox/node_modules/@babel/parser/lib/index.js:8370:28)
    at Object.parseParenAndDistinguishExpression (/sandbox/node_modules/@babel/parser/lib/index.js:9766:14)
    at Object.parseExprAtom (/sandbox/node_modules/@babel/parser/lib/index.js:9560:21)
    at Object.parseExprSubscripts (/sandbox/node_modules/@babel/parser/lib/index.js:9219:23)
    at Object.parseMaybeUnary (/sandbox/node_modules/@babel/parser/lib/index.js:9199:21)
    at Object.parseMaybeUnary (/sandbox/node_modules/@babel/parser/lib/index.js:6265:20)
    at Object.parseExprOps (/sandbox/node_modules/@babel/parser/lib/index.js:9067:23)
    at Object.parseMaybeConditional (/sandbox/node_modules/@babel/parser/lib/index.js:9040:23)pos: 57, loc: Position { line: 3, column: 16 } }
> Sandbox Container: Sandbox ixbfy started
```

**Comment by dflock** [comment]
If I put the whole of two.vue into here: https://babeljs.io/repl I get this error:

![image](https://user-images.githubusercontent.com/47756/75733067-1df44e80-5ca9-11ea-99fa-2b5e187cb05b.png)

If I just put the code inside the `<script>` part, babel works fine, with no errors.

**Comment by elevatebart** [comment]
I found the problem. 
docgen does not like multi-line expressions in `@click`.
I fixed the issue and added a bit more details in errors.

**Comment by dflock** [comment]
Ah, like this one:

```js
@click="
  criteria = null
  refreshTable()
"
```

... I would never have found that :joy: thanks for all your hard work!
