### ISSUE TITLE
.pug support in docs (.md) files

### ISSUE THREAD

**Issue by vbabenko** [vue-styleguidist/vue-styleguidist#773]
**The problem**
There is no way to use `.pug` syntax in docs (`.md`) file. I have pug templates for my vue components, but for examples in documents I need to use html template

**Proposed solution**
Current behavior
`// button.md`
```vue
<template>
  <my-button>Fancy button </my-button>
</template>
```
Expected behavior:
`// button.md`
```vue
<template lang="pug">
  my-button Fancy button
</template>
```

**Alternative solutions**

**Additional context**

**Comment by elevatebart** [comment]
That is a great idea. For now the inbrowser compiler only allows pure HTML and pure css.

What I would like to allow is to customize the compiler by adding what you need (sass, pug, less, maybe even typescript) to the compiler.

Would you be interested in making a pull request? That would be super helpful.
