### ISSUE TITLE
Exported files not named

### ISSUE THREAD

**Issue by cssinate** [vue-styleguidist/vue-styleguidist#778]
**Current behavior**

Vue files exported with names still have `exportName` set to `default`

**To reproduce**

Create three files:

```
// MyComponent.vue

<template><div></div></template>
<script>
export default {
name: 'MyComponent'
}
<script>
```

```
// exporter.js

import FirstComponent from './MyComponent.vue'
export { MyComponent }
```

```
// proof.js

const vueDocs = require('vue-docgen-api')
vueDocs.parseMulti('./exporter.js').then(component => {
console.log(component.exportName)
})
```

The last file, when run, results in `default`
**Expected behavior**
I had expect the last file to result in a log of `FirstComponent`

I'm not sure if this is intended or not. When I tried to describe the issue on Discord, @elevatebart seemed to think it was not correct, which admittedly may have been my own poor explanation.

**Comment by elevatebart** [comment]
Thank you @cssinate
