### ISSUE TITLE
"Failed to mount component: template or render function not defined" when running `npm run styleguide`

### ISSUE THREAD

**Issue by alexcushing** [vue-styleguidist/vue-styleguidist#787]
I get the following errors for all my components when trying to add styleguidest to an existing repo that is imported to other projects like a library as a submodule 

```
[Vue warn]: Failed to mount component: template or render function not defined.

found in
---> <Modal> at vue/Modal.vue
       <Anonymous>
         <Root>
```

The structure is 
```
- - vue/
- - - - Modal.vue
- - - - OtherComponents.vue
- - scss/
- - - - Modal.scss
- - - - OtherComponents.scss
- - styleguide.config.js
- - webpack.config.js
```

The styleguide config looks like this 

```
module.exports = {
	title: 'Style Guide',
	components: './vue/**/[A-Z]*.vue',
	defaultExample: true,
	webpackConfig: require('./webpack.config'),
	exampleMode: 'expand'
}
```

and the webpack config is

```
const path = require('path');

module.exports = {
  module: {
    rules: [
      {
        include: [
          path.resolve(__dirname, "vue")
        ],
        exclude: /node_modules/,
        loader: "vue-loader"
      },
      {
        test: /\.js?$/,
        exclude: /node_modules/,
        loader: "babel-loader"
      },
      {
        include: [
          path.resolve(__dirname, "scss")
        ],
        loader: "sass-loader"
      }
    ]
  }
};

```

Any thoughts why this would be happening?

**Comment by elevatebart** [comment]
Hello @alexcushing this looks like an issue with the inbrowser compiler.
Would you be so kind and create a repro repo on codesandbox?

<a href="https://codesandbox.io/s/github/vue-styleguidist/vue-styleguidist-example">
    <img src="https://codesandbox.io/static/img/play-codesandbox.svg" alt="Start documenting"/>
</a>

**Comment by alexcushing** [comment]
@elevatebart will do, awesome talk at vue conf by the way

**Comment by elevatebart** [comment]
You rock ! and thank you \o/

**Comment by elevatebart** [comment]
I see that in your webpack config you do not use the VueLoader plugin. Is it on purpose of an woops ?

**Comment by elevatebart** [comment]
https://vue-loader.vuejs.org/guide/#manual-setup

**Comment by alexcushing** [comment]
lol wow look at me not reading the documentation closely enough, while tying to make my own documentation. Good catch, that's gotta be it @elevatebart

**Comment by elevatebart** [comment]
@alexcushing can you close this issue if it is fixed?

**Comment by elevatebart** [comment]
feel free to re-open if needed
