### ISSUE TITLE
cannot resolve prop type with vue-property-decorator in typescript

### ISSUE THREAD

**Issue by zhuqingguang** [vue-styleguidist/vue-styleguidist#791]
I am using` vue-property-decorator` in typescript. And i declare an interface named FormData  which is used to prop type:
```ts
@Prop({ type: Object, required: true }) data!: PropData
```
and rendered page is show as following:
![image](https://user-images.githubusercontent.com/24694223/76746354-5704e680-67b2-11ea-8f66-33c9991ed0d8.png)

My question is if we displayed more detail of the `FormData` ? 
For example, if `FormData`  is 
```
interface FormData { 
   key: string;
}
```
i can see the detail in prop table.

**Comment by elevatebart** [comment]
First, it is a great idea. 
Especially given that Vue 3 is getting more TS compatibility.
The information is not present yet in the result of the docgen parser. 

It will be very hard if the interface is in a different file, but I believe it can be super easy in the same file. 

Would you be interrested in trying your hand at a Pull Request ?
