### ISSUE TITLE
Using an alias on a mixin import results in "could not be found" warning

### ISSUE THREAD

**Issue by patric-eberle** [vue-styleguidist/vue-styleguidist#793]
**Current behavior**

vue-styleguidist: 4.13.1
webpack: 4.42.0

We import mixins via an alias. E.g. `import myMixin from '@/mixins/my-mixin'. Unfortunately, this causes vue-styleguidist to throw warnings, that the source for the import could not be found. It also does not work, if I add the file extension. Only relative paths seem to work.

```
ates.vue' nor '@/mixins/form-states.js(x)' or '@/mixins/form-states/index.js(x)' or '@/mixins/form-states/index.ts(x)' could be found in '/Users/patriceberle/Projects/valantic/vue-template/src/components'idist/lib/client/utils/handleHash.jsNeither '@/mixins/form-st
either '@/mixins/form-states.vue' nor '@/mixins/form-states.js(x)' or '@/mixins/form-states/index.js(x)' or '@/mixins/form-states/index.ts(x)' could be found in '/Users/patriceberle/Projects/valantic/vue-template/src/components'-template/src/components/c-form.scss
```

The warning seems to be thrown by the documentation part of vue-styleguidist, since the props, that are defined in the mixin are not documented in the styleguide, when I use the alias import. The component itself seems to work correct though.

**To reproduce**

1. Check out https://github.com/valantic/vue-template/tree/feature/4.0 (if branch should be merged, use current `development`).
2. Switch to Node 12.x and `npm ci`
3. Open `src/components/e-textarea.vue` and change the import `import formStates from '../mixins/form-states';` to `import formStates from '@/mixins/form-states';`
4. `npm run dev:s`

**Expected behavior**

No warning about missing import sources when using a webpack alias is used is shown.

**Comment by elevatebart** [comment]
@patric-eberle thank you for reporting it. I will try to have a look today.

**Comment by elevatebart** [comment]
I have noticed that you are using version `~3.0.2` is there a reason for not using 4.X.X?

**Comment by elevatebart** [comment]
I found the bug.
To send the alias to the parser, I forgot that `webpackConfig` could be a function. 
It is an easy fix, thank you for bringing it up.
