### ISSUE TITLE
Feature Request: @throws tag to parsable

### ISSUE THREAD

**Issue by fifzteen** [vue-styleguidist/vue-styleguidist#795]
**The problem**

I have some methods throws exception, and explain that exceptions by "@throws" JSDoc tag.
But when compling my codes, "@throws" tag lines are ignored. 

**Proposed solution**

Add "@throws" tag to parsable ones, and show the description of exception like @returns => Return:.

**Comment by elevatebart** [comment]
Hello @fifzteen 

The parser already returns "@throws" it in the free tags list but the rendering engine ignores it.
I will try to fix it.
