### ISSUE TITLE
Error when trying to run styleguide server

### ISSUE THREAD

**Issue by ymatuhin** [vue-styleguidist/vue-styleguidist#8]
`Error when parsing src/global-components/icon/index.vue: Error: The component has no name, add 'el' property on the Vue component.`

I have default vue app from vue-cli.
My config:
```
module.exports = {
  components: 'src/global-components/**/*.vue',
  webpackConfig: require('./build/webpack.dev.conf.js')
}
```

**Comment by ymatuhin** [comment]
My components js, scss and template are separated by files. For example:
```
<template>
  <i ng-if="hasIcon"
     class="icon fa"
     :class="[iconClass, iconColor]"
     :style="sizeStyle"
     aria-hidden="true">
  </i>
</template>

<script src="./index.js"></script>
<style src="./index.scss" lang="scss" scoped></style>
```

**Comment by rafaesc92** [comment]
Hello, what is the content of index.js?

**Comment by ymatuhin** [comment]
```
export default {
  props: {
    type: String,
    size: Number,
    color: String,
  },
  computed: {
    hasIcon() {
      return this.type.length > 0;
    },
    iconClass() {
      return this.type ? `fa-${this.type}` : '';
    },
    iconColor() {
      return this.color ? `c-${this.color}` : '';
    },
    sizeStyle() {
      return this.size
        ? `font-size: ${this.size / 10}rem;line-height: ${this.size / 10}rem`
        : '';
    },
  },
};
```

**Comment by rafaesc92** [comment]
Ok, You have to add the name component, like this
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/examples/basic/src/components/Button/Button.vue#L19

**Comment by ymatuhin** [comment]
Yeah, thanks. Now it works. I think you must note this somewhere in documentation, because name usually isn't required property (only for recursive component).

**Comment by rafaesc92** [comment]
Yes, it is true, I will improve the documentation to avoid confusion, regards

**Comment by rafaesc92** [comment]
Ok, update [documentation](https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Documenting.md)

> **Note:** The 'name' property in the component is mandatory, as it will be the component name to use in the examples. If you need to configure the component name before you document it, you can review the following [example](https://github.com/vue-styleguidist/buefy-styleguide-example/blob/master/styleguide.config.js#L43)
