### ISSUE TITLE
build and server has different behavior in  Nodejs Api

### ISSUE THREAD

**Issue by zhuqingguang** [vue-styleguidist/vue-styleguidist#800]
**Current behavior**
> vue-styleguidist@4.14.0

I am using **nodejs api** of vue-styleguidist in my command,but i get different behavior between `styleguide.build` and `styleguide.server` .

`styleguide.server()` works correctly but `styleguide.build()`  throw many error as follows:

![b1458225c95777b5ba636be699af10ea](https://user-images.githubusercontent.com/24694223/77632160-94266100-6f88-11ea-81e3-65035a9c44a2.png)

Some dependency is as follows:
![image](https://user-images.githubusercontent.com/24694223/77632547-1e6ec500-6f89-11ea-90c0-c3e207311f0f.png)

**To reproduce**

**Expected behavior**
when i run `styleguide.build` it should work correctly.

**Comment by elevatebart** [comment]
Hello @zhuqingguang 

It looks like one of your examples is not parsing properly and the node precompillation of the vue-inbrowser-compiler is not happy about it.

Can you try to isolate which example the parser does not like and pasete the code for this example here?

If you prefer a solution where everything works the same in serve and build, you can always disable [codeSplit](https://vue-styleguidist.github.io/Configuration.html#codesplit)

**Comment by zhuqingguang** [comment]
Sorry to bother you. Thanks to your advice, I find the problem. As i am introducing vue-styleguidist in my current project, there are some nonstandard `README.md`  in some components. Now I can build normally.

And I have two questions , could you have a look ? Or i should open a new Issue?

1. `vue-styleguidist` depends on `core-js@3.6.x` but there is no dependency in `package.json`.
    This cause version conflict with my project.
    Do you think it'a a good idea to add `core-js@3.6.x` in `package.json` ?
2. I have found  if I use a url string that starts with `//`, there will be an  error.
    code example:
   ```
      data() {
          return {
               img: '//www.baidu.com/img/baidu_resultlogo@2.png'
          };
      }
   ```
   error is shown as following:

![f049fd923ed44187b849b14fcb2fb89a](https://user-images.githubusercontent.com/24694223/77727704-dbb6f680-7035-11ea-9fec-04af88801dea.png)

**Comment by elevatebart** [comment]
Hello @zhuqingguang, 

I added the (much needed) dependency to core-js in vue-styleguidist 4.15.0.
Tell me if it helps.

Bart

**Comment by elevatebart** [comment]
Your second error is probably an issue in acorn, the parse behind babeljs that I use. I can try debugging it or updating it but you might have better luck talking to them directly.

**Comment by elevatebart** [comment]
@zhuqingguang would you please create a quick repo to show me the acorn issue?

I tried parsing :
```js
data() {
       return {
            img: '//www.baidu.com/img/baidu_resultlogo@2.png'
       };
   }
```

**Comment by zhuqingguang** [comment]
> Hello @zhuqingguang,
> 
> I added the (much needed) dependency to core-js in vue-styleguidist 4.15.0.
> Tell me if it helps.
> 
> Bart

Thank you very much! Now it will install core-js in its own  node_modules.

Sorry to reply so late. 😂

**Comment by zhuqingguang** [comment]
> @zhuqingguang would you please create a quick repo to show me the acorn issue?
> 
> I tried parsing :
> 
> ```js
> data() {
>        return {
>             img: '//www.baidu.com/img/baidu_resultlogo@2.png'
>        };
>    }
> ```
> 
> It works as a parser.

Probably you can close this issue if it parses successfully. I am trying to add vue-styleguidist in a big project and it's `webpack config` is very complex and is not a file . 
`webpack config` is used in cli with some args. I will try to  reproduct the issue later.
