### ISSUE TITLE
Document multiple file components in one markdown file

### ISSUE THREAD

**Issue by elevatebart** [vue-styleguidist/vue-styleguidist#809]
**The problem**

When a component has multiple parts it gets hard to document.

Say we use a composition API for a dropdown:

```vue
<Dropdown>
   <Option value="1">option - 1</Option>
   <Option value="2">option - 2</Option>
</Dropdown>
```

The option component should not appear in the sidebar and should probably not have an independent documentation entry/file. It should still be available in the docs examples and have its props documented.

**Proposed solution**

Have a `@requires` flag to tell what components are part of the current components scope.

in our case, it would look like this:

```js
/**
 * A dropdown component
 * 
 * @requires ./Option.vue
 * @requires ./OptionGroup.vue
 */
export default {
  name: 'Dropdown'
}
```

It would show all usage tabs one after the other under the same URL.
only display the main documentation.

**Implementation**

- [x] register additional components globally when they are in the requires
- [x] register them locally when registerLocally flag is on
- [x] display props info for extra components

**Comment by JessicaSachs** [comment]
This is super! I like this. It reminds me of Vuetify's way of grouping similar components that don't make sense outside of their parent context.

**Comment by elevatebart** [comment]
It is my inspiration indeed (and Bootstrap as well)
