### ISSUE TITLE
Incorrect array prop types when using vue-property-decorator

### ISSUE THREAD

**Issue by Djaler** [vue-styleguidist/vue-styleguidist#812]
**Current behavior**
Vue-styleguidist uses TSArrayType instead of correct type.

**To reproduce**
https://github.com/Djaler/vue-styleguidist-vue-property-decorator-bug/commit/9d930c0c43ab78c7c415fb4ebd4de0bedcf6b521
Prop definition:
```
@Prop({type: Array, default: ()=>[]})
someArray!: string[];
```
In generated documentation type for this prop is `TSArrayType`

**Expected behavior**
In generated documentation type for this prop should be `string[]` or `Array<string>`

**Comment by elevatebart** [comment]
Hello @Djaler,

You are absolutely right. 
I, for now, simply spit out what babel gives me and it is the wrong value. 
Would you be interrested in creating a Pull Request?

Bart

**Comment by Djaler** [comment]
I don't think I have enough babel knowledge.
But isn't this the same issue that you fixes here https://github.com/vue-styleguidist/vue-styleguidist/issues/796?

**Comment by elevatebart** [comment]
Yep, you are right,
It seems there is a concept missing in this function
https://github.com/vue-styleguidist/vue-styleguidist/blob/6bdfcad629579e2c294a20ee27eacbe3167c0893/packages/vue-docgen-api/src/utils/getTypeFromAnnotation.ts#L4-L15

...the concept of composed type. Array<string>, Record<string, string>
I will look into it asap.

**Comment by elevatebart** [comment]
I could always add a line here in the meantime:
https://github.com/vue-styleguidist/vue-styleguidist/blob/6bdfcad629579e2c294a20ee27eacbe3167c0893/packages/vue-docgen-api/src/utils/getTypeFromAnnotation.ts#L17-L29

TSArrayType: 'Array' but this would not be very helpful, though better.
