### ISSUE TITLE
Font colors in examples being overwritten in Safari

### ISSUE THREAD

**Issue by viljamis** [vue-styleguidist/vue-styleguidist#82]
We’ve been running into this issue with the latest versions of Vue StyleGuidist and tracked it down to be related to this same issue on React Styleguidist: styleguidist/react-styleguidist#739

I created a reduced test case in Codepen that replicates the issue in Safari: https://codepen.io/viljamis/pen/XZEaee

Updating jss-isolate to the latest (5.1.0) fixes the issue as it includes a fix for this Safari bug. I created a pull request that fixes this behaviour: https://github.com/vue-styleguidist/vue-styleguidist/pull/81

**Comment by rafaesc** [comment]
Thanks @viljamis!

Updated on 1.4.8

Regards

**Comment by viljamis** [comment]
@rafaesc wonderful! Thank you.
