### ISSUE TITLE
docs tag gives error in development when running 'npm run serve'

### ISSUE THREAD

**Issue by DSC-CSTS** [vue-styleguidist/vue-styleguidist#822]
When adding the `<docs>` tag to a .vue component the documentation is generated correct however the development environment (via 'npm run serve') generates an error:

>  ERROR  Failed to compile with 1 errors                                                                      12:17:41 PM
> 
> Module build failed (from ./node_modules/vue-loader/lib/index.js):
> TypeError: Cannot read property 'content' of undefined
>     at selectBlock (D:\Develop\web\csts_gui\node_modules\vue-loader\lib\select.js:52:13)
>     at Object.module.exports (D:\Develop\web\csts_gui\node_modules\vue-loader\lib\index.js:79:12)
> 
> You may use special comments to disable some warnings.
> Use // eslint-disable-next-line to ignore the next line.
> Use /* eslint-disable */ to ignore all warnings in a file.

The used versions are: 

> +-- @mdi/font@4.9.95
> +-- @vue/cli-plugin-babel@4.2.2
> +-- @vue/cli-plugin-eslint@4.2.2
> +-- @vue/cli-plugin-router@4.2.2
> +-- @vue/cli-plugin-vuex@4.2.2
> +-- @vue/cli-service@4.2.2
> +-- @vue/eslint-config-prettier@5.1.0
> +-- apexcharts@3.18.1
> +-- axios@0.19.2
> +-- babel-eslint@10.1.0
> +-- bcryptjs@2.4.3
> +-- chart.js@2.9.3
> +-- core-js@3.6.5
> +-- eslint@5.16.0
> +-- eslint-plugin-prettier@3.1.3
> +-- eslint-plugin-vue@5.2.3
> +-- node-sass@4.13.1
> +-- null-loader@3.0.0
> +-- prettier@1.19.1
> +-- sass@1.26.3
> +-- sass-loader@8.0.2
> +-- stylus@0.54.7
> +-- stylus-loader@3.0.2
> +-- vue@2.6.11
> +-- vue-apexcharts@1.5.3
> +-- vue-chartjs@3.5.0
> +-- vue-cli-plugin-vuetify@2.0.5
> +-- vue-router@3.1.6
> +-- vue-styleguidist@4.17.0
> +-- vue-template-compiler@2.6.11
> +-- vuetify@2.2.22
> +-- vuetify-loader@1.4.3
> +-- vuetify-snackbar-queue@0.0.3
> +-- vuex@3.1.3
> `-- webpack@4.42.1

How get 'npm run serve' to work when a component uses `<docs>` tags?

Regards,
Dirk

**Comment by elevatebart** [comment]
Hello @DSC-CSTS ,

I found this one on the vue-loader repo.
I know I had to work around some stuff.
https://github.com/vuejs/vue-loader/issues/1344

I believe the solution is to deal with the docs block with a null-loader in serve mode.
It will avoid the loader from from picking up on it and not knowing what to do with it.

First, install null-loader

```sh
npm install -D null-loader
```

Then modify your `webpack.config.js` in dev mode with the following rule.
**Note** there is no `test` or `includes`

```js
module.exports = {
		module: {
			rules: [
				{
					resourceQuery: /blockType=docs/,
					loader: 'null-loader'
				}
			]
		}
	}
```

**Comment by DSC-CSTS** [comment]
Hi @elevatebart,

Thanks for the quick response!
null-loader was already installed and I updated my vue.config.js as follows. Unfortunately with no luck. I keep getting the same error. 
```
module.exports = {
  transpileDependencies: ["vuetify"],
  configureWebpack: {
    module: {
      rules: [
        {
          resourceQuery: /blockType=docs/,
          loader: "null-loader"
        }
      ]
    }
  }
};
```
I also added a webpack.config.js in the root with only the information you provided. Probably not correct, but was worth the try.
Do you have any other options?

Regards,
Dirk

**Comment by elevatebart** [comment]
Hello @DSC-CSTS 

I just ran into this issue again yesterday. 
Are you using the Vue CLI? If yes are you using the vue-cli-plugin?

In other words in your `devDependencies` do you see vue-cli-plugin-styleguidist?

If not, uninstall vue-styleguidist and do `vue add styleguidist`. 
It should fix your issue.

I hope this helps.

**Comment by DSC-CSTS** [comment]
Hi @elevatebart,

Thanks for your reply!
Indeed, I didn't use the vue-cli-plugin so I uninstalled vue-styleguidist and did `vue add styleguidist`. But still, when running `yarn run serve` I get the following error when adding a `<docs>` tag to my BaseButton.vue component:
```
 ERROR  Failed to compile with 1 errors

 error  in ./src/components/BaseButton.vue?vue&type=custom&index=0&blockType=docs

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'content' of undefined
    at selectBlock (D:\Sandbox\yarn_test\node_modules\vue-loader\lib\select.js:52:13)
    at Object.module.exports (D:\Sandbox\yarn_test\node_modules\vue-loader\lib\index.js:79:12)

 @ ./src/components/BaseButton.vue 20:0-76 21:11-17 21:34-40
 @ ./src/components sync nonrecursive Base[A-Z]\w+\.(vue|js)$
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.80:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```
This is how my vue.config.js looks like:
```
module.exports = {
  transpileDependencies: ["vuetify"],
  configureWebpack: {
    module: {
      rules: [
        {
          resourceQuery: /blockType=docs/,
          loader: "null-loader",
        },
      ],
    },
  },
};
```
At first I thought it didn't read this config but after changing `null-loader` to `no-loader` I was notified that `no-loader` didn't exist. So that does seem to work.

Any other ideas?

Thanks in advance...

**Comment by elevatebart** [comment]
With the plugin, you do not need the null-loader. The plugin is going to take care of it. What happens if you remove the webpack config and run serve ?

**Comment by DSC-CSTS** [comment]
Unfortunately still an error. It's a bit different than with the webpack config :

```
 ERROR  Failed to compile with 1 errors                                                                       2:19:34 PM

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'content' of undefined
    at selectBlock (D:\Sandbox\yarn_test\node_modules\vue-loader\lib\select.js:52:13)
    at Object.module.exports (D:\Sandbox\yarn_test\node_modules\vue-loader\lib\index.js:79:12)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
```

**Comment by elevatebart** [comment]
I can't seem to reproduce your bug.
Do you think it could be cache related?

Here is that I have right now, feel free to fork and reproduce
https://github.com/elevatebart/vuetify-woops

Are you allowed to share the contents of your package.json file? Maybe this would help

**Comment by DSC-CSTS** [comment]
I cleared the cache before starting the server. Here is my package.json file, it is also attached. In the meantime I will fork your code and give that a try.

{
  "name": "csts_gui",
  "version": "0.0.9",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "styleguide": "vue-cli-service styleguidist",
    "styleguide:build": "vue-cli-service styleguidist:build"
  },
  "dependencies": {
    "apexcharts": "^3.18.1",
    "axios": "^0.19.2",
    "bcryptjs": "^2.4.3",
    "chart.js": "^2.9.3",
    "core-js": "^3.6.5",
    "vue": "^2.6.11",
    "vue-apexcharts": "^1.5.3",
    "vue-chartjs": "^3.5.0",
    "vue-router": "^3.1.6",
    "vuetify": "^2.2.22",
    "vuetify-snackbar-queue": "0.0.3",
    "vuex": "^3.1.3"
  },
  "devDependencies": {
    "@mdi/font": "^4.9.95",
    "@vue/cli-plugin-babel": "^4.2.2",
    "@vue/cli-plugin-eslint": "^4.2.2",
    "@vue/cli-plugin-router": "^4.2.2",
    "@vue/cli-plugin-vuex": "^4.2.2",
    "@vue/cli-service": "^4.2.2",
    "@vue/eslint-config-prettier": "^5.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^5.16.0",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-vue": "^5.0.0",
    "node-sass": "^4.13.1",
    "null-loader": "^3.0.0",
    "prettier": "^1.18.2",
    "sass": "^1.26.3",
    "sass-loader": "^8.0.2",
    "stylus": "^0.54.7",
    "stylus-loader": "^3.0.2",
    "vue-cli-plugin-styleguidist": "^4.19.1",
    "vue-cli-plugin-vuetify": "^2.0.5",
    "vue-template-compiler": "^2.6.11",
    "vuetify-loader": "^1.4.3",
    "webpack": "^4.42.1"
  }
}

[package.zip](https://github.com/vue-styleguidist/vue-styleguidist/files/4558889/package.zip)

**Comment by DSC-CSTS** [comment]
Yess!!! That fixed it. Thank you very much!!! 

Unfortunately still 2 issues left:
### **First issue:**
I noticed you fixed the bug already in v4.19.3 but I experience new problems. After updating your testproject to this version, the same error occured there. Here is the error after updating your project. If you put anything between the `<docs>` tags it will show this error:
```
 ERROR  Failed to compile with 1 errors                                                                       9:48:52 AM

 error  in ./src/components/HelloWorld.vue?vue&type=custom&index=0&blockType=docs

Module parse failed: Unexpected character '#' (145:0)
File was processed with these loaders:
 * ./node_modules/vuetify-loader/lib/loader.js
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|
|
> # Mewtwo
|
| cuckooo

 @ ./src/components/HelloWorld.vue?vue&type=custom&index=0&blockType=docs 1:0-252 1:268-271 1:273-522 1:273-522
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vuetify-loader/lib/loader.js??ref--19-0!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.80:8083/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```
### **Second issue:**
We use SVN as versioning system. When I run `vue add styleguidist` in my working environment it seems like it is accessing the .svn directory after which it 'crashes' SVN. I can't use it anymore in this folder. The solution for me was to move the .svn directory, run the `vue add styleguidist`  and then copy the directory back. It works for me but maybe you need to put it on the bug-list. I thought I should mention it to you.

Here's the error:

```
PS D:\Develop\web\csts_gui>vue add styleguidist

📦  Installing vue-cli-plugin-styleguidist...

yarn add v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.12: The platform "win32" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    success Saved 1 new dependency.
info Direct dependencies
└─ vue-cli-plugin-styleguidist@4.19.2
info All dependencies
└─ vue-cli-plugin-styleguidist@4.19.2
Done in 35.89s.
✔  Successfully installed plugin: vue-cli-plugin-styleguidist


🚀  Invoking generator for vue-cli-plugin-styleguidist...
 ERROR  Error: EPERM: operation not permitted, open 'D:\Develop\web\csts_gui\.svn\pristine\00\0079397d99e93d06dd675bb502c694d8a71bb804.svn-base'
Error: EPERM: operation not permitted, open 'D:\Develop\web\csts_gui\.svn\pristine\00\0079397d99e93d06dd675bb502c694d8a71bb804.svn-base'
    at Object.openSync (fs.js:440:3)
    at Object.writeFileSync (fs.js:1265:35)
    at C:\Users\dsc\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\writeFileTree.js:25:8
    at Array.forEach (<anonymous>)
    at writeFileTree (C:\Users\dsc\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\writeFileTree.js:22:22)
    at async Generator.generate (C:\Users\dsc\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:173:5)
    at async runGenerator (C:\Users\dsc\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:120:3)
    at async invoke (C:\Users\dsc\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:101:3)
```

**Comment by elevatebart** [comment]
About svn, the solution is probably to add the --no-git flag to the vue cli api. 
I did not know the vue CLI worked with svn. TIL.

I will check it, but it has been forever since I had a run-in with SVN.
It might be more of a vue CLI bug though.

**Comment by elevatebart** [comment]
I am checking bug 1, which seems to be caused by the `vuetify-loader` this time.
To get an idea on priority, are any of those bugs bothering you in your work?

**Comment by DSC-CSTS** [comment]
The SVN bug is not bothering me at all. I had a work around for it.

The other one does since I can't add in-component documentation via `<docs>` which I would like to have and wherefore I have chosen styleguidist :-).
However, if you can tell me how to revert to the 14.9.1 version (which worked without the null-loader) it might buy you some time. (not too experienced with Vue-CLI yet so any help is appreciated ;-) )

**Comment by elevatebart** [comment]
OK, I will focus on the vuetify bug then.
