### ISSUE TITLE
[vue-docgen-api] index.vue fallback for displayName

### ISSUE THREAD

**Issue by jrtitus** [vue-styleguidist/vue-styleguidist#825]
**The problem**

I have a folder structure such as
```
src
|-- components
|--|-- ProjectCard
|--|--|-- index.vue
```
The `displayName` is currently showing up as `index.vue` in the generated documentation.

![image](https://user-images.githubusercontent.com/1756049/79795002-426fbd00-8321-11ea-9073-3561e5230a21.png)

**Proposed solution**

In the example above, `ProjectCard` would show up as the `displayName` automatically without needing to add a `displayName` tag to the `index.vue` file.

![image](https://user-images.githubusercontent.com/1756049/79795098-659a6c80-8321-11ea-80dc-b32508c5c84a.png)

**Alternative solutions**

N/A

**Additional context**

In the `ComponentDoc` interface, there's the following comment:
```js
  /**
   * Usual name of the component:
   *  It will take by order of priority
   *  - The contents of the @displayName tag of the component
   *  - The name of the variable containing the component (or the class if class component)
   *  - the name of the file containing the component
   */
```
It would be nice to add this feature as the fourth fallback, if the name of the file is `index.vue`.

**Comment by elevatebart** [comment]
that is a great idea !! I think I can make it in a few minutes.
Let me figure it out.
