### ISSUE TITLE
Destructured import causes @displayName to not render correctly

### ISSUE THREAD

**Issue by jrtitus** [vue-styleguidist/vue-styleguidist#826]
**Current behavior**

Placing a block comment with `@displayName` tag after a destructured `import` causes the `displayName` to not take effect in the generated documentation.

**To reproduce**

Something like this causes the bug:
```vue
<script>
import Icon from '@/components/Icon'
import { call } from 'vuex-pathify'

/**
 * @displayName MyComponent
 */
export default {}
</script>
```
![image](https://user-images.githubusercontent.com/1756049/79798771-74841d80-8327-11ea-85d8-01791b9fbb48.png)

Flipping the order of the imports does not:
```vue
<script>
import { call } from 'vuex-pathify'
import Icon from '@/components/Icon'

/**
 * @displayName MyComponent
 */
export default {}
</script>
```
![image](https://user-images.githubusercontent.com/1756049/79798710-5fa78a00-8327-11ea-9a8d-795dbb45ba61.png)

This is more of a predicament when the _only_ `import `statement in a file uses destructuring and we want to use `@displayName`.

(sorry, I don't have a public repo to share with this behavior)

**Expected behavior**

The import statements should not affect the documentation output tags.

**Comment by elevatebart** [comment]
What version do you have installed? 
I cannot seem to reproduce the bug.

If you have time you should probably create a code sandbox.
I think I have already seen this issue a month or two ago.

Thank you in advance.

**Comment by jrtitus** [comment]
Hi @elevatebart - It is 4.18.0. I just installed vue-styleguidist yesterday after watching your Vue Mastery presentation on YouTube for "Component Documentation Made Easy." Great stuff! I'll try to recreate this in a sandbox if I have a chance later today. Thank you for the quick replies!

**Comment by elevatebart** [comment]
Hello @jrtitus did you have time to create the codesandbox?

**Comment by jrtitus** [comment]
Hi @elevatebart sorry for the delay. I cannot reproduce this with the latest version of the library, so I'll close it. Thank you!
