### ISSUE TITLE
support pure api methods docgen.

### ISSUE THREAD

**Issue by lefreet** [vue-styleguidist/vue-styleguidist#828]
I want to show vue-case and some utils case in `styleguidist`，like

```js
sections: [{
  name: 'components',
  components: 'src/components/**/*.vue'
}, {
  name: 'utils',
  components: 'src/utils/**/*.js'
}]
```

so that I can write doc for some utils, like `src/utils/foo/index.js`

```js
/**
 * [foo description]
 * @param  {[type]}   bar [description]
 * @return {[type]}       [description]
 */
export default function foo (bar) {}
```

then `src/utils/foo/README.md`

```md
### useage

** code js static begin**
/**
 * [foo description]
 * @param  {[type]}   bar [description]
 * @return {[type]}       [description]
 */
import foo from './foo'

// 1. base usage
var message = foo('Bob') // => 'hello Bob'
**code js static end**

### live demo

** code vue begin **
<template>
  <div>
    <input v-model='input' />
   <p>i will parse by foo, then to <b>{{output}}</b></p>
  </div>
</template>
<script>
import foo from './foo'
export default {
  data () { return { input: '' } },
  computed: {
    output () { return foo(this.input) }
  }
}
</script>
** code vue end **
```

now, `sg`‘s feature can help me to do this, by mock a entry like `export default { name: 'foo' }` . but the doc of `foo` is still in the code.

so, have some feature can copy the code doc to the case ? maybe:

```md

### useage
<jsdoc />

### live demo
```

then to be: (like `lodash` ?)

![WX20200423-134948](https://user-images.githubusercontent.com/25679627/80063909-86ed9980-8569-11ea-945f-077877c6abbb.png)

**`All in all：some way to parse utils function's jsdoc to .md ?`**

**Alternative solutions**

**Additional context**

**Comment by elevatebart** [comment]
Hello @lefreet 

This sounds like a very useful feature. 
Would you see it having anything Vue specific?

Have you tried using a free-text page (`content` of a section)? 
Like what is done on the vue-design-system example:

https://github.com/vue-styleguidist/vue-styleguidist/blob/2e4870668b2fb643dd4bd48847d9310d74411407/examples/vueds/styleguide.config.js#L68-L73

In these markdown files, you can still have live examples rendered in vue.
The only missing piece would be automated parsing of the JSDoc.

**Comment by lefreet** [comment]
@elevatebart I has try to use `js static` to show my JSDoc，like lodash's doc, but with copy manual。I will look forward to the new feature that can auto catch the JSDoc piece. thanks your anwser.
