### ISSUE TITLE
IE11 Unsupported?

### ISSUE THREAD

**Issue by lancetharper** [vue-styleguidist/vue-styleguidist#83]
My project doesn't load in IE11 and has a syntax error. To confirm this is a problem outside of my project I tried opening the [example site](http://rafaelescala.com/vue-styleguide/) and got the same result.

![bs_win10_ie_11 0](https://user-images.githubusercontent.com/4389981/36455927-4a501008-1657-11e8-8cc5-f1d1c9a257ba.jpg)

I think it has to do with Buble not transpiling something correctly for IE11.

Update:

Safari 9.1 also has an error, "SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode." So it is definitely related to js not being transpiled properly.

**Comment by rafaesc** [comment]
Yes, vue-styleguidist was forked of react-styleguidist.

**Comment by andreasvirkus** [comment]
Can this be fixed now? React-styleguidist says they've fixed it after a Buble update
https://github.com/styleguidist/react-styleguidist/issues/764#issuecomment-376783320

**Comment by geroldboehler** [comment]
+1

**Comment by rafaesc** [comment]
Hi @geroldboehler, @andreasvirkus.

Yes, I saw that there are some issues to work in IE, I will fix it soon.

Regards

**Comment by rafaesc** [comment]
Fixed it, on the version 1.7.7

Regards!

**Comment by viljamis** [comment]
@rafaesc Is this actually fixed though? I at least can’t get it working properly as sections enabled I still end up seeing all the sections in one view and navigation is broken. This error also shows up in IE11:

<img width="476" alt="screenshot 2018-05-31 15 05 22" src="https://user-images.githubusercontent.com/671836/40781561-02f35fda-64e5-11e8-8c4d-de1870a22dc8.png">

**Comment by rafaesc** [comment]
@viljamis Fixed on 1.7.8 version of vue-styleguidist. Regards

**Comment by lukenofurther** [comment]
This appears to be unresolved still:

https://vue-styleguidist.github.io/sections/
