### ISSUE TITLE
Vue Loader transformAssetUrls not working

### ISSUE THREAD

**Issue by SasanFarrokh** [vue-styleguidist/vue-styleguidist#832]
I have a `<icon-component src="~icons/...">` and i added `src` attribute in `transformAssetUrls` to convert it to actual import.

But in vue-styleguidist, a string like '~icons...' is passed.

I'm using `vue-cli-plugin-styleguidist` and did not configure webpack directly.

Thanks a lot.

**Comment by elevatebart** [comment]
Hello @SasanFarrokh,
Where do you have this code: `<icon-component src="~icons/...">`?
Is it in an example?

**Comment by SasanFarrokh** [comment]
Sorry had a mistake in configurations.
