### ISSUE TITLE
Show an example import statement for components

### ISSUE THREAD

**Issue by dflock** [vue-styleguidist/vue-styleguidist#843]
**The problem**

Showing an `import component from ...` statement would be very useful. It shows new developers how to do this, as well as letting you copy & paste it into your code to start using the component.

**Proposed solution**

Somewhere on the components page, show the import statement you would need to use to start using this component. Probably just print out whatever import the styleguide used?

**Comment by elevatebart** [comment]
Hello @dflock 

Have you looked into the [getComponentPathLine](https://vue-styleguidist.github.io/Configuration.html#getcomponentpathline) option?

I probably need to change the default for it but isn't this what you are looking for?

If it is indeed what you were looking for, did you look at the documentation website? 
If yes, what keyword did you search for?

I know the docs are a work in progress...

**Comment by dflock** [comment]
Oh, I didn't realise that `getComponentPathLine` was that configurable - that does what I want, thanks!
