### ISSUE TITLE
how can I hide a event?

### ISSUE THREAD

**Issue by tainlee** [vue-styleguidist/vue-styleguidist#857]
when i write like this
```
      this.$emit('input', value)
```
it will create a empty describe
![image](https://user-images.githubusercontent.com/18365681/81467899-574bbc00-920e-11ea-8307-9936ceb5c206.png)
how can i hidden it?

**Comment by elevatebart** [comment]
Hello @tainlee 

This is a good question, for the moment, I believe it is not possible. 
It should still show with the proper name "input" though.

I will to get to it soon.

**Comment by elevatebart** [comment]
Do you have a repo where I can reproduce the empty name of your event?
