### ISSUE TITLE
Customizing Styleguide components blows up using jsx

### ISSUE THREAD

**Issue by wadetandy** [vue-styleguidist/vue-styleguidist#86]
When trying to customize a component of the styleguide, I get an error that the webpack config doesn't know how to parse jsx syntax (I started by copying the `PathlineRenderer` component directly): 

```
Module parse failed: /Users/wtandy/projects/fishtank-vue/docs/components/ComponentImport.jsx Unexpected token (21:2)
You may need an appropriate loader to handle this file type.
| export function PathlineRenderer({ classes, children }) {
| 	return (
| 		<div className={classes.pathline}>
| 			{children}
| 			<ToolbarButton
```

I have added `babel-preset-react` to my project and `react` to my `.babelrc` file for good measure, but still nothing.  Any ideas?

**Comment by rafaesc** [comment]
Hi @wadetandy,

I added a new example with customed components.

https://github.com/vue-styleguidist/vue-styleguidist/tree/master/examples/customised

Regards
