### ISSUE TITLE
Top level comment "example" gets returned as "examples"

### ISSUE THREAD

**Issue by mesqueeb** [vue-styleguidist/vue-styleguidist#868]
**Current behavior** & **To reproduce**

```js
/**
 * @example {defaultContent: { '0': '🍍' }}
 */
export default {
  props: {
    /**
     * @example '0'
     */
    value: { String },
```

Gives this:

<img width="908" alt="Screenshot 2020-05-13 at 15 28 43" src="https://user-images.githubusercontent.com/3253920/81778972-bbcc8b00-952e-11ea-82cb-2b22bd1e909e.png">

- The prop's `@example` tag is returned as `tags.example`
- The top level `@example` tag is returned as `tags.examples`

I find this to be a bit odd. 😄 

Of course I can work around this, but if this can be changed without a breaking change, I would love this to both return as `tags.example`, just as a peace of heart.

**Comment by elevatebart** [comment]
Unfortunately, this is one of those quirks that come from the historical JSDoc API.
This would be a breaking change indeed.
We could have this in the pipe for v5.
