### ISSUE TITLE
JDoc tags documentation is missing @values

### ISSUE THREAD

**Issue by dflock** [vue-styleguidist/vue-styleguidist#869]
The current docs say have the following about JSDoc tags:

```md
## Using JSDoc tags

You can use the following [JSDoc](http://usejsdoc.org/) tags when documenting components, props and methods:

- [@deprecated](http://usejsdoc.org/tags-deprecated.html)
- [@see, @link](http://usejsdoc.org/tags-see.html)
- [@author](http://usejsdoc.org/tags-author.html)
- [@since](http://usejsdoc.org/tags-since.html)
- [@version](http://usejsdoc.org/tags-version.html)
```

This is incomplete, as you can definitely use `@values` now - and maybe others that I don't know about?

**Comment by dflock** [comment]
Hmmm, I see that `@values` isn't actually a JSDoc tag, just a styleguideist one. I know that `@values` is documented part way through: https://vue-styleguidist.github.io/docs/Documenting.html#code-comments - but it would be useful to have a page in the docs that lists all the tags you can use, rather than having to read everything to discover them.

**Comment by mesqueeb** [comment]
@dflock I agree! 
BTW, any page in the docs is editable!! 😉 

Your PR would be much appreciated!
<img width="574" alt="Screenshot 2020-05-13 at 16 48 37" src="https://user-images.githubusercontent.com/3253920/81785776-ad37a100-9539-11ea-94c0-b005bb015b54.png">

**Comment by elevatebart** [comment]
Thank you @dflock ,

This is a great idea. How would you feel about having this list of valid tags (tags glossary) should have its own section in https://vue-styleguidist.github.io/docs/Documenting.html?

If you like the idea of a new section, we can work on a PR together.

**Section name** : Available Tags

each tag should have it's own subtitle and should contain 
- a sentence describing what the intent behind it is
- a link to where it can be found elsewhere in the doc (if available)
- maybe a quick screenshot?

I hope you have time to do it in a PR. If not, can you comment here if you think the concept above would work ?

**Comment by dflock** [comment]
Sure, I can do that.

I'll try and squeeze it in today.

- Are there any other tags, apart from `@values`, that should be listed there, but aren't on the existing page?
- Presumably I should remove the existing JSDocs tags list and replace it with this new section?

**Comment by dflock** [comment]
OK, I finally made time to start this. I have a work-in-progress branch here:

https://github.com/dflock/vue-styleguidist/tree/tags-documentation-is-missing-869

So far, just [one commit](https://github.com/dflock/vue-styleguidist/commit/64c6a08c427854c72fbdf6948d6d9ee233f29662). Wanted to get your feedback before I go any further: is this what you had in mind? Is this the right direction?

**Comment by elevatebart** [comment]
This is super nice thank you, I think it will help a lot of people.

**Comment by dflock** [comment]
Ok, I'll carry on in this direction.

**Comment by elevatebart** [comment]
Hey @dflock can you create a PR with the changes you have, I can complete the docs afterwards.

**Comment by dflock** [comment]
Arghh - sorry, life got in the way.

**Comment by dflock** [comment]
Here you go: #945 Sorry I wasn't able to complete this :(
