### ISSUE TITLE
Version 1.4.8 enters recursion

### ISSUE THREAD

**Issue by patric-eberle** [vue-styleguidist/vue-styleguidist#87]
I updated vue-styleguidist (beside other npm packages) from 1.4.6 to 1.4.8. First, I've got a `Module build failed: Error: Cannot find module 'typescript'` error, which I was able to solve by installing the `typescript` module (unsure thought, why this is suddenly needed now).
But now I still have the issue, when opening the page in the Browser I get heaps of error resulting in a blank page. Was unable to find a solution for this problem. Returning to 1.4.6 made it work like expected again.

You can test this on the following repository, by raising the `vue-styleguidist`version to 1.4.8:
https://github.com/valantic/vue-template/tree/8a8b1d880411d6b72ea90f262552d4d4fb3ff9a6

**Comment by rafaesc** [comment]
Hi @patric-eberle,

yes, [vue-docgen-api](https://github.com/vue-styleguidist/vue-docgen-api) it was updated to version 2.3.0, in that version it added [typescript support](https://github.com/vue-styleguidist/vue-docgen-api/issues/9#issuecomment-371876980).

However, vue-styleguidist still have the version 2.2.3 of vue-docgen-api
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/package.json#L87

It is strangeth, are you sure that only have updated vue-styleguidist and not vue-docgen-api?

**Comment by rafaesc** [comment]
Ok, for the moment, I had to add typescript as dependency to vue-docgen-api to fixed it, but, I need more time to extract this dependency as optional.

**Comment by rafaesc** [comment]
On version 1.4.9, typescript is optional, so I can close this issue.
