### ISSUE TITLE
Support for Router Documentation?

### ISSUE THREAD

**Issue by Twoody** [vue-styleguidist/vue-styleguidist#880]
First, thank you for the great library and service! I have it all setup without failure so far..

It seems like providing a segment for `src/router.js` within the generated files is working, but neither the filename, not the docs I have in the code are getting picked up.

Is there a way to provide support for documenting `router.js`?
<img width="672" alt="Screen Shot 2020-05-25 at 4 27 00 PM" src="https://user-images.githubusercontent.com/5855700/82847737-992e6080-9ea4-11ea-8ae9-bf63f58d4797.png">

**Comment by elevatebart** [comment]
Hello @Twoody 

If I understand correctly, you want to document non-component utilities (documented with JSDoc) in styleguidist. 
That is a great idea. It would make styleguidist a one-stop-shop for documentation.
I would love to implement that.

## Unsolved Challenge

Components will have to be run through docgen, the component parser, while js utilities should be run through doctrine. Some components are .vue files, some components are .js files. 

How to distinguish js utilities from components in js files without running docgen on it?
If we do run them through docgen should how can we avoid the performance hit that it will bring?

Once this is resolved, we can start talking about design, but I think this part will be easier.

**Comment by elevatebart** [comment]
An alternative would be to use [jsdoc-to-markdown](https://github.com/jsdoc2md/jsdoc-to-markdown) to create a Markdown file that vsg can load as [content of a section](https://vue-styleguidist.github.io/docs/Components.html#sections)
