### ISSUE TITLE
Way to expand type aliases when auto generating docs

### ISSUE THREAD

**Issue by pocketcolin** [vue-styleguidist/vue-styleguidist#881]
**The problem**

When Styleguidist is generating docs from Typescript annotations for component props, it does not expand type aliases and thus displays the Type name (i.e., `TSomeThing`). This is an issue because it requires the user to open up the code and track down the type declaration to figure out the prop's actual type.

**Proposed solution**

It would be great if Styleguidist could automatically expand Type aliases at least one level. So, for example the following type declaration:
```
type TSomeThing = 'option1' | 'option2' | 'option3'
```

Would show up as `'option1' | 'option2' | 'option3'` in Styleguidist instead of just `TSomeThing`.

It probably shouldn't expand beyond the first level to prevent large or recursive objects from causing issues, but it could also be useful to be able to specify the number of levels to expand.

**Alternative solutions**

A way to override the automatically generated type would be a good alternative. It's just not very useful for our designs to see `TSomeThing` when reviewing our components.

**Comment by elevatebart** [comment]
I like this idea. It really feels essential to make those types useful to be able to do deeper that one level. Making it configurable would even avoid the extra performance hit for systems that don't need it.

Where are the types defined in your codebase? Is it in a separate file? the current file?

Would you be open to helping me ith a PR?

**Comment by pocketcolin** [comment]
Glad you like the idea! Our types are usually defined in the same file as the component, but I could definitely see wanting to support abstracted types as well.

Happy to help with a PR! I'll start looking into it later today or tomorrow.

**Comment by pocketcolin** [comment]
Hey @elevatebart :

**Comment by pocketcolin** [comment]
Hey @elevatebart : I've started working on this issue and think I have an idea for what _should_ be done, but need some help applying it. It seems like we may want to add a type check for `bt.TSTypeReference` to the ternary in the `getTypeObjectFromTSType()` function in `vue-docgen-api/src/getTypeFromAnnotations.ts`. What I am unsure of is how to approach mapping the type reference to its type declaration. The `NodePath` has the declaration nested in it, but I don't know the preferred way to parse out all of the TypeAnnotations from the massive object. I'm also brand new to `vue-styleguidist` (we literally applied it to our project yesterday) so let me know if there's a parser utility function or an example of something similar somewhere else already in the project!

**Comment by pocketcolin** [comment]
Hey @elevatebart just wanted to check in here. Any thoughts on how to proceed?

**Comment by elevatebart** [comment]
Sorry @pocketcolin,

I dropped the ball a bit on this one. Missed your answer.

To help you a bit, I wrote an [article on aligator, now DigitalOcean](https://www.digitalocean.com/community/tutorials/js-traversing-ast).

In short, you want to use `recast.visit` to traverse your megaobject and find all typescript type/interface declarations. 
When you find it, you can `recast.print()` what you find and call it a day. The code in this declaration will be returned as a string and you can display it as the type.
- Challenge 1: You might have another TSTypeReference reference in this, that you need to resolve and merge with the current object. If this is what you want to do I advise putting a limit to recursion.
- Challenge 2: The type might be imported from another file. So when you traverse the megaobject, look into es6 imports and requires as well. If it is in another file, you will need to parse this file before resolving the type. 

Hope this helps a little

Please ping me on Discord when I don't answer for that long (more than a week). It often means I missed the notification.

ElevateBart#1057

**Comment by elevatebart** [comment]
Unfortunately, the same job was never done before in docgen. 
If you look at the event handler there is a good example of a visit to determine all the `this.$emit` in the component

https://github.com/vue-styleguidist/vue-styleguidist/blob/355c874b4c7cbc3190457a90c0617b35fececc1e/packages/vue-docgen-api/src/script-handlers/eventHandler.ts#L90-L102

**Comment by hamilr2** [comment]
Hello,

I wanted to add a couple additional similar use cases to this issue that my team encountered when working with TS Vue with Class Components + Storybook argsTable (via vue-docgen-api):

* When using inline ad-hoc types, for example `@Prop() styleObject!: { [key: string]: string };`, the result is `TSTypeLiteral`.
* When using arrays of TS interfaces, for example `@Prop() frameConfig!: FrameConfigInterface[]`, the result is `Array` rather than the expected `FrameConfigInterface[]`.

If these are sufficiently different issues, I can file a separate issue.
