### ISSUE TITLE
Add event listeners to styleguide from custom JS file

### ISSUE THREAD

**Issue by brianecook** [vue-styleguidist/vue-styleguidist#884]
Hello, I'm working on a project where there are components that are Vue based, as well as some that are built just using HTML/Vanilla JS. I'd like to document both types of components using Vue styleguidist, which in theory seems possible. I have a .README, where this html is added to produce the components in the styleguide DOM.

```jsx
<div class="u-bgTeal pa4">
  <div class="c-accordionMenu" data-accordion>
    <div class="c-accordionMenu__toggle" data-accordion-toggle>
      About Us
    </div>
    <div class="c-accordionMenu__content">
      <a class="c-menuLink u-caps" href="#">
        Press
      </a>
      <a class="c-menuLink u-caps" href="#">
        Team
      </a>
      <a class="c-menuLink u-caps" href="#">
        Careers
      </a>
    </div>
  </div>
</div>
```

I'm using the ```jsx notation to wrap the above code. To handle event listeners on the HTML/Vanilla JS components, I added a custom JS file per the [docs](https://vue-styleguidist.github.io/docs/Cookbook.html#how-to-add-custom-javascript-and-css-or-polyfills), however, the elements my file is attaching event listeners to do not seem to exist when the file is loaded.

```js
document.addEventListener("DOMContentLoaded", function() {
  const accordionToggle = document.querySelectorAll('[data-accordion-toggle]');
  console.log(accordionToggle)
});
```

The console log returns null. Is there any way I can add event listeners from my custom JS file after my html has been loaded in the styleguide?

This method works, but I find it overly complex, especially since this JS would be used in project as well. So basically for every event listener in the project I would have to write it in this very long-winded way to accomodate it in the styleguide:

```js
document.addEventListener("DOMContentLoaded", function() {
  document.querySelector('body').addEventListener('click', function(event) {
    if (event.target.dataset.accordionToggle === "") {
      event.target.closest('[data-accordion]').classList.toggle('c-accordionMenu--open')
    }
  });
});
```

**Comment by elevatebart** [comment]
Hello @brianecook 

I like to get difficult requests from time to time.
Would an event triggered every time the preview refreshes help?

Instead of doing the onDomContentLoaded event you could do this on custom event and bind your tricks on referesh.

You are touching on the very reason frontend frameworks like angular and react were invented in the first place...

**Comment by brianecook** [comment]
@elevatebart Interesting, I didn't realize! So, I think the refresh event would help, but doesn't that still make it so that I have to duplicate all of my event listeners so that they work both in the project and in the styleguide? Ideally, all of my event listeners would work in both using the same file/code. What I'm worried about is that I'd have to do everything like this:

```js
// For event listeners to work in project
document.addEventListener("DOMContentLoaded", function() {
  const accordionToggle = document.querySelectorAll('[data-accordion-toggle]');
  console.log(accordionToggle)
});

// For event listeners to work in styleguide
document.addEventListener("StyleguidistRefreshEvent", function() {
  const accordionToggle = document.querySelectorAll('[data-accordion-toggle]');
  console.log(accordionToggle)
});
```

**Comment by brianecook** [comment]
I guess I could just loop through an array of event strings and attach them for both events.
