### ISSUE TITLE
Markdown highlighting colors in VSCode

### ISSUE THREAD

**Issue by luan-orlandi-ifood** [vue-styleguidist/vue-styleguidist#894]
Hello, is there a way to use the markdown with better highlighting in vue code? Maybe a vscode extension can resolve this, but couldn't find anything for that

![image](https://user-images.githubusercontent.com/61207092/84298945-53b99680-ab26-11ea-8ef4-a71d1890055d.png)

Expected (better, but can be improved)

![image](https://user-images.githubusercontent.com/61207092/84299020-76e44600-ab26-11ea-9ff9-56905aca22bd.png)

**Comment by luan-orlandi-ifood** [comment]
Thank you for the quick reply. Using HTML looks much better

The component element becomes red because it's an invalid element, but I think it's ok

![image](https://user-images.githubusercontent.com/61207092/84700597-cf9e4f00-af29-11ea-9bc3-3e4572aaba5f.png)

I will take care of this issue soon

**Comment by luanorlandi** [comment]
I managed to highlight colors using ```vue block and [Vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur) extension for VSCode 🎉 

![image](https://user-images.githubusercontent.com/6919329/85092684-9e8b7c00-b1c0-11ea-9432-fba056dc91a1.png)

@elevatebart do you think it's good to mention Vetur as recommended in the docs? It's been some months since this extension is highlighting Vue code in Markdown files, thanks to https://github.com/vuejs/vetur/pull/1485. I found one mention here, but I think it's not related:

https://vue-styleguidist.github.io/docs/Cookbook.html#i-have-multiple-components-in-the-same-folder-what-can-i-do

Even though, I made the PR to add the support of HTML files (maybe such enhancement it's not useful anymore): https://github.com/vue-styleguidist/vue-styleguidist/pull/899

**Comment by elevatebart** [comment]
Good find!

I still think that the `<template>` tag is not useful to most demos and can be visually confusing.
In the documentation, space and attention are extremely valuable. 
Whatever we can strip out to get the meaningful parts is worth it.

Thank you for the PR, good work on the docs too.
