### ISSUE TITLE
events are not shown in the documentation?

### ISSUE THREAD

**Issue by PakTo** [vue-styleguidist/vue-styleguidist#898]
Hi!!!
When I trigger some events by 'this', the document will show my events as expected, but when i trigger some events by an other variable like 'vm', these events will not shown in the documentation.
How I can do when I use other variable to trigger events?
![image](https://user-images.githubusercontent.com/26544876/84970607-9fcf9100-b14d-11ea-93b7-7fe1748bb7ea.png)

**Comment by elevatebart** [comment]
Hello @PakTo ,

There is a solution as it was asked in #836.
I completely forgot to add this new feature to the documentation.

Use the `@fires` tag on the function that emits it.

```js
/** 
   * Define the event just before the function block
   *
   * @event xxx
   * @property { String } - the first prop given by the event
   */
 /** 
   * Some comment for the function
   * @fires xxx
   * @arg { String } name updated property name
   * @arg newValue new value that we want to update
   */
  onUpdate (name, newValue) {
    // some external method, for example from a method
    // (bind to the Vue instance) provided by a standard js class
  }
```

**Comment by PakTo** [comment]
It works now! 
thx @elevatebart for the solution
