### ISSUE TITLE
Webpack 3 support

### ISSUE THREAD

**Issue by Kevin115** [vue-styleguidist/vue-styleguidist#9]
Just tried to setup the styleguide with webpack 3. Got the following message:

> Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

Is this a issue because Webpack 3 is not supported?
All works fine with Webpack 2

**Comment by rafaesc92** [comment]
Ok, I've published the fix under v1.1.7.
Please try it and let me know if it works.

**Comment by Kevin115** [comment]
It works! Thanks for the fast fix 👍
