### ISSUE TITLE
Improve presentation while using vue-types

### ISSUE THREAD

**Issue by csardinha** [vue-styleguidist/vue-styleguidist#902]
**The problem**
After [this issue](https://github.com/vue-styleguidist/vue-styleguidist/issues/237), it is possible to use [vue-types](https://github.com/dwightjack/vue-types) but it shows all the code instead of the allowed values/shape.

**Proposed solution**
Please, implement a better visualization of the props while using vue-types.

**Additional context**
https://github.com/reactjs/react-docgen/blob/master/src/handlers/propTypeHandler.js

**Comment by elevatebart** [comment]
Hello @Claudia-Sardinha-Bose 

I am not super good at design, would you have suggestions as to what the output would be?
Both the docgen ComponentDoc object and its usage by styleguidist and docgen-cli would need to be updated.

That is not a simple task but could be made possible.

Thank you for reporting this issue.

**Comment by csardinha** [comment]
Hi @elevatebart,

I don't think we need so much design, we just need to get the arguments part and probably base ourselves on the existing implementations from other tools.

Examples:

- `VueTypes.oneOf(['apple', 'orange', 'banana'])` can simply be `['apple', 'orange', 'banana']` or even better `'apple' | 'orange' | 'banana'`

- `VueTypes.shape({ one: String, two: VueTypes.integer })` can simply be `{one: String, two: Integer}`

- `VueTypes.oneOfType([String, Number])` can simply be `[String, Number]` or even better `String | Number`

- etc

Does my answer help? Thanks

**Comment by elevatebart** [comment]
Sorry @Claudia-Sardinha-Bose I have been super busy lately with work.

I need to find a good way to do this without disturbing the rest of the users that have not installed VueTypes...
I do not think it would be realistic to do it in the standard product.

I could write a recipe in the [cookbook](https://vue-styleguidist.github.io/docs/Cookbook.html) showing how to replace the content of the `types` column and leave the rest alone.

Would you be open to that?

**Comment by RCK-DEV** [comment]
@elevatebart Can you tell us how to how replace the content of the types column? I couldn't find it in the cookbook so i'm guessing you haven't been able to add the guide yet?
