### ISSUE TITLE
Multiple components, only one rendered

### ISSUE THREAD

**Issue by andywd7** [vue-styleguidist/vue-styleguidist#91]
Hi,

I am trying to display 3 versions of a button in one template but it is only rendering one of them? I'm not sure what is wrong but I sense that is something to do with the slots? Could you please advise on how to do this?

`
<template>
  <div>
    <button type="button" class="primary">
      <slot></slot>
    </button>
    <button type="button" class="primary" disabled>
      <slot></slot>
    </button>
    <button type="button" class="primary small">
      <slot></slot>
    </button>
  </div>
</template>

<script>
/**
 * Primary buttons
 */
export default {
  name: "Primary button"
}
</script>

<docs>
  ```jsx
  <button type="button" class="primary">Primary button</button>
  <button type="button" class="primary" disabled>Primary button disabled</button>
  <button type="button" class="primary small">Primary button small</button>
  ```
</docs>
`

**Comment by andywd7** [comment]
chopped my code out. Will repost shortly but what I want to achieve essentially is like the top example on [bootstrap](https://getbootstrap.com/docs/4.0/components/buttons/) just as an example?

Thanks

**Comment by andywd7** [comment]
```
<template>
  <div>
    <button type="button" class="primary">
      <slot></slot>
    </button>
    <button type="button" class="primary" disabled>
      <slot name="disabled"></slot>
    </button>
    <button type="button" class="primary small">
      <slot name="small"></slot>
    </button>
  </div>
</template>

<script>
/**
 * Primary buttons
 */
export default {
  name: "Primary button",
  version: "prototype",
}
</script>

<docs>
  ```jsx
  <button class="btn btn-primary">Primary button</button>
  <button class="btn btn-primary disabled" disabled slot="disabled">Primary button</button>
  <button class="btn btn-primary btn-sm" slot="small">Primary button</button>
  ```
</docs>
```

**Comment by narramadan** [comment]
@andywd7 Why did you close this issue ? Did you solve it.. ?

I am also facing the same challange. I cannot include multiple components with in same code block for example.

**Comment by viljamis** [comment]
@narramadan I believe the issue here is that there are multiple root elements while only one is allowed. You would face the same issue if you’d have multiple root elements inside `<template />` as well. So the following won’t work:

``` 
<docs>
    ```jsx
    <button class="btn btn-primary">Primary button</button>
    <button class="btn btn-primary disabled" disabled slot="disabled">Primary button</button>
    <button class="btn btn-primary btn-sm" slot="small">Primary button</button>
    ```
</docs>
 ``` 

But this will:

``` 
<docs>
    ```jsx
    <div>
        <button class="btn btn-primary">Primary button</button>
        <button class="btn btn-primary disabled" disabled slot="disabled">Primary button</button>
        <button class="btn btn-primary btn-sm" slot="small">Primary button</button>
    </div>
    ```
</docs>
 ```
