### ISSUE TITLE
create-server.js  have a bug

### ISSUE THREAD

**Issue by luozheao** [vue-styleguidist/vue-styleguidist#912]
in the create-server.js ,  examples of mistakes:

```bash
  var compiler = (0, _webpack["default"])(webpackConfig);
  var devServer = new _webpackDevServer["default"](compiler, webpackDevServerConfig); // User defined customizations

  if (config.configureServer) {
    config.configureServer(devServer, env);
  }

  return {
    app: devServer,
    compiler: compiler
  };
```

and,the right example
```bash

  if (config.configureServer) {
    config.configureServer(webpackDevServerConfig, env);
  }
  var compiler = (0, _webpack["default"])(webpackConfig);
  var devServer = new _webpackDevServer["default"](compiler, webpackDevServerConfig); // User defined customizations
 
  return {
    app: devServer,
    compiler: compiler
  };
```

**Comment by elevatebart** [comment]
Hello @luozheao 

Thank you for reaching out, it means that you care, and it means a lot to me.

What is the bug that you are seeing? What made you come here and suggest this change?
How can I reproduce the situation?

I am asking this to make sure the fix I provide will at least work in your use case.
If I do a change and do not know the consequences, we will both have accomplished nothing

Thank you ;-)

先感谢您

**Comment by elevatebart** [comment]
And pardon my broken Chinese... very rusty

**Comment by luozheao** [comment]
styleguidist.config.js
```
module.exports = {
   ...
    configureServer: (WebpackDevServer, env) => { 
      WebpackDevServer.proxy = {
        '/api': {
           target: 'http://p.codeshop.com:7001/',
          changeOrigin: true, 
        }
     }
 ...
 }
```
1. this configuration is not in effect 
2. because _webpackDevServer will Generate proxy mapping by webpackDevServerConfig, and change the devServer will not work
``` 
  var devServer = new _webpackDevServer["default"](compiler, webpackDevServerConfig)
```

**Comment by elevatebart** [comment]
Hello @luozheao,

Have you tried applying the proxy to the `webpackConfig` property or use the `dangerouslyUpdateWebpackConfig`?

Namely:

```js
module.exports = {
   // ...
    webpackConfig: { 
      devServer{
        proxy: {
        '/api': {
           target: 'http://p.codeshop.com:7001/',
          changeOrigin: true, 
        }
     }
   }
 }
 // ...
}
```

```js
module.exports = {
   // ...
    dangerouslyUpdateWebpackConfig(WebpackDevServer, env) { 
      WebpackDevServer.proxy = {
        '/api': {
           target: 'http://p.codeshop.com:7001/',
          changeOrigin: true, 
        }
     }
 // ...
 }
```

**Comment by elevatebart** [comment]
Using configureServer is meant for something else than what you are doing:

https://vue-styleguidist.github.io/Configuration.html#configureserver

Is meant to allow you to post-configure the express app. 
Useful to build custom endpoints.
Configure outputs of the server in the console if you want more information.

**Comment by luozheao** [comment]
```
module.exports = {
   // ...
    webpackConfig: { 
      devServer{
        proxy: {
        '/api': {
           target: 'http://p.codeshop.com:7001/',
          changeOrigin: true, 
        }
     }
   }
 }
 // ...
}
```
well,friend,I've  tried it in the version 4.26.0 ,but in this file lib/scripts/schemas/config.js, not contain devServer  .
if I use webpackConfig.devServer , I will get a error tips. 

So, Can you add "devServer" to the file lib/scripts/schemas/config.js ?

**Comment by elevatebart** [comment]
> Can you add "devServer" to the file lib/scripts/schemas/config.js ?
unfortunately not. `config` is a flat structure and `webpackConfig` contains an object.

If you had this error, it is probably that you added devServer to the root this way

```js
module.exports = {
   // ...
// no webpackConfig:{ while it is needed 
      devServer{
        proxy: {
        '/api': {
           target: 'http://p.codeshop.com:7001/',
          changeOrigin: true, 
        }
     }
 }
 // ...
}
```

I hope this tip helps ;-)

**Comment by luozheao** [comment]
gooodman !

when I see serverHost and serverPort under the root ,take it for granted that devServer also to be.

Sorry to disturb you , and I will  take time to read english documents.

thank you ,again.

**Comment by elevatebart** [comment]
No worries, glad I can help a bit.
