### ISSUE TITLE
prettier config file is required

### ISSUE THREAD

**Issue by florentinap** [vue-styleguidist/vue-styleguidist#914]
The new version of vue-docgen-cli (4.26.2) throws an error if I do not add a prettier config file in my directory, so the output file is not generated. 
`(node:15859) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at prettyMd (/root/capri/components/capri.components.all/capri.stepper/node_modules/vue-docgen-cli/lib/utils.js:69:162)
    at Object.<anonymous> (/root/capri/components/capri.components.all/capri.stepper/node_modules/vue-docgen-cli/lib/utils.js:81:43)
    at step (/root/capri/components/capri.components.all/capri.stepper/node_modules/vue-docgen-cli/lib/utils.js:33:23)
    at Object.next (/root/capri/components/capri.components.all/capri.stepper/node_modules/vue-docgen-cli/lib/utils.js:14:53)
    at fulfilled (/root/capri/components/capri.components.all/capri.stepper/node_modules/vue-docgen-cli/lib/utils.js:5:58)
(node:15859) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15859) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
The problem is caused by this [commit](https://github.com/vue-styleguidist/vue-styleguidist/commit/0c04a73dbe694ddc925661826fea54172242e49d)

Is there any way to fix it, please? I do not think it is ok to add an extra file in my project that is required only by vue-docgen-cli and it is useless for me. Thanks!

**Comment by elevatebart** [comment]
Oh "whoops" ! Yeah I will fix that ASAP.

**Comment by elevatebart** [comment]
Should be better in an hour, sorry about that.

**Comment by florentinap** [comment]
> Should be better in an hour, sorry about that.

Awesome. Thank you!

**Comment by elevatebart** [comment]
Can you try it now ?

Bart Ledoux

Join me on LinkedIn
Or as @elevatebart on Discord, Twitter and Github

**Comment by florentinap** [comment]
> Can you try it now ? Bart Ledoux Join me on LinkedIn Or as @elevatebart on Discord, Twitter and Github
> […](#)
> On Jul 16, 2020, 09:38 -0500, Florentina Petcu ***@***.***>, wrote: > Should be better in an hour, sorry about that. Awesome. Thank you! — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

It works without prettier config file. There is no error. Thanks!
