### ISSUE TITLE
Vuetify Components

### ISSUE THREAD

**Issue by mcstepp** [vue-styleguidist/vue-styleguidist#92]
I'm creating a custom Vue component library that extends [Vuetify](https://github.com/vuetifyjs/vuetify) components. However, to render Vuetify components, it requires a main `<v-app>` element for components to render into. 

At first, I started poking around the StyleGuideRenderer.js file, but I see that it's written in React. I saw the instructions on how to customize the StyleGuideRenderer, but not sure if it is required to be a React component also or if I can write it as a Vue component. Can you advise on what to do, or would that be considered a feature request? With some guidance on where to implement this so that the styleguiderenderer can render Vuetify components, I would be more than happy to submit a PR for this feature for other users. 

Also, the goal of the library is to also include design patterns and pre-made templates of these custom Vuetify components in addition to component documentation, but it is my understanding that Vue-styleguidist does not output back to the main application, but rather runs outside of the application, i.e the design patterns and templates would be the main app, and the component style guide/documentation would be a separate application. There isn't a way to loop back the output from styleguidist back into the main application where the components live, is there?

**Comment by rafaesc** [comment]
Hi @mcstepp 

Interesting project.

yes, how you already have seen, the UI of vue-styleguidist was developed with react, so if you want deep change in the design of style guide, you need to use react components. here, there is an example
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/examples/customised/styleguide.config.js

I can understand that you want to render components that needs `<v-app>` as a wrapper to render your extends components. First, you need import vuetify using the property [require in styleguidist.config.js](https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Configuration.md#require), then you can render the components in the examples, in this way.

```vue
<template>
  <v-app>
    <Button @click.native="pushButton">Push Me</Button>
  </v-app>
</template>
<script>
export default {
  methods: {
    pushButton() {
      console.log('Hello')
    }
  }
}
</script>
```

It's possible that the problem will be that you will have to add `v-app` always in all your examples.

But I think that the best way, as you say, add a before function to render, with the options components available and return a new options object.

```js
{
  beforeRender: options => {
    return {
      ...options,
      template: `<v-app>${options.template}</v-app>`
    };
  }
};
```

**Comment by mcstepp** [comment]
Great, thank you for your insight. I'll try this out!

**Comment by rafaesc** [comment]
Yes, you can try with the first option.

But if you definitely need `beforeRender`, you can send a PR.

And tell me if you need more information

Regards!

**Comment by beckelmw** [comment]
I was able to get Vuetify working doing the following:

1. I created an init.js file at the root of the project with:
```javascript
import 'vuetify/dist/vuetify.min.css' // Ensure you are using css-loader
import Vue from 'vue';
import Vuetify from 'vuetify';

Vue.use(Vuetify);
```
2. Modified the styleguide.config.js file to:
```javascript
const path = require('path');

module.exports = {
  template: './styleguide.ejs',
  require: [path.join(__dirname, 'init.js')],
};
```
3. Added a styleguide.ejs template file (for the fonts):
```html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title>MSG Components</title>
    <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
</head>

<body>
    <div id="app"></div>
</body>
</html>
```

**Comment by ultraJeff** [comment]
Hey @beckelmw -

I'm running into Babel errors after trying your solution. Can I ask what your .babelrc and package.json files look like?

Thanks!

**Comment by webzellentOpenSource** [comment]
Does stylegudist supports vue-cli version 3?
I get the message: "template config option format has been changed, you need to update your config."
But there's no way to trace it.

**Comment by viljamis** [comment]
@webzellentOpenSource That is related to the new Styleguidist version. The format of that option changed in the latest release, see https://github.com/styleguidist/react-styleguidist/blob/master/docs/Configuration.md#template

**Comment by webzellentOpenSource** [comment]
@viljamis How can I change the used HTML-Wrap instead?
With vuetify this pattern is required.
(template: './styleguide.ejs',)

**Comment by philwolstenholme** [comment]
@rafaesc could you give me a pointer on how to implement your beforeRender idea from https://github.com/vue-styleguidist/vue-styleguidist/issues/92#issuecomment-374263000?

I need to do the same thing as @mcstepp (wrap all my components in Vuetify's `v-app` component)

**Comment by mcstepp** [comment]
@philwolstenholme 

Here's what I did to get it work:

I created a `styleguide` directory inside my root project. Then inside the directory: 

styleguide.ejs:

```
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title>My Vuetify Components</title>
    <link href='https://fonts.googleapis.com/css?family=Material+Icons' rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
</head>

<body>
    <div id="app"></div>
</body>

</html>
```

styleguide-app.vue:

```
<template>
	<v-app>
		<div id="app">
		</div>
	</v-app>
</template>

<style>
#app {
	font-family: 'Avenir', Helvetica, Arial, sans-serif;
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale;
	text-align: center;
	color: #2c3e50;
}

#nav {
	padding: 30px;
}

#nav a {
	font-weight: bold;
	color: #2c3e50;
}

#nav a.router-link-exact-active {
	color: #42b983;
}
</style>
```

styleguide-main.js:

```
import Vue from 'vue';
import Vuetify from 'vuetify';

import App from './styleguide-app.vue';

import 'vuetify/dist/vuetify.min.css'; // Ensure you are using css-loader

Vue.use(Vuetify);

new Vue({
	render: h => h(App)
}).$mount('#app');
```

In the root directory, styleguide.config.js:

```
const path = require('path');

module.exports = {
	title: 'My Vuetify Styleguide',
	components: 'src/components/**/[A-Z]*.vue',
	// showSidebar: false,
	getComponentPathLine(componentPath) {
		const name = path.basename(componentPath, '.vue');
		return `import { ${name} } from 'my-vuetify-library';`;
	},
	template: './styleguide/styleguide.ejs',
	require: [path.join(__dirname, 'styleguide/styleguide-main.js')],
	webpackConfig: {
		module: {
			rules: [
				{
					test: /\.vue$/,
					loader: 'vue-loader'
				},
				{
					test: /\.js?$/,
					loader: 'babel-loader',
					exclude: /node_modules/,
					query: {
						cacheDirectory: true,
                                                  presets: ['react']
					}
				},
				{
					test: /\.css$/,
					use: ['style-loader', 'css-loader', 'sass-loader']
				},
				{
					test: /\.scss$/,
					use: ['style-loader', 'css-loader', 'sass-loader']
				},
				{
					test: /\.png$/,
					use: ['url-loader']
				}
			]
		}
	},
	showUsage: true,
	showCode: true
};
```
Then in my package.json, I had to add `babel-preset-react` to devDependencies, and then add `react` as a babel preset. Why? Because styleguidist is written in React...

```
"babel": {
        "presets": [
            [
                "env",
                {
                    "targets": {
                        "uglify": true
                    },
                    "modules": false
                }
            ],
            "react"
        ],
       ...
}
```

**Comment by philwolstenholme** [comment]
@rafaesc this is amazing, thank you so much Rafael! Such a neat and tidy way to wrap our components in a third-party library 👍

**Comment by philwolstenholme** [comment]
This issue can probably be closed now we have the `renderRootJsx` option and documentation on how to use it to wrap components in Vuetify's wrapper.

**Comment by rafaesc** [comment]
Perfect!
