### ISSUE TITLE
Upgrade vue-docgen-api to use pug ^3

### ISSUE THREAD

**Issue by JoshRobertson** [vue-styleguidist/vue-styleguidist#928]
This gets rid of a nested dependency on `core-js 2` by using `constantinople ^4`

`warning @storybook/addon-docs > vue-docgen-api > pug > pug-code-gen > constantinople > babel-types > babel-runtime > core-js@2.6.11`

https://github.com/pugjs/pug/releases/tag/pug%403.0.0

**Comment by elevatebart** [comment]
Thank you @JoshRobertson 
Would you be OK to create a PR?

**Comment by JoshRobertson** [comment]
@elevatebart sure here you go: https://github.com/vue-styleguidist/vue-styleguidist/pull/929
