### ISSUE TITLE
Customize Footer of original template

### ISSUE THREAD

**Issue by thovu162020** [vue-styleguidist/vue-styleguidist#935]
I have searched for a way to customize footer element (default is 'Generated with Vue Styleguidist') but the best option I can find so far is using `styleguideComponents` in config to customize `StyleGuideRenderer`. However, I still have a few questions/issues:
- Is there any other way to do this without using `StyleGuideRenderer` since it touches everything in the template?
- The example https://vue-styleguidist.github.io/Examples.html#customised does not contain all elements in the original template (e.g. sidebar) so I ended up using the default file https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-styleguidist/src/client/rsg-components/VsgStyleGuide/StyleGuideRenderer.js and modifying upon it. I suggest to put this file somewhere in the documentation as reference.
- There is no where listing all the options available for `styleguideComponents`. It would be nice if this is included in the documentation, too.

**Comment by elevatebart** [comment]
Hello @thovu162020,

First thank you for taking the time to ask for what you need. It does not only help me but anybody that wants to build a styleguide and faces the same issues as you do.

As for making the footer its own component, that is a brilliant idea and I will implement it as part of fixing this request.

On the documentation issue, there is just too many customizable components to list. 
What would you think if I wrote a guide with all the steps?
- discover what components can be overridden using the react dev tools
- find where in the codebase the customizable components can be found in vue-styleguidist and if not there, in react-styleguidist
- start with the original code and iterate through changes

Would you be open to proof read it?

**Comment by thovu162020** [comment]
Hi @elevatebart, many thanks to the response.

As of now, the hardest part of using this library is to customize the React elements - I have to look into guide, sample projects like VueDS and finally dig in source code to get full picture of how to add or remove an UI part. Thus I really appreciate your suggestion and am happy to proof read the updated documentation.
