### ISSUE TITLE
highlightTheme option warning (New editorConfig option doesn't work)

### ISSUE THREAD

**Issue by viljamis** [vue-styleguidist/vue-styleguidist#94]
I’m currently getting the following warning when using `highlighTheme` option:

```
Warning: highlightTheme config option is deprecated. Use the theme property in the editorConfig option instead.
```

I guess this is caused since I’m using the old highlighTheme config option. But! The new editorConfig.theme doesn’t actually work at all with any other theme than the default, so it forces users to use this.

It looks like this is something that was previously fixed in React Styleguidist, so wondering if the fix can be ported from there? See: https://github.com/styleguidist/react-styleguidist/issues/788

**Comment by rafaesc** [comment]
Hi @viljamis,

yes, I will update it.

Regards!

**Comment by viljamis** [comment]
@rafaesc Wonderful! 👍

**Comment by rafaesc** [comment]
Ok @viljamis, I've published the fix under v1.5.0.
Please try it and let me know if it works.

Regards

**Comment by viljamis** [comment]
@rafaesc Works perfectly! Great work once again. I updated Vue Design System to use this version as well. :-)

**Comment by rafaesc** [comment]
Perfect @viljamis! and congratulate you on your great project!

Regards!
