### ISSUE TITLE
Slot description empy with styleguide:build

### ISSUE THREAD

**Issue by snakemastr** [vue-styleguidist/vue-styleguidist#942]
When using styleguidist:build, the description for slots is empty (-).
When using styleguidist server, the description for slots as is expected.

`<template>
    <div v-show="isActive"
             :aria-hidden="! isActive"
             class="tab__content__panel"
             :id="computedId"
             role="tabpanel"
    >
        
        <slot />
    </div>
</template>`

Compiled/served with styleguidist
![tab_server](https://user-images.githubusercontent.com/18302945/89884172-74a37400-dbc9-11ea-809e-0ae6cb45423b.PNG)

Generated with styleguidist:build
![tab_generated](https://user-images.githubusercontent.com/18302945/89884174-753c0a80-dbc9-11ea-91a2-3eebb37b411e.PNG)

Version 6.14.4

**Comment by elevatebart** [comment]
Hello @snakemastr 

Thank you for reporting this, I am looking for a solution.
A bit of a spikey problem.

Will report back soon.

**Comment by elevatebart** [comment]
It seems like when NODE_ENV === 'production', the template parser of vue 3 completely ignores all comments in the template which creates this difference.

**Comment by snakemastr** [comment]
That actually makes a lot of sense! Thank you so much for picking this is up so fast
