### ISSUE TITLE
Document slot in Vue functional component

### ISSUE THREAD

**Issue by fireofearth** [vue-styleguidist/vue-styleguidist#943]
# Specs

vue: 2.6.11
vue-styleguidist: 4.30.0

# Description

Hi there, I'm also working on (multiple) pure JS functional component and I'm encountering the same problem as in an [earlier ticket](https://github.com/vue-styleguidist/vue-styleguidist/issues/837).
For example, I have a component here that is a toolbar that has a default slot that should receive buttons and button groups (actually loops through the children). This component also has a named slot named 'logo'. The comments with `@slot` aren't displaying with vsg.

```
./toolbar.js
import { mergeData } from 'vue-functional-data-merge';
const WRAP_OPTIONS = ['nowrap', 'forward', 'backward'];

/**
 * Toolbar
 */
export default {
    name: 'AimToolbar',
    functional: true,
    props: {
        /**
         * Alternative HTML tag to use.
         */
        tag: {
            type: String,
            default: 'div',
        },
        /**
         * Flex wrap property of toolbar row.
         * @see https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap
         */
        flexWrap: {
            type: String,
            default: null,
            validator: str => arrayIncludes(WRAP_OPTIONS, str)
        },
    },
    /* @slot describe default slot */
    render(h, { props, data, slots }) {
        /* @slot describe default slot */
        const children = [ ];
        const defaultSlots = slots().default;
        const numberOfSlots = defaultSlots.length;
        const logo = slots().logo;
        if(logo) {
            children.push(h('div', { staticClass: 'logo' }, [logo]));
            if(numberOfSlots > 0)
                children.push(h('div', { staticClass: 'divider' }));
        }
        for(let i = 0; i < numberOfSlots; i++) {
            const slot = defaultSlots[i];
            slot.key = i;
            children.push(h('div', { staticClass: 'item' }, [slot]));
            if(i < numberOfSlots - 1) {
                children.push(h('div', { staticClass: 'divider' }));
            }
        }
        const classList = [ ];
        classList.push({
            [`flex-wrap-${props.flexWrap}`]: props.flexWrap,
        });

        /* @slot describe default slot */
        return h(
            props.tag,
            mergeData(data, { staticClass: 'toolbar', class: classList }),
            children
        );
    },
};
```

Technically, how does `vue-docgen-api` process non-standard slot workarounds?
Let me know if you can solve this problem using the issue body or if you want me to create a repo reproducing the bug.

**Comment by elevatebart** [comment]
Thank you @fireofearth 

I understand the issue, the short answer is this was never implemented before (probably because I did not know this syntax).
I should create a handler for it.

**Comment by fireofearth** [comment]
Thanks @elevatebart 

Something else you should think about is whether you want to create a handler for that specific case or whether you want to create a universal workaround for documenting non-standard slots. Something like just declaring them in at the top of the component like so:

```
/**
 * Toolbar
 * @slot default - buttons to add to toolbar
 * @slot logo - alternative logo brand
 */
export default {
    ...
}
```

Otherwise you may end up playing whack-a-mole with getting `vue-docgen-api` to work with slots. In particular I have been using some very non-standard slots logic in component render functions (calling `createElement()` from methods and retrieving slots from mixins are examples) that I don't think static code analysis can pick up. Thoughts?
