### ISSUE TITLE
Apparently, vue-docgen-api cannot handle union types in Vue/TS setup (Storybook)

### ISSUE THREAD

**Issue by HerrBertling** [vue-styleguidist/vue-styleguidist#946]
**Describe the bug**

Transferred from https://github.com/storybookjs/storybook/issues/11944 as suggested by @elevatebart :)

Hey :wave:

I tried to update SB to version 6. Our project setup is Vue/NuxtJS/Typescript + `vue-property-decorator` for writing class components.

Initially, no components would render and I'd get this error:

```sh
Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined
    at convert (http://localhost:1337/vendors~main.dcec9cf333cc0105409b.bundle.js:5805:22)
    at convert (http://localhost:1337/vendors~main.dcec9cf333cc0105409b.bundle.js:5688:51)
    at javaScriptFactory (http://localhost:1337/vendors~main.dcec9cf333cc0105409b.bundle.js:6183:41)
    at extractProp (http://localhost:1337/vendors~main.dcec9cf333cc0105409b.bundle.js:6328:19)
    at http://localhost:1337/vendors~main.dcec9cf333cc0105409b.bundle.js:6292:12
    at Array.map (<anonymous>)
    at extractComponentSectionArray (http://localhost:1337/vendors~main.dcec9cf333cc0105409b.bundle.js:6291:24)
    at extractComponentProps (http://localhost:1337/vendors~main.dcec9cf333cc0105409b.bundle.js:6318:41)
    at http://localhost:1337/vendors~main.dcec9cf333cc0105409b.bundle.js:5554:51
    at Array.forEach (<anonymous>)
```

Going through single stories, I found out that apparently a union type declared within the props produces this error.

I tried to drill down within the `node_modules`, but I was lost quite fast within the Storybook stuff – I guess you'll be able to pinpoint this faster than I am 😄 

**To Reproduce**

1. Clone  https://github.com/HerrBertling/nuxt-ts-storybook-docs-issue & run `yarn`
2. Start Storybook via `yarn storybook`
3. See error

If you switch the `brokenMsg` type to one of the working ones explained below, Storybook works as expected.

**Expected behavior**

This should™ just™ work™ 😄 

**Code snippets**

Not working prop:

```
<script lang="ts">
import Vue from 'vue'
import { Prop, Component } from 'vue-property-decorator'

@Component({})
export default class BaseCheckbox extends Vue {
  @Prop({ default: '' }) id!: string | number
  [… more props here]
}
</script>
```

Working prop:

```
<script lang="ts">
import Vue from 'vue'
import { Prop, Component } from 'vue-property-decorator'

@Component({})
export default class BaseCheckbox extends Vue {
  @Prop({ default: '' }) id!: string
  [… more props here]
}
</script>
```

Also working, but feels rather stupid

```
<script lang="ts">
import Vue from 'vue'
import { Prop, Component } from 'vue-property-decorator'

@Component({})
export default class BaseCheckbox extends Vue {
  @Prop({ default: '' }) id!: StringOrNumber
  [… more props here]
}
</script>
```

with a global type declared somewhere:

```ts
declare type StringOrNumber = string | number
```

Passing along different strings works also without issues, like for a button:

```
<script lang="ts">
import Vue from 'vue'
import { Prop, Component } from 'vue-property-decorator'

@Component({})
export default class BaseButton extends Vue {
  @Prop({ default: 'primary' }) variant!: 'primary' | 'secondary' | 'text'
  [… more props here]
}
</script>
```

**Comment by elevatebart** [comment]
I added your case as a test and it seems to work. 
I will check out storybooks code tomorrow.

https://github.com/vue-styleguidist/vue-styleguidist/blob/a55fccf9ebf015b3478544d461ea12e80479d9c9/packages/vue-docgen-api/src/script-handlers/__tests__/classPropHandler.ts#L179-L206

I will also re-open the SB issue.
