### ISSUE TITLE
Parsing of 'validator' fails when using a function reference

### ISSUE THREAD

**Issue by RaffaeleCanale** [vue-styleguidist/vue-styleguidist#954]
**Current behavior**

The vue-docgen-api parser fails to parse the prop validator function with `TypeError: Cannot read property '0' of undefined`.

![Screenshot_20200826_105548](https://user-images.githubusercontent.com/2411506/91283298-b5cf8280-e78a-11ea-9b8e-aa229120804d.png)

Since the parsing fails, the respective component will be ignored from the guide.

**To reproduce**

This happens when a prop validator is defined through a variable name rather than an inline function or lambda.

- Create a function called `myValidator`
```js
function myValidator(value) {
    return value.length = 3;
}
```
- Add a validator to a component prop using this syntax:
```js
props: {
    color: {
        type: String,
	validator: myValidator,
    },
},
```

**Expected behavior**

The parsing of the `validator` function should work even if it is not written inline.

**Comment by lopis** [comment]
I've hit this same issue using Vue and Storybook and tracked it down to this line:

https://github.com/vue-styleguidist/vue-styleguidist/blob/025ad018a646e6a74d37f6cf85bade8e11348c60/packages/vue-docgen-api/src/script-handlers/utils/parseValidator.ts#L34

For future reference, the error I was getting was 

```
[vue-docgen-loader] failed to parse the component file with docgen-api: Cannot read property '0' of undefined
```

**Comment by elevatebart** [comment]
Thank you @lopis,
This is super helpful. 
I will create a PR today.
