### ISSUE TITLE
No matching version found for vue-inbrowser-compiler-utils@^4.31.2

### ISSUE THREAD

**Issue by w0rse** [vue-styleguidist/vue-styleguidist#957]
**Current behavior**

Installing @storybook/addon-docs fails with the following error:

npm ERR! notarget No matching version found for vue-inbrowser-compiler-utils@^4.31.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'vue-docgen-api'

There's no such version published on npm from what I can see: https://www.npmjs.com/package/vue-inbrowser-compiler-utils

**Comment by elevatebart** [comment]
I believe it is now fixed

**Comment by elevatebart** [comment]
Would you please check?

**Comment by w0rse** [comment]
The build is working. Thank you for a quick fix.

**Comment by w0rse** [comment]
The build is working. Thank you for a quick fix.

**Comment by w0rse** [comment]
The build is working. Thank you for a quick fix 👍

**Comment by w0rse** [comment]
The build is working. Thank you for a quick fix 👍

**Comment by w0rse** [comment]
The build is working. Thank you for a quick fix 👍

**Comment by w0rse** [comment]
The build is working. Thank you for a quick fix 👍

**Comment by w0rse** [comment]
The build is working. Thank you for a quick fix 👍

**Comment by w0rse** [comment]
The build is working. Thank you for a quick fix 👍
