### ISSUE TITLE
styleguidist:build removes some HTML classes that are required for styling

### ISSUE THREAD

**Issue by CarsonBain** [vue-styleguidist/vue-styleguidist#964]
## Current behavior

Styleguide works great locally when spinning up the development server, but I notice that when I run `styleguidist:build` some of the HTML classes that are generated by styleguidist are not added to the final build resulting in some elements unstyled like the `h1` of the Logo and the Prism.js code highlighting.

### Development build
**(class `rsg--logo-49` exists on the `h1` element)**
![image](https://user-images.githubusercontent.com/33740139/92968255-ccdbc900-f448-11ea-863c-fba96da7afe2.png)

**(`rsg--jssEditor-61` class and other classes exist to style the code example syntax highlighting)**
![image](https://user-images.githubusercontent.com/33740139/92968359-f563c300-f448-11ea-9e70-e98f3f156d5f.png)

### Production Build
**(class missing from `h1`)**
![image](https://user-images.githubusercontent.com/33740139/92968568-63a88580-f449-11ea-86ae-4bc2f8d047cb.png)

**(classes seem missing and code example is unstyled)**
![image](https://user-images.githubusercontent.com/33740139/92968626-7a4edc80-f449-11ea-8beb-36be5010a685.png)

This is my `styleguide.config.js`

```const path = require('path');
const config = {
  theme: {
    fontFamily: {
      base: '"Matter", sans-serif',
    },
    color: {
      base: '#544742',
      sidebarBackground: '#fffbf7',
      link: '#D14010',
      linkHover: '#d14010bf',
    },
    sidebarWidth: 300,
    borderRadius: 0,
  },
  styleguideDir: '../../public/styleguide',
  // Code below can split page into sections
  // Note you will need more than one section to show the section name in the sidebar
  sections: [
    {
      name: 'Layout',
      components: 'src/js/v3/Components/layout/*.vue',
    },
    {
        name: 'Inputs',
        components: 'src/js/v3/Components/utils/inputs/*.vue',
    },
    {
      name: 'Cards',
      components: 'src/js/v3/Components/cards/*.vue',
    },
    {
      name: 'Notifications/Errors',
      components: 'src/js/v3/Components/notifications/*.vue',
    },
    {
      name: 'Lists',
      components: 'src/js/v3/Components/lists/*.vue',
    },
  ],
  title: 'Felix Component Guide',
  components: ['src/js/v3/Account/Components/*.vue', 'src/js/v3/Components/**/**/*.vue'],
  webpackConfig: Object.assign({}, require('./webpack.config.js')),
  copyCodeButton: true,
  skipComponentsWithoutExample: true,
  // Any assets you want to use need to be imported here and need appropriate webpack loaders 
  // Eventually this should be a separate file(s) or array of included assets
  require: [
    path.join(__dirname, './src/scss/app.scss'),
    path.join(__dirname, '/assets/fonts/Matter-Regular.woff'),
    path.join(__dirname, '/assets/fonts/Matter-Bold.woff'),
    path.join(__dirname, '/assets/img/new/back arrow.svg'),
  ],
};

// Add additionnal font loader for font files
config.webpackConfig.module.rules.push({
  test: /\.(woff(2)?|ttf|eot)(\?v=\d+\.\d+\.\d+)?$/,
  use: [
    {
      loader: 'file-loader',
      options: {
        name: '[name].[ext]',
        outputPath: 'themes/pillbox/assets/fonts/',
      },
    },
  ],
});

config.webpackConfig.module.rules.push({
  test: /\.(png|jpe?g|gif|svg)$/i,
  use: [
    {
      loader: 'file-loader',
      options: {
        name: '[name].[ext]',
        outputPath: 'themes/pillbox/assets/img/new/',
      },
    },
  ],
});


module.exports = config;
```

**Comment by elevatebart** [comment]
Hello @CarsonBain,

You are absolutely right. The CSS classes of vue-styleguidist cannot be relied upon. 
Styleduidist is rendering using React... and uses JSS (CSS-in-JS) to apply its classes and styling. Therefore the class names are generated and are shortened in production to make the bundle size smaller.

So if you want to change any element of the React rendering, anything outside of your examples, you should prefer using the [styles config property](https://vue-styleguidist.github.io/Configuration.html#styles) instead of pure css classes in external files.

[Here is a cookbook recipe that might help you along the way](https://vue-styleguidist.github.io/docs/Cookbook.html#how-to-change-styles-of-a-style-guide)

I hope this helps a little.

**Comment by CarsonBain** [comment]
Thanks for the response @elevatebart!

I think my problem here is not that I am trying to target these particular CSS classes and change the styles from what they are by default, I'm just seeing classes that seem important to the default styling of the styleguidist components completely stripped away in production. 

I think I can pretty easily fix the issue with the `Logo` component as per your examples that you sent, but what becomes trickier is adding back all of the CSS properties that style the Prisim code editor preview. Shouldn't these classes remain constant? It's weird that the code editor preview section become essentially un-styled in production is it not?

### Development build 

![image](https://user-images.githubusercontent.com/33740139/93111860-3ba56600-f685-11ea-88d4-a29057ad746a.png)

### Production build

![image](https://user-images.githubusercontent.com/33740139/93111889-46f89180-f685-11ea-9e31-b8ccd2e3682f.png)

**Comment by CarsonBain** [comment]
@elevatebart I also noticed that using the `styles` object works well for the development build, but again when I build using `styleguidist:build` I'm having issues. The styles aren't applying to the component as they do locally:

### `styleguide.config.js`
![image](https://user-images.githubusercontent.com/33740139/93110992-05b3b200-f684-11ea-9aac-add16c6f91d7.png)

### Development build
![image](https://user-images.githubusercontent.com/33740139/93111058-1d8b3600-f684-11ea-858e-47b69cfd2fdc.png)

### Production build
![image](https://user-images.githubusercontent.com/33740139/93111093-2845cb00-f684-11ea-8a3f-5f61022e1c3a.png)

**Comment by elevatebart** [comment]
I tried to reproduce this issue without success. 
It is very probably due to the webpack configuration that styleguidist is using.

What framework/library/rendering tool are you using to build and render your library?

Nuxt? Quasar? 

It could as well be a 3rd party webpack plugin like `purge-css` that removes all the "unused" classes in production.
If it's the case, remove this plugin from your webpack config, for styleguidist, and everything should return to normal.

**Comment by CarsonBain** [comment]
@elevatebart your comment got me thinking about my webpack config a bit. This is a project that's using Laravel Encore to do the webpack config, and there's lots of legacy stuff in there that I'm not 100% on. I ended up just writing a simple new webpack config specifically for the styleguidist and now all my problems are resolved.

Thanks so much for your speedy replies! Appreciate it! :)

**Comment by Eternal-Rise** [comment]
setting `minimaze: false` in `styleguide.config.js` fixed issue
