### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by hgascoigne** [vue-styleguidist/vue-styleguidist#97]
We're trying to migrate most of our projects to Webpack 4. Do you have a timeline for making that migration? I'd be happy to submit a PR if it helps.

**Comment by viljamis** [comment]
Interested about this too. Let us know if we can help somehow!

**Comment by rafaesc** [comment]
Hi @hgascoigne and @viljamis ,

I saw that it's possible to use webpack 4, only you need to add this dependency in your package.js

```diff
{
  "name": "vue-styleguidist-example-basic",
  "description": "Vue styleguidist basic example",
  "version": "1.6.1",
  "private": true,
  "homepage": "https://github.com/vue-styleguidist/vue-styleguidist",
  "repository": {
    "type": "git",
    "url": "git://github.com/styleguidist/vue-styleguidist.git"
  },
  "license": "MIT",
  "engines": {
    "node": ">=4"
  },
  "dependencies": {
    "dog-names": "^1.0.2",
    "vue-styleguidist": "1.6.1"
  },
  "scripts": {
    "styleguide": "vue-styleguidist server",
    "styleguide:build": "vue-styleguidist build"
  },
  "devDependencies": {
    "css-loader": "^0.28.7",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.19.0",
+   "vue-docgen-api": "^2.3.4",
+   "html-webpack-plugin": "github:webpack-contrib/html-webpack-plugin",
+   "vue-loader": "^14.2.2",
+   "webpack": "^4.2.0"
  }
}

```

**Comment by viljamis** [comment]
@rafaesc That is very nice. Will try this later today :-)

**Comment by hgascoigne** [comment]
@rafaesc In my case, vue-styleguidist kept its own dependency on an older version of html-webpack-plugin even when updating mine to 3.0. I'm assuming this is because of the major version change?

I have put in a PR for webpack 4 support.
