### ISSUE TITLE
Documenting events fired from eventBus

### ISSUE THREAD

**Issue by Alona2156** [vue-styleguidist/vue-styleguidist#973]
I see well how to document events fired by `this.$emit('eventToEmit')` but I don't find in the docs how to document event emitted from components by event bus. I tried to use `@event`, `@type`, `@property` and just plain comments, but the compiler seems not understanding what I want to do. I wrote comments just one line before `eventBus.$emit('eventToEmit')` and also before the method itself. But nothing works.

**Comment by elevatebart** [comment]
Hello @Alona2156 ,

You are not alone to face this issue. Though I have always hear that using the eventBus pattern can be regretfully painful to debug, and I would implore you to reconsider and maybe use vuex store instead, there is a way to have those events show up in your doc.

You can use the `@fires` doclet linked below.

https://github.com/vue-styleguidist/vue-styleguidist/issues/836

It is not documented properly yet.
If you find in your heart to do it, and send a pull request, I would really appreciate it.

Thank you in advance
Bart
