### ISSUE TITLE
The link style should not be overwritten by emphasis/strong/inlineCode styles

### ISSUE THREAD

**Issue by ikatyang** [vue-styleguidist/vue-styleguidist#975]
**Current behavior**

The link style are overwritten by emphasis/strong/inlineCode styles:

- The `cursor: pointer` is missing in the "inline-code-in-link"
- The `cursor: pointer; color: $link-color` is missing in the "emphasis-in-link"
- The `cursor: pointer; color: $link-color` is missing in the "strong-in-link"

**To reproduce**

```sh
mkdir overwritten-link-style-repro
cd overwritten-link-style-repro
yarn init -y
yarn add vue vue-loader vue-styleguidist vue-template-compiler webpack
echo '
module.exports = {
  sections: [
    {
      name: "Get Started",
      content: "README.md",
    },
  ],
  webpackConfig: {}
};
' > styleguide.config.js
echo '
[`inline-code-in-link`](#)

[_emphasis-in-link_](#)

[**strong-in-link**](#)
' > README.md
yarn vue-styleguidist server --open
```

**Expected behavior**

The link style should be presented for inlineCode/emphasis/strong in link.

**Environments**

- vue-styleguidist: 4.32.3

**Additional context**

As a temporary workaround, the "emphasis-in-link" and "strong-in-link" can be rewritten as "link-in-emphasis" and "link-in-strong", but this workaround is not applicable for "inline-code-in-link" since inline code takes precedence over the link.

**Comment by elevatebart** [comment]
There is a way to work around this issue without changing the library (which would be a breaking change).
We can update the JSS properties that force this override and use the [styles](https://vue-styleguidist.github.io/Configuration.html#styles) config option like this.

```js
export default {
  styles:{
    // component name
    Code: {
      // class name to change
      code: {
        // remove the isolation (prevention of cascading styles)
        isolate: false
      }
    }
  }
}
```

I have not tried it yet, but it should work.

Reference of the updated component:
https://github.com/styleguidist/react-styleguidist/blob/master/src/client/rsg-components/Code/CodeRenderer.tsx

**Comment by elevatebart** [comment]
I do not think I will have time to fix this bug though.
