### ISSUE TITLE
Broken link to Style tweak

### ISSUE THREAD

**Issue by wsjscss** [vue-styleguidist/vue-styleguidist#976]
**Current behavior**

In this page [How to change styles of a style guide?](https://vue-styleguidist.github.io/docs/Cookbook.html#how-to-change-styles-of-a-style-guide) exist link to [Style](https://vue-styleguidist.github.io/docs/Configuration.html#styles), but it's broken.

**To reproduce**

  1. Enter [How to change styles of a style guide?](https://vue-styleguidist.github.io/docs/Cookbook.html#how-to-change-styles-of-a-style-guide)
  2. Click on the [Style](https://vue-styleguidist.github.io/docs/Configuration.html#styles) link.

Is Style tweaks deprecated or it is just broken link?

Thank you!

**Comment by elevatebart** [comment]
Hey @wsjscss thank you for your remark.

Woopsies !! The proper link does not have `docs` in it

https://vue-styleguidist.github.io/Configuration.html#styles

`styles` are very much a thing. 
Note: If you write the styles in a separate file, and give the `styles` config the path to your file, you will get style Hot Module Replacement (HMR). When running the styleguide, if you change the styles, when you save the styles file, it will update the styles in your styleguide.

I hope you enjoy the Developer Experience.

**Comment by wsjscss** [comment]
@elevatebart Thank you. 
And you're right - separate style file is much easier. 
Can you give me advice? Right now in the DOM (generated by styleguidist), i see this structure

```html
<body class="rsg--body-0">
  <div id="rsg-root">
    <div class="rsg--root-1 rsg--hasSidebar-2">
      <main class="rsg--content-3">
        <section class="rsg--root-7"></section>
        <footer class="rsg--root-23"></footer>
      </main>
      <div class="rsg--sidebar-4">
        <div class="rsg--logo-5"></div>
      </div>
    </div>
  </div>
</body>
```

and my custom style file looks like this:
```css
/* doc-styles.css */
#rsg-root {
    [class*='rsg--sidebar'] {
        background: #dadada;
    }

    [class*='rsg--heading2'] {
        font-size: 24px;
    }

    [class*='rsg--type'] {
        margin-left: 0;
    }
}
```
1. I use `#rsg-root` to avoid using `!important` in all style rules
2. I use partial selectors `[class*='rsg--sidebar'] {...}` because DOM classes has numbers in names (ex: `class="rsg--sidebar-4"`) and I don't know if the won't change later.

Am I doing everything right or there is more proper way to add custom styles?

**Comment by elevatebart** [comment]
Styleguidist uses [JSS](https://cssinjs.org/) to set up the styles of its components. 
So you are supposed to update those style in this fashion.

Please tell me what you think of [this guide](https://github.com/vue-styleguidist/vue-styleguidist/blob/docs-customize/docs/docs/Customize.md) I cooked up this week-end. 
If you have any questions or things you, please ask them. It's important to me that this documentation is readable. You can give more context to your comments on [the PR](https://github.com/vue-styleguidist/vue-styleguidist/pull/977).
