### ISSUE TITLE
Documentation not generated for components with Pug template

### ISSUE THREAD

**Issue by Thomasan1999** [vue-styleguidist/vue-styleguidist#979]
**Current behavior**

When a component contains Pug template, the documentation is not generated.

**To reproduce**

Here in this example: https://vue-styleguidist.github.io/vuecli3-class-pug-ts/, both AppButton and HelloWorld components should be displayed, but only the HelloWorld component is visible because it contains HTML template. I've cloned the repo and changed the template in AppButton component to HTML and it has appeared in the docs.

**Comment by elevatebart** [comment]
Hello @Thomasan1999 

I don't know how I missed that. 
Thank you for reporting.

**Comment by elevatebart** [comment]
I found out that the AppButton component is malformed. It had an extra space on line one.

I really do not have a nag for pug.

**Comment by Thomasan1999** [comment]
I've looked at your commit and I see you'd removed the base indent. If I put back the base indent in the example, it doesn't work.

**Comment by elevatebart** [comment]
Does it work with the vue-loader?

**Comment by elevatebart** [comment]
If you load this component in the vue-loader, does the component render?

**Comment by Thomasan1999** [comment]
Yes. I've tried to render the component from the example and it works just fine, with or without the base indent. I've also tried to create the docs from the several components I use in my project (where I have Pug with base indent), it didn't show them either. If I removed the base indent, it worked.

**Comment by elevatebart** [comment]
The pug parser seems to hate this initial base indent. 

Vue docgen api should really try to remove it if it exists.

Let me see what I can do.
