### ISSUE TITLE
Supporting page per section

### ISSUE THREAD

**Issue by viljamis** [vue-styleguidist/vue-styleguidist#98]
I noticed React Styleguidist adding support for [page per section](https://github.com/styleguidist/react-styleguidist/releases/tag/v6.5.0) very recently in [v6.5.0](https://github.com/styleguidist/react-styleguidist/releases/tag/v6.5.0). While it is still somewhat experimental, I’m wondering what would it require to incorporate that feature into Vue Styleguidist as well? 

Personally think that’s one of the most useful additions to Styleguidist as it makes it much more usable for large style guides. I can help if there’s anything that can do to make porting this feature over to Vue Styleguidist easier.

**Comment by brightWeen** [comment]
We have very many components and we are very much looking forward to supporting.
`pagePerSection` [pull request](https://github.com/styleguidist/react-styleguidist/pull/835) in React Styleguidist

**Comment by rafaesc** [comment]
Actually, there had already been a way to separate the sections in vue-styleguidist.

https://github.com/vue-styleguidist/vue-styleguidist/issues/26

http://rafaelescala.com/vue-styleguide-navigation/

I need to review react-styleguidist and compare it. But I would like to know your opinions.

Regards!

**Comment by viljamis** [comment]
@rafaesc Oh wow, that is very nice! I had no idea such feature existed. A few thoughts around this:

* I noticed that the navigation is slightly broken in latest desktop Safari in the example you provided (http://rafaelescala.com/vue-styleguide-navigation/). if I click “components” and then one of the component names, that link in the sidebar doesn’t take me to the component. I noticed the same behaviour when trying this in my own project locally. Works in Chrome and Firefox though.

* The way React Styleguidist now seems to do this is that it only shows one component per page, so every link in the sidebar is basically a separate page. I wonder if it would be hard to achieve something similar since I’ve noticed that many larger companies often need a lot of documentation per component. A quick example that comes to my mind would be: https://polaris.shopify.com/components/forms/radio-button (imagine having that much documentation per component in a view which has multiple components listed, wouldn’t really work very well anymore)

**Comment by viljamis** [comment]
Btw, I’m happy to look into and fix that Safari bug in a separate pull if you wish. Let me also know your thoughts on having a setting that would allow having only one component at a page instead of all components under a section.

**Comment by viljamis** [comment]
@rafaesc I fixed the first issue I mentioned and did a pull: https://github.com/vue-styleguidist/vue-styleguidist/pull/99

**Comment by rafaesc** [comment]
Hi @viljamis,

Thanks for your PR! I didn't have mac to testing it :D

I saw that there are some differences between vue-styleguidist and react-styleguidist.

I created an issue to resolve it.

https://github.com/styleguidist/react-styleguidist/issues/892

**Comment by rafaesc** [comment]
Ok @viljamis, on 1.7.2 version

`navigation` config, already separate components and sections, you can see a demo here:
http://rafaelescala.com/vue-styleguide-navigation/

Regards

**Comment by elevatebart** [comment]
I believe this one is done ;)
