### ISSUE TITLE
after npm install vue-docgen-api , error can't resolve module

### ISSUE THREAD

**Issue by zhaozhe0831** [vue-styleguidist/vue-styleguidist#980]
When I install vue-docgen-api in vue-cli, it tells me 'can't resolve module'.

I can't find problem, I don't know what happened...
When I install these dependencies, it still doesn't work...

![image](https://user-images.githubusercontent.com/12945873/93976969-5de96300-fdac-11ea-8a9d-33a1ec35a23e.png)

> These dependencies were not found:
>
> * atpl in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * babel-core in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * bracket-template in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * dot in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * dustjs-linkedin in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * eco in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * ect in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * haml-coffee in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * hamlet in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * hamljs in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * handlebars in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * hogan.js in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * htmling in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * jazz in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * jqtpl in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * just in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * liquor in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * marko in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * module in /Users/zhaozhe/node_modules/coffee-script/lib/coffee-script/coffee-script.js, /Users/zhaozhe/node_modules/coffee-script/lib/coffee-script/register.js
> * mote in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * mustache in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * plates in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * ractive in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
> * react in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js, /Users/zhaozhe/node_modules/react-dom/cjs/react-dom-server.browser.development.js
> * underscore in ./node_modules/@vue/compiler-sfc/node_modules/consolidate/lib/consolidate.js
>
> To install them, you can run: npm install --save atpl babel-core bracket-template dot dustjs-linkedin eco ect haml-coffee hamlet hamljs handlebars hogan.js htmling jazz jqtpl just liquor marko module mote mustache plates ractive react underscore

**Comment by zhaozhe0831** [comment]
I guess vue-docgen-api has some questions on building

**Comment by elevatebart** [comment]
Hello @zhaozhe0831 

Can you be a little more specific on what does not work?
Are you using npm? yarn? pnpm? 

This seems like a misfire on your package managers side.

Can you try this first?  
- delete node_modules directory and install again
- delete node_modules + yarn.lock or package-lock.json and install again

If this does not work or if it poses an problem to do so, then would you please create a repository to reproduce your issue?

**Comment by zhaozhe0831** [comment]
ok, I will try

**Comment by wakaryry** [comment]
I can not make docgen-api run. I install it with npm. When I use parse, it reports `Can't resolve`. How could I solve it?

Or can add a json output example?

I just need the parsed object into json, I do not need the markdown doc.
