### ISSUE TITLE
Incomplete documentation section (How to hide some components in a style guide but make them available in examples?)

### ISSUE THREAD

**Issue by cyp-v** [vue-styleguidist/vue-styleguidist#981]
**Current behavior**

In the documentation, Cookbook section,  "How to hide some components in a style guide but make them available in examples?", the first sentence is incomplete.

**To reproduce**

[Link to said documentation section](https://vue-styleguidist.github.io/docs/Cookbook.html#how-to-hide-some-components-in-a-style-guide-but-make-them-available-in-examples)

**Expected behavior**

Sentenced should be complete. This section of the documentation is confusing.

**Comment by elevatebart** [comment]
Thank you @cyp-v, 

I guess I should not write guides when I am half asleep...
I will fix this as soon as possible.

**Comment by elevatebart** [comment]
@cyp-v @wal0x 

Can you check out the PR I added and tell me if it is any clearer?

better reading here
https://github.com/vue-styleguidist/vue-styleguidist/blob/docs-cookbook-fix/docs/docs/Cookbook.md#how-to-hide-some-components-in-a-style-guide-but-make-them-available-in-examples

**Comment by cyp-v** [comment]
Much clearer, thanks ! I think this could be a little bit more straight to the point though. I've added a few comments in the review of your PR. Thank you for the great work !
