### ISSUE TITLE
about docgen api when use @property

### ISSUE THREAD

**Issue by zhaozhe0831** [vue-styleguidist/vue-styleguidist#985]
Thanks for your git，it’s very helpful to me.

I write comment like this. the docgen api parse to this.

I would like to learn about this is youer design? or is not noticed thing？

I'm hesitant to format the result of docgen api.

```js
      /**
       * Success event.
       * @property {string} content content of the first prop passed to the event
       * @property {string} content.text content of the first prop passed to the event
       */
      this.$emit('success', content, {
        demo: 'example'
      })
```

```json
{
    "name":"on-click",
    "description":"点击事件",
    "type":{
        "names":[
            "undefined"
        ]
    },
    "properties":[
        {
            "type":{
                "names":[
                    "object"
                ]
            },
            "name":"defaults",
            "description":"The default values for parties."
        },
        {
            "type":{
                "names":[
                    "number"
                ]
            },
            "name":"defaults",
            "description":".players       - The default number of players."
        },
        {
            "type":{
                "names":[
                    "string"
                ]
            },
            "name":"defaults",
            "description":".level         - The default level for the party."
        },
        {
            "type":{
                "names":[
                    "object"
                ]
            },
            "name":"defaults",
            "description":".treasure      - The default treasure."
        },
        {
            "type":{
                "names":[
                    "number"
                ]
            },
            "name":"defaults",
            "description":".treasure.gold - How much gold the party starts with."
        }
    ]
}
```

**Comment by elevatebart** [comment]
Just to be sure I understand the question you are asking, I will reformulate your questions.

Is this output format designed this way or is the output you see a bug?
- Answer: It is designed this way and it is not going to change in any minor version that is coming.

Is this design good/satisfying to work with?
- Answer: I am not satisfied with it. I plan to change the design in the Major version. You can follow issue #963 if you are interested. No change is going to be made to the output format until version 5 (at least next year) since storybook 6 heavily relies on it.

**Comment by elevatebart** [comment]
@zhaozhe0831 did this answer your question?

**Comment by zhaozhe0831** [comment]
ok, thank you, I understand your mean.

I already use `template handlers` to format `@slots` and `@property` in template
now, I try to use the `Script Handlers` to format, but it can't work. 

yeah... it's another question or issue.

![image](https://user-images.githubusercontent.com/12945873/95536793-76998000-0a1e-11eb-9a4e-15fb0a4e0e2e.png)

**Comment by zhaozhe0831** [comment]
oh,sorry, I think it's my mistake ...
